Fix mobile notifications
mautic/mautic pull request #10062
Opened 2021-05-19 15:56 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We noticed some issues for mobile notifications

1. Error 

> Notification subtitle must not be null for any languages.

iOS require subtitle, then we add not blank validation

2. Process error in timeline

At the moment error from response is not set to database and not display in timeline. This PR added standard error message to timeline, for example: 

![image](https://user-images.githubusercontent.com/462477/118844547-52aeee80-b8cb-11eb-9f0c-4bb08e686f35.png)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. You should use mobile notification, what is really hard to setup
3. Then code review is good and basic test for mobile notification (create/edit)

2022-05-05 06:18 UTC, mabumusa1 approved these changes
The code is good to go after rebase

2022-05-06 08:44 UTC, kuzmany commented
@mabumusa1 do not look like it need rebase

2022-05-06 09:17 UTC, escopecz requested changes

2022-05-06 09:17 UTC, escopecz commented on app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php
> +    <?php return; ?>
Wow, haven't seen this in a HTML view yet. Does it mean you don't want to show the rest of the view? Can this be replaced with an `else` statement instead? I cannot find how to do this in a Twig template. And we'll need to rewrite this PHP template to TWIG pretty soon.

2022-05-06 15:58 UTC, mabumusa1 commented
> @mabumusa1 do not look like it need rebase

@kuzmany I did that yesterday.

2024-09-09 18:40 UTC, kuzmany commented
Close at the moment. We will push it again once ready to M5

2024-09-09 18:40 UTC, closed without merging