Fix company contacts list
mautic/mautic pull request #10125
Opened 2021-06-03 12:56 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
If company has not assigned contacts, it show wrong contacts.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contacts
3. Create companies
4. Check detail of company without contact
5. In some cases you see contacts, even If we do not expect it
6. This PR fixed it

2021-06-07 11:04 UTC, dadarya0 commented
@kuzmany Your fix is good no issue in code but I am not able to reproduce above mentioned issue in feature branch.

<img width="1674" alt="Screenshot 2021-06-07 at 4 23 24 PM" src="https://user-images.githubusercontent.com/48244990/121006060-170e9280-c7ae-11eb-9626-8759d624ccf4.png">

I am getting `No Results Found` message if no contact is associated with company.

2021-06-24 19:30 UTC, RCheesley requested changes
I too am unable to reproduce this bug with the features branch - perhaps you could give us some examples of when this issue is being triggered @kuzmany ?

Small grammar suggestion for the language string.

2021-06-24 19:30 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/messages.ini
> +mautic.company.contact.is.not.associated="No contact assigned to this company."
```suggestion
mautic.company.contact.is.not.associated="No contacts are assigned to this company."
```

2021-07-13 07:11 UTC, HN-PRO commented
> I too am unable to reproduce this bug with the features branch - perhaps you could give us some examples of when this issue is being triggered @kuzmany ?
> 
> Small grammar suggestion for the language string.

I reproduced the problem. This problem will occur if the company does not have any contacts and there are ids characters in the firstname, lastname, email, company, city, state, zipcode, and country fields in the contact.
The following is the SQL I debugged, FYI.
`SELECT l.* FROM leads l LEFT JOIN users u ON u.id = l.owner_id 
WHERE (l.firstname LIKE :MnNcgRPr) OR (l.lastname LIKE :MnNcgRPr) OR (l.email LIKE :MnNcgRPr) OR (l.company LIKE :MnNcgRPr) 
OR (l.city LIKE :MnNcgRPr) OR (l.state LIKE :MnNcgRPr) OR (l.zipcode LIKE :MnNcgRPr) OR (l.country LIKE :MnNcgRPr) 
ORDER BY l.last_active DESC LIMIT 30`

2021-07-15 18:11 UTC, RCheesley commented
@HN-PRO did this patch fix the issue for you?  If so we have a code review and test and can look at merging it.

2021-07-16 05:36 UTC, HN-PRO commented
> @HN-PRO did this patch fix the issue for you? If so we have a code review and test and can look at merging it.

Yes, it has helped me solve the problem.

2021-07-27 18:28 UTC, kuzmany commented
@RCheesley seems like two good reviews here

2021-08-09 15:24 UTC, RCheesley commented
@kuzmany indeed but we need test coverage - it is [currently failing](https://github.com/mautic/mautic/pull/10125/checks?check_run_id=3181404085) on that.

2021-08-23 16:15 UTC, RCheesley commented
Bumping from release due to inadequate automated test code coverage.

2022-01-24 17:21 UTC, RCheesley commented
Last milestone bump before closing the PR - @kuzmany if you are able to rebase to 4.x and look at the test before the 4.2 release we can consider it for the release.

2023-06-12 06:07 UTC, mollux commented
Closing in favor of #12464

2023-06-12 06:07 UTC, closed without merging