Export excel
mautic/mautic pull request #10322
Opened 2021-08-09 21:07 UTC by snoblucha

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     |  

#### Description:

This pull request adds

- choose format (xlsx,csv) of the report when scheduled
- option to not send out blank report
- schedule time and timezone of the report to be sent

In the company there was the request to send out report in XLSX format. So this pull request adds a format dropdown to choose format when scheduling report. Also there was a request to not send out report when the report is empty. This was also added as a configuration to the schedule of the report sending out.

While working on that we hit a bug, that sometimes the report was sent out twice a day. The cause was that when scheduling a report, the report is cheduled first time by web worker in the timezone of the user  (in out configuration the Europe/Berlin UTC+2). When it was sent out by cron, it is then rescheduled in the default timezone of the mautic (in our case UTC). So example. First time it was scheduled to be sent out at 2021-08-09 00:00:00 CEST (2021-08-08 22:00:00 UTC) and then it was scheduled to 2021-08-09 00:00:00 UTC, because for the scheduler the next day was not yet reached 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a report
3. Choose schedule and configure new options for the schedule
4. run a cron to send out a report

2021-08-10 10:09 UTC, RCheesley commented
Thanks for making the PR @snoblucha - looks like a helpful feature and thanks for squashing the bug you found also!

2021-08-14 20:24 UTC, kuzmany commented
> First time it was scheduled to be sent out at 2021-08-09 00:00:00 CEST (2021-08-08 22:00:00 UTC) and then it was scheduled to 2021-08-09 00:00:00 UTC, because for the scheduler the next day was not yet reached

This was already fixed by https://github.com/mautic/mautic/pull/9482

2021-08-16 19:42 UTC, kuzmany requested changes
Need migrations

2021-08-16 19:53 UTC, kuzmany commented
I tested it and looks very cool. Probably we could hide **Send at** option If we choose send NOW.

![image](https://user-images.githubusercontent.com/462477/129621670-8c3ddda1-739a-4a32-af27-65061e67103e.png)

2021-10-25 07:09 UTC, kuzmany requested changes
I made review and works as expected and it's awesome addition. Just small improvements need:

- need migrations
- need hide Send at/Timezone option If now is selected (you can use data-show-on attribute)
- need pre-select timezone (not UTC) from configuration


@snoblucha do you have time to finish it? Or can you give me a permission and I can make improvements myself...

2021-10-25 07:26 UTC, snoblucha commented
@kuzmany You can make the changes, the time is what is missing and I would have to find out how exactly to create migration, because I work mostly in RoR and I do not have Symphony best practices covered in details. I think you will have the requested changes done in a few moments. 

Do you need some special permission to be set? In this pull is checked, that maintainers can add commits, should be enough I think.

2021-11-22 21:36 UTC, snoblucha commented
@kuzmany Hi, I finally got to this issues and finished the required changes.

2021-11-25 21:00 UTC, kuzmany requested changes
Very nice. Everything work as expected.
Just see one issue with migrations. I left comment there

2021-11-25 21:00 UTC, kuzmany commented on app/migrations/Version20211121211138.php
> +        $this->addSql("ALTER TABLE {$this->prefix}reports ADD schedule_time VARCHAR(191) DEFAULT '00:00' NOT NULL, ADD schedule_timezone VARCHAR(191) DEFAULT 'UTC' NOT NULL, ADD send_empty TINYINT(1)
You should check  If columns already exist and does not force create it.  Because it return end with exception

> SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'schedule_time'                                                                                     

Something like this for each column
```
        if ($schema->getTable($this->prefix.'reports')->hasColumn('schedule_time ')) {
        }
```

2021-11-25 21:02 UTC, kuzmany commented
I also see like example table not recalculated time based on selected time 

![image](https://user-images.githubusercontent.com/462477/143499616-f5e8070a-6a90-4000-86cf-09b2a07a57fd.png)

2023-10-13 05:10 UTC, kuzmany commented
Close favor to https://github.com/mautic/mautic/pull/12448

2023-10-13 05:10 UTC, closed without merging