Add services  to use cofnig parameters in storage like DB
mautic/mautic pull request #10357
Opened 2021-08-23 10:55 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

2021-08-30 17:53 UTC, RCheesley commented
@kuzmany just updated the base for you to 4.x as it's a feature PR.

2021-10-18 18:35 UTC, alanhartless requested changes
@kuzmany I made some comments just by reading the code. I have not tested it. It needs code coverage for the new services and that existing services still work as expected.

2021-10-18 18:35 UTC, alanhartless commented on app/bundles/CacheBundle/Cache/Adapter/DatabaseTagAwareAdapter.php
> +            new \Symfony\Component\Cache\Adapter\PdoAdapter($connection, (string) $namespace, $lifetime, $options)
Did you mean to duplicate this?

2021-10-18 18:35 UTC, alanhartless commented on app/bundles/CacheBundle/Cache/CacheProvider.php
> +            $this->psr16 = new Psr6Cache($this->getCacheAdapter($cacheAdapter));
I think this will cause issues when the cache provider is used for caching (i.e. Redis) and the database (for config) because first to call the method wins resulting subsequent to use something other than the cache adaptor configured. 

Consider using a complete new service for this instead of sharing the same as the cache provider. DatabaseParametersStorage could potentially use the same class but should be defined as a new/separate service.

2021-10-18 18:35 UTC, alanhartless commented on app/bundles/CoreBundle/Config/config.php
> +                    'mautic.cache.provider',
See my comment above about using a new service instead of sharing mautic.cache.provider

2021-10-18 18:35 UTC, alanhartless commented on app/bundles/CoreBundle/ParametersStorage/Database/DatabaseParametersStorage.php
> +        $this->simpleCache->set(ParametersStorage::PARAMETERS_STORAGE, $parameters);
I'm torn on this. I see the benefit of quicker coding by using the cache provider to do this but I also think it's a bit risky because important configuration options will be stored in the same location as cached items. It'll need to be called out that using the DB to store parameters means you cannot reset or truncate the database cache blindly. If using a different service than the shared `mautic.cache.provider`, maybe you could use a new table just for config parameters as well to help protect from that scenario?

2021-10-18 18:35 UTC, alanhartless commented on app/bundles/InstallBundle/Install/InstallService.php
> -        if (empty($params['db_driver']) || empty($params['mailer_from_name'])) {
Was this check moved somewhere else? If not, then was the installer tested with the default file based config? It looks like this method is used in a few places so I'm not sure of the full impact of removing this nor if there is really any value in having it now.

2021-10-18 19:03 UTC, kuzmany commented on app/bundles/CoreBundle/ParametersStorage/Database/DatabaseParametersStorage.php
> +        $this->simpleCache->set(ParametersStorage::PARAMETERS_STORAGE, $parameters);
@alanhartless thank you for your comments. Do you mean use cache service with store to another table like cache_items  or do you mean create new table as part of Mautic?

2021-10-18 19:10 UTC, alanhartless commented on app/bundles/CoreBundle/ParametersStorage/Database/DatabaseParametersStorage.php
> +        $this->simpleCache->set(ParametersStorage::PARAMETERS_STORAGE, $parameters);
A new table that stores just config values that doesn't get tangled up in other cached items because the `mautic.cache.provider` service is shared for both.

2024-02-14 06:44 UTC, kuzmany commented
Close, we need release M5 version of the solution

2024-02-14 06:44 UTC, closed without merging