Fix Installer Exception Handling v2 - TPROD-194
mautic/mautic pull request #10350
Opened 2021-08-21 16:28 UTC by dennisameling

Clone of https://github.com/mautic/mautic/pull/9934 but reset to https://github.com/dennisameling/mautic/commit/ee5e6c3830eed9dfa333902d12e2883150dfe2db which was the last known good state for CI to pass. Starting from here

2021-08-21 19:03 UTC, dennisameling commented
Tested all 4 scenarios listed above:

With prefix
Install via the UI ✅
Install via CLI ✅

No prefix
Install via the UI ✅
Install via CLI ✅

2021-08-21 19:06 UTC, dennisameling commented on app/bundles/InstallBundle/Command/InstallCommand.php
> +        if (!empty($allParams['site_url'])) {
`empty()` first checks if the variable is set, so the `isset()` is superfluous here. That's why I removed it. See https://www.php.net/manual/en/function.empty.php for details.

2021-08-22 11:49 UTC, RCheesley commented
Going round in circles trying to work out how to install at CLI without a database prefix. Tried to omit the prefix entry, use "", but not getting anywhere fast. Anyone able to shed some light please?

2021-08-22 12:34 UTC, RCheesley requested changes
Seems like the same error is still occurring when installing at the command line without a prefix.

In case it is relevant I am running this on a Mac with Docker Desktop 3.6.0 (67351), DDEV v1.17.7, PHP 7.4/Apache FPM/MariaDB 10.3.

CLI install with prefix: ✅ 
CLI install without prefix: ❌  Schema error (see below)

```
ruth.cheesley@MacBookPro-RuthCheesley mautic % ddev exec bin/console mautic:install --mailer_from_name="DDEV" --mailer_from_email="mautic@ddev.local" --mailer_transport="smtp" --mailer_host="localhost" --mailer_port="1025" --db_driver="pdo_mysql" --db_host="db" --db_port="3306" --db_name="db" --db_user="db" --db_password="db" --admin_email="admin@mautic.local" --admin_password="mautic" https://mautic4.ddev.site --env=dev

 // Clearing the cache for the dev environment with debug true                                                          

                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
                                                                                                                        

Mautic Install
==============

Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
12:15:40 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.lead_fields' doesn't exist
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```
GUI install with prefix ✅ 
GUI install without prefix ✅ 

To add: The table lead_fields does actually exist in the database:

![screenshot-mautic4 ddev site_8037-2021 08 22-13_36_42](https://user-images.githubusercontent.com/2930593/130355436-cca8c178-e091-4a9e-b4f4-02770b13a7e3.png)

2021-08-23 08:43 UTC, dennisameling commented
@RCheesley I subconsciously ignored `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.lead_fields' doesn't exist` as it's not actually an error (see [Alan's comment](https://github.com/mautic/mautic/issues/3436#issuecomment-595752911) on an issue you reported back in 2017). It doesn't show up in the current `features` branch, so let's call it a regression indeed.

I was able to fix the original issue in https://github.com/mautic/mautic/pull/9934, so let's move back to that PR. That way we keep the history intact for the release notes etc.

2021-08-23 08:43 UTC, closed without merging