fix: handle missing page-hit in point-action
mautic/mautic pull request #10374
Opened 2021-08-26 23:37 UTC by donbowman

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #10316

#### Description:

#### Steps to test this PR:

This is a type of race condition. A page hit is getting recorded asyncrhonously of being referenced in another worker. To reproduce, make sure you are running w/ multiple fcgi backends, and record some events w/ mtc.js. You will see some 'crashes' (e.g. the sql returns false, but the code expects an array), or, the original issue submitter (not me) had some issue w/ getting 2 hits recorded instead of one

2021-08-27 08:14 UTC, RCheesley commented
@cla-bot check

2021-08-27 08:16 UTC, RCheesley commented
Thanks for the PR @donbowman 🎉  I have just set the automated tests running.

Are you able to add a description which explains how to reproduce the bug, and then how to test that it is fixed? This will help testers enormously which makes it more likely to get your PR merged swiftly. Thanks in advance!

2021-10-04 12:03 UTC, patrykgruszka requested changes
Thanks @donbowman for your contribution. I've found some problems in your PR please check it. I would also recommend to add some unit tests to cover this issue.

2021-10-04 12:03 UTC, patrykgruszka commented on app/bundles/PageBundle/Entity/HitRepository.php
>          return new \DateTime($result['latest_hit'], new \DateTimeZone('UTC'));
I would suggest more explicit return statement using null when hit is not found.
```suggestion
return $result ? new \DateTime($result['latest_hit'], new \DateTimeZone('UTC')) : null;
```

2021-10-04 12:03 UTC, patrykgruszka commented on app/bundles/PageBundle/Helper/PointActionHelper.php
> +        if (false != $latestHit) {
When latest hit is not found you are skipping some logic here. When you look at the return statement of this method you will find that it will return true when no false value is present in the array. After your change this method will always return true when latest hit is not found and one of this conditions are configured.

2023-07-27 12:45 UTC, patrykgruszka commented
@RCheesley I've made a new PR #12609, as there was no response from author.

2023-07-27 12:53 UTC, RCheesley commented
Thanks @patrykgruszka let's close this in favour of #12609

2023-07-27 12:53 UTC, closed without merging