content type contains an array and isJson is not correctly set.
mautic/mautic pull request #10515
Opened 2021-10-07 19:31 UTC by woutersf

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ✅ ]
| New feature/enhancement? (use the a.x branch)      | [ ❌ ]
| Deprecations?                          | [ ❌ ]
| BC breaks? (use the c.x branch)        | [❌  ]
| Automated tests included?              | [❌  ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | none created.

The batch ( _bin/console mautic:integration:fetchleads -i Dynamics_ ) throws the following warning: 

`preg_match() expects parameter 2 to be string, array given in /var/www/mauticinagro/live/application/docroot/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php on line 90
`

This points us to 
`$isJson   = isset($response->getHeaders()['Content-Type']`
and 
`$isXml    = isset($response->getHeaders()['Content-Type']`
however the ['Content-Type'] contsains a structure like so: 
`array(1) {
  [0]=>
  string(62) "application/json; odata.metadata=minimal; odata.streaming=true"
}`

This results in the (isJson) boolean not correctly set at the moment. 

#### Steps to test this PR:

1. Set up MS dynamics
2. Set up Mautic
3. Add patches https://github.com/mautic/mautic/pull/10344
and https://github.com/mautic/mautic/pull/9559. Otherwise the sync will not be triggered correctly
4. Map fields between Mautic and dynamics
5. create contacts in Dynamics
6. run the mentioned console command (fetchleads)

2021-10-19 19:42 UTC, woutersf commented
Should be ok now?

2021-10-21 13:39 UTC, RCheesley commented
@cla-bot check

2021-10-29 07:30 UTC, escopecz requested changes
Please add a unit test

2021-11-10 08:16 UTC, mollux commented
@woutersf it seems like a lot of extra files were added in this PR that are unrelated to this original change, e.g. the email validation change of the change in the release_metadata.json file

Can you check what happened and only add the relevant parts?

2021-12-07 12:09 UTC, mollux commented
@woutersf 

this was fixed in another way in https://github.com/mautic/mautic/pull/10308

2022-03-02 13:30 UTC, RCheesley commented
@woutersf some conflicts to be resolved in this PR now, and please add the unit tests as requested above so that we might consider merging in a future release! I have updated the base to 4.2 as that's where we'll make the next batch of bug fix releases from.

2025-07-17 10:54 UTC, jos0405 commented
It seems ithe issue was fixed in https://github.com/mautic/mautic/pull/10308.
I'm closing it.

2026-06-08 18:22 UTC, andersonjeccel commented
Hey, I'm closing this for now because it looks like the PR has been idle for quite a while and hasn't had recent updates since 2025. We're cleaning up older items so reviewers can spend time on PRs that are still active and near the finish line. If this should stay open, feel free to reopen it.

2026-06-08 18:22 UTC, closed without merging