Fix email translations lost and overwritten by parent
mautic/mautic pull request #10525
Opened 2021-10-12 07:15 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is just minor addition to use flag updatingTranslationChildren in plugins. It help us prevent some entity save content during process entities via  `EmailEvents::EMAIL_POST_SAVE`

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Just code review. Nothing more

2021-10-26 17:10 UTC, mohit-rocks submitted a review, later dismissed

2021-10-27 03:42 UTC, mohit-rocks commented
Closing and reopening it to trigger the test bot again.

2021-10-29 07:43 UTC, escopecz submitted a review, later dismissed
The code looks good. I'm not sure about one row. Please let me know why it is there.

2021-10-29 07:43 UTC, escopecz commented on app/bundles/EmailBundle/Tests/Model/EmailModelTest.php
> +define('SORTARRIVAL', 1);
Why is this needed here?

2021-10-29 08:16 UTC, kuzmany commented on app/bundles/EmailBundle/Tests/Model/EmailModelTest.php
> +define('SORTARRIVAL', 1);
It return error undefined while I tested it on local enviroment. I forgot removed it. It's removed it

2021-11-01 20:41 UTC, alanhartless requested changes, later dismissed
The only thing I'd call out is that the new testIsUpdatingTranslationChildren is only testing the negative (assertFalse) but not the positive (assertTrue). 

I know that the model only has access after the code is ran. To better cover the new method, I think you could instantiate `new EventDispatcher()` in a second test instead of mocking it. Mock/create a couple email entities (you'll have to be able to programmatically determine that one of them is a translation likely through getTranslation()), create and register a listener class to EmailEvents::EMAIL_POST_SAVE that checks if the email is one of the variants and if so, check that EmailModel::isUpdatingTranslationChildren() returns true.

2021-11-09 11:29 UTC, fedys submitted a review, later dismissed
There are no issues apart from the Alan's last comment. I added the assertions in 4a1360a35fb86e92519556f26345a15ac7410bdc.

2021-11-09 21:28 UTC, dennisameling approved these changes
Approving and merging since the feedback has been addressed now 👍🏼

2021-11-09 21:28 UTC, merged

2021-11-16 16:52 UTC, garzettone commented
Hi, I just updated to 4.02 release and the problem of translation override is still there.

2021-11-16 16:57 UTC, RCheesley commented
> Hi, I just updated to 4.02 release and the problem of translation override is still there.

Please can you raise a new issue? Thanks!