Support for date/month date text segment filters
mautic/mautic pull request #10542
Opened 2021-10-19 07:22 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 
| New feature/enhancement? (use the a.x branch)      | ✅ 
| Deprecations?                          | 
| BC breaks? (use the c.x branch)        | 
| Automated tests included?              | not yet
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/266
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

#### Steps to test this PR:
This PR added nee date/month text string segment date filter

- day check current day to date/datetime field month
- month - check current month to date/datetime field month

1. Load up [this PR](https://mautibox.com)
2. Create custom date time field
3. Create contact with value
- if today is 19. 10. 2021
- then add to custom field 19.09.2020
Create another contact and add
- if today is 19. 10. 2021
- then add to custom field 07.19.2019
3. Create segment 1 with field to custom field equal = day
4. Create segment 2 with field to custom field equal = month
5. Rebuild segment
6. You should see first contact added to segment 1
7. You should see second contact added to segment 2

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-19 07:39 UTC, npracht submitted a review, later dismissed
Works perfectly from user perspective.
Needs code review.
<img width="483" alt="Capture d’écran 2021-10-19 à 09 38 00" src="https://user-images.githubusercontent.com/14075239/137864842-c7fc8951-a266-4215-b7ce-d3448c087a37.png">
<img width="485" alt="Capture d’écran 2021-10-19 à 09 38 08" src="https://user-images.githubusercontent.com/14075239/137864852-33cf2292-01b8-4c8e-b5d7-0035203dbd06.png">

2021-10-29 08:46 UTC, escopecz requested changes
Please add tests

2021-10-29 08:46 UTC, escopecz commented on app/bundles/LeadBundle/Segment/Decorator/Date/Day/DateDay.php
> +    protected function modifyBaseDate(DateTimeHelper $dateTimeHelper)
Can this method be removed when it's empty?

2021-10-29 08:46 UTC, escopecz commented on app/bundles/LeadBundle/Segment/Decorator/Date/Day/DateDay.php
> +     * @return array|bool|float|string|null
Isn't it returning only string?

2021-10-29 08:46 UTC, escopecz commented on app/bundles/LeadBundle/Segment/Decorator/Date/Month/DateMonth.php
> +     * @return array|bool|float|string|null
```suggestion
     * @return string
```

2021-10-29 08:54 UTC, kuzmany commented on app/bundles/LeadBundle/Segment/Decorator/Date/Day/DateDay.php
> +    protected function modifyBaseDate(DateTimeHelper $dateTimeHelper)
Thanks for review. I clean up all reported code

2021-10-29 09:13 UTC, kuzmany commented
@escopecz unit tests added

2021-10-30 15:28 UTC, escopecz requested changes
There are still uncovered lines that CodeCov is reporting. I cannot find a functional test as an example. We already have some in our fork. The test should:
1. create a date field
2. create several contacts with various date field values
3. create segment with the new filter
4. run the `mautic:segment:update` command
5. check the lead lists leads table if the contacts with matching date value are in the segment.

This way you ensure these new filters work now and won't be broken in a future update. In many cases a functional test is faster to write than cover all new methods with unit tests and it really gives you confidence that everything is working as intended.

2021-11-08 14:13 UTC, kuzmany commented
@escopecz thanks. I did functional tests but it failed in another ListModelFunctionalTest
Should I delete my created segments after tests? I thought changes are rollback. Nothin help

Can you review it please?

2024-09-09 08:31 UTC, kuzmany commented
Close at the moment. We will push it again once ready to M5

2024-09-09 08:31 UTC, closed without merging