Truncate page hit title
mautic/mautic pull request #10709
Opened 2021-12-25 08:04 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If you use page with tilte longer like 191 chars, then tracking pixel is not triggered. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create page with title longer like 191 chars like this

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars Title longer than 191 chars </title>

</head>
<body>

</html>
```
3. Put tracking pixel on the page
4. Open the page
5. Tracking pixel is not triggered
6. After PR tracking pixel is triggered with title of page truncated to 191 chars

2021-12-29 14:55 UTC, mmarton commented
Hi!

I've tested this with title lengths 190 and 2000 characters (linux mint, firefox 95, chrome 96)

I could not confirm the original issue. The tracking worked for me with any title length.

sidenotes:

- mautic throws an exception if you try to save a page with title longer than 190 (could use a length validation, is this PR a good candidate for that or should I open a new issue?) 
> 500 Internal Server Error - An exception occurred while executing 'UPDATE pages SET date_modified = ?, checked_out = ?, checked_out_by = ?, title = ?, revision = ? WHERE id = ?' with params ["2021-12-29 14:23:35", null, null, "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012", 4, 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1 

- Could't use gitpod for testing because the pagebuilder throw a cors js error, so I tested locally, is there a way to make it work?

- this is my first review, please correct me if I made any mistakes. Thankyou

2021-12-29 14:55 UTC, mmarton commented
Hi!

I've tested this with title lengths 190 and 2000 characters (linux mint, firefox 95, chrome 96)

I could not confirm the original issue. The tracking worked for me with any title length.

sidenotes:

    mautic throws an exception if you try to save a page with title longer than 190 (could use a length validation, is this PR a good candidate for that or should I open a new issue?)

    500 Internal Server Error - An exception occurred while executing 'UPDATE pages SET date_modified = ?, checked_out = ?, checked_out_by = ?, title = ?, revision = ? WHERE id = ?' with params ["2021-12-29 14:23:35", null, null, "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012", 4, 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1

    Could't use gitpod for testing because the pagebuilder throw a cors js error, so I tested locally, is there a way to make it work?

    this is my first review, please correct me if I made any mistakes. Thankyou

2021-12-29 15:21 UTC, mmarton reviewed
Hi!

I've tested this with title lengths 190 and 2000 characters (linux mint, firefox 95, chrome 96)

I could not confirm the original issue. The tracking worked for me with any title length.

sidenotes:

 - mautic throws an exception if you try to save a page with title longer than 190 (could use a length validation, is this PR a good candidate for that or should I open a new issue?)
> 500 Internal Server Error - An exception occurred while executing 'UPDATE pages SET date_modified = ?, checked_out = ?, checked_out_by = ?, title = ?, revision = ? WHERE id = ?' with params ["2021-12-29 14:23:35", null, null, "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012", 4, 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1

- Could't use gitpod for testing because the pagebuilder throw a cors js error, so I tested locally, is there a way to make it work?

- this is my first review, please correct me if I made any mistakes. Thankyou

2022-01-04 16:49 UTC, escopecz requested changes
Thanks Zdeno! 2 small suggestions.

2022-01-04 16:49 UTC, escopecz commented on app/bundles/PageBundle/Entity/Hit.php
> +        $urlTitle       = mb_strlen($urlTitle) <= 191 ? $urlTitle : substr($urlTitle, 0, 191);
Let's use the multibyte functions
```suggestion
        $urlTitle       = mb_strlen($urlTitle) <= 191 ? $urlTitle : mb_substr($urlTitle, 0, 191);
```

2022-01-04 16:49 UTC, escopecz commented on app/bundles/PageBundle/Tests/Entity/HitTest.php
> +        Assert::assertEquals($expected, strlen($hit->getUrlTitle()));
```suggestion
        Assert::assertEquals($expected, mb_substr($hit->getUrlTitle()));
```

2022-01-04 17:01 UTC, escopecz commented
@mmarton can you please check that you were able to store a page title longer than 255 characters in the page_hits table before this change? I found an issue (https://github.com/mautic/mautic/issues/7367) reporting the same problem.

2022-01-04 17:05 UTC, escopecz approved these changes, later dismissed
The code make sense, I can see the `page_hits.url_title` column is type of `VARCHAR(191)`, the test confirms it works as expected 👍

2022-01-04 17:08 UTC, escopecz commented on app/bundles/PageBundle/Tests/Entity/HitTest.php
> +        Assert::assertEquals($expected, mb_substr($hit->getUrlTitle()));
OOps, I meant
```suggestion
        Assert::assertEquals($expected, mb_strlen($hit->getUrlTitle()));
```

2022-01-05 15:30 UTC, escopecz submitted a review, later dismissed
Re-approving

2022-02-04 16:15 UTC, mabumusa1 approved these changes
I did a code review, I think it works and solve a problem for long URL titles

2022-02-05 07:50 UTC, merged