Correct bug no forms in the select contact source campaign when the forms have identical names
mautic/mautic pull request #10717
Opened 2021-12-31 10:19 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [- ]
| Deprecations?                          | [- ]
| BC breaks? (use the c.x branch)        | [-]
| Automated tests included?              | [- ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
When we have defined the same form names 
![image](https://user-images.githubusercontent.com/39382654/147817702-5c06763c-2a63-461f-9976-1252c112a874.png)

and create campaigns on the basis of contact source, only the forms with the highest ID are displayed in the campaign source step. 

in the case of a predefined form, e.g. id 13 after creating the form, e.g. ID 14 with the same name, the field for the campaign is empty

![image](https://user-images.githubusercontent.com/39382654/147817591-20b6a907-9ae5-4128-9d7c-c81727216861.png)

The fix adds an identifier to the form name and allows you to display and select all campaign forms
![image](https://user-images.githubusercontent.com/39382654/147817777-3c73154c-2665-47ef-a3ba-612f15695aa0.png)

2022-01-04 14:53 UTC, escopecz requested changes
Nice work! I can replicate the issue and this code will fix it. I suggested a couple improvements.

Every PR must have a test. This would be nicely covered by a functional test. Something like this:
```php
<?php

declare(strict_types=1);

namespace Mautic\CampaignBundle\Tests\Controller;

use Mautic\CoreBundle\Test\MauticMysqlTestCase;
use Mautic\FormBundle\Entity\Form;

use function GuzzleHttp\json_decode;

final class SourceControllerTest extends MauticMysqlTestCase
{
    public function testTwoSoucesWithSameName(): void
    {
        $form1 = new Form();
        $form1->setName('test');
        $form1->setFormType('campaign');

        $form2 = new Form();
        $form2->setName('test');
        $form2->setFormType('campaign');

        $this->em->persist($form1);
        $this->em->persist($form2);

        $this->em->flush();
        $this->em->clear();

        $this->client->request('GET', '/s/campaigns/sources/new/random_object_id?sourceType=forms');
        $clientResponse = $this->client->getResponse();
        $this->assertSame(200, $clientResponse->getStatusCode(), $this->client->getResponse()->getContent());

        $html = json_decode($clientResponse->getContent(), true)['newContent'];
        $this->assertStringContainsString("<option value=\"{$form1->getId()}\">test</option></select>", $html);
        $this->assertStringContainsString("<option value=\"{$form2->getId()}\">test</option></select>", $html);
    }
}
```
I did not run the test but it should be close. Just paste it to a new file in the `app/bundles/CampaignBundle/Tests/Controller/SourceControllerTest.php` file, make sure you have `.env` file configured properly so it would run the functional tests on a new database and then run `composer test -- --filter SourceControllerTest` so you could see if the tests passes or not. Let me know if you have any questions!

2022-01-04 14:53 UTC, escopecz commented on app/bundles/CampaignBundle/Form/Type/CampaignLeadSourceType.php
> +        $sourceChoices = $options['source_choices'] ?? null;
The default value should be an array as we iterate on it later on.
```suggestion
        $sourceChoices = $options['source_choices'] ?? [];
```

2022-01-04 14:53 UTC, escopecz commented on app/bundles/CampaignBundle/Form/Type/CampaignLeadSourceType.php
> +        }
I would use parentheses to display the ID as I think that's already done in some other select box.
```suggestion
        foreach($sourceChoices as $key => $val) {
            $sourceChoices[$key] = $val.' ('.$key.')';
        }
```

2022-01-20 13:53 UTC, escopecz commented
@tomekkowalczyk thanks for pushing the test in! I polished it so it actually works and it discovered a bug. This is perfect example why each code change needs to have test coverage!

2022-01-20 14:19 UTC, escopecz approved these changes

2022-01-24 14:49 UTC, RCheesley approved these changes
Confirmed the bug where only one of the forms was showing in the dropdown, after applying the PR both show in addition to the form ID. Thanks for the PR @tomekkowalczyk - LGTM! 🚀

2022-01-24 15:07 UTC, merged

2022-01-25 12:39 UTC, RCheesley commented
@all-contributors please add @tomekkowalczyk for code