Fix primary email company tokens
mautic/mautic pull request #10733
Opened 2022-01-06 14:09 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:
This PR fix wrong primary company tokens in email

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create company Test1 with address 1  Test1
3. Create company and assign company Test1
4. Create company Test2 with address 1 Test2
5. Then assign company Test2 to contact as primary but let also Test1 as secondary company
6. Create email with tokens
7. 
```
{contactfield=email}
{contactfield=companyname}
{contactfield=companyaddress1}
```

8. You should receive companyname and address1 from secondary company. Expect primary company data
9. After PR should work

2022-01-18 15:43 UTC, escopecz approved these changes, later dismissed
The code makes sense. Nice test. Thanks Zdeno! 👍

2022-01-23 20:13 UTC, mmarton requested changes
I've tried to test this, following the steps, but I didn't got any company info in the mails...
dumping the $lead variable from Tokenhelper  i have the following:

```
array:30 [
  "id" => "3"
  "title" => "test"
  "firstname" => null
  "lastname" => null
  "company" => "test 2"
  "position" => null
  "email" => "marton@m.hu"
  "mobile" => null
  "phone" => null
  "points" => 0.0
  "fax" => null
  "address1" => null
  "address2" => null
  "city" => null
  "state" => null
  "zipcode" => null
  "country" => null
  "preferred_locale" => null
  "timezone" => null
  "last_active" => "2022-01-23 20:07:39"
  "attribution_date" => null
  "attribution" => null
  "website" => null
  "facebook" => null
  "foursquare" => null
  "instagram" => null
  "linkedin" => null
  "skype" => null
  "twitter" => null
  "owner_id" => 1
]
```
Did I miss something?

2022-01-23 20:13 UTC, mmarton commented on app/bundles/LeadBundle/Helper/TokenHelper.php
> +                    $value = $company[$alias];
```suggestion
                    $value = $company[$alias];
                    break;
```

2022-01-24 13:44 UTC, kuzmany commented
@mmarton I suppose to  companies are fetch just for campaign/segment emails? Did you test these kind of emails?

2022-01-24 13:46 UTC, kuzmany commented on app/bundles/LeadBundle/Helper/TokenHelper.php
> +                    $value = $company[$alias];
Make sense. Thanks

2022-01-24 13:52 UTC, mmarton commented
No, I tried with the send email button on the top of the contact's page.

2022-01-24 13:53 UTC, kuzmany commented
You have to test campaign or segment email

2022-03-04 13:33 UTC, escopecz approved these changes
The code looks good 👍

2022-03-04 13:38 UTC, volha-pivavarchyk approved these changes
Works as expected

2022-03-04 17:47 UTC, merged