add pagehit index in entity metadata instead of fixture
mautic/mautic pull request #10787
Opened 2022-01-24 20:14 UTC by mollux

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | []
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

When testing and working on the PHP 8 support (see https://github.com/mautic/mautic/pull/9969#issuecomment-1020322075), I noticed there are some fixtures that contain [DDL queries](https://www.geeksforgeeks.org/sql-ddl-dql-dml-dcl-tcl-commands/).

As Doctrine processes fixtures as 1 transaction that can be rolled back, and DDL queries force a commit when executed,
this results in an error when Doctrine tries to commit the transaction again.

in PHP < 8, this error was silently ignored, but in PHP >= 8 this error results in a ` There is no active transaction` PDOException.

One of the fixtures create an index on the `page_hits` table.
This was not possible to do in the `Hit` entity with existing functionality in the `ClassMetadataBuilder`, hence the workaround via a fixture.

This PR adds the extra functionality to support this and removed the fixture.
The extra functionality is also covered by a (minimal) test

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. install Mautic, and check if the `page_hits` table has an `page_hits_url` index

2022-02-10 15:29 UTC, escopecz commented on app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php
> +    public function addDateAdded(bool $nullable = false)
Could you please revert the param types in the legacy methods? It is considered a BC break to do this for public and protected methods as some plugin can extend the class and such change in the method signature would break the plugin. Otherwise this looks great!

2022-02-10 22:26 UTC, mollux commented on app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php
> +    public function addDateAdded(bool $nullable = false)
yes makes sense not to change that for keep BC.
I probably ran php-cs / phpstan locally on PHP 8.0 or 8.1, which requires such param style.

I reverted those changes

2022-02-11 09:21 UTC, escopecz commented on app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php
> +    public function addIndexWithOptions(array $columns, string $name, array $options)
On the other hand the new methods should have param and return types :)
```suggestion
     */
    public function addIndexWithOptions(array $columns, string $name, array $options): ClassMetadataBuilder
```

2022-02-11 09:28 UTC, mollux commented on app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php
> +    public function addIndexWithOptions(array $columns, string $name, array $options)
hah, how does the pipeline not cover this? both locally as the github pipelines I have no issues in phpstan or php-cs-fixer

2022-02-11 09:37 UTC, escopecz requested changes
I executed `bin/console doctrine:schema:update --dump-sql` on the 4.x branch and then on this one. This branch added this statement to it:

```sql
DROP INDEX page_hit_url ON page_hits;
```

So it this change did not seem to fix the problem why the fixture was created in the first place. Doctrine does not see this index and wants to remove it.

2022-02-11 09:44 UTC, mollux commented
That index need to exist, but on 4.x docrine is not aware
with this PR, it makes sense that doctrine is aware of that index :) 

What you describe is the expected behaviour:
on 4.x, index is created manually (https://github.com/mautic/mautic/pull/10787/files#diff-d90a10975b9809ec2733d44a9d359a1aee17e53ee7ea32c4e0262169f129c1bbL44), so doctrine is not aware and cannot dump it
with this PR, index is created in a way doctrine knows about it, so it is present tin the `--drop-sql` output.

2022-02-11 10:43 UTC, escopecz commented on app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php
> +    public function addIndexWithOptions(array $columns, string $name, array $options)
We'll have to add the rule and rebuild the PHPSTAN baseline. It's on my todo list for some time, but wouldn't mind if you get to it first :)

2022-02-11 16:37 UTC, escopecz approved these changes
I cannot reproduce my previous problem. I probably forgot to clear cache. This is good to go. 👍

2022-02-13 18:52 UTC, kuzmany approved these changes
Looks good 👍

2022-02-13 19:26 UTC, merged