Dynamics integration does not fetch leads
mautic/mautic pull request #10848
Opened 2022-02-10 18:02 UTC by bodrak

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| New feature/enhancement? (use the a.x branch)      | no
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

I just tried the Dynamics integration with mautic today, and it didn't work as expected.
In my Dynamics configuration (in database) I do have {object: "contacts", ...}. That said, with the "magic" that is done here: https://github.com/mautic/mautic/blob/10141afbf8163282928592407a2f7c6825467e8b/app/bundles/PluginBundle/Command/FetchLeadsCommand.php#L165 it is transformed into "Contacts", which isn't the good key to get back the contact fields. The "$select" parameter of the final request is then empty insead of having the mapping fields.
The result is that the request to https://[DYNAMICS URL]/api/data/v8.2/contacts produces a 400 error from Dynamics with the message: "The provided query options are not valid: System.ArgumentException: 'select' and 'expa...".

There are several ways to actually fix this issue, I tried to propose the one that is imo the best upgrade safe.

A cleaner way would be like "if ('Contacts' === $object)" (note the "s"), but I think this may break for some people that would already have the Dynamics config with {object: "contact"}.

Just tell me if you think there is a better/cleaner way to fix this issue and I'll update my PR.

#### Steps to test this PR:

1. Install Mautic with this PR
2. Install/Configure Dynamics 365
3. Configure the Dynamics 365 plugin integration in Mautic to work with Dynamics Contacts
4. Create some Leads on Dynamics
5. Run command: php bin/console mautic:integration:fetchleads --fetch-all --integration=Dynamics --time-interval=1day

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10848"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-02-11 10:20 UTC, escopecz requested changes
I can't wait for PHP8's https://www.php.net/manual/en/function.str-starts-with.php

The code change makes sense. Please write unit tests for the getLeads method that will prove that the change works and will continue working with the future changes too. Let me know if you need some help with it.

2022-03-02 13:23 UTC, RCheesley commented
Hi @bodrak I have updated the base to 4.2 as that's where we'll make the next bugfix releases. Are you able to get the unit tests written per the comment above so we can consider it for merging? Drop John a line if you need any assistance with that!

2022-03-05 14:31 UTC, bodrak commented
Hello,
I tried a bit with those tests, but I am a bit lost here. 
Basically I am able to run tests, and I tried to get inspired by the SalesforceIntegrationTest class, but I can't figured out how the Integration object and the mock are supposed to work.
Would you have some documentation to share with me about this @escopecz ?
Thanks

2022-03-15 15:02 UTC, escopecz commented
@bodrak can you push your WIP test so I can see what you managed to get done and suggest changes to move the test forward?

2024-04-02 07:17 UTC, escopecz commented
This got fixed in https://github.com/mautic/mautic/pull/13208

2024-04-02 07:17 UTC, closed without merging