Add a way to directly modify the html code in Advanced mode
mautic/mautic pull request #10976
Opened 2022-03-17 17:03 UTC by volha-pivavarchyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes [#10769](https://github.com/mautic/mautic/issues/10769) 

#### Description:
If GrapesJS is enabled, a simple textarea (emailform_customHtml)  field is displayed in the advanced tab that can be used to to directly add HTML. The textarea is only visible if code mode was selected. The builder button to launch GrapesJS is disabled.

![image](https://user-images.githubusercontent.com/96085911/158850048-e01d4be5-013d-499d-aad9-8f5d1f7aa839.png)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new email
3. Select the code mode email type
4. The builder button is disabled
5. Select the advanced tab
6. The HTML Code field is displayed

2022-03-18 09:36 UTC, kuzmany commented on plugins/GrapesJsBuilderBundle/Assets/library/js/builder.js
> +function switchBuilderButton(theme) {
I don't know If GrapesJsBuilderBundle is right place to put it.
We need cover it for emails and pages in general not related what builder is enabled.
I understand legacy builder is removed in M5 but If we push this now, we need rewrite it in M5 again.

2022-03-24 11:42 UTC, kuzmany approved these changes
Even If I am not okay with the change, we need fixed it soon as possible. Then let's go to merge it. 

Works for me.

2022-03-24 12:55 UTC, kuzmany requested changes
Does not work for pages (no Advanced tab there)

2022-03-24 14:27 UTC, volha-pivavarchyk commented
Will it be good solution if I add the Advanced tab?

2022-03-24 16:32 UTC, volha-pivavarchyk commented
I added the advanced tab in the edit page

2022-03-25 14:20 UTC, kuzmany commented
Works. Probably for future we can add HTML to separate tab Code Mode for both email/pages to make it more clear

2022-03-25 14:23 UTC, kuzmany submitted a review, later dismissed
Works. 
Probably we can add HTML to separate tab Code Mode for both email/pages to make it more clear. But it's up to community. I am gonna approve it for now

2022-04-01 15:21 UTC, escopecz approved these changes, later dismissed
I see no issue with the code 👍

2022-04-06 21:34 UTC, biggala2310 commented
I also tested this issue in Gitpod and find one problem. When I choose code mode Builder is still active. So I opened this and seen GrapeJS Builder. After closed builder I can't select any theme. It looks like JS bug.

@volha-pivavarchyk looks Builder is still active. I have chosen code mode.
![image](https://user-images.githubusercontent.com/56032973/162075059-bf4c60c4-9bfd-4133-887d-aa26fd690a8e.png)

2022-04-07 07:44 UTC, kuzmany commented
@biggala2310 seems like button is not disabled for mobile version of view.  Works on desktop properly
@volha-pivavarchyk can you check it?

2022-04-07 08:45 UTC, biggala2310 commented
@kuzmany This is only first bug. Second is to change themes.
Step to reproduce:
1. Choose HTML mode
2. Choose Blank mode
3. Go to Builder and exit
4. Try change theme - it is impossible.

2022-04-07 14:56 UTC, volha-pivavarchyk commented
@biggala2310  @kuzmany I checked and fixed the issue for mobile version. 

@biggala2310 I couldn't reproduce the second bug it in my local version, only in Gitpod. And I've checked this bug is reproduced in another PR as well.

2022-04-08 19:05 UTC, kuzmany approved these changes, later dismissed
Works on mobile too.

2022-04-21 18:54 UTC, renatocron commented
I just tested this locally, I was able to change the theme after using Code editor, both when saving and closing, and when just changing without saving

2022-04-22 09:02 UTC, escopecz commented
@volha-pivavarchyk I changed the target branch from 4.x to 4.2 so we could release this in 4.2.2. Do you think you could rebase and fix the conflict? Or if you wish to release in 4.3 then we can switch back to 4.x and merge right away.

2022-04-22 13:08 UTC, volha-pivavarchyk commented
@escopecz I rebased and didn't get a good result. Maybe the best way is to reopen the PR to branch 4.2?

2022-04-22 16:23 UTC, volha-pivavarchyk commented
Rebase gone wrong

2022-04-22 16:23 UTC, closed without merging