Dont show empty fields in the contact and company detail view
mautic/mautic pull request #11016
Opened 2022-03-29 14:30 UTC by volha-pivavarchyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If we view detailed information about a contact or company on the view page, all fields are displayed. We propose to display only filled fields in this PR

Before:
![image](https://user-images.githubusercontent.com/96085911/160633510-d8f9a202-773a-455b-be19-136c675142b4.png)

After:
![image](https://user-images.githubusercontent.com/96085911/160633346-5df752d2-a353-4b0a-8632-47fecdcc9a3b.png)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new contact/company or open an existing one
3. Open details information
4. Only filled fields here

2022-03-30 12:05 UTC, kuzmany requested changes
If value is 0 then field is not int he list. Usually boolean field, or select field with 0 value

2022-03-30 18:45 UTC, volha-pivavarchyk commented
@kuzmany I agree with you. I was confused by the "Points" field, which defaults to 0.

2022-04-01 14:27 UTC, escopecz approved these changes, later dismissed
Looks good. I noticed one possible improvement, but since it's in the test and it does not change the functionality I'm approving it with or without the change.

2022-04-01 14:27 UTC, escopecz commented on app/bundles/LeadBundle/Tests/Controller/LeadDetailFunctionalTest.php
> +        );
I'm wondering why `ARRAY_FILTER_USE_BOTH` flag was used as the key is not used in the callback. Also, we can use arrow functions now 🚀 
```suggestion
        $leadFields = array_filter($lead->getFields(true), fn ($value) => isset($value['value']));
```

2022-04-11 12:53 UTC, escopecz approved these changes
Re-approving after the latest commit 👍

2022-04-11 18:31 UTC, kuzmany approved these changes
Works as expected

2022-04-13 11:15 UTC, merged