TPROD-291 Remove use of KernelInterface::getName() and the kernel.name parameter
mautic/mautic pull request #11138
Opened 2022-05-03 07:40 UTC by rohitpavaskar

…y name i.e. app

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [n]
| New feature/enhancement? (use the a.x branch)      | [n]
| Deprecations?                          | [y]
| BC breaks? (use the c.x branch)        | [n ]
| Automated tests included?              | [n] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | https://mautic.atlassian.net/browse/TPROD-291

#### Description:
KernelInterface::getName() and the kernel.name parameter is removed from symfony 5 and we are removing use of the same.

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Try executing following command 'bin/console --version’. and check if outputs correctly and not breaking anything.

2022-05-17 13:41 UTC, RCheesley submitted a review, later dismissed
Command works fine:

```
gitpod /workspace/mautic (TPROD-291) $ ddev exec bin/console --version
Mautic 4.2.2 - app/prod (env: prod, debug: false)
```

2022-06-03 13:35 UTC, volha-pivavarchyk submitted a review, later dismissed
Works well

![image](https://user-images.githubusercontent.com/96085911/171864832-13450012-f28c-4b44-b68a-944cfbbf6557.png)

2022-07-08 11:26 UTC, RCheesley commented
This is good to go pending code review.

2022-10-05 19:30 UTC, biozshock approved these changes, later dismissed

2022-10-07 10:53 UTC, mollux requested changes
This re-introduces a deprecated method. IMO the correct way is to set it statically to `app`

2022-10-07 11:54 UTC, mollux requested changes
`$kernel->getRootDir()` is deprecated, so using this method as a solution is not a good idea.
See https://github.com/mautic/mautic/pull/11145 and https://github.com/symfony/symfony/issues/29110

In https://github.com/mautic/mautic/pull/11145 the general approach is to change `$kernel->getRootDir()` with the string `app`.

2022-10-07 11:54 UTC, mollux commented on app/assets/scaffold/files/console
> +$application->setVersion($kernel->getVersion().' - '.basename($kernel->getRootDir()).'/'.$kernel->getEnvironment().($kernel->isDebug() ? '/debug' : ''));
```suggestion
$application->setVersion($kernel->getVersion().' - app/'.$kernel->getEnvironment().($kernel->isDebug() ? '/debug' : ''));
```

2022-10-07 11:54 UTC, mollux commented on bin/console
> +$application->setVersion($kernel->getVersion().' - '.basename($kernel->getRootDir()).'/'.$kernel->getEnvironment().($kernel->isDebug() ? '/debug' : ''));
```suggestion
$application->setVersion($kernel->getVersion().' - app/'.$kernel->getEnvironment().($kernel->isDebug() ? '/debug' : ''));
```

2022-10-07 12:23 UTC, escopecz approved these changes

2022-10-07 13:08 UTC, merged