Modify the form label
mautic/mautic pull request #11166
Opened 2022-05-17 11:38 UTC by volha-pivavarchyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [x]
| BC breaks? (use the c.x branch)        | [x]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The form label and tooltip were modified. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new campaign or use an existing one
3. Add an email to the campaign 
4. Select the "in relative time period" option
5. New form label here
![image](https://user-images.githubusercontent.com/96085911/168800975-661bba7f-61b8-4f4b-a2c2-8784ff522e25.png)

![image](https://user-images.githubusercontent.com/96085911/168802091-6363530e-00d4-47cf-ae3a-fd914fe28b5b.png)

2022-05-17 12:04 UTC, npracht reviewed
👍🏽 good for me :)

2022-05-17 14:45 UTC, RCheesley commented
Small grammar suggestions to bring it in line with our styleguide.

2022-05-17 14:45 UTC, RCheesley requested changes

2022-05-17 14:45 UTC, RCheesley commented on app/bundles/CampaignBundle/Translations/en_US/messages.ini
> +mautic.campaign.form.type.help="This event will be executed for newly added contacts to the campaign even if the scheduled date is in the past. For scheduled emails, we recommend you unpublish it if
```suggestion
mautic.campaign.form.type.help="This event will be executed for newly added Contacts to the Campaign, even if the scheduled date is in the past. For scheduled Emails, it is recommended that you unpublish the Email if you would not like Contacts to receive it after that date. All dates are in the Contact's timezone."
```

2022-05-17 14:59 UTC, volha-pivavarchyk commented
@RCheesley Thanks! I updated the message.

2022-05-24 12:55 UTC, escopecz approved these changes

2022-05-24 13:11 UTC, merged