Marketplace version fix
mautic/mautic pull request #11197
Opened 2022-05-27 13:00 UTC by escopecz

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

With the release of the Custom Objects plugin we found that the Marketplace could handle some things better. So this PR fixes:
1. It takes the latest stable version and fallbacks to a feature branch if stable release does not exists.
2. Lets developers set a human readable name. Composer.json allows only for vendor/repository as the name.
3. The Issue Tracker button was not working. When in there I also added the wiki/documentation button.
4. I reordered the buttons a little. The install and the Close button is visible all the time, the Issue Tracker and Documentation are hidden in the context menu. It used to show the Install and the Issue Tracker button and Close being in the context menu.
5. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
6. Browse the Marketplace and notice the fixes in the description.

2022-06-10 15:07 UTC, RCheesley requested changes
Thanks for the PR @escopecz - a few grammar changes and I spotted this issue with the batch select - something weird, or maybe no options? Either way I think we need to decide what behaviours are meant to be happening here:

https://watch.screencastify.com/v/j6UHIy6bDMLNhJB8KrSa

As a user I was expecting to find there the ability to select several plugins and have them installed, in case that is helpful :)

2022-06-10 15:07 UTC, RCheesley commented on app/bundles/MarketplaceBundle/Translations/en_US/messages.ini
> +marketplace.clear.cache.tooltip="Some data are temporarily stored to speed up loading the Marketplace. Clear the cache to refresh the stored data."
```suggestion
marketplace.clear.cache.tooltip="Some data is temporarily stored to speed up loading the Marketplace. Clear the cache to refresh the stored data."
```

2022-06-10 15:07 UTC, RCheesley commented on app/bundles/MarketplaceBundle/Translations/en_US/messages.ini
> +marketplace.package.remove.html.success.continue="Back to marketplace overview"
```suggestion
marketplace.package.remove.html.success.continue="Back to Marketplace overview"
```

2022-06-17 08:27 UTC, kuzmany approved these changes
I did test in my ddev environment and looks like works pretty well. We can merge it, any improvement to marketplace welcome 👍

2022-06-17 13:25 UTC, merged