Fix: A border on the mj-column is shown twice in the editor
mautic/mautic pull request #11209
Opened 2022-06-01 13:30 UTC by adiux

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [n]
| Automated tests included?              | [ n]
| Related user documentation PR URL      | 
| Related developer documentation PR URL |
| Issue(s) addressed                     | Fixes #11207

#### Description:
See https://github.com/mautic/mautic/issues/11207

In addition I updated all JS dependencies. Mainly grapesjs itself:
from  "grapesjs": "^0.17.29" to "grapesjs": "^0.18.4"

There were some breaking changes, but as far as I can tell Mautic is not affected by them:
https://github.com/artf/grapesjs/releases

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add a border to a section: `<mj-column border="4px solid #F45E43">`
3. It should be displayed only one border. Not like this: 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/13075514/171410726-7a48d3a7-4cef-4329-9fca-8bc849daac34.png">
4. All other email builder functionality should work as expected 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-06-28 17:11 UTC, RCheesley approved these changes
Before the PR:
![New Email _ Mautic](https://user-images.githubusercontent.com/2930593/176242442-8fe47e1f-050c-4715-8dcd-86afa0b26cd8.png)

After the PR:
![New Email _ Mautic (1)](https://user-images.githubusercontent.com/2930593/176242459-78f68252-dfd9-4a60-a923-0ec38da3155b.png)

Thanks for making this fix @adiux 🚀 

Also tested inserting all the blocks available which are working as expected.

2022-06-28 17:14 UTC, RCheesley requested changes
Actually - just looked at saving the template, as soon as I try to save Brienz (just as it is without the border) with this PR applied, I am not able to do so. I am in dev mode so should not need to rebuild the assets - would there be some way to find what the specific error is that is preventing saving?

2022-08-12 14:06 UTC, RCheesley commented
@adiux which theme are you using to test this PR with? Any time I try to use Brienz it says there is an error with the template and does not allow me to save :(

2022-08-12 14:08 UTC, adiux commented
@RCheesley that is weird.. if you look at the console you should get some more information about the error in the mjml

2022-08-12 14:10 UTC, RCheesley commented
```
mjml.service.js:64 TypeError: Cannot read properties of undefined (reading 'replace')
    at e.default (index.js:1:1357172)
    at e.default (index.js:1:9732)
    at r.mjmlToHtml (mjml.service.js:60:14)
    at r.getEditorHtmlContent (mjml.service.js:24:25)
    at r.closeEditorEmailMjml [as run] (buttonClose.command.js:35:34)
    at r.callRun (CommandAbstract.js:90:25)
    at Object.runCommand (index.js:399:38)
    at r.updateActive (ButtonView.js:120:18)
    at m (backbone.js:371:57)
    at v (backbone.js:356:19)
mjmlToHtml @ mjml.service.js:64
getEditorHtmlContent @ mjml.service.js:24
closeEditorEmailMjml @ buttonClose.command.js:35
callRun @ CommandAbstract.js:90
runCommand @ index.js:399
updateActive @ ButtonView.js:120
m @ backbone.js:371
v @ backbone.js:356
h @ backbone.js:155
c.trigger @ backbone.js:346
set @ backbone.js:516
toggleActive @ ButtonView.js:168
clicked @ ButtonView.js:159
be @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
t @ cash-dom.js:794
mjml.service.js:27 Cannot read properties of null (reading 'html')
getEditorHtmlContent @ mjml.service.js:27
closeEditorEmailMjml @ buttonClose.command.js:35
callRun @ CommandAbstract.js:90
runCommand @ index.js:399
updateActive @ ButtonView.js:120
m @ backbone.js:371
v @ backbone.js:356
h @ backbone.js:155
c.trigger @ backbone.js:346
set @ backbone.js:516
toggleActive @ ButtonView.js:168
clicked @ ButtonView.js:159
be @ _executeBound.js:8
(anonymous) @ bind.js:10
(anonymous) @ restArguments.js:16
t @ cash-dom.js:794
buttonClose.command.js:39 Uncaught Error: Could not generate html from MJML
    at r.closeEditorEmailMjml [as run] (buttonClose.command.js:39:13)
    at r.callRun (CommandAbstract.js:90:25)
    at Object.runCommand (index.js:399:38)
    at r.updateActive (ButtonView.js:120:18)
    at m (backbone.js:371:57)
    at v (backbone.js:356:19)
    at h (backbone.js:155:16)
    at c.trigger (backbone.js:346:5)
    at r.set (backbone.js:516:16)
    at r.toggleActive (ButtonView.js:168:11)
```

2023-01-02 06:04 UTC, lechuhuuha commented
Hi @adiux any chances you can do a pull request on this fix in the main [repo](https://github.com/artf/grapesjs-mjml)
Would love to see the fix on this.
Thanks

2025-07-17 10:25 UTC, jos0405 commented
I close this as the issue seems to be solved.

2025-07-17 10:25 UTC, closed without merging