Fix: The decision step ignores the preceding condition in the campaign
mautic/mautic pull request #11200
Opened 2022-05-30 13:30 UTC by patrykgruszka

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Y
| New feature/enhancement? (use the a.x branch)      | N
| Deprecations?                          | N
| BC breaks? (use the c.x branch)        | N
| Automated tests included?              | Y 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
If a conditional step is placed before a decision step in a Mautic campaign, it will be ignored when a negative decision path is executed.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create campaign with decision step after condition, for example: ![obraz](https://user-images.githubusercontent.com/8580942/171001064-1d1f0fd7-6b5b-4d1a-a263-f4a13a300f2d.png)
3. Add contact and run this campaign
4. The condition will be ignored and both paths from example will be executed ![obraz](https://user-images.githubusercontent.com/8580942/171001106-2efb4a37-817e-43c8-bf0e-b0c35aa068ce.png)

2022-06-02 09:15 UTC, patrykgruszka commented
@RCheesley I've got error during composer dependencies installation after latest update. I don't think this is caused by my changes, do you have similar problem with other CI failing?

```
Error: '/home/runner/work/mautic/mautic/vendor/composer/tmp-ce932fb7b25749abf2fd30ab845a3c57' is not a zip archive.
```

2022-06-03 14:14 UTC, escopecz commented
@patrykgruszka it was temporary network issue. I'm re-running the failed jobs now. Should be OK.

2022-06-03 15:07 UTC, escopecz requested changes
I noticed that the code is mostly copied from https://github.com/mautic/mautic/blob/4.x/app/bundles/CampaignBundle/Executioner/RealTimeExecutioner.php#L239-L254 but I couldn't find a simple way how to make it more DRY and performant. Both classes use EventRepository but we'd have to make the `$this->leadRepository->getContactRotations()` call out of the if statement which would create more SQL queries than necessary. Maybe we could move just the lines 108 - 123 to a method in the EventRepository? What do you think?

2022-06-03 15:07 UTC, escopecz commented on app/bundles/CampaignBundle/Tests/Helper/InactiveHelperTest.php
> +            ->getMock();
Shorter syntax:
```suggestion
        $this->scheduler = $this->createMock(EventScheduler::class);
        $this->inactiveContactFinder = $this->createMock(InactiveContactFinder::class);
        $this->eventLogRepository = $this->createMock(LeadEventLogRepository::class);
        $this->eventRepository = $this->createMock(EventRepository::class);
        $this->leadRepository = $this->createMock(LeadRepository::class);
        $this->logger = $this->createMock(LoggerInterface::class);
```

2022-06-03 15:07 UTC, escopecz commented on app/bundles/CampaignBundle/Tests/Helper/InactiveHelperTest.php
> +            ->willReturn($campaign);
We should avoid mocks wherever possible to test code closer to reality. It would be great if you find a way how to avoid other mocks in this test. I don't want to force you to more work. I really like this test! Just in case you want it. There are many articles if you want to dig deeper. Like [this one](https://tomasvotruba.com/blog/2018/06/11/how-to-turn-mocks-from-nightmare-to-solid-kiss-tests/).
```suggestion
        $event = new Event();
        $event->setParent($parentEvent);
        $event->setDecisionPath('yes');
        $event->setCampaign($campaign);
```

2022-06-03 15:07 UTC, escopecz commented on app/bundles/CampaignBundle/Tests/Helper/InactiveHelperTest.php
> +            ->getMock();
```suggestion
        /** @var LeadEventLog&MockObject */
        $log = $this->createMock(LeadEventLog::class);
```

2022-06-03 15:07 UTC, escopecz commented on app/bundles/CampaignBundle/Tests/Helper/InactiveHelperTest.php
> +            ->getMock();
```suggestion
        /** @var Campaign&MockObject */
        $campaign = $this->createMock(Campaign::class);
```

2022-06-03 15:07 UTC, escopecz commented on app/bundles/CampaignBundle/Tests/Helper/InactiveHelperTest.php
> +            ->getMock();
```suggestion
        /** @var Event&MockObject */
        $parentEvent = $this->createMock(Event::class);
```

2022-06-06 12:20 UTC, escopecz requested changes
@patrykgruszka nice! Great idea to create new service. I suggest some PHP 7.4 syntax sugar as that's Mautic's minimum PHP version.

2022-06-06 12:20 UTC, escopecz commented on app/bundles/CampaignBundle/Executioner/Helper/DecisionHelper.php
> +
```suggestion

declare(strict_types=1);

```

2022-06-06 12:20 UTC, escopecz commented on app/bundles/CampaignBundle/Executioner/Helper/DecisionHelper.php
> +    private $leadRepository;
```suggestion
    private LeadRepository $leadRepository;
```

2022-06-06 12:20 UTC, escopecz commented on app/bundles/CampaignBundle/Executioner/Helper/DecisionHelper.php
> +    public function checkIsDecisionApplicableForContact(Event $event, Lead $contact, $channel = null, $channelId = null): void
```suggestion
    /**
     * @throws DecisionNotApplicableException
     */
    public function checkIsDecisionApplicableForContact(Event $event, Lead $contact, ?string $channel = null, ?int $channelId = null): void
```

2022-06-06 12:20 UTC, escopecz commented on app/bundles/CampaignBundle/Executioner/Helper/InactiveHelper.php
> +    private $decisionHelper;
```suggestion
    private DecisionHelper $decisionHelper;
```

2022-06-06 12:43 UTC, patrykgruszka commented
@escopecz thanks for review! I've just committed your suggestions.

2022-06-06 12:57 UTC, escopecz approved these changes
The code looks great 👍  (not tested, just code reviewed)

2022-06-18 19:44 UTC, kuzmany approved these changes
I was able to reproduce issue. 
After PR works as expected

2022-06-20 09:09 UTC, merged