Company merge event
mautic/mautic pull request #11228
Opened 2022-06-08 23:47 UTC by bmcclure

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

This is a developer-only feature which adds an event (CompanyMergeEvent) which is fired both before and after companies are merged.

It includes a very simple test class for the new class which follows how similar event tests work.

#### Steps to test this PR:

Note: Since this is a developer-only PR, testing this feature fully requires having another feature which is listening for the new event.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Install/start Mautic
3. Create two companies to be merged
4. Merge the companies from within Mautic and ensure there are no errors related to the event
5. Optionally, install an integration which relies on the company merge event (I will link to another relevant PR here shortly) and run through steps 3 and 4 again to ensure that there are no errors related to actually using the new event.

2022-06-10 10:06 UTC, RCheesley commented
Thanks for the PR @bmcclure - I am sure that this will be useful! cc @kuzmany @escopecz for code review :)

2022-06-10 14:37 UTC, escopecz requested changes
Thanks for the PR! It looks good. As Mautic supports PHP 7.4 as minimal PHP version we can use types and our static analysis checks force us to do so. I'm suggesting mostly the same changes as PHPSTAN and CS Fixer. Take a look at the failing CI jobs. It will show you what else can be improved.

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +class CompanyMergeEvent extends Event
I suggest to have value objects final. The comment has no value so I suggest to remove it.
```suggestion
final class CompanyMergeEvent extends Event
```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +    private $victor;
```suggestion
    private Company $victor;
```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +    private $loser;
```suggestion
    private Company $loser;
```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +    public function getVictor()
```suggestion
    /**
     * Returns the victor (loser merges into the victor).
     */
    public function getVictor(): Company
```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +
New classes should declare strict types. Leave it as is for existing classes as adding it to an existing class could break unexpected code.
```suggestion

declare(strict_types=1);

```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Event/CompanyMergeEvent.php
> +    public function getLoser()
```suggestion
    /**
     * Returns the loser (loser merges into the victor).
     */
    public function getLoser(): Company
```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Tests/Event/CompanyMergeEventTest.php
> +
```suggestion

declare(strict_types=1);

```

2022-06-10 14:37 UTC, escopecz commented on app/bundles/LeadBundle/Tests/Event/CompanyMergeEventTest.php
> +    public function testConstructGettersSetters()
```suggestion
    public function testConstructGettersSetters(): void
```

2022-11-24 12:25 UTC, kuzmany commented
Close favor to https://github.com/mautic/mautic/pull/11748

2022-11-24 12:25 UTC, closed without merging