[WIP] Add the stage and owner fields to the contact fields list
mautic/mautic pull request #11248
Opened 2022-06-13 17:18 UTC by volha-pivavarchyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The `stage` and `owner` fields can be selected as a 'contact field' that relates to that particular form field. In this way the stage and owner will be set for the contact. 

![image](https://user-images.githubusercontent.com/96085911/173406792-edac98b5-36d3-4814-8827-5a131c4786ff.png)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new form or edit the existing one 
3. Add a new field with type `Email`
4. Match the form fields with the contact field `owner by email`
5. Add a new field with type `Text`
6. Match the form field with the contact field `stage`
7. Open the form, fill in the fields and submit
8. Check the contact. 
* The stage is selected by name or id. If no stage is founf by the entered data, the exception will be thrown (it was an existing behaviour)
* The owner is selected by email. If no user is found by the entered email address, no owner will be set, owner field remains the same. Empty or if an existing owner exists then that will be used.

2022-06-16 11:12 UTC, adiux commented
@escopecz @kuzmany can you say anything about the architecture? Does it make sense to implement it in that way?

2022-06-17 07:32 UTC, escopecz commented
I think we did something similar with points, didn't we, @kuzmany? I can't tell what else will need changing. We must ensure that wherever the new fields show up they will work. We use the field list in many places.

2022-06-17 07:53 UTC, kuzmany commented
@escopecz no I didn't

But you're true. That field list is on many places.  We need extend just forms field list and process I think
Anyway, for me it's not clear what these two options do. I had to check code to understand it. Then for end users it will be difficult understand too. Are we able to make it more clear? What is use case for it?

2023-07-05 09:34 UTC, adiux commented
@kuzmany not sure how to make it more clear. To me it is in line with the functionality of the other options e.g. firstname. So I think it should be ok understandable.

The use case is that a form should be placed on the website where the contact can choose a certain person that he/she wants to contact. So this person gets a notification (via existing "send to owner" functionality) and becomes assigned to that contact.

The stage use case is: as a user I want to have an internal form where my fellow colleagues can add a new contact and at the same time select the stage accordingly. In a kiosk mode.

2025-06-20 10:42 UTC, kuzmany commented
Because it's WIP I convert it to draft

2025-06-20 10:54 UTC, adiux commented
@kuzmany @escopecz is it worth working on this?

2025-06-20 11:01 UTC, kuzmany commented
@adiux do you use it on production?

2025-06-20 12:56 UTC, adiux commented
No, not yet. Waiting for this.

2025-06-20 19:48 UTC, kuzmany commented
@adiux it's up to you.  Otherwise close it.

2025-07-02 12:33 UTC, escopecz requested changes
I think this adds good value to Mautic. I went through the review.

2025-07-02 12:33 UTC, escopecz commented on app/bundles/FormBundle/Model/SubmissionModel.php
> +            }
Similar catch for all exceptions is on several places in Mautic. It's hiding errors from the logs or removes stack trace so no one can investigate where the error comes from.

Suggestion: Catch only the specific exception that you want to display to the user and let other exceptions fail hard and logged.
2.

2025-07-02 12:33 UTC, escopecz commented on app/bundles/FormBundle/Model/SubmissionModel.php
> +            $lead->setStage($stage);
I think the stages should be a select list like we have for countries for example. Not a text field where we'd be guessing if 22 is ID or name of the stage.

Although now I'm thinking that users could build the select box themselves with the stages they want to show publicly. So there is a valid use case. Just have to be well-documented.

2025-07-02 12:33 UTC, escopecz commented on app/bundles/FormBundle/Model/SubmissionModel.php
> +                        '%name%' => $this->userHelper->getUser()->getUsername(),
A form submission happens when the user is logged out for most production cases. So there will be no user.

2025-07-02 12:33 UTC, escopecz commented on app/bundles/LeadBundle/Model/FieldModel.php
> +        }
This feels hacky. I'd use it like this instead:
```php
$leadFields = array_merge($this->leadFieldModel->getFieldListWithProperties(false), $this->leadFieldModel->getSpecialLeadFields());
```

2025-07-10 10:16 UTC, jos0405 commented
This PR adds value, is there a chance @volha-pivavarchyk will have time to finish it?

2025-07-22 05:28 UTC, shinde-rahul commented
I have ported this PR here https://github.com/mautic/mautic/pull/15267. This can be closed.

2025-07-22 08:23 UTC, closed without merging