Add UTM to Asset download
mautic/mautic pull request #11266
Opened 2022-06-17 12:06 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  no
| New feature/enhancement? (use the a.x branch)      | yes
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              |
| Related user documentation PR URL      | 
| Related developer documentation PR URL |
| Issue(s) addressed                     | Fixes #... 

#### Description:
The functionality allows you to register UTM tags from asset links through GET parameters. UTM columns are added to the asset download table, where the data is retrieved.

These parameters can be read from the level of asset download reports.

URL: http://mautic4.local/asset/15:test?utm_source=test2&utm_medium=test3&utm_campaign=test6&utm_id=test1&utm_term=test4&utm_content=test4

![image](https://user-images.githubusercontent.com/39382654/174294721-8a87caf4-ad54-4578-a848-0063450e37a3.png)

Report Asset Downloads
![image](https://user-images.githubusercontent.com/39382654/174294953-35db8e31-9445-4572-8777-3a5b4f8e6cb3.png)

2022-06-20 11:17 UTC, escopecz requested changes
Thanks for this feature! I made some comments on how to improve it. Please also take a look at failing CI jobs. I did not report the same issues that are covered by PHPSTAN like adding param and return types for the new methods.

2022-06-20 11:17 UTC, escopecz commented on app/bundles/AssetBundle/Entity/Download.php
> +    private $utmTerm;
Let's use typed properties in new code at least. All entity properties can be null if they are not set directly through the constructor.
```suggestion
    private ?string $utmCampaign;

    private ?string $utmContent;

    private ?string $utmMedium;

    private ?string $utmSource;

    private ?string $utmTerm;
```

2022-06-20 11:17 UTC, escopecz commented on app/bundles/AssetBundle/Entity/Download.php
> +        $builder->createField('utmTerm', 'string')
Let's use constants over strings wherever possible
```suggestion
        $builder->createField('utmCampaign', Types::STRING)
            ->columnName('utm_campaign')
            ->nullable()
            ->build();

        $builder->createField('utmContent', Types::STRING)
            ->columnName('utm_content')
            ->nullable()
            ->build();

        $builder->createField('utmMedium', Types::STRING)
            ->columnName('utm_medium')
            ->nullable()
            ->build();

        $builder->createField('utmSource', Types::STRING)
            ->columnName('utm_source')
            ->nullable()
            ->build();

        $builder->createField('utmTerm', Types::STRING)
```

2022-06-20 11:17 UTC, escopecz commented on app/bundles/AssetBundle/Model/AssetModel.php
> +        $download->setUtmTerm($request->get('utm_term') ?? null);
Setting default value of `null` like this is not necessary as the get method returns `null` as the default value automatically.
```suggestion
        $download->setUtmCampaign($request->get('utm_campaign'));
        $download->setUtmContent($request->get('utm_content'));
        $download->setUtmMedium($request->get('utm_medium'));
        $download->setUtmSource($request->get('utm_source'));
        $download->setUtmTerm($request->get('utm_term'));
```

2022-06-20 11:17 UTC, escopecz commented on app/bundles/PageBundle/Controller/PublicController.php
> +                }
Isn't this if opposite of what it should do? If it contains `&` then append the GET param with `&`? Also, check the warning in the docs for this function: https://www.php.net/manual/en/function.strpos.php

It's better to compare with `false` as the `0` value can cause unwanted behavior.

2022-06-20 11:17 UTC, escopecz commented on app/bundles/PageBundle/Model/TrackableModel.php
> +            $url = preg_replace('/{(\S+?)}/i', '', $url);
What is the intent behind this replace? Do you expect whitespaces to be in the links? If so, shouldn't those be replaced with `+` or even better use https://www.php.net/manual/en/function.urlencode.php for the values in the GET params?

2022-06-20 11:17 UTC, escopecz commented on app/bundles/ReportBundle/Translations/en_US/messages.ini
> +mautic.report.field.utm_term="UTM Term"
Can you use these translation strings from the LeadBundle instead?
```
mautic.lead.report.utm.campaign="UTM campaign"
mautic.lead.report.utm.content="UTM content"
mautic.lead.report.utm.medium="UTM medium"
mautic.lead.report.utm.source="UTM source"
mautic.lead.report.utm.term="UTM term"
```
I understand that this way there is dependency of the ReportBundle on the LeadBundle but this dependency exists already in so many places that the ReportBundle cannot work without LeadBundle anyway. I think we should use what's already there and save some time for our translators.

2022-06-28 14:29 UTC, RCheesley commented
@tomekkowalczyk it would help testers a lot if you were able to give a couple of clear steps as to how they might test this PR. I notice you already have some feedback from code review to address as well :)

2022-06-28 15:11 UTC, RCheesley commented
In testing this PR, I was not getting any result at all in the asset downloads table despite the asset showing four downloads:
![mautic ddev site_8037 _ db _ db _ assets _ phpMyAdmin 5 1 3](https://user-images.githubusercontent.com/2930593/176215197-db2351ae-7dab-499a-ba06-47c193a3196f.png)
![mautic ddev site_8037 _ db _ db _ asset_downloads _ phpMyAdmin 5 1 3](https://user-images.githubusercontent.com/2930593/176215214-48eee5f8-e982-4a0a-beab-704c84e949f4.png)

I am not sure why this is the case but would appreciate some proper testing instructions before wasting more time trying to understand myself!

2023-03-21 11:00 UTC, tomekkowalczyk commented
@escopecz, @RCheesley 

I rewrote the solution to version 5.x and also added tests and applied the tips above https://github.com/mautic/mautic/pull/12098

2023-03-21 11:00 UTC, closed without merging