Contacts should export via mail instead of immediate download
mautic/mautic pull request #11272
Opened 2022-06-21 10:32 UTC by tejasync

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ❌ 
| New feature/enhancement? (use the a.x branch)      | ✅ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ✅ 
| Automated tests included?              | ✅  
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR puts active download of contact exports (CSV only) to be queued, and email link is sent over email to download the exports. This enables users to download large contacts without hampering the UX like longer times to get the export file and freezing the page etc. Excel export will work as it is.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run the migration using `ddev exec bin/console doctrine:migrations:execute --up 20220429091934`
3. Go to contacts page
4. Click on export CSV from the menus (Try different filters like ids, emails etc)
5. Check notification if appropriate message is displayed
6. Run `php bin/console mautic:contacts:scheduled_export --ids=<comma separated contact_export_scheduler ids>` (ids are optional)
7. Once email is received, click on link to download the expected contact export file and also check notification for correct message
8. Verify if data in the file is correct
9. Remove the migration if required using `ddev exec bin/console doctrine:migrations:execute --down 20220429091934`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203523494025843

2022-06-28 16:35 UTC, RCheesley commented
Thanks for the PR @ts-navghane - looks like there are some test failures to resolve with this one.

2022-07-04 16:30 UTC, RCheesley requested changes
Thanks for the PR @ts-navghane - a useful feature for the higher volume Mautic users.

A couple of things that I think we need to take into consideration:

* The average user of Mautic would be really inconvenienced if, every single time they want to do an export, they have to go find the ID of the scheduled export, log in at the command line, fire off the cron. We should be able to fire off **any** pending exports using the command without any arguments, in my opinion. Currently running without the ID specified when there is a pending export does nothing.
* Should this be behind a global config switch to give the user an option to download directly or download with the cron task, like we do with sending emails for exactly? I can imagine that many would not have problems with performance and would prefer an immediate download over waiting for the cron job to fire. @jos0405 any thoughts on this from the user perspective?
* Some of the language strings were a bit confusing / not grammatically correct - I have suggested changes for those
* We need to have a documentation PR for this - can you please do it on the updated user docs [here](https://github.com/mautic/user-documentation/blob/main/docs/configuration/cron_jobs.rst)? Thanks!
* If you have migrations in the PR, it _really_ helps testers if you provide them with the specific instructions to apply and reverse the migration. I have edited the PR description after getting an SQL error on testing and not realising there was a migration to apply ;)

Other than that, the PR works as expected. I was able to export contacts as a CSV and the email was correctly queued, it was sent as expected and the link to download worked perfectly!

Thanks again for the PR @ts-navghane - a great feature for those using Mautic at scale!

2022-07-04 16:30 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/flashes.ini
> +mautic.lead.export.being.prepared="File is getting processed. The file will be send to your email address '%user_email%' You can download the file from the link provided in the email."
```suggestion
mautic.lead.export.being.prepared="File is queued for processing. The file will be sent to your email address '%user_email%' You can download the file from the link provided in the email."
```

We should ensure we are setting expectations for the users and tell them it is queued for processing. Small grammar fixes also :)

2022-07-04 16:30 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/messages.ini
> +mautic.lead.export.being.prepared="File is getting processed. The file will be send to your email address '%user_email%' You can download the file from the link provided in the email."
```suggestion
mautic.lead.export.being.prepared="File is queued for processing. The file will be sent to your email address '%user_email%' You can download the file from the link provided in the email."
```

2022-07-04 16:30 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/messages.ini
> +mautic.lead.export.email_subject="Contact Exported: %file_name%"
```suggestion
mautic.lead.export.email_subject="Contacts export: %file_name%"
```

2022-07-04 16:30 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/messages.ini
> +mautic.lead.export.email="Your requested contact export: <a href="%link%">%label%</a>."
```suggestion
mautic.lead.export.email="Your requested Contacts export: <a href="%link%">%label%</a>."
```

2022-07-14 09:22 UTC, jos0405 commented
Great feature!
I'm trying to load this in Gitpod, but recieving the following error:
![image](https://user-images.githubusercontent.com/4246909/178949421-71ae00a5-4fda-46fc-ad91-e858fb0437d0.png)

@RCheesley any tips how to fix this?

2022-12-09 14:07 UTC, ts-navghane commented
Hello @RCheesley,
> The average user of Mautic would be really inconvenienced if, every single time they want to do an export, they have to go find the ID of the scheduled export, log in at the command line, fire off the cron. We should be able to fire off any pending exports using the command without any arguments, in my opinion. Currently running the cron without the ID specified when there is a pending export does nothing.

Now the CRON can be executed without the IDs. For e.g. `bin/console mautic:contacts:scheduled_export`.

### Screenshot 1:
![Screenshot 2022-12-09 at 19 22 59](https://user-images.githubusercontent.com/54406786/206717632-13c7fc6d-ff12-40a6-8aff-b61eacbb3b7c.png)
---

> Should this be behind a global config switch to give the user an option to download directly or download with the cron task, like we do with sending emails for example? I can imagine that many would not have problems with performance and would prefer an immediate download over waiting for the cron job to fire. 

This feature can be turned ON/OFF by using global config in Settings > Configuration > Contact Settings > Export Settings.

### Screenshot 2:
![Screenshot 2022-12-09 at 16 46 05](https://user-images.githubusercontent.com/54406786/206719223-04c81402-fa7d-4ad7-92aa-5fc9b6bf3ecc.png)
---

> Some of the language strings were a bit confusing / not grammatically correct - I have suggested changes for those.

Done.
---

> We need to have a documentation PR for this - can you please do it on the updated user docs here? Thanks!

Will be updating this soon!
---

Kindly review/re-test.
Thank you.

2023-01-11 09:44 UTC, RCheesley commented
@fakela could you assist with the documentation for this PR so that we can consider it for merging?

2023-03-03 12:40 UTC, mabumusa1 commented
@ts-navghane can you please fix the conflicts on this PR? I love this feature and can not wait to use it

2023-03-05 00:36 UTC, fakela commented
> @fakela could you assist with the documentation for this PR so that we can consider it for merging?

sure, i will look into it

2023-03-09 06:33 UTC, ts-navghane commented
@mabumusa1 Conflicts are resolved, please take a look. Hoping to get this PR merged soon.

2023-03-10 13:12 UTC, escopecz requested changes

2023-03-10 13:12 UTC, escopecz commented on app/bundles/LeadBundle/Entity/ContactExportScheduler.php
> +    private int $id;
I think this should be
```suggestion
    private ?int $id = null;
```
And then we can avoid ignoring
```
- '#Property [a-zA-Z0-9\\_]+::\$id is never written, only read.#'
```
in phpstan.neon

In fact, I'd recommend to make all entity properties nullable. The only properties that can have a strict type are those set via constructor. Otherwise accessing them like
```php
$contactExportScheduler = new ContactExportScheduler();
$contactExportScheduler->getId();
```
will end up with an error as the value of the property is not set to an int before accessing it.

2023-03-14 11:19 UTC, ts-navghane commented
@escopecz I have committed your suggestion regarding nullable id and removed the ignore error from phpstan.neon file.
But, the build is failing because it is not able to upload the coverage report. Could you please rebuild this PR?

2023-03-14 11:52 UTC, escopecz commented
Thanks Tejas! I meant that all typed entity properties must either be:
1. set the default value for the property directly
2. set the property value in constructor
3. or must be nullable

From my experience there will be a bug sooner or later that some code will try to access an entity property that is in undefined state. Can you make sure that the new entity properties use one of the 3 options?

2023-03-14 14:43 UTC, escopecz approved these changes
Thank you Tejas! I see no other issues in the code 👍

2023-03-15 14:11 UTC, kuzmany requested changes
It works for me for the enabled or disabled option in the configuration.
Just If it's enabled, I do not see any notification about export starting in the background.

2023-03-15 14:22 UTC, tejasync commented
@kuzmany I can see the notification banner whenever I export CSV with background option turned ON.
![Screenshot 2023-03-15 at 19 49 22](https://user-images.githubusercontent.com/54406786/225338180-fd22a4cf-8b32-442a-abae-d5d9e391d05d.png)

Also, I can see the notification in the bell icon (you need to refresh or click on some other page).
![Screenshot 2023-03-15 at 19 49 37](https://user-images.githubusercontent.com/54406786/225338218-95dcb451-634b-4288-99db-bfd0a17441a2.png)

2023-03-15 14:37 UTC, kuzmany approved these changes
Everything works . Nice feature

2023-03-15 15:25 UTC, merged