Added attachment, cc and bcc possibilities to direct mail
mautic/mautic pull request #11297
Opened 2022-06-28 08:02 UTC by dev-marcel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [No]
| New feature/enhancement? (use the a.x branch)      | [Yes]
| Deprecations?                          | [No]
| BC breaks? (use the c.x branch)        | [No]
| Automated tests included?              | [No] 

| Issue(s) addressed                     | Fixes #... 

#### Description:

Makes it possible to add attachment (via upload and file manager), BCC and CC for direct mail

![image](https://user-images.githubusercontent.com/11071510/176126239-a0a7f40f-baca-492a-a2ef-7ee7f61a83f6.png)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make sure you can send mail
3. Make sure you got an attachment
4. Add a contact
5. Click on the arrow before a contact and click send mail
6. Add bcc, cc and attachments.

2022-06-30 13:42 UTC, automatyzuj commented
Tested on M4.12
![image](https://user-images.githubusercontent.com/104569506/176692368-8c7b27bc-f055-43a5-9821-eaa1a2d89e9b.png)
Works perfectly.

PS Perfect timing, today client ask me about this funcion! :)

2022-06-30 13:45 UTC, automatyzuj approved these changes
Works with M4.12

2022-06-30 13:50 UTC, RCheesley commented
Thanks for the PR @dev-marcel - one thought, would you not want to track the attachments (eg as an Asset in Mautic)? I would have thought that might be preferable to a straight upload.

Also, will need to base this on the 5.x branch as the next feature release will be 5.0.

2022-06-30 14:38 UTC, dev-marcel commented
Hi Ruth,

it is possible to add both (local and existing asset) or one of both, but tracking for direct mails is not yet fully supported. Also we can't add an attachment as attachment and track it. That is technically imposible. If we would like to do that, than it has to go with an link or button in the e-mail. 

So good thinking but this is as good as it gets. Will check if i can make an 5.0 version.

2022-06-30 14:55 UTC, RCheesley commented
OK thanks for getting back to me so quickly!

2022-06-30 18:00 UTC, kuzmany commented
@RCheesley 

It's also mentioned in tooltip of attachment 

> Note that the assets added to the email as an attachment cannot be tracked. The asset file copy is sent with the email. Link the attachment in the email content instead if you want to track downloads.

![image](https://user-images.githubusercontent.com/462477/176746050-ffb7cb3c-4182-48ff-a279-54aab33120c5.png)

2022-06-30 18:09 UTC, kuzmany requested changes

2022-06-30 18:09 UTC, kuzmany commented on app/bundles/LeadBundle/Controller/LeadController.php
> +                            $model = $this->factory->getModel('asset');
`$this->factory` is deprecated-. You should use `$this->getModel('asset.asset')` or  `$this->get('mautic.asset.model.asset')`. Or better use initialize method allow use variable enywhere same like here https://github.com/mautic/mautic/blob/b05c93c2d96ca04220357fc8b2bee53e67469701/app/bundles/FormBundle/Controller/FieldController.php#L42 

Also we don't need call model in foreach cycle few times. We can move it above or to initialize method

2022-06-30 18:09 UTC, kuzmany commented on app/bundles/LeadBundle/Controller/LeadController.php
> +                                $asset->setUploadDir($this->factory->getParameter('upload_dir'));
Same like comment above. You should use `$this->get('mautic.helper.core_parameters')`

2022-07-01 05:21 UTC, kuzmany requested changes

2022-07-01 05:21 UTC, kuzmany commented on app/bundles/LeadBundle/Controller/LeadController.php
> +                        // Set BCC/CC
I think these lines need to check values, If I let it empty, then return error for me 

>  500 Internal Server Error - PHP Warning - count(): Parameter must be an array or an object that implements Countable 

```
/app/bundles/EmailBundle/Helper/MailHelper.php:1156 at
Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '2', 'PHP Warning - count(): Parameter must be an array or an object that implements Countable', '/var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php', '1156', array('addresses' => null, 'name' => null) )
/app/bundles/EmailBundle/Helper/MailHelper.php:1156 at count ( null )
/app/bundles/LeadBundle/Controller/LeadController.php:1436 at Mautic\EmailBundle\Helper\MailHelper -> setBcc ( null )
```

2022-07-08 14:07 UTC, escopecz requested changes
Thanks for this feature, it's a great idea! Please check the code review comments and CI checks. Another question is what will happen with the files sent as an attachment. From what I understand they will be stored in the media/attachment folder indefinitely. Is that true? Can they be removed after send?

2022-07-08 14:07 UTC, escopecz commented on app/bundles/LeadBundle/Controller/LeadController.php
> +                        $assetsIds  = (!empty($email['assetAttachments'])) ? $email['assetAttachments'] : [];
Shorter syntax can be used:
```suggestion
                        $assetsIds  = $email['assetAttachments'] ?? [];
```

2022-07-08 14:07 UTC, escopecz commented on app/bundles/LeadBundle/Controller/LeadController.php
> +                                $assets[$asset->getId()] = $asset;
Is it necessary to put the asset ID as the array key? I don't see it being used.

2022-07-20 21:54 UTC, automatyzuj commented
Hello @ dev-marcel, unfortunately I found something in your add-on. When I send emial with PDF attachment from emails section (for example as test) everything works fine. But when I use your add-on sent PDF isn't readable for my explorer. Also PDF has more weight (4,3 mb in your add-on vs 3,12 in normal).

I tried this with 2 other files and simple names like 123.pdf. Always PDF is finally impossible to open.

M4.12
PHP Version 7.4.29
AWS as emial provieder

2025-07-17 10:52 UTC, jos0405 commented
This is a great feature.
Can someone rebase this into M7?

2026-06-08 18:23 UTC, andersonjeccel commented
Hey, I'm seeing this PR has been quiet for a while and the last update was in 2025, so it looks like it has been stalled for some time. We're doing a little cleanup in the queue so the team can focus on PRs that are still being actively worked on and are closer to merge. If this was not the right call, I'd be happy to see it reopened and updated.

2026-06-08 18:23 UTC, closed without merging