WIP: Disabled send button If sending is in background
mautic/mautic pull request #11351
Opened 2022-07-23 09:08 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

If email is sending in background, then we need disable send button to avoid send duplicate emails. This happen already few times for customers.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Setup Publish UP of segment email date lower like now
3.  Go to detail of email and see send button is disabled

2022-07-28 20:06 UTC, RCheesley requested changes
This is a good idea, but if I click on the button I do still get to the send interface.

Screen recording: https://watch.screencastify.com/v/vZNhRaGaILyhT68icd1c

We should prevent this happening at all if we are going to block them from sending the emails.

2022-07-28 20:06 UTC, RCheesley commented on app/bundles/EmailBundle/Translations/en_US/messages.ini
> +mautic.email.send.disabled="Email is sending in background. Sending from browser is disabled to avoid duplicate emails"
```suggestion
mautic.email.send.disabled="Email is sending in the background. Sending from the browser is blocked to prevent duplicate emails"
```

2022-08-04 18:38 UTC, kuzmany commented
@RCheesley should be better now

2022-08-12 13:50 UTC, volha-pivavarchyk submitted a review, later dismissed
Works as described now
![image](https://user-images.githubusercontent.com/96085911/184367258-77be6627-ed24-4bd2-9359-e662cac73888.png)

2022-08-15 07:56 UTC, escopecz commented
It will disable the button if the email is published and the publish up date is set and less than now. Is that all we need to check? The instance must also have a cron job to process the emails in the background, right? This is not checked (and I'm not sure how to check it easily) so if the instance does not have the cron job configured then this will prevent the users to send the email if they set the publish up date to some valule.

Another question is why is there the `($this->getPublishUp() < new \DateTime()` part? Is it allowed to hit the send button when the send in the background is in progress?

2022-08-16 12:41 UTC, kuzmany commented
@escopecz 


> It will disable the button if the email is published and the publish up date is set and less than now. Is that all we need to check? The instance must also have a cron job to process the emails in the background, right? This is not checked (and I'm not sure how to check it easily) so if the instance does not have the cron job configured then this will prevent the users to send the email if they set the publish up date to some value.

We are not able to check cron job. I know It's not perfect but avoid the issue what happen few times.

Probably would be better make warning on sending page.

> Another question is why is there the ($this->getPublishUp() < new \DateTime() part? Is it allowed to hit the send button when the send in the background is in progress?

If publishUp is lower like now, then command in background start sending email. In this case button is blocked

2022-08-16 15:32 UTC, escopecz approved these changes
@kuzmany gotcha. Thanks for the explanation. This is good improvement in my eyes. Users can always change the publish up date to enable the button as a workaround if they don't have the cron job configured. And if they don't have the cron job configured there is no reason to use the publish up date. So this would be an edge case anyway.

Thanks! 👍

2022-08-16 15:33 UTC, escopecz commented
@RCheesley are you OK with merging this?

2022-08-16 15:43 UTC, RCheesley commented
I would be more comfortable if we can make it really clear to users why this might be greyed out in the documentation as folks may not really get the publish-up functionality and how that impacts sending - pinging @favour-chibueze to incorporate into the new docs (but this might need to go in the current documentation in the interim).

2022-08-16 19:57 UTC, favour-chibueze commented
> I would be more comfortable if we can make it really clear to users why this might be greyed out in the documentation as folks may not really get the publish-up functionality and how that impacts sending - pinging @favour-chibueze to incorporate into the new docs (but this might need to go in the current documentation in the interim).


Are we adding this new functionality to the docs

2022-08-26 09:29 UTC, RCheesley commented
@favour-chibueze when this PR is merged, we will need to document the fact that the button will be greyed out if a send should already be in progress. So, when you get to the Email section we should factor this in.

2022-08-26 09:37 UTC, RCheesley approved these changes
Thanks for fixing the button still being clickable - just re-tested and all is good, so we are good to merge!

2022-08-29 11:10 UTC, merged