Notify user that after enabling API they must clear cache to load new routes.
mautic/mautic pull request #11410
Opened 2022-08-23 21:47 UTC by biozshock

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Issue(s) addressed                     | #10568 

#### Description:
While we wait for the decision on another PR that addresses the issue.
Add a note that users must clear cache after enabling API.
Please check wording.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. See the message is displayed on the API configuration page.

2022-08-26 13:25 UTC, RCheesley requested changes
Thanks for the PR @biozshock, hopefully this will reduce the number of support questions!

Works as intended - please see some grammar suggestions.

![screenshot-8080-biozshock-mautic-ekweucigm38 ws-eu63 gitpod io-2022 08 26-14_23_38](https://user-images.githubusercontent.com/2930593/186913774-2d602acc-1314-4ef1-8175-880eb79fd33c.png)

2022-08-26 13:25 UTC, RCheesley commented on app/bundles/ApiBundle/Translations/en_US/messages.ini
> +mautic.api.config.form.api.cache_notice="After enabling/disabling API you must clear cache using console command <code>bin/console cache:clear</code>."
```suggestion
mautic.api.config.form.api.cache_notice="After enabling/disabling the API you must clear your cache using the console command <code>bin/console cache:clear</code>."
```

2022-08-26 14:53 UTC, nick-vanpraet commented
![image](https://user-images.githubusercontent.com/7923739/186932614-78387e6e-8b5d-4d72-a352-41c81bf7e1b7.png)

Matches the post-grammar suggestions text, all good.

2022-08-26 14:56 UTC, nick-vanpraet approved these changes
Looks good to me

2022-08-27 13:09 UTC, kuzmany commented
I am not sure If this message:

> After enabling/disabling the API you must clear your cache using the console command bin/console cache:clear

Is helpful for end users. Usually they don't have access to SSH and related know how.
Probably ask to you administrator for clear cache would be much better

2022-08-30 12:42 UTC, escopecz commented
I'd like to avoid adding this alert and rather fix the issue. See https://github.com/mautic/mautic/pull/11420

2022-08-30 14:19 UTC, escopecz commented
Closing in favore of https://github.com/mautic/mautic/pull/11420

2022-08-30 14:19 UTC, closed without merging