Fix password reset enumeration users
mautic/mautic pull request #11417
Opened 2022-08-29 07:49 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ v]
| New feature/enhancement? (use the a.x branch)      | [x ]
| Deprecations?                          | [x ]
| BC breaks? (use the c.x branch)        | [x ]
| Automated tests included?              | [ x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Risk level:  **MEDIUM**
Impact: 	**Enumerate users**
Vulnerability use conditions: 	**Access to login page**

There are different repsonses when we are trying to reset password in using an existing user, and when the account doesn’t exist.

**Existing user:**
![image](https://user-images.githubusercontent.com/39382654/187150581-a6a332a0-b519-40df-85a5-8ac97c8fd3d9.png)

![image](https://user-images.githubusercontent.com/39382654/187150904-d417f1cc-8cda-4b17-801f-2dcc80ab710d.png)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2022-09-07 15:32 UTC, escopecz requested changes
Thanks for taking care of this issue! I don't quite understand the solution though. If the user exists you get message:

> If this user exist, you have successfully reset your password. You may now login.

If the user does not exist then you get redirect without a message. So the responses are still different whether the user exists or not.

Please write a functional test for those scenarios asserting that the output is the same. That should make it clear. It is also requirement to get the PR merged.

2022-09-07 15:32 UTC, escopecz commented on app/bundles/UserBundle/Controller/PublicController.php
> -                    $form['identifier']->addError(new FormError($this->translator->trans('mautic.user.user.passwordreset.nouserfound', [], 'validators')));
Please remove the `mautic.user.user.passwordreset.nouserfound` message from the ini file too as you removed all its usages.

2022-10-03 09:50 UTC, tomekkowalczyk commented on app/bundles/UserBundle/Controller/PublicController.php
> -                    $form['identifier']->addError(new FormError($this->translator->trans('mautic.user.user.passwordreset.nouserfound', [], 'validators')));
oki

2022-10-03 09:55 UTC, tomekkowalczyk commented
@escopecz 
`If the user does not exist then you get redirect without a message. So the responses are still different whether the user exists or not.`

The point is that the answers vary depending on whether the user exists or not. This way the attacker can check which email addresses are in the system

2022-10-03 12:31 UTC, escopecz commented
> @escopecz `If the user does not exist then you get redirect without a message. So the responses are still different whether the user exists or not.`
> 
> The point is that the answers vary depending on whether the user exists or not. This way the attacker can check which email addresses are in the system

That's the point I'm making. This PR does not solve this problem.

2022-10-04 07:28 UTC, tomekkowalczyk commented
@escopecz 

Can you justify why in your opinion it does not solve this problem? We have a unified response, regardless of whether the user exists or not, we receive the same message. Additionally, no redirection to the login page if the user existed in the database. If the PR does not solve the problem, ask for suggestions on how to solve the problem.

2022-10-04 09:30 UTC, escopecz submitted a review, later dismissed
I was reading the changes poorly. The message will be the same whether the user exists or not and it will always redirect to the login path. All good from code perspective. Thanks! 👍

2022-10-04 09:31 UTC, escopecz commented
Let me know if you need some help with the tests.

2023-03-03 13:03 UTC, tomekkowalczyk commented
@escopecz Tests have been added

2023-03-06 15:14 UTC, escopecz reviewed
Looks great! Please fix the CS check.

2023-03-20 13:54 UTC, tomekkowalczyk commented
@escopecz I fixed CSFixer

2023-03-20 13:56 UTC, tomekkowalczyk commented
We have build CI error: `There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue`

2023-03-20 15:58 UTC, escopecz commented
That's a network issue. I'm re-running the failed job. Should be green in 10 minutes

2023-03-20 15:59 UTC, escopecz approved these changes, later dismissed
The code looks good 👍

2023-04-21 11:29 UTC, tomekkowalczyk commented
Hi, can we merge the changes now?

2023-04-24 09:26 UTC, escopecz commented
@tomekkowalczyk  It needs 2 things:
1. Resolve the conflict
2. One more approval from any tester.

2023-04-24 12:04 UTC, tomekkowalczyk commented
@annamunk You will verify the changes?

2023-04-27 14:58 UTC, annamunk approved these changes
Works well ✔️ Mautic shows the same message for existing and non-existing user.

![reset_2](https://user-images.githubusercontent.com/102536220/234901948-05e571c7-4bf7-412a-b100-af1f65430834.jpg)
![reset_1](https://user-images.githubusercontent.com/102536220/234901957-6ffd83bb-8cc1-4e08-8261-a9541f53fce1.jpg)

2023-04-28 07:48 UTC, escopecz approved these changes
Thank you! Great work! 👍

2023-04-28 08:00 UTC, merged