Hubspot - Fix errors when the API returns a 401 code
mautic/mautic pull request #11416
Opened 2022-08-28 17:06 UTC by Cr7t3K

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     | Fixes #11064

#### Description:

This PR fixes the infinite loading bug of the Hubspot plugin when it return a 401 error or other unmanaged code.
![Hubspot-error-loading](https://image.noelshack.com/fichiers/2022/34/7/1661705694-hubspot.png).

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Setup Hubspot plugin with a valid api key
3. Disable your hubspot api key
4. Return to the plugin, an error message indicates the error encountered with the api

2022-08-29 11:02 UTC, PierreAmmeloot submitted a review, later dismissed

2022-09-07 15:22 UTC, escopecz requested changes
Thanks for the fix! Please write PHPUNIT tests for this new code. It is requirement for the PR to be merged.

2022-09-07 15:22 UTC, escopecz commented on plugins/MauticCrmBundle/Api/HubspotApi.php
> +                throw new ApiErrorException($message);
Why would you throw an exception with `$message = null`?

2022-09-07 15:34 UTC, escopecz commented
Also please rebase on 4.4 branch which is for bug fixes and check the failing CI checks. Let me know if you need help with anything.

2022-09-29 08:31 UTC, escopecz approved these changes
I see no issue with the code. Thank you! 👍

2022-09-29 15:25 UTC, PierreAmmeloot approved these changes

2022-09-30 08:01 UTC, merged