Configurable assets stream extensions
mautic/mautic pull request #11474
Opened 2022-09-14 06:18 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Follow up for https://github.com/mautic/mautic/pull/11043
Some extensions have to be download everytime, for example ICS. 
Then we've added list of extensions to display in browser by default. Others are download as before

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create PDF asset
3. Check If download link open the PDF
4. Create CSV asset
5. Check If download link download the CSV

2022-09-14 07:00 UTC, mollux requested changes

2022-09-14 07:00 UTC, mollux commented on app/bundles/AssetBundle/Controller/AssetController.php
> +        $fileStorageEvent = new StorageAssetFileEvent($activeAsset->getFilePath());
this class isn't referenced in a `use` statement, so this will fail

2022-09-14 19:18 UTC, volha-pivavarchyk approved these changes, later dismissed
Works well. Assets are streamed as expected

2022-09-16 09:31 UTC, kuzmany commented
I've rebased it based on 5.x

2022-09-27 18:45 UTC, RCheesley submitted a review, later dismissed
Thanks for this, I recall having this discussion at the time the PR was created!

This PR will need documentation to be added to the configuration section, pinging @favour-chibueze because of course we need to add more to that epic configuration PR for the new docs! 😅

2022-09-27 19:26 UTC, kuzmany commented
@RCheesley in fact, this do not have configuration.  It just allow for any company change list of stream able extensions by parameter.

2023-01-23 10:20 UTC, RCheesley commented
Looks like this PR needs some attention - conflicts and failing tests to address.

2023-06-23 05:47 UTC, kuzmany commented
Conflicts resolved and documentation added.

2023-08-04 14:08 UTC, RCheesley approved these changes
Works as explained - PDF is opened in a new tab, CSV is downloaded.

2023-08-04 14:27 UTC, escopecz approved these changes
👍 the code makes sense

2023-08-04 14:36 UTC, merged