Capture exceptions it's anything fails in command segments:update
mautic/mautic pull request #11497
Opened 2022-09-23 09:38 UTC by vgpastor

Version 4.4

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| Issue(s) addressed                     | Fixes  #11495 

#### Description:

Capture exception to prevent segments:update flow fails and don't update other segments that doesn't have errors

#### Steps to test this PR:

Create an error segment how #11493
Update all the segments and this works fine , only the error segment are locked.

2022-09-23 12:22 UTC, galvani commented
From my point of view; the issue you mentioned should be resolved differently. exit code 1 is correct and should be returned. your try catch would simply return exit code 0. Secondly you silently ignore the exception. No record in log, only output is to console.

2022-10-04 13:05 UTC, escopecz requested changes
I agree with @galvani. The command must return 1 as it has failed to do its job. And the error must be written in the error log.

Also, each PR must contain PHPUNIT tests confirming that the change is working. Please add the tests. Let me know if you need some help with that.

2022-12-23 18:34 UTC, mabumusa1 commented
Following this issue, it is valid and needs a solution

2023-01-03 11:21 UTC, escopecz commented
This can be done properly with:
1. Log all the errors with stack traces to the logs
2. Output the errors to the console (done by this PR)
3. The command must return `1` if some exception is caught. It cannot end with `0` as successful if one or more segments are failing.

2025-10-03 00:05 UTC, closed without merging