Add contact owner message to duplicate message
mautic/mautic pull request #11526
Opened 2022-09-29 22:01 UTC by JakubHelis

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ False]
| New feature/enhancement? (use the a.x branch)      | [ True]
| Deprecations?                          | [ None]
| BC breaks? (use the c.x branch)        | [None ]
| Automated tests included?              | [ No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 

#### Description:
I added Mautic owner within the message that appear when user try to add contact with email, that already exists in database. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Open contacts.
3. Add new contact, remember the email.
4. Try to add new contact using the same email.
5. Message should appear

2022-10-05 09:17 UTC, escopecz requested changes
Code looks good!

Please add a functional test similar to https://github.com/mautic/mautic/blob/09702e10e92a3a6d6b4b7246c392a15df1a3626f/app/bundles/EmailBundle/Tests/Functional/PendingCountTest.php that will ensure this works as intended with and without the owner.

Let me know if you need a hand with it! To run functional tests you have to copy the .env.dist file to .env file and fill in credentials to a testing database. 

The test can be executed by `composer test -- --filter NameOfYourTest`

2022-10-05 09:19 UTC, escopecz commented
Oh and please rebase on the 5.x branch. There won't be any feature release for Mautic 4 anymore.

2022-10-21 09:22 UTC, RCheesley commented
@JakubHelis thanks for the PR - please can you take note of the feedback so that we can look at reviewing and merging?

It needs:

- Rebasing on 5.x branch
- Functional test per the suggestions in this comment: https://github.com/mautic/mautic/pull/11526#pullrequestreview-1131128572

If you need any help with either please let us know, we're here to help!

2025-07-17 11:01 UTC, jos0405 commented
Can we have this fixed and rebased to M7?

2026-06-08 18:22 UTC, andersonjeccel commented
Hey, I'm closing this for now because it looks like the PR has been idle for quite a while and hasn't had recent updates since 2025. We're cleaning up older items so reviewers can spend time on PRs that are still active and near the finish line. If this should stay open, feel free to reopen it.

2026-06-08 18:22 UTC, closed without merging