Segment - Fix filter URL Visited with regex and more
mautic/mautic pull request #11541
Opened 2022-10-05 09:35 UTC by Cr7t3K

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [Y]
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #11427 

#### Description:

This PR fixes the problem with regex filters, like the visited url.
The filter did not take into account the regex, and display the same number of contacts no matter the regex.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Login
4. Create two segments with filter "Visited URL" and "regexp", but not same expression (depends on your current data in table page_hits)
5. Update your two segments with command
6. You will see that the filters work
7. Enjoy

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

PR funded by @PierreAmmeloot from [WebAnyOne](https://www.webanyone.net/)

2022-10-05 18:21 UTC, PierreAmmeloot approved these changes

2022-10-07 08:24 UTC, escopecz requested changes
I added a small request before we merge this PR. Also, please create a duplicate PR against the 5.x branch to confirm it will work there too and all conflicts will be solved. Thanks for the functional tests! It makes me a lot more confident that it works!

2022-10-07 08:24 UTC, escopecz commented on app/bundles/LeadBundle/Segment/ContactSegmentFilterCrate.php
> +    public function isBehaviorsType()
```suggestion
    public function isBehaviorsType(): bool
```

2022-10-10 09:22 UTC, escopecz approved these changes
Thank you! 👍

2022-10-10 09:30 UTC, escopecz commented
@Cr7t3K create please also PRs with these commits against the 5.x branch. It may need rebase or cherry-pick. See https://github.com/mautic/mautic/compare/5.x...Cr7t3K:fix-segment-filter-regex

2022-10-10 09:33 UTC, escopecz commented
Aha, you already did. https://github.com/mautic/mautic/pull/11556 Thank you!

2022-10-10 10:08 UTC, merged