Autowiring for all!
mautic/mautic pull request #11587
Opened 2022-10-13 15:14 UTC by escopecz

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [N]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [not-ish]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Symfony can autowire and autoconfigure services for some time. Here is the doc:

https://symfony.com/doc/4.4/service_container.html

Mautic was still continuing the old way where each service must be configured in the config.php file with all its dependencies. It is a bit daunting to keep all the dependencies up to date in the config file. So this PR is making the developers work a bit nicer.

1. New services do not need to be configured in config.php files
2. Old services can drop their parameters and keep the aliases for BC
3. Did you know that commands were autowired since M3? We still configured them in config.php files...
4. So far this PR focuses only on internal bundles. But we can do the same for plugins too.

The biggest problem here is with classes that are not services. Like DTO, value objects, events (which is also DTO) or exceptions. We have to exclude those. And that's why there is a big list of excluded folders and files in the `app/config/services.php` file. 

If we'd want to reduce this list we'd have to move them to some excluded folder like `DTO` or `Exception` in the bundle dir. This may be BC change for plugins if we decide to autowire plugins too. But I think it's worth the benefit.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. The container build would fail if there would be a bug in the changed code. So Mautic wouldn't even load.
3. But I was testing with `bin/console debug:autowiring` command to show me that all services are wired correctly. Clear cache in between runs and changes you make.
4. As a PoC I removed service definition for the command `mautic:segments:update` and service it uses to show that it can be done. So you can run that it works.

2022-10-13 19:21 UTC, biozshock commented
Maybe instead of `serviceAliases` we should add a pass:
```
class AliasPass implements CompilerPassInterface
{

    public function process(ContainerBuilder $container): void
    {
        foreach ($container->getDefinitions() as $definitionId => $definition) {
            if ($definition->isAbstract()) {
                continue;
            }

            if ($definition->getClass() === '' || $definition->getClass() === null) {
                continue; // most of these are childDefinitions
            }

            if ($definitionId === $definition->getClass()) {
                continue;
            }

            if ($container->hasAlias($definitionId) || $container->hasAlias($definition->getClass())) {
                continue;
            }

            if (strpos($definitionId, '\\') !== false) {
                continue;
            }
            
            $container->removeDefinition($definitionId);
            $container->setDefinition($definition->getClass(), $definition);

            $container->setAlias($definitionId, new Alias($definition->getClass(), $definition->isPublic()));
        }
    }

}
```

2022-10-13 19:26 UTC, biozshock commented
Also would it be possible to refactor `config.php` files to symfony `services.php` and load classes from there? That will allow to get rid of a huge excludes in `app/config/services.php` and will allow to apply this improvement to plugins? e.g. if the services.php exists the code will be symfony autoloaded and if not then the older config.php will be used.

2022-10-14 10:23 UTC, escopecz commented
@biozshock thanks for the suggestions! So you suggest to leave the service configuration as is, maybe remove the `arguments` array and leave the `class` and service name?

The short term plan I have in mind is that we'd enable autowiring to be used for M5 but the service aliases would still exit. In M6 we'd remove the aliases too. Is that something you and others agree with?

Allowing bundles and plugins to configure their own excludes would be great. I'll look into it.

2022-10-14 12:30 UTC, escopecz commented
@biozshock I'm playing with a bundle having option to have its own `Config/service.php` to exclude its own files. I'm afraid we'll have to choose whether we want to let the Core bundle configure it for all bundles and plugins or force each bundle to configure its own namespace. It cannot be both. What would you prefer?

2022-10-14 13:06 UTC, biozshock commented
@escopecz sure thing - each bundle must configure itself. As only bundle knows what's need to be be configured and how.
As far as i can see the services.php will contain:

1. a default configuration autowire:true, autoconfigure: true, public: false
2. a bunch of aliases to current string service names, if we are getting rid of `config.php` completely.
3. services that can not be autoconfigured automaticelly. But please don't use indexed arguments, but a named ones.

Maybe the first iteration should have only point 1. Because getting rid of config.php in the current state is not really an easy task (tried that locally, but have couple of ideas). Introducing services.php will allow us to autowire at least the core services and default plugins and for plugin authors to use autowiring.

2022-10-14 15:06 UTC, escopecz commented
@biozshock makes sense. I found a way how to keep the configuration for bundles (including plugins) that do not need to exclude anything special and let other bundles to configure their own services if needed. This is quick&dirty implementation with showcase on LeadBundle and a plugin:

https://github.com/mautic/mautic/pull/11587/commits/d695f15f128fc558209b8411bde4ac284fe002fd

WDYT?

So the next work would be to move the excluded services in app/config/services.php to their own bundle configurations.

2022-10-18 13:37 UTC, escopecz commented
@biozshock I tried the trait you suggested but it creates a loop:
```
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                                                       
  Circular reference detected for service "LightSaml\Store\Credential\CompositeCredentialStore", path: "LightSaml\Store\Credential\CompositeCredentialStore -> LightSaml\Store\Credential\CompositeCredentialStore". 
```

2022-10-26 13:45 UTC, RCheesley requested changes
I have found an issue with the builder:

When opening emails or landing pages, the old legacy builder is being loaded but GrapesJS is enabled, so that should be loaded.

2022-10-26 20:20 UTC, biozshock commented
> @biozshock I tried the trait you suggested but it creates a loop:
> 
> ```
>   [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                                                       
>   Circular reference detected for service "LightSaml\Store\Credential\CompositeCredentialStore", path: "LightSaml\Store\Credential\CompositeCredentialStore -> LightSaml\Store\Credential\CompositeCredentialStore". 
> ```

Hm, are you sure you added this to the DI extension class in the `load` method? Before compiling the container wouldn't know anything about the Ligtsaml classes, and the trait will process only services added in the loading process.

BTW: Actually after refactoring the aliasing should be done only in the `app/bundles/CoreBundle/DependencyInjection/Compiler/ServicePass.php`. I didn't look deeper into what the pass actually does, but it seems it already creates class aliases if the `id` of the service is not the classFQCN here https://github.com/mautic/mautic/pull/11587/files#diff-c970d70821380696974e49f7cef5ee199e8124dda95d21e2b2e5fdd25e29b5c7R117 ?

2022-11-02 16:02 UTC, escopecz commented
@RCheesley Thanks for you tests! I fixed the issues. The one with the builder took me quite a while to figure out. The problem was that the AssetsHelper was instantiated twice. The first instance got the builder JS but the other instance was asked to print it to the HTML.

2022-11-07 08:44 UTC, escopecz commented
Rebased to resolve conflicts.

2022-11-10 11:26 UTC, mabumusa1 approved these changes, later dismissed
I used gitpod to test the controllers, and every controller I tested worked without issues. Mautic loaded without.

I think this PR is good to go

2022-11-11 13:37 UTC, volha-pivavarchyk submitted a review, later dismissed
Works well for me locally and on Gitpod

2022-11-11 14:36 UTC, biozshock approved these changes, later dismissed
A leap forward!
Created couple tickets instead of commenting on the code.

2022-11-11 14:36 UTC, biozshock commented on app/AppKernel.php
> +        $container->registerForAutoconfiguration(\Mautic\CoreBundle\Model\MauticModelInterface::class)
This must be added to a documentation.

2022-11-11 16:52 UTC, escopecz commented on app/AppKernel.php
> +        $container->registerForAutoconfiguration(\Mautic\CoreBundle\Model\MauticModelInterface::class)
Nothing has changed for the model classes themselves. They are "Mautic models" when they extend `AbstractCommonModel` and `AbstractCommonModel implements MauticModelInterface` so all existing and new "Mautic models" will be autoconfigured. What would you suggest to add to the docs?

2022-11-11 16:53 UTC, merged

2022-11-14 07:34 UTC, biozshock commented on app/AppKernel.php
> +        $container->registerForAutoconfiguration(\Mautic\CoreBundle\Model\MauticModelInterface::class)
Oh, i have overlooked that all models should extend `AbstractCommonModel` to actually be models in Mautic.