TPROD-313 - DashboardBundle: migrate views from PHP Engine to Twig
mautic/mautic pull request #11791
Opened 2022-12-06 22:57 UTC by JoshuaEstes

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2022-12-07 16:21 UTC, escopecz commented
I got this error:
```
Unable to find template "MauticCoreBundle:Helper:map.html.twig"
```
When going to `/index_dev.php/s/dashboard/import?preview=alternative-default`

2022-12-08 12:06 UTC, escopecz approved these changes, later dismissed
I found that some widget types shows:
```
This form should not contain extra fields.
```
and the report widget can be saved without a report selected and it causes a PHP notice. 

But all that already exists in the 5.x branch so it was not caused by this PR and can be merged. Thanks! :+1:

2022-12-08 12:06 UTC, escopecz commented
Oh, the failing test will need fixing first.

2022-12-08 12:14 UTC, JoshuaEstes commented
> I found that some widget types shows:
> 
> ```
> This form should not contain extra fields.
> ```
> 
> and the report widget can be saved without a report selected and it causes a PHP notice.
> 
> But all that already exists in the 5.x branch so it was not caused by this PR and can be merged. Thanks! +1

Which widgets are you getting these errors with? I tried a few any everything seemed to work fine.

2022-12-08 12:39 UTC, escopecz commented
Luckily, I make screenshots of those :) But don't feel pressured to fix it in this PR. It can be done later on. The twig migration is now blocking other tickets.
![Screen Shot 2022-12-08 at 10 54 02](https://user-images.githubusercontent.com/1235442/206448108-9700a0cd-d7bd-43b8-bbf4-f457a6577c3a.png)
![Screen Shot 2022-12-08 at 10 53 02](https://user-images.githubusercontent.com/1235442/206448123-3569211f-15cf-4c57-8435-283215bef06d.png)
![Screen Shot 2022-12-08 at 10 52 37](https://user-images.githubusercontent.com/1235442/206448127-3df76a46-1d99-4bcd-ac72-669cb028a53a.png)
![Screen Shot 2022-12-08 at 10 52 26](https://user-images.githubusercontent.com/1235442/206448131-14e43ac3-01b8-4442-a514-e4cdd859935a.png)
![Screen Shot 2022-12-08 at 10 51 31](https://user-images.githubusercontent.com/1235442/206448135-8bbb4828-d937-4e7c-8f08-ca175d085d43.png)

2022-12-08 16:16 UTC, JoshuaEstes commented
It looks like it was trying to load a twig template that wasn't found. https://github.com/mautic/mautic/pull/11791/commits/498e072994773b236ca67a776f322a63c68ce86b should resolve the issue.

2022-12-09 08:23 UTC, escopecz submitted a review, later dismissed
You are right! It fixed the problem! 👍

2022-12-09 13:58 UTC, RCheesley requested changes
When I try to save a dashboard from /index_dev.php/s/dashboard/import?preview=stats-overview I am getting a 500 error:

```
[2022-12-09 13:57:31] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "dashboard.globalstats-overview does not exist." at /var/www/html/app/bundles/CoreBundle/Helper/PathsHelper.php line 196 {"exception":"[object] (InvalidArgumentException(code: 0): dashboard.globalstats-overview does not exist. at /var/www/html/app/bundles/CoreBundle/Helper/PathsHelper.php:196)
[stacktrace]
#0 /var/www/html/app/bundles/DashboardBundle/Controller/DashboardController.php(408): Mautic\\CoreBundle\\Helper\\PathsHelper->getSystemPath('dashboard.globa...')
#1 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(442): Mautic\\DashboardBundle\\Controller\\DashboardController->applyDashboardFileAction('globalstats-ove...', '')
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('applyDashboardF...', 0, 0, '')
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#5 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#6 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#14 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#15 {main}
"} {"hostname":"mautic-web","pid":2428}
```

When adding the Read Ratio report widget I get the following error:

```
[2022-12-09 14:01:37] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Warning - Undefined array key "e.is_published"" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php line 436 {"exception":"[object] (ErrorException(code: 0): PHP Warning - Undefined array key \"e.is_published\" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:436)
[stacktrace]
#0 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(436): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - U...', '/var/www/html/a...', 436)
#1 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(199): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->applyFilters(Array, Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Object(Mautic\\ReportBundle\\Event\\ReportGeneratorEvent))
#2 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(119): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->configureBuilder(Array)
#3 /var/www/html/app/bundles/ReportBundle/Generator/ReportGenerator.php(77): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->getQuery(Array)
#4 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(559): Mautic\\ReportBundle\\Generator\\ReportGenerator->getQuery(Array)
#5 /var/www/html/app/bundles/ReportBundle/EventListener/DashboardSubscriber.php(79): Mautic\\ReportBundle\\Model\\ReportModel->getReportData(Object(Mautic\\ReportBundle\\Entity\\Report), NULL, Array)
#6 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\ReportBundle\\EventListener\\DashboardSubscriber->onWidgetDetailGenerate(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#7 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#8 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'mautic.dashboar...', Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent))
#9 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...')
#10 /var/www/html/app/bundles/DashboardBundle/Model/DashboardModel.php(248): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...')
#11 /var/www/html/app/bundles/DashboardBundle/Controller/DashboardController.php(165): Mautic\\DashboardBundle\\Model\\DashboardModel->populateWidgetContent(Object(Mautic\\DashboardBundle\\Entity\\Widget), Array)
#12 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(442): Mautic\\DashboardBundle\\Controller\\DashboardController->newAction(0, '')
#13 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Mi [...]

2022-12-12 13:19 UTC, RCheesley requested changes
Second round of testing:

### All emails on Report Graphs
Adding any of the All Emails report graphs as a widget on the Dashboard yields:

```
[2022-12-12 12:51:29] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Warning - Undefined array key "e.is_published"" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php line 436 {"exception":"[object] (ErrorException(code: 0): PHP Warning - Undefined array key \"e.is_published\" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:436)
[stacktrace]
#0 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(436): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - U...', '/var/www/html/a...', 436)
#1 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(199): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->applyFilters(Array, Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Object(Mautic\\ReportBundle\\Event\\ReportGeneratorEvent))
#2 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(119): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->configureBuilder(Array)
#3 /var/www/html/app/bundles/ReportBundle/Generator/ReportGenerator.php(77): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->getQuery(Array)
#4 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(559): Mautic\\ReportBundle\\Generator\\ReportGenerator->getQuery(Array)
#5 /var/www/html/app/bundles/ReportBundle/EventListener/DashboardSubscriber.php(79): Mautic\\ReportBundle\\Model\\ReportModel->getReportData(Object(Mautic\\ReportBundle\\Entity\\Report), NULL, Array)
#6 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\ReportBundle\\EventListener\\DashboardSubscriber->onWidgetDetailGenerate(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#7 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#8 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'mautic.dashboar...', Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent))
#9 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...')
#10 /var/www/html/app/bundles/DashboardBundle/Model/DashboardModel.php(248): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...')
#11 /var/www/html/app/bundles/DashboardBundle/Controller/DashboardController.php(165): Mautic\\DashboardBundle\\Model\\DashboardModel->populateWidgetContent(Object(Mautic\\DashboardBundle\\Entity\\Widget), Array)
#12 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(442): Mautic\\DashboardBundle\\Controller\\DashboardController->newAction(0, '')
#13 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#25 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#26 {main}
"} {"hostname":"mautic-web","pid":2393}
```

### Instances with debugging text showing:

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-12_53_23](https://user-images.githubusercontent.com/2930593/207050030-f654cd2a-9e1a-4119-9d6b-f8ff049089f3.png)

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-13_08_35](https://user-images.githubusercontent.com/2930593/207053000-fe951175-5946-496f-bbe9-089a96245be6.png)

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-13_10_50](https://user-images.githubusercontent.com/2930593/207053427-804b66c4-0094-4bec-a415-1e5c845ff8e3.png)

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-13_13_49](https://user-images.githubusercontent.com/2930593/207053974-e68d7fa7-ef18-4d0e-bbbe-46f3ad1705bd.png)

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-13_15_15](https://user-images.githubusercontent.com/2930593/207054185-ed0f8c20-1d8c-4b9f-9456-0c0eaf4501a3.png)

![screenshot-8080-joshuaestes-mautic-1kivfij7vg8 ws-eu78 gitpod io-2022 12 12-13_15_59](https://user-images.githubusercontent.com/2930593/207054375-11d8b060-7677-40cb-9a87-89ded0d59862.png)

### Other widgets with errors
Trying to add the widget 'Sent email to contacts' results in this error:

```

[2022-12-12 13:03:27] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "MauticEmailBundle:SubscribedEvents:Dashboard/Sent.email.to.contacts.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/html/app/bundles/DashboardBundle/Views/Widget/detail.html.twig line 48 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"MauticEmailBundle:SubscribedEvents:Dashboard/Sent.email.to.contacts.html.twig\" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/html/app/bundles/DashboardBundle/Views/Widget/detail.html.twig:48)
[stacktrace]
#0 /var/www/html/vendor/symfony/twig-bundle/Loader/FilesystemLoader.php(82): Twig\\Loader\\FilesystemLoader->findTemplate('MauticEmailBund...')
#1 /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php(131): Symfony\\Bundle\\TwigBundle\\Loader\\FilesystemLoader->findTemplate('MauticEmailBund...')
#2 /var/www/html/vendor/twig/twig/src/Environment.php(261): Twig\\Loader\\FilesystemLoader->getCacheKey('MauticEmailBund... [...]

2022-12-16 09:53 UTC, RCheesley reviewed
I'm not sure if this is relating to this PR, but when I save and close a contact now, it's not completing the task. No errors in the console or the log.

https://watch.screencastify.com/v/PaciUGnHuKsEHBLhmmYQ

2022-12-16 12:46 UTC, RCheesley requested changes
@JoshuaEstes getting this in the log trying to add the 'Sent email to contacts' widget and it never saves:

```
[2022-12-16 12:45:19] mautic.CRITICAL: Uncaught PHP Exception TypeError: "mb_substr(): Argument #3 ($length) must be of type ?int, string given" at /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php line 666 {"exception":"[object] (TypeError(code: 0): mb_substr(): Argument #3 ($length) must be of type ?int, string given at /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php:666)
[stacktrace]
#0 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(666): mb_substr('MatthewSDell@ar...', 0, 'table', 'UTF-8')
#1 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(124): twig_slice(Object(Twig\\Environment), 'MatthewSDell@ar...', 0, 'table')
#2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_79fca252555d1b8fd984e708cb04b0280e1ce907d8f2433d83a182cb518ea364->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#5 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1323): Twig\\TemplateWrapper->render(Array)
#7 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(139): twig_include(Object(Twig\\Environment), Array, 'MauticEmailBund...', Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c0259f996ce7e24b1a72dd1553070268ee4bf96b89f0ffbbfb294067b68a1cfc->doDisplay(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#11 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(54): Twig\\Template->render(Array)
#12 /var/www/html/vendor/symfony/templating/DelegatingEngine.php(41): Symfony\\Bridge\\Twig\\TwigEngine->render('MauticDashboard...', Array)
#13 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(213): Symfony\\Component\\Templating\\DelegatingEngine->render('MauticDashboard...', Array)
#14 /var/www/html/app/bundles/DashboardBundle/Controller/DashboardController.php(171): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->renderView('MauticDashboard...', Array)
#15 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\DashboardBundle\\Controller\\DashboardController->newAction(0, '')
#16 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#17 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#18 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#28 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#29 {main}
"} {"hostname":"mautic-web","pid":2473}

```

2022-12-16 15:16 UTC, JoshuaEstes commented
@RCheesley 

The issue with the widget Sent email to contacts was a typo and has been resolved.
---
From what I can tell, the lifecycle widget needs a lot of space and needs to have a Segment Filter selected. Without selecting a segment, it seems to pull all the segments with contacts/leads in them
---
For the Report graph: All emails sent issue, I need to know how you setup the report. Do you get the same error on the 5.x branch or just this branch?

2022-12-16 15:21 UTC, RCheesley commented
> For the Report graph: All emails sent issue, I need to know how you setup the report. Do you get the same error on the 5.x branch or just this branch?

This is a standard widget - choose the very last option in the dropdown and then you will see the reports which are available to show as widgets in the dropdown box like when you set a segment etc. Just firing up the instance to check the actual wording on the dropdown!

2022-12-23 19:17 UTC, mabumusa1 approved these changes
I tested this PR, import, export, creating widget, editing, moving, and deleting are all working as expected. I think this PR is good to go

2022-12-23 19:19 UTC, mabumusa1 commented
> @JoshuaEstes getting this in the log trying to add the 'Sent email to contacts' and other email related widgets, and it never saves:
> 
> ```
> [2022-12-16 12:45:19] mautic.CRITICAL: Uncaught PHP Exception TypeError: "mb_substr(): Argument #3 ($length) must be of type ?int, string given" at /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php line 666 {"exception":"[object] (TypeError(code: 0): mb_substr(): Argument #3 ($length) must be of type ?int, string given at /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php:666)
> [stacktrace]
> #0 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(666): mb_substr('MatthewSDell@ar...', 0, 'table', 'UTF-8')
> #1 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(124): twig_slice(Object(Twig\\Environment), 'MatthewSDell@ar...', 0, 'table')
> #2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_79fca252555d1b8fd984e708cb04b0280e1ce907d8f2433d83a182cb518ea364->doDisplay(Array, Array)
> #3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
> #4 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
> #5 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)
> #6 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1323): Twig\\TemplateWrapper->render(Array)
> #7 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(139): twig_include(Object(Twig\\Environment), Array, 'MauticEmailBund...', Array)
> #8 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c0259f996ce7e24b1a72dd1553070268ee4bf96b89f0ffbbfb294067b68a1cfc->doDisplay(Array, Array)
> #9 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
> #10 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
> #11 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(54): Twig\\Template->render(Array)
> #12 /var/www/html/vendor/symfony/templating/DelegatingEngine.php(41): Symfony\\Bridge\\Twig\\TwigEngine->render('MauticDashboard...', Array)
> #13 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(213): Symfony\\Component\\Templating\\DelegatingEngine->render('MauticDashboard...', Array)
> #14 /var/www/html/app/bundles/DashboardBundle/Controller/DashboardController.php(171): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->renderView('MauticDashboard...', Array)
> #15 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\DashboardBundle\\Controller\\DashboardController->newAction(0, '')
> #16 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
> #17 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
> #18 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #19 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #20 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #21 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #22 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #23 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #24 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #25 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #26 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #27 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
> #28 /var/www/html/index_dev.php(25): Stack\
> un(Object(Stack\\StackedHttpKernel))
> #29 {main}
> "} {"hostname":"mautic-web","pid":2473}
> ```
> 
> With the lifecycle widget, selecting no segment looks rather broken - maybe the segment is meant to be required?
> 
> ![screenshot-8080-joshuaestes-mautic-7r3tp7te16i ws-eu79 gitpod io-2022 12 16-12_57_33](https://user-images.githubusercontent.com/2930593/208103677-339023f5-e0b2-4371-aa06-509f669e76c0.png)
> 
> Report graph: All emails sent:
> 
> ```
> [2022-12-16 13:01:43] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Warning - Undefined array key "e.is_published"" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php line 436 {"exception":"[object] (ErrorException(code: 0): PHP Warning - Undefined array key \"e.is_published\" at /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:436)
> [stacktrace]
> #0 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(436): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - U...', '/var/www/html/a...', 436)
> #1 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(199): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->applyFilters(Array, Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Object(Mautic\\ReportBundle\\Event\\ReportGeneratorEvent))
> #2 /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php(119): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->configureBuilder(Array)
> #3 /var/www/html/app/bundles/ReportBundle/Generator/ReportGenerator.php(77): Mautic\\ReportBundle\\Builder\\MauticReportBuilder->getQuery(Array)
> #4 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(559): Mautic\\ReportBundle\\Generator\\ReportGenerator->getQuery(Array)
> #5 /var/www/html/app/bundles/ReportBundle/EventListener/DashboardSubscriber.php(79): Mautic\\ReportBundle\\Model\\ReportModel->getReportData(Object(Mautic\\ReportBundle\\Entity\\Report), NULL, Array)
> #6 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\ReportBundle\\EventListener\\DashboardSubscriber->onWidgetDetailGenerate(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
> #7 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
> #8 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'mautic.dashboar...', Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent))
> #9 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Mautic\\DashboardBundle\\Event\\WidgetDetailEvent), 'mautic.dashboar...')
> #10 /var/www/html/app/bundles/DashboardBundle/Model/DashboardModel.php(247): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Ob [...]

2022-12-27 17:32 UTC, JoshuaEstes commented
@mabumusa1 @RCheesley 
* https://github.com/mautic/mautic/pull/11791/commits/c97ffc8461ad2bec96ebf50498e3e75af55a4b3a fixed the mb_string issue
* The lifecycle issue happens on the 5.x branch as well. Only solution I can think of right now is to add a limit to the SQL
* The `Undefined array key "e.is_published"` happens on the 5.x branch

I would suggest we create issues to track the issues that happen on other branches as well. I'd rather fix it correctly than add something quickly to get this pushed on the finish line.

2023-01-05 16:44 UTC, merged