Fix: GrapesJS assets transfer is slowing admin panel view loading
mautic/mautic pull request #11818
Opened 2022-12-15 14:03 UTC by patrykgruszka

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
I noticed that all GrapesJS assets are sent with view requests. In this case, if you have a lot of assets, it can significantly slow down view loading.

In my case, with large assets database the Contact, Companies, Segments, Campaigns views are transferring > 2MB of GrapesJS data.
![image](https://user-images.githubusercontent.com/8580942/207875667-c9f8570a-2e72-4c1a-95ed-08c78830df34.png)

This PR changes this behavior and loads assets asynchronously when GrapesJS builder is initialized. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open ten test GrapesJS builder including assets 
3. GrapesJS assets should not be transferred in panel view requests as encoded JSON, it can be verified using browser dev tools:
![image](https://user-images.githubusercontent.com/8580942/207880019-9011f80d-0a62-48a4-936c-1437635d261d.png)

2022-12-15 14:28 UTC, patrykgruszka commented
@cla-bot check

2022-12-22 16:50 UTC, jos0405 submitted a review, later dismissed
Hi, it does what it claims.
The assets are not visible in panel anymore

2023-01-04 13:34 UTC, escopecz requested changes
The code looks great! Please create one functional test that will cover the new endpoint.

2023-01-04 13:34 UTC, escopecz commented on plugins/GrapesJsBuilderBundle/Controller/FileManagerController.php
> +    public function assetsAction()
```suggestion

    public function assetsAction(): JsonResponse
```

2023-01-04 13:34 UTC, escopecz commented on plugins/GrapesJsBuilderBundle/Controller/FileManagerController.php
> +    public function assetsAction()
Please create a functional test that will hit this endpoint and check that some pre-installed asset is present in the response.

2023-01-06 13:42 UTC, mabumusa1 submitted a review, later dismissed
This PR is good to go, I opened 10 tabs with grapejs opened, I looked in the developers there were assets that are passed all the time, after applying the PR they were not loaded anymore.

Thanks @patrykgruszka for this PR

2023-01-09 08:18 UTC, patrykgruszka commented
@escopecz  done, added functional test and suggestion. Thanks everyone for tests!

2023-01-09 12:17 UTC, escopecz approved these changes
Thank you!

2023-01-09 12:36 UTC, merged