TPROD-319 - LeadBundle - Segment Templates
mautic/mautic pull request #11816
Opened 2022-12-15 00:02 UTC by JoshuaEstes

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2022-12-16 11:46 UTC, daniellord32 requested changes
**Segment create** - works as expected
    **segment with email equals filter** - works as expected
    **Segment with first name equals** - works as expected
    **Segment with first name equals (Lowercase)** - works as expected

**Segment build** - works as expected
**Segment update** - changed filter to not like and it processed as expected
**And filter** works as expected
**Or filter** works as expected

**Cloned segment** works as expected with filters

**Delete segment** works as expected

**segment has not been rebuilt notice/error**
Not sure what the idea is for this, but even after running a segment update command, I seen that this error/notice did not go away. I created a bunch of segments manually first then ran the segment update command. I knew these segments would get populated with contacts after the command ran
![image](https://user-images.githubusercontent.com/25160505/208090397-8faa047c-5bba-47c3-af07-62cc2e2f90fa.png)

2022-12-16 12:03 UTC, escopecz requested changes
Please check the PHPSTAN and PHPUNIT issues reported in CI. Ping me if you'd need any help with that.

2022-12-16 12:03 UTC, escopecz commented on app/bundles/CoreBundle/Views/Helper/details.html.twig
> +{% if attribute(entity, 'getCategory') is defined and method_exists(entity, 'getCategory') %}
Is this necessary? based on [the docs](https://twig.symfony.com/doc/2.x/functions/attribute.html) the `is defined` part performs method_exists so this change seems redundant

2022-12-16 13:20 UTC, RCheesley commented
> Not sure what the idea is for this, but even after running a segment update command, I seen that this error/notice did not go away.

I think this happens if the segment is not using any filters maybe - so there is nothing to build (eg if you use it for importing contacts or in campaigns rather than using the filter criteria to add to the segment. Might be wrong though! Agree the time period could be more human-friendly when it goes beyond a couple of days maybe!

2022-12-23 20:44 UTC, mabumusa1 submitted a review, later dismissed
I think this PR is good to go, I tested the following cases

Create
Filters (single and multiple)
Semgnet CLI
Clone 
Delete 
View

@JoshuaEstes please fix the failing tests so we can merged it, thanks for your contribution

2023-01-04 09:11 UTC, escopecz approved these changes
I was clicking through the UI, adding different segment filters, cloning, searching, sorting, paginating, selecting date ranges and I couldn't find any issue. Thank you!

2023-01-04 09:11 UTC, merged