[DPMMA-1861] Duplicate segment clone action
mautic/mautic pull request #12045
Opened 2023-03-01 12:33 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [x ]
| Deprecations?                          | [ x]
| BC breaks? (use the c.x branch)        | [x ]
| Automated tests included?              | [ yes] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
When re-saving the segment, duplicates are created, this is because the action attribute in the form is not changed after saving the cloned form

![image](https://user-images.githubusercontent.com/39382654/222140431-36fe488c-db51-4d8c-8c73-25d029bbb73b.png)

#### Steps to test this PR:

1. Clone Segment https://mautic.ddev.site/index_dev.php/s/segments/clone/{id_segment}
2. save Changes
3. save changes again

2023-03-02 05:48 UTC, kuzmany approved these changes, later dismissed
Face the same issue and it looks like this fixes it 👍

2023-03-02 09:01 UTC, npracht commented
@galvani can you please review code and test it ? Thanks :)`

2023-03-02 09:09 UTC, galvani requested changes
just a minor chanhe for phpstan ;-) thanks for the solution/

2023-03-02 09:09 UTC, galvani commented on app/bundles/LeadBundle/Controller/ListController.php
> +
You need to fix the php doc signature of Mautic\LeadBundle\Model\ListModel::createForm()
. to make phpstan happy at least:
```php
    /**
     * {@inheritdoc}
     *
     * @param       $entity
     * @param       $formFactory
     * @param array $options
     *
     * @return mixed
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    public function createForm($entity, $formFactory, ?string $action = null, $options = [])
    {
```

2023-03-10 14:49 UTC, sdoering commented
Was not able to test this as I ran into an error twice: 

![image](https://user-images.githubusercontent.com/765204/224346452-8454de08-ed88-4d99-b75b-10cd4c244e84.png)

_Not sure about potential reasons for this_.

2023-03-10 15:52 UTC, volha-pivavarchyk approved these changes, later dismissed
Works well

I tested in the local instance because I had an error in gitpod as well.

2023-03-20 12:47 UTC, tomekkowalczyk commented
@sdoering I correct PHPStan ;)

2023-03-21 10:00 UTC, escopecz approved these changes
Thanks! 👍

2023-03-21 10:01 UTC, merged