Translation for date/datetime contactfield token
mautic/mautic pull request #12152
Opened 2023-03-31 04:00 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

IF we set different language in configuration, then we expect translation date/datetime output for contactfield token translate too. This PR added support

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Switch default language in configuration

2023-04-13 09:07 UTC, escopecz requested changes
Great idea! I suggest to refactor the TokenHelper to be a new service that can use DI instead of the static calls that limits it.

2023-04-13 09:07 UTC, escopecz commented on app/bundles/CoreBundle/Config/config.php
> +                ],
How are these changes related to `MaxMindDoNotSellList`?

2023-04-13 09:07 UTC, escopecz commented on app/bundles/CoreBundle/Helper/DateTime/DateTimeLocalization.php
> +    }
Can you please instead of building on this static nonsense create a new service class that will do the same thing and will be using DI? This class would be then deprecated.

2023-04-13 10:08 UTC, kuzmany commented on app/bundles/CoreBundle/Helper/DateTime/DateTimeLocalization.php
> +    }
Ah, ok. If I find some time, I would do it. TokenHelper is used to use on many places, then I will use the new DI just for emails at the moment.

2023-05-05 04:37 UTC, kuzmany commented
Close it. It needs more time to be ready.

2023-05-05 04:37 UTC, closed without merging