TPROD-399 Removed Doctrine deprecations from Campaign mautic:campaigns:rebuild command.
mautic/mautic pull request #12192
Opened 2023-04-10 22:35 UTC by biozshock

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Automated tests included?              | [ x ] 

#### Description:
Remove Doctrine deprecations from Campaign mautic:campaigns:rebuild command.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create Campaign
3. Create contact that does not belong to the campaign.
4. Create contact that belong to the campaign.
5. Run `mautic:campaigns:rebuild` command.

2023-04-11 10:16 UTC, mabumusa1 approved these changes, later dismissed
This PR is hard to test on gitpod at the moment given the [issue](https://github.com/mautic/mautic/pull/12166#issuecomment-1498907535) 

I tested it locally with a campaign that was saved in the database already, the command worked as expected

2023-04-11 14:51 UTC, escopecz commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
I'm not sure that this comment still makes sense. The change will clear all the entities. Not just the Lead entities. @fedys do you know about better replacement than the one that is suggested here?

2023-04-11 14:59 UTC, fedys commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
I would say
```php
$this->leadRepository->detachEntities(contacts);
```

2023-04-12 11:40 UTC, fedys requested changes

2023-04-12 11:40 UTC, fedys commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
But it is not the same as calling `clear()`.

2023-04-12 11:40 UTC, fedys commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
I checked the internals of Doctrine UoW and the only difference between calling `$this->leadRepository->detachEntities(contacts);` and `$this->leadRepository->clear();` in this particular situation is that the latter triggers `Events::onClear` event. As we have no such listener, there should not be any difference.

2023-04-12 11:40 UTC, fedys commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
> +            $this->objectManager->clear();
```suggestion
            $this->leadRepository->detachEntities(contacts);
```
Let's replace it with detaching entities.

2023-04-12 21:28 UTC, biozshock commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
Please check now

2023-04-13 06:41 UTC, fedys approved these changes

2023-04-13 06:41 UTC, fedys commented on app/bundles/CampaignBundle/Membership/MembershipBuilder.php
>              // Clear Lead entities from RAM
Looks good. Thanks!

2023-04-13 06:42 UTC, fedys approved these changes
Thanks @biozshock! 👍

2023-04-13 07:29 UTC, escopecz approved these changes
Thank you!

2023-04-13 07:29 UTC, merged