Multiple companies management
mautic/mautic pull request #12219
Opened 2023-04-14 06:06 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Fork of https://github.com/mautic/mautic/pull/10817 for M5
We need use only one company to each contact. This PR added option to not use multiple companies to contact

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. We add new option to configuration 
![image](https://user-images.githubusercontent.com/462477/151988239-c4db4996-ef01-42f7-ae52-52b5150721b5.png)

By default it is enabled and should works like before. You can use companies to contact same like before.

3. If you disable it, you can use  just one company to assign to contact

![image](https://user-images.githubusercontent.com/462477/151988489-23df9f8a-699b-416a-8039-d3a05f6a2f22.png)

4. You can test any combination
5. Also test  new command `mautic:contact:delete:secondary-companies` to delete all secondary companies, If you migrate to  to single company managment.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10817"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-04-14 11:52 UTC, mabumusa1 commented
@kuzmany please fix failing test, I will test it today

2023-04-23 04:30 UTC, setti21 commented
Probably my fault as trying to do my first contribution following newbie instructions, but I can't get past the login page in Gitpod environment. It loads up to that stage just fine and then stops. Eventually just times out. I'll try again another day.

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

Apache/2.4.51 (Debian) Server at 8080-kuzmany-mautic-ny6lxdzfi5b.ws-us95.gitpod.io Port 80

2023-04-27 07:20 UTC, jos0405 commented
Same issue - can't run this on gitpod

2023-05-03 08:31 UTC, RCheesley commented
Same issue for me - I have raised it with GitPod support: https://discord.com/channels/816244985187008514/1103236689138298890

Might have to test this one locally for the time being.

2023-05-26 10:22 UTC, axonasif commented
> Same issue for me - I have raised it with GitPod support: https://discord.com/channels/816244985187008514/1103236689138298890
> 
> Might have to test this one locally for the time being.

Hi folks 👋
Apologies for the inconvenience. I was able to login after trying today. I'm not sure what was the issue before but it seems to be working now.

2023-06-30 09:37 UTC, mollux requested changes

2023-06-30 09:37 UTC, mollux commented on app/bundles/LeadBundle/Tests/Controller/LeadControllerTest.php
> +    }
@kuzmany I would split off those lines to a separate controller test, and remove the `useCleanupRollback` property

2023-07-22 09:59 UTC, oltmanns-leuchtfeuer requested changes
Tested and it worked fine, but I found a little detail that should be changed:
When creating a company while editing a contact, all his prior companies get deleted and only the newly created one stays.

1.
<img width="483" alt="PR-company1" src="https://github.com/mautic/mautic/assets/55587275/50353016-286c-4331-8393-8dbb19042773">

2.
<img width="623" alt="pr-company2" src="https://github.com/mautic/mautic/assets/55587275/aac7e051-5e8c-4696-a8b7-157c6551ccd6">

3.
<img width="405" alt="pr-company3" src="https://github.com/mautic/mautic/assets/55587275/860fc9ab-699b-45ad-bd78-f8c817245f42">

2023-07-22 10:16 UTC, oltmanns-leuchtfeuer commented
> Tested and it worked fine, but I found a little detail that should be changed: When creating a company while editing a contact, all his prior companies get deleted and only the newly created one stays.
> 
> 
> <img alt="PR-company1" width="483" src="https://user-images.githubusercontent.com/55587275/255323590-50353016-286c-4331-8393-8dbb19042773.png">
> 
> <img alt="pr-company2" width="623" src="https://user-images.githubusercontent.com/55587275/255323598-aac7e051-5e8c-4696-a8b7-157c6551ccd6.png">
> 
> <img alt="pr-company3" width="405" src="https://user-images.githubusercontent.com/55587275/255323609-860fc9ab-699b-45ad-bd78-f8c817245f42.png">

This is a bug in Mautic present since atleast 4.4.6 and not related to this PR, thus I will approve it

2023-07-22 10:17 UTC, oltmanns-leuchtfeuer approved these changes
LGMT

2023-07-22 10:24 UTC, jos0405 approved these changes
Works for me (besides the Mautic bug @oltmanns-leuchtfeuer kindly described.)
I also tested API, works well, the contact's company is overwritten instead of added.

2024-01-31 18:13 UTC, escopecz reviewed
@kuzmany I can see this is marked as ready to commit. Could you please resolve the conflicts and also add a functional test for the new command? It's completely untested.

2024-02-01 06:33 UTC, kuzmany commented
@escopecz seems it cover command tests: https://github.com/kuzmany/mautic/blob/Multiple_companies_management_5x/app/bundles/LeadBundle/Tests/Command/DeleteContactSecondaryCompaniesCommand.php

Conflicts resolved

2024-02-01 11:28 UTC, escopecz commented
@kuzmany the file name must end with "Test" so it would be picked up by PHPUNIT. That's probably why CodeCov reports it's not being covered.

2024-02-02 06:33 UTC, kuzmany commented
@escopecz good catch. Fixed

2024-02-02 10:28 UTC, escopecz approved these changes, later dismissed

2024-02-08 11:51 UTC, escopecz approved these changes

2024-02-08 11:52 UTC, merged

2024-04-16 08:44 UTC, RCheesley commented
@kuzmany this requires some documentation to explain how this works. Can you please make the PR at https://github.com/mautic/user-documentation/blob/5.x/docs/companies/companies_overview.rst and https://github.com/mautic/user-documentation/blob/5.x/docs/configuration/settings.rst?

cc @mautic/education-team as this is required for 5.1.