Shorten redirect urls
mautic/mautic pull request #12228
Opened 2023-04-18 08:55 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Current redirect URLs are so long. This PR reduces the size of content hash in redirect URLs without BC.

- add support for igbinary serialize https://www.php.net/manual/en/book.igbinary.php , If it's enabled on server, it will use it instead of php serialize. It''s save almost 40% 
- If It's disabled, then use PHP serialize like before
- pack keys in the clickthrough data (email > e, lead > l....)
- move UTM tags directly to clickthrough  and pack keys too
- change rediret URLS from `/r/hash?ct=xxx` to `/r/hash/ct` (inspired by https://github.com/mautic/mautic/pull/12169)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-07-04 07:46 UTC, adiux commented
As this solves a bug with the CT value where contacts are not identified, and it is a breaking change, is it possible to still get this into v5?

2023-07-07 07:18 UTC, kuzmany commented
@adiux I don't know what issue you're talking about. We use it on our 4.x branch and fork it to the community for 5.x.

2023-07-07 07:24 UTC, adiux commented
@kuzmany https://github.com/mautic/mautic/pull/12169

2023-07-07 07:57 UTC, kuzmany commented
@adiux Yes, that PR or part is included in this PR. But I see it's enhancement, do not see what issue should fix that PR

2023-07-07 08:05 UTC, adiux commented
@kuzmany I believe it fixes e.g. this issue https://github.com/mautic/mautic/issues/6775. It did in my tests.

2023-07-07 08:21 UTC, kuzmany commented
@adiux It should gone

2023-07-22 11:02 UTC, jos0405 requested changes
The PR works almost 100% okay.
[x] It does generate the right link.
[x] Id does include the query
[ ] It doesn't record UTM tags.

The link is formed as:
https://www.google.com/?query=123&utm_source=thisissource&utm_medium=thisismedium&utm_campaign=thisisname&utm_content=thisiscontent

But UTM tags are not recorded:
![image](https://github.com/mautic/mautic/assets/4246909/c26f5da0-66a6-42a9-b1c6-c385c2d66dcb)

The same thing was working in Mautic 4.x
![image](https://github.com/mautic/mautic/assets/4246909/c7688622-0a97-4e54-9637-7ef70426be19)

2023-08-04 12:01 UTC, RCheesley commented
@kuzmany please note the feedback about the UTM tags not getting correctly tracked.

2023-08-18 08:06 UTC, kuzmany commented
@jos0405 we should track UTM tags just on tracking pages? Not redirect links? Could It considered as bug?

2023-08-24 19:08 UTC, RCheesley commented
@jos0405 feedback for you on this PR - would be great to get this merged!

2023-09-08 07:05 UTC, kuzmany commented
Waiting to feedback

2023-11-24 06:50 UTC, kuzmany commented
Waiting to feedback

2023-11-24 07:24 UTC, adiux commented
IMO: The redirects should also record the utm tags. Otherwise marketers will not get the reporting for e.g. their visits from emails.

2023-11-24 07:28 UTC, kuzmany commented
@adiux I believe UTM tags are used to track webpage campaigns for analytics purposes. It simply involves redirection, and the end page contains UTM tags. But anyway, if you use a tracking code on the final page, you end up setting UTM tags twice: once for redirection and once for the tracking pixel fired at the same time. It seems odd.

2023-11-24 08:07 UTC, adiux commented
I understood that they are removed from the URL? If the tracking on the destination page is still possible I think it's ok.

2023-11-24 08:31 UTC, kuzmany commented
@adiux destination page has UTM tags of course

2023-11-24 08:37 UTC, adiux commented
Should we not see them in the image from @jos0405 then? I remember we had this problem with our implementation: https://github.com/mautic/mautic/pull/12169/files#diff-c1c31cf7a6f5ca450d84c2e2babfeb10fabc2d9732e23070e39a808e0a4b823aR469

2023-11-24 09:04 UTC, kuzmany commented
At the moment works like that
- page hit without UTM is redirection item
- page hit with UTM is destination page with UTM and tracked UTM

![image](https://github.com/mautic/mautic/assets/462477/f3a321c2-ea02-474d-a04b-297ffc3273b8)


For me it's correct

2026-03-03 20:27 UTC, closed without merging