TPROD: Fix entity names using rector
mautic/mautic pull request #12257
Opened 2023-04-22 10:35 UTC by mabumusa1

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-04-27 23:49 UTC, mabumusa1 commented
Rules to be added after this PR

```
To be applied
AddEntityIdByConditionRector
ClassAnnotationToNamedArgumentConstructorRector
ManagerRegistryGetManagerToEntityManagerRector
MoveRepositoryFromParentToConstructorRector
ReplaceLifecycleEventArgsByDedicatedEventArgsRector
ReplaceParentRepositoryCallsByRepositoryPropertyRector
ServiceEntityRepositoryParentCallToDIRector

Not found in the current version of rector
ChangeCompositeExpressionAddMultipleWithWithRector
RemoveEmptyTableAttributeRector
```

2023-05-16 11:35 UTC, escopecz requested changes
@mabumusa1 I did another part of review. I still cannot get through it all. I'll continue another day to get to other tasks. If you'll see similar issues in the diff, please change them.

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/LeadEventLog.php
> +     * @var LeadEntity
This should be nullable

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/LeadEventLog.php
> +     * @var Event
This should be nullable

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/LeadEventLog.php
> +     * @var LeadEntity
This should be nullable

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/LeadEventLog.php
> +     * @var bool|null
This should not be nullabe. It has a default value of `false`

2023-05-16 11:35 UTC, escopecz commented on app/bundles/ChannelBundle/Entity/Message.php
> +     * @var string
This should be nullable

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CoreBundle/Entity/TranslationEntityInterface.php
> +     * @return mixed
This won't work?
```suggestion
     * @return TranslationEntityInterface|null
```

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CoreBundle/Entity/TranslationEntityTrait.php
> +     * @var mixed
This won't work? Similar to other changes in this file
```suggestion
     * @var ArrayCollection<TranslationEntityInterface>
```

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CoreBundle/Entity/VariantEntityInterface.php
> +     * @return mixed
```suggestion
     * @return VariantEntityInterface|null
```

2023-05-16 11:35 UTC, escopecz commented on app/bundles/CoreBundle/Entity/VariantEntityTrait.php
> +     * @var mixed
This won't work? Similar to other changes in this file
```suggestion
     * @var ArrayCollection< VariantEntityInterface >
```

2023-05-16 11:35 UTC, escopecz commented on app/bundles/EmailBundle/Entity/Stat.php
> +     * @var string
Should be nullable

2023-05-16 11:35 UTC, escopecz commented on app/bundles/LeadBundle/Entity/Company.php
> +     * @var int|null
This should not be nullable as it has default value of `0`

2023-05-16 11:35 UTC, escopecz commented on app/bundles/LeadBundle/Entity/CompanyLead.php
> +     * @var bool|null
This should not be nullable as it has a default value of `false`

2023-05-23 14:23 UTC, escopecz approved these changes
I see no problem with these changes. Thanks for replacing those strings! 👍

2023-05-23 14:23 UTC, merged