A/B test enhancements M5
mautic/mautic pull request #12275
Opened 2023-04-28 08:59 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Fork https://github.com/mautic/mautic/pull/11990 for M5

This feature will let users to send the A/B test to a small subset of contacts, decides which version is the winner based on configured criteria and then the rest of the segment(s) will receive the winner variant.

An example of how it would look:

Start with a segment of 1,000 contacts

1.) Set up an A/B Test with three different emails, each of a weight of 10%

Email A - send to 100 people
Email B - send to 100 people
Email C - send to 100 people

2.) Create a 'winning criteria' i.e. email open rate

Email A - Open rate is 25%
Email B - Open rate is 15%
Email C - Open rate is 10%

3.) The winning email is sent to the rest of the contacts after a predetermined amount of time

Email A is sent to remaining 70% of segment 3 hours later

New command for sending winner variant:
mautic: email:sendwinner - searches for all emails with variant settings for automatic sending the winner variant, can be used by a cron job
mautic: email:sendwinner --id=101 - works for a single email only

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Crete Email, enable AB test in settings, set total weight for the AB test and predetermined amount of hours for sending Winner variant to remaining contacts
3. Add A/B test variant, set weight
4. Send email, variants are sent using total weight for the AB test
5. Run mautic: email:sendwinner command, if the command is run after predetermined amount of hours, email is sent to remaining contacts, winner variant is converted to parent variant, weight of the winner variant is set to 100 and other variants are unpublished. Test it also when a winner variant is already the parent one.
6. Verify that it works also with email variants created before this change
7. Verify that Page variants are still working the same, part of the functionality is shared

#### List backwards compatibility breaks:
1. Variant criteria is now saved in parent variant, instead of each variant child. Should still work with already created variants in old way.

2023-06-25 14:30 UTC, volha-pivavarchyk commented
@kuzmany Could you please clarify how to enable AB test in settings. I didn't find the setting. And it is not available by default, as before.
![image](https://github.com/mautic/mautic/assets/96085911/557756cc-46af-4b2a-8400-5c90f79c0cc8)

2023-06-26 03:23 UTC, kuzmany commented
@volha-pivavarchyk you can create A/B test just from the new segment email. 
You will find on the right side A/B test switch button to enable it. Then you continue based on docs

https://github.com/kuzmany/mautic-documentation/blob/a96fe3ae102319a4b77461f8939c9800f67d64e3/pages/09.Channels/02.Emails/06.%20AB%20testing/docs.en.md

2023-06-26 09:55 UTC, MarketingProductionDepartment commented
Hi @kuzmany,
do you plan to develop this function also for template email? Unfortunately, email segments are not used in our organisation.

2023-06-26 10:14 UTC, kuzmany commented
@MarketingProductionDepartment no

2023-06-30 15:27 UTC, volha-pivavarchyk commented
@kuzmany I crete a segment email
![image](https://github.com/mautic/mautic/assets/96085911/40311875-2445-42b9-9353-992eaf49280e)
![image](https://github.com/mautic/mautic/assets/96085911/787763b5-a6dd-422b-a262-ed51bd9b1a01)
I can see `add A/B test` after switching to 5.x
![image](https://github.com/mautic/mautic/assets/96085911/0bdf7c85-4536-4281-a9d0-6e81fc91a5c8)

If I could solve this problem I would test this PR :)

2023-07-02 10:23 UTC, kuzmany commented
@volha-pivavarchyk check docs.: https://github.com/kuzmany/mautic-documentation/blob/a96fe3ae102319a4b77461f8939c9800f67d64e3/pages/09.Channels/02.Emails/06.%20AB%20testing/docs.en.md

New A/B testing you can use just on emails that are created as A/B tests. That means If you create a segment email, you can on the right side enable the emails as A/B testing and then you are able to create from parent email children.

2023-07-03 13:28 UTC, patrykgruszka requested changes
I've got problem with the `mautic:email:sendwinner` command.

Tried calling it without parameter:
```
$ ddev exec bin/console mautic:email:sendwinner

Email id 0 not found
```

And with `id` parameter:
```
$ ddev exec bin/console mautic:email:sendwinner --id=5

In MissingNamedParameter.php line 15:
Named parameter "email" does not have a bound value.
```

This PR also removes the A/B testing functionality for template emails, so it will no longer be available when sending emails during the campaign. This should be described in the BC section if you are not implementing this feature.

2023-07-03 13:28 UTC, patrykgruszka commented on .ddev/config.yaml
> +name: mautic5
I think this is something from your local configuration and shouldn't be committed.

2023-07-03 13:28 UTC, patrykgruszka commented on app/bundles/CoreBundle/Event/DetermineWinnerEvent.php
> +     *   factory?: \Mautic\CoreBundle\Factory\MauticFactory,
Do we need this factory in this event? I can't find any usage of it in code, but maybe I'm missing something because the objects are hidden in an array.

2023-07-03 13:28 UTC, patrykgruszka commented on app/bundles/EmailBundle/Command/SendWinnerEmailCommand.php
> +        $emailId       = (int) $input->getOption('id');
Calling this command without `id` parameter results in `$emailId = 0` due to type casting in this line.

2023-07-04 06:56 UTC, kuzmany commented
@patrykgruszka as I know A/B for template emails never supported https://kb.mautic.org/article/how-to-create-an-a-b-test-for-emails-in-mautic.html 

> A/B testing is available for Segment emails only.

Others, I'll take a look

2023-08-04 12:14 UTC, RCheesley commented
Conflicts and pending feedback to be resolved on this one.

2023-08-16 04:10 UTC, kuzmany commented
I am gonna make it a draft,  we have some improvements in the private branch I will update it  within next days

2024-01-09 18:29 UTC, RCheesley commented
Shall we close this PR @kuzmany ? There's a linked docs PR for it.

2024-01-09 20:33 UTC, kuzmany commented
@RCheesley Meanwhile, we made more PRs related to this, but don't know when to find the hours to push it all to the community.

2024-02-27 11:10 UTC, dadarya0 commented
@kuzmany could you please make this PR mergeable?  we are blocked to push many PR related to A/B testing because of this in part of unforking.

CC - @escopecz

2024-02-27 11:39 UTC, kuzmany commented
@dadarya0 We using it in production on 4. x. There are more PRs related to it, I can push it as a single PR, If we are able to merge it.

2024-07-23 14:52 UTC, RCheesley commented
@kuzmany if you can't dedicate the time to update this PR I suggest that we move forward with another solution, or ask another developer to bring it over the line. Many PRs are waiting on this since back in February and it's a long-requested feature. Can you focus any time on this do you think? If not we will close this by the end of August and find a different way forward.

2024-07-23 18:56 UTC, kuzmany commented
@RCheesley We aim to have this feature ready by the end of August, prepared for Mautic 5 (without unit tests). Then, we can share it with the community if @npracht agrees.

2024-07-23 19:07 UTC, npracht commented
Good for me. @RCheesley we rely on you for a fast test and merge when ready to not carry new conflicts.

2024-07-24 08:06 UTC, RCheesley commented
That sounds great, but we won't be able to merge without the unit test coverage. Can you please ensure that is factored into the work that needs to be done? Thanks!

2024-07-24 08:29 UTC, kuzmany commented
@RCheesley I hope someone will help with it

2024-08-22 15:01 UTC, RCheesley commented
@kuzmany just checking in, are you on track to get this completed and ready for review by the end of August?

2024-08-23 10:19 UTC, kuzmany commented
@RCheesley working on it. Hope next week

Close at the moment. We will push it again once ready to M5

2024-08-23 10:19 UTC, closed without merging