Backport: remove citrix plugin
mautic/mautic pull request #12367
Opened 2023-05-19 15:39 UTC by mabumusa1

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Companion PR to #12333

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-05-19 20:15 UTC, escopecz commented
We did not understand each other. Apologies. I meant that you'd deprecate the Citrix plugin for Mautic 4.4.9 as Ruth suggested. We have to firstly deprecate the plugin in one version and then we can delete it in the next major version. We cannot remove it in 4.4.9 as it is a BC break.

This is the deprecation PR I did for Pipedrive for inspiration: https://github.com/mautic/mautic/pull/12364

2023-05-21 20:56 UTC, mabumusa1 commented
Sample outputs
![image](https://github.com/mautic/mautic/assets/12627658/aa2b455a-396a-4d20-9e77-2a31004aab69)
![image](https://github.com/mautic/mautic/assets/12627658/ef72d2ee-802c-4a9a-9e6b-d52107f60fbb)

2023-05-21 21:05 UTC, mabumusa1 commented on phpstan-baseline.neon
> +		-
@escopecz this error was ignored for other plugins so I ignored it as well

2023-05-21 21:06 UTC, mabumusa1 commented
> We did not understand each other. Apologies. I meant that you'd deprecate the Citrix plugin for Mautic 4.4.9 as Ruth suggested. We have to firstly deprecate the plugin in one version and then we can delete it in the next major version. We cannot remove it in 4.4.9 as it is a BC break.
> 
> This is the deprecation PR I did for Pipedrive for inspiration: #12364

No worries and thanks for pointing me to the right direction, I updated the PR as required

2023-05-22 09:15 UTC, escopecz commented on phpstan-baseline.neon
> +		-
I'm OK with this since the goal of this PR is to remove the Citrix plugin altogether. Thanks for pointing this out!

2023-05-22 09:24 UTC, escopecz requested changes
@mabumusa1 please create also similar migration to https://github.com/mautic/mautic/pull/12364/files#diff-ac792d02497f71aedb711f6dd2540b2870677153a10b9bf74cd5a9cc196bffaaR12 that will add the deprecation messages to all users if the Citrix plugin is enabled in that Mautic instance.

@RCheesley @mollux Do we need an announcement blog post like we had for Pipedrive (https://github.com/mautic/mautic/pull/12364) or is it OK with deprecating it and suggesting an alternative plugin?

2023-05-22 09:27 UTC, RCheesley commented
> @RCheesley @mollux Do we need an announcement blog post like we had for Pipedrive (#12364) or is it OK with deprecating it and suggesting an alternative plugin?

I think that if there is an alternative that is open source and freely available, it's helpful to raise more awareness of the process in a blog post which will reach a different audience. If that is the case maybe the maintainers of the plugin would be up for writing it?

2023-05-22 12:07 UTC, mabumusa1 commented
@escopecz I added the migration in this commit 095a3d2fa61ef5864f4776011f29a736b4c0c181

2023-05-22 13:42 UTC, escopecz commented on app/migrations/Version20230522115137.php
> +        $header  = 'The Pipedrive plugin will be removed in Mautic 5.0.0';
```suggestion
        $header  = 'The Citrix plugin will be removed in Mautic 5.0.0';
```

2023-05-22 13:46 UTC, escopecz reviewed
Once they forgotten plugin name is corrected this is good to go from code perspective. The command alert works:
```
bin/console mautic:citrix:sync

                                                                                                                        
 [WARNING] The Citrix plugin is deprecated and will be removed in Mautic 5. See <a                                      
           href="https://www.leuchtfeuer.com/en/mautic/know-how/mautic/gotowebinar-plugin-new-features/"                
           target=”_blank”>an alternative</a> for this plugin.
```
The notification is created.

And the warning appears in all 3 Citrix plugins:
![Screenshot 2023-05-22 at 15 44 56](https://github.com/mautic/mautic/assets/1235442/cafd6cf9-1bf0-44eb-a616-45bd05b8be71)

2023-05-22 13:50 UTC, escopecz approved these changes, later dismissed
Good to go from code perspective. Thanks! 👍

2023-05-23 17:47 UTC, RCheesley commented
Before this is merged can we just double check with Ekke and team that it's the right place to direct people (eg current URL or GitHub etc) before we push it out to everyone?

2023-05-24 16:37 UTC, ekkeguembel requested changes
Please change deprecation / replacement URL to https://www.leuchtfeuer.com/en/mautic/downloads/mautic-goto-plugin/
(Looks of that page preliminary, content is largely rendered from README.md which will be overhauled prior to 4.4.9... but URL is final : )

2023-05-24 18:42 UTC, mabumusa1 commented
> Please change deprecation / replacement URL to https://www.leuchtfeuer.com/en/mautic/downloads/mautic-goto-plugin/ (Looks of that page preliminary, content is largely rendered from README.md which will be overhauled prior to 4.4.9... but URL is final : )

Fixed in commit 5334fc3a1f911b3b4ba325a2ba0c8d9e7c2ab3c1

2023-05-25 08:59 UTC, merged