WIP: TPROD-457 - PHP 8.1
mautic/mautic pull request #12382
Opened 2023-05-24 17:14 UTC by diaboloshogunate

#### Description:

There are a number of issues with upgrading to PHP 8.1. They will be fixed in separate PRS. When all issues are resolved this will be taken out of WIP.

2023-06-08 13:03 UTC, mabumusa1 requested changes
Initial running to the code resulted in these notes, plus the notes that we know from `SendGrid` 

```

Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /var/www/html/vendor/mrclay/minify/min/lib/Minify/CSS/Compressor.php on line 238
PHP Deprecated:  ord(): Passing null to parameter #1 ($character) of type string is deprecated in /var/www/html/vendor/mrclay/minify/min/lib/JSMin.php on line 326

Deprecated: ord(): Passing null to parameter #1 ($character) of type string is deprecated in /var/www/html/vendor/mrclay/minify/min/lib/JSMin.php on line 326
PHP Deprecated:  ord(): Passing null to parameter #1 ($character) of type string is deprecated in /var/www/html/vendor/mrclay/minify/min/lib/JSMin.php on line 326

Deprecated: ord(): Passing null to parameter #1 ($character) of type string is deprecated in /var/www/html/vendor/mrclay/minify/min/lib/JSMin.php on line 326

```

2023-06-08 13:03 UTC, mabumusa1 commented on .ddev/config.yaml
> +php_version: "8.1"
Line #16 should be changed as well to `php8.1-imap`

2023-06-09 15:08 UTC, escopecz commented
@mabumusa1 I'm not getting these warnings. But I created https://github.com/mautic/mautic/pull/12461 which should fix it. Please review.

2023-06-09 16:13 UTC, mabumusa1 approved these changes
Looks good, works as expected

2023-06-09 18:35 UTC, escopecz approved these changes

2023-06-09 18:35 UTC, merged