Fix an issue where dateFrom and dateTo are null in the 'Contact Segment Activity Log' report
mautic/mautic pull request #12431
Opened 2023-06-05 12:50 UTC by volha-pivavarchyk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ &check; ]
| New feature/enhancement? (use the a.x branch)      | [&cross;]
| Deprecations?                          | [&cross;]
| BC breaks? (use the c.x branch)        | [&cross;]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

An error is returned when trying to retrieve the `Contact's segments activity log` report via the API without parameters. This PR fixes it.
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create the report with `Contact's segments activity log` as a data source.
3. Try to get the report via API `/api/reports/ID`.
4. It works well. 500er was before

2024-02-01 12:08 UTC, LordRembo commented
I just get a 401: access denied error when viewing the report via the API path that is described.
The segment I used is just 1 contact and the report uses first name and last name.

2024-02-01 12:10 UTC, LordRembo commented
![Screenshot 2024-02-01 at 13 10 22](https://github.com/mautic/mautic/assets/758957/20af038e-6342-4cbe-9437-afd4f45fdaa8)

![Screenshot 2024-02-01 at 13 09 48](https://github.com/mautic/mautic/assets/758957/3bd98495-e6bb-4d1e-814b-259e5aa826bf)
![Screenshot 2024-02-01 at 13 09 52](https://github.com/mautic/mautic/assets/758957/8cff30cc-ddfa-45a5-9cfe-b5b0860383c0)
![Screenshot 2024-02-01 at 13 09 58](https://github.com/mautic/mautic/assets/758957/9f14e188-5c71-4f80-9a37-acd7b2726c79)

2024-02-01 13:14 UTC, kuzmany commented on app/bundles/LeadBundle/EventListener/SegmentLogReportSubscriber.php
> +        $dateFrom = $event->getOptions()['dateFrom'] ?? (new \DateTime('-30 days'));
If we use it in php.ini different timezone, then Datetime object return time in timezone from php.ini.
Need force set UTC time or use DateTimeHelper with toUtcString method.

2024-02-01 16:43 UTC, kuzmany requested changes

2024-02-01 16:43 UTC, kuzmany commented on app/bundles/LeadBundle/EventListener/SegmentLogReportSubscriber.php
> +        $dateTo   = $event->getOptions()['dateTo'] ?? (new \DateTime());
If we use a different timezone in php.ini, the DateTime object will return the time based on the timezone set in php.ini. To ensure that the time is in UTC, we need to either forcibly set it to UTC or use the toUtcString method provided by DateTimeHelper.

2024-04-19 13:42 UTC, LordRembo requested changes
@volha-pivavarchyk Is it possible to pick up the change request for this ticket?

2024-04-21 20:39 UTC, volhapivavarchyk commented
@LordRembo 

I think I should be able to get back to my PRs by the end of next week. I don't mind if someone picks up the PR and does it faster. 

I apologize, I've been involved in other projects lately and haven't had any time at all to do anything here.

2025-06-20 11:07 UTC, adiux commented
@volha-pivavarchyk are you able to finish this?

2025-07-01 06:55 UTC, shinde-rahul commented
This can be closed since I have re-created https://github.com/mautic/mautic/pull/15140 from this.

2025-07-01 07:02 UTC, closed without merging