Doctrine deprecated functions 11970
mautic/mautic pull request #12459
Opened 2023-06-09 13:35 UTC by lenonleite

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-06-09 18:43 UTC, escopecz commented
@lenonleite is this ready to review or WIP?

2023-06-09 18:52 UTC, mabumusa1 requested changes
There is a couple of places that needs changing other than that, it is good

2023-06-09 18:52 UTC, mabumusa1 commented on app/bundles/AssetBundle/Entity/DownloadRepository.php
> +        return $query->fetchAllAssociative();
```suggestion
        return $query->executeQuery()->fetchAllAssociative();
```

2023-06-09 18:52 UTC, mabumusa1 commented on app/bundles/AssetBundle/Entity/DownloadRepository.php
> +        $results = $query->fetchAllAssociative();
```suggestion
        $results = $query->executeQuery()->fetchAllAssociative();
```

2023-06-09 18:58 UTC, mabumusa1 commented
> @lenonleite is this ready to review or WIP?

@escopecz I talked to him in the morning, it is ready for testing

2023-08-24 19:50 UTC, RCheesley commented
@lenonleite please provide test instructions to help testers with reviewing this PR? Thanks!

2023-10-26 17:53 UTC, RCheesley commented
@lenonleite we need some test instructions here? It'd be good to know what parts it touches and what testers should look for - can you update the description?

2023-11-13 08:37 UTC, closed without merging