00-Rector: Upgrade code to PHP8.0
mautic/mautic pull request #12477
Opened 2023-06-13 07:33 UTC by mabumusa1

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

I managed to run rector config set to upgrade the code base to be `php8.0` compatible, this PR is the first in a series of PRs that upgrade each bundle on its own. 

This PR fixes all the issues I encountered in #12322, once this is merged I will start running the rules for all the other bundles in sequence  

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-06-16 08:51 UTC, escopecz requested changes
@mabumusa1 I added a few comments just to the first file. When we are changing a method signature, we should think about that very carefully as it is a BC break change. So we should do it completely. Adding one type and leaving other params or return type empty doesn't look that good.

Also, we cannot count on the types defined in the method doc blocks. They ware copied most of the time and developers do not pay attention to them when the code works. So we must carefully evaluate every type. This can add many bugs to the product. And adding `mixed` type everywhere is the same thing as having no types at all.

2023-06-16 08:51 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/Event.php
> +    private function isChanged($prop, mixed $val)
Why not adding all the types when in it?

2023-06-16 08:51 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/Event.php
> +    public function getLogByContactAndRotation(Contact $contact, $rotation): ?LeadEventLog
Same here. When we are changing the method signature, why not add all types?

2023-06-16 08:51 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/Event.php
> +    public function getChildren(): Collection|array
The `children` property can only hold a `Collection` value. Is the return type of `array` valid?

2023-06-16 08:51 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/Event.php
> +    public function setTriggerMode(mixed $triggerMode)
```suggestion
    public function setTriggerMode(?string $triggerMode): void
```

2023-06-16 08:51 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/Event.php
> +    public function setTriggerIntervalUnit(mixed $triggerIntervalUnit)
```suggestion
    public function setTriggerIntervalUnit(string? $triggerIntervalUnit): void
```

2023-06-21 21:49 UTC, mabumusa1 commented
Can not be implemented at the moment, we must fix `phpdoc` blocks with the correct types before

2023-06-21 21:49 UTC, closed without merging