[DPMMA-1660] Charts with email time stats in the contacts view
mautic/mautic pull request #12616
Opened 2023-08-01 09:32 UTC by annamunk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [WIP] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Charts with email time stats in the contacts view

![contact_email_time](https://github.com/mautic/mautic/assets/102536220/5f9754a2-7ca6-4803-8af0-83460fc3255e)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-08-04 04:16 UTC, kuzmany requested changes
I do not see benefits to having these statistics for a single contact, it makes sense for segments/emails...
But looks fancy.
Even though the graphs have to load with Ajax, similar like or others related PRs
 https://github.com/mautic/mautic/pulls?q=is%3Apr+sort%3Aupdated-desc+ajaxify+is%3Aclosed https://github.com/mautic/mautic/pull/6598

2023-08-04 04:20 UTC, kuzmany commented on app/bundles/EmailBundle/Model/EmailModel.php
> +    public function getEmailDayStats(Lead $lead): array
Do not see the reason to create these two public  methods instead of the call methods directly from repo

2023-08-24 13:40 UTC, annamunk commented
@kuzmany our marketers reported the need to have such charts. I think it's a good idea to add similar charts in segment/email views. If you don't mind, I could add them as a separate PR. I made suggested improvements and changed the way charts are loaded (AJAX). Could you please take a look again?

2023-09-07 06:05 UTC, PatrickJenkner approved these changes
Works exactly as described for a user and looks great 👍

2023-09-27 08:33 UTC, magdalenaleonow requested changes
@annamunk I found an issue:
 The charts don’t change with the system timezone (time and day) – charts are always in UTC timezone, correct day and time in chosen timezone is in Events history. Some examples below.
UTC timezone:
![image](https://github.com/mautic/mautic/assets/130159751/06e66e1b-ab94-4080-b2d0-69dbedc67d36)
Warsaw timezone:
![image](https://github.com/mautic/mautic/assets/130159751/4e943c95-f361-4ddc-85fd-ac7882e4e701)
Kiritimati timezone:
![image](https://github.com/mautic/mautic/assets/130159751/2a814431-6359-45f3-a15f-e4a74aea29c3)
The same issue for days of the week.
Kiritimati timezone -email2 read should be on Tuesday in this timezone
![image](https://github.com/mautic/mautic/assets/130159751/721bd01d-9d9a-4a47-adac-083c2daf8a81)
![image](https://github.com/mautic/mautic/assets/130159751/bfc90c86-8a9f-42e7-a2cc-3184106a71ce)
Everything else works great!

2023-09-27 14:49 UTC, annamunk commented
@magdalenaleonow thanks for noticing that! I added time zone offset to calculations. Could you please check again?

2023-10-04 10:45 UTC, magdalenaleonow requested changes
@annamunk everything works with the timezones, the only thing i found now is that the charts have stopped working for me at all in some timezones (Kiritimati, Chatha)
![image](https://github.com/mautic/mautic/assets/130159751/1f582885-739e-495d-866e-592ce3e7d765)

2023-10-20 11:55 UTC, annamunk commented
@magdalenaleonow thank you for catching this error! I checked what could be the reason and it seems that the SQL function that converts the time to the appropriate time zone (CONVERT_TZ) does not work properly if the offset exceeds +13:00, e.g. for 'Pacific/Chatham' - https://bugs.mysql.com/bug.php?id=90043. I will try to calculate statistics differently to avoid using convert_tz.

2024-01-04 16:00 UTC, annamunk commented
@magdalenaleonow I replaced the CONVERT_TZ method with another one. Could you please check whether the data is now displayed correctly for the indicated time zones?

2024-01-09 11:35 UTC, magdalenaleonow approved these changes
@annamunk everything is working now, thanks!

2026-06-08 18:36 UTC, andersonjeccel commented
Hey, I'm seeing this PR has been quiet for a while, so it looks stalled. We're doing a small cleanup so the review queue stays focused on PRs that are still being worked on and closer to merge. If this was not the right call, I'm happy to see it reopened and updated.

2026-06-08 18:37 UTC, closed without merging