Label support for contactfield token
mautic/mautic pull request #12620
Opened 2023-08-04 05:27 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR follow up https://github.com/mautic/mautic/pull/10623
Enable new modifier to contactfield token to display label of values for select and boolean type.  To display label we can use:

`{contactfield=select_alias|label}`

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create contact and company select and boolean  fields
3.  Create contact and set value to these fields
4. Create email and put tokens
Contact fields:

contact select field with value `{contactfield=select_alias}`
contact select field with label  `{contactfield=select_alias|label}`
contact bool field with value `{contactfield=bool_alias}`
contact bool  field with label  `{contactfield=bool_alias|label}`

Company fields:

company select field with value `{contactfield=company_select_alias}`
company select field with label  `{contactfield=company_select_alias|label}`
company bool field with value `{contactfield=company_bool_alias}`
company bool  field with label  `{contactfield=company_bool_alias|label}`

5. Send email and check If you receive values as you requested

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10626"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-08-06 22:32 UTC, volha-pivavarchyk approved these changes
Works well. Thanks.

![image](https://github.com/mautic/mautic/assets/96085911/59a8f9af-ad2e-4379-88a7-24d8e7d9a4ad)

2023-08-08 07:15 UTC, PatrickJenkner reviewed
Almost all of the labels worked fine, but the company booleans weren't displayed, the space was left blank. Might be user error since I'm relatively new to mautic, but I checked for typos etc.

2023-08-18 12:53 UTC, RCheesley commented
@kuzmany did your latest commits address the feedback from @PatrickJenkner ?

2023-08-25 11:09 UTC, kuzmany commented
@PatrickJenkner I receive correct boolean label for company field

![image](https://github.com/mautic/mautic/assets/462477/ffe22165-4d00-44f9-b35b-8c9deff6d2d6)

2023-09-09 13:58 UTC, volha-pivavarchyk reviewed
Works well for me. Boolean company fields are displayed
![image](https://github.com/mautic/mautic/assets/96085911/6d7d8a3c-8b92-4769-bfe5-7a8c15331c0f)

I faced only the following case. Company field values and labels are not displayed in personal emails  (sent from conatct view page). Don't know it is ok or not.
![image](https://github.com/mautic/mautic/assets/96085911/58bb2bdb-4aba-4ae1-8748-bf4a6b76b27d)

2023-09-11 05:19 UTC, kuzmany commented
@volha-pivavarchyk good catch. But I assume it's related to another issue.  Se set just contact values in LeadController https://github.com/mautic/mautic/blob/03da89b48332bc7a17cd6228262f7b143ba3ddc1/app/bundles/LeadBundle/Controller/LeadController.php#L1430

We need to add company values there. But we figure out it in another PR

2023-12-08 13:05 UTC, RCheesley commented
Hi folks, thanks for the reviews! I've raised a separate issue and assigned it to you @kuzmany to ensure we don't lose sight of the company fields not being displayed. Let's address that in a separate PR as suggested. RTC with code review.

2024-01-09 16:42 UTC, escopecz commented
Multiple conflicts here too

2024-09-02 05:14 UTC, shinde-rahul requested changes

2024-09-02 05:14 UTC, shinde-rahul commented on app/bundles/LeadBundle/Tests/EventListener/ReportNormalizeSubscriberTest.php
> +        $field =  new LeadField();
```suggestion
        $field = new LeadField();
```

2024-09-02 05:14 UTC, shinde-rahul commented on app/bundles/LeadBundle/Field/FieldList.php
> +        /**
This method needs re-indentation.

2024-09-13 09:44 UTC, adiux commented
This seems to be almost ready to merge? Would be great if we can get it done!

2024-10-26 07:37 UTC, adiux commented
@kuzmany any chance you can take a look at this? Since we closed our PR with this functionality, we are now kinda blocked by this to be implemented. Let us know if we can help.

2024-10-28 10:27 UTC, shinde-rahul requested changes

2024-10-28 10:27 UTC, shinde-rahul commented on app/bundles/LeadBundle/Field/FieldList.php
> +            $leadFields = [];
The indentation needs to be fixed.

2024-11-08 23:39 UTC, shinde-rahul reviewed
The code changes look good to me.

The only question is the following, 

I see an additional empty file `.ddev/commands/host/phpmyadmin`. Is this needed?

2024-11-09 00:28 UTC, shinde-rahul commented
@kuzmany, this is failing with the following error,
```
 500 Internal Server Error - Typed static property Mautic\LeadBundle\Entity\LeadRepository::$leadFieldRepository must not be accessed before initialization 
/html/app/bundles/LeadBundle/Entity/LeadRepository.php:101 at
/html/app/bundles/LeadBundle/Helper/TokenHelper.php:165 at Mautic\LeadBundle\Entity\LeadRepository :: getLeadFieldRepository ( )
/html/app/bundles/LeadBundle/Helper/TokenHelper.php:91 at Mautic\LeadBundle\Helper\TokenHelper :: getNormalizeValue ( )
/html/app/bundles/LeadBundle/Helper/TokenHelper.php:44 at Mautic\LeadBundle\Helper\TokenHelper :: getTokenValue ( )
/html/app/bundles/LeadBundle/EventListener/EmailSubscriber.php:58 at Mautic\LeadBundle\Helper\TokenHelper :: findLeadTokens ( )
/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:118 at Mautic\LeadBundle\EventListener\EmailSubscriber -> onEmailGenerate ( )
/html/vendor/symfony/event-dispatcher/EventDispatcher.php:230 at Symfony\Component\EventDispatcher\Debug\WrappedListener -> __invoke ( )
/html/vendor/symfony/event-dispatcher/EventDispatcher.php:59 at Symfony\Component\EventDispatcher\EventDispatcher -> callListeners ( )
/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154 at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( )
/html/app/bundles/EmailBundle/Helper/MailHelper.php:1494 at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> dispatch ( )
/html/app/bundles/EmailBundle/Helper/MailHelper.php:334 at Mautic\EmailBundle\Helper\MailHelper -> dispatchSendEvent ( )
/html/app/bundles/LeadBundle/Controller/LeadController.php:1479 at Mautic\EmailBundle\Helper\MailHelper -> send ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\LeadBundle\Controller\LeadController -> emailAction ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:156 at Symfony\Component\HttpKernel\HttpKernel -> handle ( )
/html/app/bundles/CoreBundle/Controller/CommonController.php:415 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( )
/html/vendor/symfony/http-kernel/Kernel.php:202 at Symfony\Component\HttpKernel\HttpKernel -> handle ( )
/html/app/AppKernel.php:109 at Symfony\Component\HttpKernel\Kernel -> handle ( )
/html/app/middlewares/CORSMiddleware.php:76 at AppKernel -> handle ( )
/html/app/middlewares/HSTSMiddleware.php:39 at Mautic\Middleware\CORSMiddleware -> handle ( )
/html/app/middlewares/CatchExceptionMiddleware.php:28 at Mautic\Middleware\HSTSMiddleware -> handle ( )
/html/app/middlewares/Dev/IpRestrictMiddleware.php:52 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( )
/html/app/middlewares/VersionCheckMiddleware.php:58 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( )
/html/app/middlewares/TrustMiddleware.php:42 at Mautic\Middleware\VersionCheckMiddleware -> handle ( )
/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( )
/html/index.php:19 at Stack\StackedHttpKernel -> handle ( )
```

<img width="783" alt="Screenshot 2024-11-09 at 5 56 50 AM" src="https://github.com/user-attachments/assets/d659ade3-3555-495c-9192-8ccc33830fed">

2024-11-21 10:52 UTC, adiux commented
@kuzmany Any chance you can take a look at this in the coming days?

2024-11-21 13:54 UTC, kuzmany commented
@adiux I will try

2025-03-07 07:14 UTC, adiux commented
@kuzmany any news?

2025-03-24 14:12 UTC, shinde-rahul commented
```
[2025-03-24T14:09:17.537773+00:00] mautic.CRITICAL: Uncaught PHP Exception Error: "Typed static property Mautic\LeadBundle\Entity\LeadRepository::$leadFieldRepository must not be accessed before initialization" at /var/www/html/app/bundles/LeadBundle/Entity/LeadRepository.php line 103 {"exception":"[object] (Error(code: 0): Typed static property Mautic\\LeadBundle\\Entity\\LeadRepository::$leadFieldRepository must not be accessed before initialization at /var/www/html/app/bundles/LeadBundle/Entity/LeadRepository.php:103)
[stacktrace]
#0 /var/www/html/app/bundles/LeadBundle/Helper/TokenHelper.php(165): Mautic\\LeadBundle\\Entity\\LeadRepository::getLeadFieldRepository()
#1 /var/www/html/app/bundles/LeadBundle/Helper/TokenHelper.php(91): Mautic\\LeadBundle\\Helper\\TokenHelper::getNormalizeValue()
#2 /var/www/html/app/bundles/LeadBundle/Helper/TokenHelper.php(44): Mautic\\LeadBundle\\Helper\\TokenHelper::getTokenValue()
#3 /var/www/html/app/bundles/LeadBundle/EventListener/EmailSubscriber.php(58): Mautic\\LeadBundle\\Helper\\TokenHelper::findLeadTokens()
#4 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(116): Mautic\\LeadBundle\\EventListener\\EmailSubscriber->onEmailGenerate()
#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke()
#6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#7 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#8 /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php(1476): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch()
#9 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(353): Mautic\\EmailBundle\\Helper\\MailHelper->dispatchSendEvent()
#10 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(171): Mautic\\EmailBundle\\Model\\SendEmailToContact->sendStandardEmail()
#11 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1451): Mautic\\EmailBundle\\Model\\SendEmailToContact->send()
#12 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1093): Mautic\\EmailBundle\\Model\\EmailModel->sendEmail()
#13 /var/www/html/app/bundles/EmailBundle/Controller/AjaxController.php(64): Mautic\\EmailBundle\\Model\\EmailModel->sendEmailToLists()
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Mautic\\EmailBundle\\Controller\\AjaxController->sendBatchAction()
#15 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#16 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(111): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#17 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(128): Mautic\\CoreBundle\\Controller\\CommonController->forwardWithPost()
#18 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction()
#19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#20 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(111): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#21 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(100): Mautic\\CoreBundle\\Controller\\CommonController->forwardWithPost()
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#23 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#24 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#25 /var/www/html/app/AppKernel.php(101): Symfony\\Component\\HttpKernel\\Kernel->handle()
#26 /var/www/html/app/middlewares/CORSMiddleware.php(76): AppKernel->handle()
#27 /var/www/html/app/middlewares/HSTSMiddleware.php(39): Mautic\\Middleware\\CORSMiddleware->handle()
#28 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(28): Mautic\\Middleware\\HSTSMiddleware->handle()
#29 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle()
#30 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle()
#31 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle()
#32 /var/www/html/app/middlewares/StackedHttpKernel.php(55): Mautic\\Middleware\\TrustMiddleware->handle()
#33 /var/www/html/index.php(19): Mautic\\Middleware\\StackedHttpKernel->handle()
#34 {main}
"} {"hostname":"mautic-web","pid":3969}
```
It's still the same error.

2025-03-24 15:08 UTC, escopecz commented on app/bundles/LeadBundle/Entity/LeadFieldRepository.php
> +    private static ?array $fields;
```suggestion
    private ?array $fields = null;
```
This is where the error comes from. Can we use just a private property instead of static? It generates hard to find bugs. For example in tests when the array is filled in one test and it remains the same for the rest of the tests no matter if the fields change or not.

2025-03-28 16:24 UTC, kuzmany commented
Please re-test now

2025-04-07 02:30 UTC, shinde-rahul commented
@kuzmany, Still failing.

<img width="1309" alt="Screenshot 2025-04-07 at 7 56 57 AM" src="https://github.com/user-attachments/assets/2b013d85-1e68-4197-a2b1-db799add1113" />

2025-05-07 13:55 UTC, adiux commented
@kuzmany was this closed on purpose?

2025-05-07 13:57 UTC, kuzmany commented
It will be re-pushed

2025-05-23 03:24 UTC, shinde-rahul commented
@kuzmany, I followed the steps as mentioned, but it still failed with,
```
 500 Internal Server Error - Typed static property Mautic\LeadBundle\Entity\LeadRepository::$leadFieldRepository must not be accessed before initialization 
``` 
Here is the attached screenshot when sending a segment email.

![image](https://github.com/user-attachments/assets/8e5ebbbb-5204-4784-944c-8f94dd0bdaee)

2025-05-23 09:17 UTC, kuzmany commented
@shinde-rahul sorry it still persit. I need ta a look deeper

2025-05-30 10:46 UTC, kuzmany commented
@shinde-rahul test now please. Does not work with Send custom email from contact profile. This should be fixed with https://github.com/mautic/mautic/pull/14944

2025-06-02 10:40 UTC, shinde-rahul approved these changes
It's working as described.

2025-06-02 11:59 UTC, escopecz approved these changes
We are stretching the limits of a static helper here. At some point we'll have to refactor these helpers to services.

2025-06-02 13:49 UTC, merged