Upgrade ckeditor 4 to 5
mautic/mautic pull request #12641
Opened 2023-08-09 13:51 UTC by dadarya0

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | No 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Upgraded ckeditor 4 to 5 as version 4 is deprecated.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-08-09 15:11 UTC, dadarya0 commented
@escopecz / @RCheesley  could you please help me in following 2 issues :-
1. why scaffolded file are exist in `app/assets/scaffold` ? , due to these files `scaffolded files mismatch` and `composer install`  is failing. As I have added all ckeditor supporting config  files in  common path`media/js/ckeditor` and due to common config files path is different at both places.

2. Ckeditor is failing in GrapesJsBuilderBundle, I check and found inside GrapesJs plugin we are downloading and using ckeditor4 via npm, could anyone look into this or help me who have experience in GrapesJs plugin ?

2023-08-09 15:31 UTC, escopecz commented
@dadarya0 the scaffolded files are used when installing Mautic via composer. Those are all files needed to run Mautic without using this repository but only `mautic/core-lib`.

cc @mollux

2023-08-09 15:31 UTC, escopecz commented
I asked for help with the second point in https://mautic.slack.com/archives/C01EGF5U422/p1691594971691209

2023-08-09 15:34 UTC, adiux commented
@dadarya0 I think the reason is that Mautic was not using npm at the time. So I guess this can be changed now.

2023-08-09 15:37 UTC, escopecz commented on package.json
> +    "webpack-cli": "^4.9.0",
Do you think it would be a better option to start implementing https://symfony.com/doc/5.4/frontend/encore/installation.html instead?

2023-08-09 16:11 UTC, dadarya0 commented
> I asked for help with the second point in https://mautic.slack.com/archives/C01EGF5U422/p1691594971691209

@escopecz  I have updated ckeditor 4 to 5 in GrapesJs, and working fine, just need to test thoroughly Email/Page builder in GrapesJs.

2023-08-10 09:16 UTC, dadarya0 commented on package.json
> +    "webpack-cli": "^4.9.0",
@escopecz  yes, I am trying to implement .

2023-08-11 04:58 UTC, dadarya0 commented on package.json
> +    "webpack-cli": "^4.9.0",
@escopecz I had tried to Install Encore but it also same webpack and If we will use encore then have to write webpack.config.js file in encore way.
I had tried to write webpack.config.js , it was generating ckeditor.js from our source file but not working as expected.
May there was missing in webpack.config.js in encore style so I had revert it.

2023-08-11 12:27 UTC, escopecz reviewed
Can we somehow remove this?
![Screenshot 2023-08-11 at 13 29 35](https://github.com/mautic/mautic/assets/1235442/3407b85f-f97f-466f-bbac-3acdb7eecef5)

2023-08-11 12:27 UTC, escopecz commented on app/assets/scaffold/files/ckeditor/src/InsertDropDown.js
> +export default class InsertDropDown extends Plugin {
I'm wondering why is it called `InsertDropDown` and not something like `DwcPlugin`?

2023-08-11 12:27 UTC, escopecz commented on app/bundles/CoreBundle/Tests/Command/GenerateProductionAssetsCommandTest.php
> +        $this->assertEquals(0, $commandTester->getStatusCode());
Is this test complete? I don't see an assert for checking if  the ck editor file exists or not.

2023-08-11 12:28 UTC, RCheesley requested changes
Thanks for making the PR @dadarya0 - will be great to update to CK5!

A few issues I found with GrapesJS editor:
Video for the first three issues: https://watch.screencastify.com/v/bAM4GyJIitveUIiU5XFE

1. When you make text bold and then change the colour, it's not represented in the editor but if you save, the colours are showing. This is not the same in other locations - seems to be specific to GrapesJS
2. It's not at all obvious that there is a hyperlink - you can't tell at all when you have the editor open. This is the case across all locations I tested.
3. It's not possible to edit links in the editor - nothing pops up to allow you to edit them when you select a hyperlink and press the link button. This is also the case in the focus item builder so not just restricted to GrapesJS.
4. In the GrapesJS builder there are more editorial options available than in the regular editing locations - is that intentional? In the focus item builder there are event more options still. I think we should be consistent and have the same options everywhere unless there is good reason not to? It would be really confusing as a user to be able to have some controls in one place and hardly any in another. Wondered if maybe it's related to the kind of content the field can accept?

![screenshot-8080-dadarya0-mautic-tt34wa3kicj ws-eu102 gitpod io-2023 08 11-13_21_15](https://github.com/mautic/mautic/assets/2930593/86f9a716-c1e3-4842-be1e-ce8346ea247d)

![screenshot-8080-dadarya0-mautic-tt34wa3kicj ws-eu102 gitpod io-2023 08 11-13_23_14](https://github.com/mautic/mautic/assets/2930593/0193398d-e225-4d4f-ab10-58cb259ab308)

2023-08-11 12:37 UTC, escopecz commented
I also noticed that the link option doesn't work in the Focus Items editor.

@RCheesley I think that Saurabh wanted to keep the similar buttons in the locations as they were. For example in the description field we want to allow only light formatting of text. In the Focus Items builder we want to allow them to insert images, videos and overall make the content more appealing to the audience.

2023-08-11 12:38 UTC, RCheesley commented
> in the description field we want to allow only light formatting of text. In the Focus Items builder we want to allow them to insert images, videos and overall make the content more appealing to the audience.

That's fine - if that is the case maybe we should have more options in GrapesJS? Or is the thought that those things would be done best with blocks maybe?

2023-08-11 12:40 UTC, escopecz commented
I think that this PR should keep the same functionality as with the CKE4. 

@dadarya0 where can we test the dropdown plugin that is there for tokens? I don't see it in the GrapesJS builder.

2023-08-11 12:47 UTC, RCheesley commented
Also found in this PR (and not in the 5.0 alpha or the 5.x branch) that all the images in the Brienz template are throwing a 404 error, although they are actually accessible. Not sure if that might be something to do with the npm build / asset regeneration process though.

2023-08-11 12:53 UTC, escopecz commented
It looks like some of the translations are missing:
<img width="353" alt="Screenshot 2023-08-11 at 14 52 33" src="https://github.com/mautic/mautic/assets/1235442/415f23b1-11af-4943-93f3-5784eed1521a">
I can see them working on the 5.x branch.

2023-08-11 12:56 UTC, dadarya0 commented
> Can we somehow remove this? ![Screenshot 2023-08-11 at 13 29 35](https://user-images.githubusercontent.com/1235442/260006062-3407b85f-f97f-466f-bbac-3acdb7eecef5.png)
@escopecz @RCheesley 
Yes, we can remove but to remove the logo, we need to obtain a commercial license and then configure the [config.licenseKey](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-licenseKey) setting.

There is 1 more way, it will not be visible if we used lower version then V38.0.0, It is started from version v38.0.0 onwards, all open-source installations of CKEditor 5 display a small “Powered by CKEditor” logo in the bottom-right corner of the editing area. The label links directly to the [CKEditor website](https://ckeditor.com/). The new branding approach is designed to make sure the entire community knows who is powering and modernizing their rich text editor.

2023-08-11 12:57 UTC, escopecz commented
Yep, it seems that we'll have to learn with that logo when the editor is in focus. https://ckeditor.com/docs/ckeditor5/latest/support/licensing/managing-ckeditor-logo.html

2023-08-11 12:57 UTC, dadarya0 commented
> It looks like some of the translations are missing: <img alt="Screenshot 2023-08-11 at 14 52 33" width="353" src="https://user-images.githubusercontent.com/1235442/260011118-415f23b1-11af-4943-93f3-5784eed1521a.png"> I can see them working on the 5.x branch.

2023-08-11 13:00 UTC, dadarya0 commented on app/assets/scaffold/files/ckeditor/src/InsertDropDown.js
> +export default class InsertDropDown extends Plugin {
yes, I will change the name of plugin.

2023-08-11 13:07 UTC, dadarya0 commented
> I also noticed that the link option doesn't work in the Focus Items editor.
> 
> @RCheesley I think that Saurabh wanted to keep the similar buttons in the locations as they were. For example in the description field we want to allow only light formatting of text. In the Focus Items builder we want to allow them to insert images, videos and overall make the content more appealing to the audience.

Yes, I am showing the similar buttons in the locations as they were at time of ckeditor 4 or froala.

2023-08-11 13:13 UTC, dadarya0 commented
@RCheesley @escopecz 
I see you are facing so many issue in ckeditor inside garpesJs editor like (color change of bold text, link and unlink etc) as GarpeJs is using own ckeditor so I am not able to do anything there but I believe on remaining pages except grapejs everything would work as expected.

2023-08-11 13:18 UTC, dadarya0 commented
> > in the description field we want to allow only light formatting of text. In the Focus Items builder we want to allow them to insert images, videos and overall make the content more appealing to the audience.
> 
> That's fine - if that is the case maybe we should have more options in GrapesJS? Or is the thought that those things would be done best with blocks maybe?

Provide me the list of options so I will add all as per our choice.

I am showing few because earlier also there was few option :
<img width="763" alt="image" src="https://github.com/mautic/mautic/assets/48244990/78acbb70-3943-487a-9099-b3944d41eefc">

2023-08-11 13:22 UTC, dadarya0 commented
> It looks like some of the translations are missing: <img alt="Screenshot 2023-08-11 at 14 52 33" width="353" src="https://user-images.githubusercontent.com/1235442/260011118-415f23b1-11af-4943-93f3-5784eed1521a.png"> I can see them working on the 5.x branch.

looks good to me, may be it is because of cache or you have not generated assets for grapejs as we have separate package.json for grapeJs.

<img width="335" alt="image" src="https://github.com/mautic/mautic/assets/48244990/a8b26214-f474-407b-a9b2-73fa5c892928">

2023-08-11 13:57 UTC, escopecz commented
Hmm, I'm not sure how to fix the translations. I've opened this branch on GitPod and it's works there so it must be an issue on my local. I've re-built caches but it did fix it. Not an issue of this PR.

The link option does not work in the Focus Items bundle either. So it's not only an issue with the GrapesJS.

But I'm missing this option:
![Screenshot 2023-08-11 at 15 45 58](https://github.com/mautic/mautic/assets/1235442/22866e24-d9b6-452e-9c0f-a4647c162f3a)


It looks like this with this PR:
![Screenshot 2023-08-11 at 15 46 35](https://github.com/mautic/mautic/assets/1235442/9278228f-a349-4bee-b1a8-ef15c8bc53de)

It now opens in a modal. Is that OK? And the token option is missing. I thought that it's what the new CKE plugin does.

2023-08-11 14:00 UTC, dadarya0 commented on app/assets/scaffold/files/ckeditor/src/InsertDropDown.js
> +export default class InsertDropDown extends Plugin {
Done

2023-08-11 14:00 UTC, dadarya0 commented on app/bundles/CoreBundle/Tests/Command/GenerateProductionAssetsCommandTest.php
> +        $this->assertEquals(0, $commandTester->getStatusCode());
Done

2023-08-11 14:05 UTC, dadarya0 commented
> Hmm, I'm not sure how to fix the translations. I've opened this branch on GitPod and it's works there so it must be an issue on my local. I've re-built caches but it did fix it. Not an issue of this PR.
> 
> The link option does not work in the Focus Items bundle either. So it's not only an issue with the GrapesJS.
> 
> But I'm missing this option: ![Screenshot 2023-08-11 at 15 45 58](https://user-images.githubusercontent.com/1235442/260026299-22866e24-d9b6-452e-9c0f-a4647c162f3a.png)
> 
> It looks like this with this PR: ![Screenshot 2023-08-11 at 15 46 35](https://user-images.githubusercontent.com/1235442/260026396-9278228f-a349-4bee-b1a8-ef15c8bc53de.png)
> 
> It now opens in a modal. Is that OK? And the token option is missing. I thought that it's what the new CKE plugin does.

Yes, token plugin is missing in grapeJs. 

@escopecz for GrapeJs related change, we have to check if we can use common ckeditor5 inside grapeJs otherwise I have to write same plugin for grapeJs's ckeditor also.

2023-08-14 11:35 UTC, escopecz commented
@dadarya0 is the token plugin used in other places than in the GrapesJS builder? I didn't see it elsewhere.

2023-08-14 13:30 UTC, dadarya0 commented
> @dadarya0 is the token plugin used in other places than in the GrapesJS builder? I didn't see it elsewhere.

Yes In Add/Edit Dynamic Content inside Components menu

2023-08-15 04:15 UTC, kuzmany submitted a review, later dismissed
Seems good to me

2023-08-15 07:29 UTC, escopecz commented
@dadarya0 I think you'll have to duplicate the plugin for GrapesJS. Otherwise this will quite limit the functionality.

2023-08-15 14:18 UTC, TechBill commented
Tested CKE which opens in a modal.   

Modal box seems touchy where an accidental bump outside of modal will closes it prematurely losing all the edits. 

First icon in CKE (chain link? for hyperlink editing?) doesn't seem to do anything or show any functions. 

All other functions seem to be working as intended.

2023-08-16 15:00 UTC, RCheesley commented
The reason we had the older version of CKE was because Mautic was using Froala at the time. I'm all for standardising so yes, where possible it would be great to have the same editor experience across Mautic.

I will raise the question about the editor options we should have available and let you know the outcome.

2023-09-06 13:02 UTC, dadarya0 commented
@escopecz @RCheesley All above issues are resolved .

2023-09-07 08:28 UTC, escopecz submitted a review, later dismissed
I can't see any issues now. The link button is working in Focus Items as well as in the Grapes JS builder.

The only difference compared to the previous version is that the GrapesJS builder the text is not edited in-line but in a modal box. It's not a big deal.

![Screenshot 2023-09-07 at 10 32 03](https://github.com/mautic/mautic/assets/1235442/b053d91b-08b6-4f15-b9ab-c6f78bd0e813)


Thank you Saurabh!

👍

2023-09-07 10:45 UTC, fedys submitted a review, later dismissed
I don't see any issues. Thanks @dadarya0!

2023-09-07 11:13 UTC, kuzmany submitted a review, later dismissed
Seems good to me 👍

2023-09-07 15:36 UTC, nick-vanpraet commented
CkEditor 5 seems to be working as intended wherever I tested it. Don't know if it's related to this PR or not but I did find two errors while using GrapesJS

- The checkmark at the top right doesn't work, it hangs forever and console errors appear
![image](https://github.com/mautic/mautic/assets/7923739/55186f8b-f87b-4d8b-b03b-395df0e2fcc4)

- When adding a dynamic content block there's no "save" button on the modal, and the "x" also does not work. Essentially you're trapped in that modal until you refresh the page.
![image](https://github.com/mautic/mautic/assets/7923739/b79354f7-3b96-4f85-a261-1c1f32aeb443)

2023-09-08 04:43 UTC, dadarya0 commented
> CkEditor 5 seems to be working as intended wherever I tested it. Don't know if it's related to this PR or not but I did find two errors while using GrapesJS
> 
> * The checkmark at the top right doesn't work, it hangs forever and console errors appear
>   ![image](https://user-images.githubusercontent.com/7923739/266368749-55186f8b-f87b-4d8b-b03b-395df0e2fcc4.png)
> * When adding a dynamic content block there's no "save" button on the modal, and the "x" also does not work. Essentially you're trapped in that modal until you refresh the page.
>   ![image](https://user-images.githubusercontent.com/7923739/266368672-b79354f7-3b96-4f85-a261-1c1f32aeb443.png)

@nick-vanpraet 
**The checkmark at the top right doesn't work, it hangs forever and console errors appear**
This is not related to this PR and these button were added in https://github.com/mautic/grapesjs-preset-mautic/commit/561ebe00a1a062619222cf06f89f162e9bd8b56f and same should be fixed in https://github.com/mautic/grapesjs-preset-mautic

**When adding a dynamic content block there's no "save" button on the modal, and the "x" also does not work. Essentially you're trapped in that modal until you refresh the page.**
This issue also required some changes in https://github.com/mautic/grapesjs-preset-mautic but I don't know how this  mautic grapejs plugin works so someone from community who had worked on this plugin can update changes in this plugin.

These are very few lines changes but need to be tested.

Replace https://github.com/mautic/grapesjs-preset-mautic/blob/main/src/dynamicContent/dynamicContent.commands.js#L22-L26 by following line :-

`
if (ckEditors != undefined && ckEditors.size > 0) {
      ckEditors.forEach(function (value, key, map) {
        const name = key.id;
        if (name.includes('dynamicContent')) {
          this.logger.debug(`Destroying Dynamic Content editor: ${name}`);
          map.get(key).destroy();
          ckEditors.delete(key);
        }
      });
}`

CC - @escopecz @adiux @RCheesley

2023-09-08 07:31 UTC, escopecz commented
I just checked that the dynamic content textarea also should have the editor. This is how it looks like on M5. And the X does close the modal in M5.
<img width="880" alt="Screenshot 2023-09-08 at 09 29 03" src="https://github.com/mautic/mautic/assets/1235442/af93df1a-ca64-4db2-8bd6-37cad3d20687">

2023-09-21 15:02 UTC, RCheesley commented
Hopefully @adiux / @annamunk / @volha-pivavarchyk might be able to help with the preset parts here?

2023-10-03 10:44 UTC, mollux commented
@escopecz @RCheesley @nick-vanpraet 

I fixed the incompatibility issues with dynamic content / GrapesJS / CKEditor
I was able to add / edit / close / ... the dynamic content editor in e mail template using the GrapesJS builder
Can you re-test?

(the spinning checkmark still needs to be fixed)

change is 2 fold:
* small change in how the editor config (the buttons) is passed when creating an editor, see https://github.com/mautic/mautic/pull/12641/commits/d00b312446891196e304c8b1844c9ce730939ee2#diff-feb45a524d9be3db7bf6ea8127c2a34e754db20e3e8322a0121b34cfde4ce764
*  ckeditor 5 compatibility in the dynamic content preset, see https://github.com/mautic/grapesjs-preset-mautic/pull/44

for now, I changed the dependency to my fork, but once https://github.com/mautic/grapesjs-preset-mautic/pull/44 is merged, we should switch back to the main repo

we CANNOT merge that branch into `main` (yet), as it would break Mautic 4

We can discuss best strategies after beta1, as it purely dependency management

I found other issues, but still checking if they are related to this CKEditor update, or core Mautic

2023-10-03 11:59 UTC, escopecz commented
Yep, the CK Editor works for the DEC feature. What else do we need to test?
![Screenshot 2023-10-03 at 13 57 58](https://github.com/mautic/mautic/assets/1235442/50231b4f-0738-4b46-a536-f96d6cce0933)

2023-10-03 12:02 UTC, RCheesley commented
Confirm that the builder is now working correctly when it comes to dynamic content,  we still have the issue with the check mark but I'm not sure if that relates to this PR  based on this comment:

> @nick-vanpraet
> The checkmark at the top right doesn't work, it hangs forever and console errors appear
> This is not related to this PR and these button were added in https://github.com/mautic/grapesjs-preset-mautic/commit/561ebe00a1a062619222cf06f89f162e9bd8b56f and same should be fixed in https://github.com/mautic/grapesjs-preset-mautic

If that's the case then it should be good to go.

 I huge thank you to everyone who has collaborated to help get this one over the line!

2023-10-04 06:30 UTC, volha-pivavarchyk commented
@escopecz @RCheesley @nick-vanpraet

I fixed the issue with the check mark. It works well on my local env now.

I didn't build dist files. Should I do it and add them to the repository?

2023-10-04 06:53 UTC, adiux commented
@volha-pivavarchyk you don't need to, there is a GitHub action that builds the dist files. But I always do it as I'm not 100% sure that always works. And I guess it makes things easier for testing.

2023-10-04 06:54 UTC, mollux commented
@volha-pivavarchyk I'll check later today for best approach, as the ckeditor5 changes can only be added for M5

2023-10-04 06:54 UTC, mollux commented
I'll move this PR forward so it's mergeable

2023-10-04 13:55 UTC, fedys approved these changes, later dismissed

2023-10-06 08:32 UTC, kuzmany submitted a review, later dismissed
Works for me after changes

2023-10-06 09:50 UTC, fedys approved these changes, later dismissed

2023-10-06 13:22 UTC, escopecz approved these changes, later dismissed
The code looks great. I browsed:
- segment description
- focus items (there is unrelated Twig bug on save, maybe fixed in 5.x already)
- email builder - custom tokens and dynamic content works!

Thank you everyone! 👍

2023-10-06 13:47 UTC, merged