Add a SerializationContextEvent to the API.
mautic/mautic pull request #12734
Opened 2023-09-18 11:26 UTC by mallezie

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [NO ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds an Event to the API on the moment (before and after) the serialization context is set. This allows event listeners to change the context, and change the existing exclusion groups and / or strategies to alter the output from the API (and limit it for example). 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Implement a listener which can alter the serialization context.

2023-09-18 12:03 UTC, mollux commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +     * @varContext
@mallezie this looks weird :)

2023-09-18 12:41 UTC, mallezie commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +     * @varContext
Removed the comment, since it's a fully typed property.

2023-09-19 13:31 UTC, RCheesley commented
@all-contributors please add @mallezie  for code

Thanks for making the PR @mallezie  -  welcome to the community!

2023-09-20 18:35 UTC, mollux commented on app/bundles/ApiBundle/ApiEvents.php
> +     * The mautic.api_pre_serialization_context event is thrown before the serialization context is created for the view.
the word `thrown` sound weird here (i know the other events in this and other files have similar comments)
```suggestion
     * The mautic.api_pre_serialization_context event is dispatched before the serialization context is created for the view.
```

2023-09-20 18:35 UTC, mollux commented on app/bundles/ApiBundle/ApiEvents.php
> +     * The mautic.api_post_serialization_context event is thrown after the serialization context is created for the view.
the word `thrown` sound weird here (i know the other events in this and other files have similar comments)
```suggestion
     * The mautic.api_post_serialization_context event is dispatched after the serialization context is created for the view.
```

2023-09-20 18:36 UTC, mollux reviewed
@mallezie looks good, some minor nitpicks about the comments

2023-09-22 09:25 UTC, mallezie commented
Updated the comments.

2023-09-22 11:00 UTC, mollux approved these changes, later dismissed
looks good to me!

2023-09-29 11:19 UTC, RCheesley commented
Could we please resolve the conversations if they have been addressed in the commits @mallezie / @mollux?  Many thanks!

2023-09-29 11:25 UTC, mallezie commented
@RCheesley I've resolved the fixed conversations.

2023-09-29 11:38 UTC, RCheesley commented
Wonderful, thanks for getting that done so quickly!

2023-10-03 10:36 UTC, RCheesley commented
It looks like we might need to bump up the code coverage on this PR. Is that something you might be willing to take a look at @mallezie ?

2023-11-10 17:49 UTC, RCheesley commented
@mallezie is there any way you can give more detail in the description to help testers? I know it's a fairly complex one to test, but maybe you could share a sample plugin or some code that could be used, and the API commands to be issued? It's more likely to get tested that way.

2024-01-31 10:33 UTC, mallezie commented
Update the branch with upstream. 
For adding test coverage, this adds a new event, which has no logic on itself, so no sure how to add test coverage for it. I see some events have tests, but those are events having logic. Mostly event listeners are tested, but there is no eventlistener to this event in core. 
For manual testing, i've added a plugin which subscribes to this event. It changes the API result to only show the id-field and not the rest of the data. 

[SerializationTestBundle.zip](https://github.com/mautic/mautic/files/14110436/SerializationTestBundle.zip)

You can test this now, by installing the attached plugin, and see the results of an API changed. 
* Install M5
* Create a contact
* Install plugin
* Do a API query. 
```
curl -s -u"admin":"Maut1cR0cks!" https://mautic5.ddev.site/api/contacts/1 | jq
{
  "contact": {
    "id": 1
  }
}
```

2024-04-24 18:15 UTC, escopecz commented
The Rector check is failing. Could you please take a look?

2024-04-24 18:17 UTC, escopecz requested changes

2024-04-24 18:17 UTC, escopecz commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +
```suggestion

declare(strict_types=1);

```

2024-04-24 18:17 UTC, escopecz commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +class ApiSerializationContextEvent extends CommonEvent
```suggestion
final class ApiSerializationContextEvent extends CommonEvent
```
There is no need for a DTO object to be extensible.

2024-04-24 18:17 UTC, escopecz commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +    }
```suggestion
    public function __construct(private Context $context, private Request $request)
    {
    }
```

2024-04-24 18:17 UTC, escopecz commented on app/bundles/ApiBundle/Event/ApiSerializationContextEvent.php
> +     */
```suggestion
```
The comment just states the obvious. It's unnecessary.

2024-04-25 08:35 UTC, mallezie commented
Processed all feedback, and rector is now passing.

2024-04-25 11:10 UTC, escopecz approved these changes
Thank you! 👍

2024-04-25 11:11 UTC, merged