Add matomo device detector for bots
mautic/mautic pull request #12750
Opened 2023-09-29 07:29 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

Mautic uses a raw list of bots from the configuration. But also use the Matomo library for device detection. 
This PR uses the library to detect bots too to avoid tracking these request.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add a tracking page to the website
3. Check IF tracking works like before
4. It should not track bot requests

2024-04-25 13:33 UTC, RCheesley commented
@kuzmany conflicts to resolve here and we need to pull in the latest changes from the branch once that's done. Thanks!

2025-07-11 15:22 UTC, RCheesley commented
Hi @kuzmany there's a couple of conflicts for you to take a look at here please, when you have a moment! Thank you!

2025-07-14 14:17 UTC, kuzmany commented
@RCheesley ready

2025-08-25 12:50 UTC, andersonjeccel requested changes
I think it's not working...

<img width="1080" height="1919" alt="image" src="https://github.com/user-attachments/assets/fb8cf9c1-4e5e-4422-ac72-9c0cc0226d40" />

How to reproduce:

1. Open Contacts
2. Toggle anonymous visitors
3. Ensure the list is empty
4. Open Settings > System settings
5. Scroll down to find accordion for IP tracking and bots
6. Find Googlebot on the list and delete it
7. Save
8. Open Components > Landing pages
9. Create a new lp and save
10. Back to list view
11. Click on 3 dots, copy public page URL
12. Open incognito window
13. In chrome, open developer settings
14. Find the Network tab
15. Click to open advanced network settings
16. In User agent, uncheck "Use browser default"
17. Under the dropdown, find a select Googlebot Smartphone
18. Reload the anonymous tab
19. Paste the URL and hit Enter/return
20. Open Mautic's contact list
21. Reload to see

2025-08-26 17:16 UTC, mabumusa1 approved these changes

2025-09-02 08:52 UTC, kuzmany commented
@andersonjeccel good catch. I found the issue and update it. 
Also removed static bot list and this option is now only optional for advanced users
Bots detection is now automatically for all requests

<img width="1081" height="542" alt="image" src="https://github.com/user-attachments/assets/6dd82467-822c-4c8a-b0f8-1632c1720720" />

2025-12-12 20:26 UTC, kuzmany commented
Note:

The decreased read rate (estimated 20%) is expected and correct after implementing industry-standard bot filtering via this PR, which now accurately excludes 500+ bots

2026-01-30 15:01 UTC, andersonjeccel approved these changes
It works now

<img width="1080" height="956" alt="image" src="https://github.com/user-attachments/assets/31189f79-7f4f-46bc-b25a-151e2a5c50a9" />

<img width="1920" height="929" alt="image" src="https://github.com/user-attachments/assets/780b9d37-0e0d-4219-8665-69bb6d5d1238" />

2026-02-03 12:17 UTC, kuzmany commented
The follow‑up to this PR is https://github.com/mautic/mautic/pull/15844. Merging both would be advisable.

2026-02-13 10:00 UTC, escopecz approved these changes
The code looks good 👍  Thanks Zdeno!

2026-02-13 13:46 UTC, andersonjeccel commented
@kuzmany Just saw now that my last comment switched words and was asking if this was compatible with landing pages when I meant emails

Some customers are having an issue where sending emails to certain domains (schools and other gov orgs) with automatic security verifiers was triggering DNC because an automated system (bot) was actually clicking all links to scan for threats, I'm wondering if this PR would fix it

@escopecz or maybe you know the answer

2026-02-13 14:04 UTC, kuzmany commented
I do not understand your question. Bot detection has been added at every location where IP lookup is used. Therefore, it is also likely applied to the landing page. Don't understand your concern. Probably not relevant.

2026-02-13 14:53 UTC, escopecz commented
The failing tests are resolved in https://github.com/mautic/mautic/pull/15872. Whoever can, please review it so I could keep merging PRs.

2026-02-13 17:53 UTC, matbcvo commented
@kuzmany, could you please take a look at this?
```
1) Mautic\CoreBundle\Tests\Unit\Helper\IpLookupHelperTest::testIsRequestTrackableReturnsTrueForNormalRequest
Failed asserting that false is true.

/home/runner/work/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/Helper/IpLookupHelperTest.php:168
```

2026-02-17 11:51 UTC, andersonjeccel commented
@kuzmany It's not a concern or a review, I'm asking a question about the scope to understand if the PR also fixes this issue in emails (not landing pages):

> Some customers are having an issue where sending emails to certain domains (schools and other gov orgs) with automatic security verifiers was triggering DNC because an automated system (bot) was actually clicking all links to scan for threats, I'm wondering if this PR would fix it

2026-02-17 12:00 UTC, kuzmany commented
@andersonjeccel No, this PR does not resolve the issue.

The recommended approach is to use the preferences center; bots should navigate to the preferences page rather than follow the unsubscribe action. 

These pull requests may partially address the problem too:

- https://github.com/mautic/mautic/pull/15844  
- https://github.com/mautic/mautic/pull/15870

These workarounds are expected to lower the counts of opens, clicks, and hits from bots.

2026-02-24 18:51 UTC, RCheesley commented on app/bundles/CoreBundle/Tests/Unit/Helper/IpLookupHelperTest.php
> +        $request = new Request([], [], [], [], [], ['REMOTE_ADDR' => '73.77.245.53']);
For reference, Sonarqube is flagging up the hard-coding of IP addresses here, I am marking it as safe, given it's used in a test.

2026-02-24 18:53 UTC, RCheesley commented
The Sonarqube warning is safe to ignore, it's flagging up a hard-coded IP address used in a test file.

@kuzmany there's a conflict here, but we should be able to merge this in 7.1-Release Candidate if we can get that resolved.

2026-03-02 16:24 UTC, escopecz commented
@kuzmany can you please check the conflict?

2026-03-03 20:35 UTC, kuzmany commented
@escopecz Conflicts resolved

2026-03-04 09:13 UTC, merged

2026-03-04 09:18 UTC, promptless-for-oss commented
📝 Documentation updates detected!

Updated existing suggestion: **[Document IpLookupHelper tracking features: automatic bot detection and isRequestTrackable()](https://app.gopromptless.ai/suggestions/1e2b2eed-6d79-4000-b797-0a22a136e95b)**

---
_Tip: Set up a GitHub Issues trigger in [Projects](https://app.gopromptless.ai/projects) to enable @Promptless mentions in issues 🐙_