Ignoring files autogenerated after composer install
mautic/mautic pull request #12776
Opened 2023-10-09 15:54 UTC by escopecz

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

When I run `composer install` I get a bunch of JS and CSS files in the git unstaged files. We should git-ignore those.

#### Steps to test this PR:

1. Must be tested with a git installation of this repository
2. Check that `git status` shows no changed files
3. Run `composer install`
4. Check that `git status` shows a bunch of files

2023-10-09 16:03 UTC, galvani approved these changes

2023-10-09 16:22 UTC, mollux requested changes
Those ignores are too wide. Only the generated filesband folders should be excluded

2023-10-10 07:19 UTC, escopecz commented
@mollux like this?

2023-10-10 08:54 UTC, mollux approved these changes
looks good!

2023-10-10 09:41 UTC, merged