Hide twitter related item if disabled
mautic/mautic pull request #12778
Opened 2023-10-11 07:56 UTC by dadarya0

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | No
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Hide following twitter related item if twitter is disabled :-

1. Social monitoring in Channel menu
2. Social tab in contact detail page
3. Social setting in global configuration
4. Social login field in form fields

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. verify following should be hidden if twitter is disabled :-

> 1. Social monitoring in Channel menu
> 2. Social tab in contact detail page
> 3. Social setting in global configuration
> 4. Social login field in form fields

2023-10-11 13:09 UTC, escopecz requested changes
Looks good! We can delete a bunch of code due to autowiring and PHP8 syntax

2023-10-11 13:09 UTC, escopecz commented on plugins/MauticSocialBundle/Config/config.php
> +        ],
Let's have autowiring handle this.
```suggestion
```

2023-10-11 13:09 UTC, escopecz commented on plugins/MauticSocialBundle/Config/config.php
> +            ],
```suggestion
```

2023-10-11 13:09 UTC, escopecz commented on plugins/MauticSocialBundle/EventListener/ConfigSubscriber.php
> +    }
PHP8 🪨 
```suggestion
    public function __construct(private Config $config)
    {
    }
```

2023-10-11 13:09 UTC, escopecz commented on plugins/MauticSocialBundle/EventListener/FormSubscriber.php
> +    }
```suggestion
    public function __construct(private Config $config)
    {
    }
```

2023-10-11 13:09 UTC, escopecz commented on plugins/MauticSocialBundle/Integration/Config.php
> +    }
```suggestion
    public function __construct(private IntegrationHelper $integrationsHelper)
    {
    }
```

2023-10-18 10:46 UTC, escopecz submitted a review, later dismissed
Thank you Saurabh! The code looks great!

2023-10-27 13:13 UTC, RCheesley requested changes
Thanks for this PR, I'm always keen for us to remove stuff if it's not needed and I agree it's great that if we don't have the twitter plugin enabled that it should not be showing in the interface.  Thanks also to @escopecz for the thorough code review!

The only thing that was a bit concerning or confusing for me was when I went to a contact who had no social media profiles present,  the social tab was there but there was no content which just looked a bit untidy:

![screenshot-8080-dadarya0-mautic-22m56ofd6ra ws-eu105 gitpod io-2023 10 27-14_10_44](https://github.com/mautic/mautic/assets/2930593/f0348c5f-ad08-4d8b-a6dc-d6c6cd30dc07)

Should we not remove the whole tab if there are no social profiles entered on the contact profile, instead of having the tab there but having it completely empty when clicked on?

2023-11-06 07:59 UTC, kuzmany commented
@RCheesley In my opinion, your request should cover separate PR. I recommend moving this to Ready to Commit instead of blocking it as not non-related request.

2023-11-06 09:52 UTC, RCheesley commented
@kuzmany I disagree. Per your acceptance criteria:

> 2\. verify following should be hidden if twitter is disabled :-
> 
> > 2. Social tab in contact detail page

The social tab is **not** being hidden on the contact detail page, where it should be, according to the test instructions, if the details are not present on the contact profile.

2024-03-08 11:36 UTC, dadarya0 commented
> @kuzmany I disagree. Per your acceptance criteria:
> 
> > 2. verify following should be hidden if twitter is disabled :-
> > > 2. Social tab in contact detail page
> 
> The social tab is **not** being hidden on the contact detail page, where it should be, according to the test instructions, if the details are not present on the contact profile.

@RCheesley in this PR description, I was not referring  `Social tab` in field , I was referring `Social tab` in lower part of detail page where we have History, audit log, Integration etc because it was related to twitter configuration.

2024-03-15 13:30 UTC, RCheesley approved these changes
Ahhhh, OK that makes sense! Screenshots ftw, could you include them in future PRs to make it easier for testers to understand what you're referring to, perhaps? Thanks!

2024-03-18 08:45 UTC, escopecz approved these changes

2024-03-18 08:45 UTC, merged