[DPMMA-2341] Fixed missing preference center
mautic/mautic pull request #12829
Opened 2023-10-26 16:41 UTC by annamunk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅]
| New feature/enhancement? (use the a.x branch)      | [❌]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | #12828

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Log in to Mautic using an account that has page:preference_center:viewown and page:preference_center:viewother permissions.
3. Create or edit email.
4. Find the "Preference Center Page" input.

2023-10-31 21:00 UTC, mollux requested changes
@annamunk 

while the code has the correct outcome, it differs from the approach in M4, see https://github.com/mautic/mautic/blob/4.4.10/app/bundles/EmailBundle/Views/Email/form.html.php#L224...L227

in M4 one of the 2 permissions was enough, in M5 both are needed

2023-10-31 21:00 UTC, mollux commented on app/bundles/EmailBundle/Resources/views/Email/form.html.twig
> +                {% if permissions['page:preference_center:viewown'] is not empty and permissions['page:preference_center:viewother'] is not empty %}
```suggestion
                {% if permissions['page:preference_center:viewown'] is not empty or permissions['page:preference_center:viewother'] is not empty %}
```

2023-11-02 13:17 UTC, annamunk commented
@mollux thanks for catching it! I commited the change.

2023-11-03 12:24 UTC, kuzmany approved these changes
I noticed same during the build https://github.com/mautic/mautic/pull/12860
This fixed it 👍

2023-11-04 18:54 UTC, volha-pivavarchyk approved these changes
Works well.

Thanks. I faced the same problem some time ago.

2023-11-06 12:22 UTC, merged