[DPMMA-2341] Added Preference Center blocks to GrapesJS builder
mautic/mautic pull request #12909
Opened 2023-11-17 17:25 UTC by annamunk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

PR adds Preference Center blocks to the GrapesJS builder. Related PR in grapesjs-preset-mautic: https://github.com/mautic/grapesjs-preset-mautic/pull/46 

![preference_center_blocks](https://github.com/mautic/mautic/assets/102536220/688e62b1-6d8c-4868-9a13-3390555e9d11)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new landing page and switch "Set as preference center page" to Yes.
3. Open the GrapesJS builder and look for the Preference Center section in the "Open Blocks" panel on the right.
4. Drag the selected blocks onto the canvas. The preferences page must contain a "Save Preferences" button.
5. Save the page and attach it to an email. Check if the preference center is displayed correctly in the sent message.

2023-11-21 08:44 UTC, patrykgruszka requested changes
I have encountered two problems:
1. The Success message is always visible, it should appear after save
2. Unsubscribe from all link doesn't work

Also, I'm not sure if this should be considered a bug, but the "save preferences" button text in the builder doesn't match the rendered text. Should we be able to change the text in the builder or am I missing something?

2023-11-22 08:53 UTC, kuzmany commented
@patrykgruszka The original pull request (PR) was submitted by someone on my team. I believe the "unsubscribe all" feature is included in a different PR (https://github.com/mautic/mautic/pull/10579) that hasn't been merged yet. So, we can probably hide the icon until it's merged.

2023-11-24 12:10 UTC, kuzmany commented
> The Success message is always visible, it should appear after save

I think this is a regression from M5 and does not work on M5 at all. 
 
@annamunk 
But in general the PR works nice (good job), just two minor issue mentioned above.

2023-11-28 10:33 UTC, annamunk commented
@patrykgruszka @kuzmany thank you!
1. I prepared a fix - #12923 
2. Ok, I will hide the "Unsubscribe all" block until #10579 is merged. Let me know if I can help with testing that PR.

During testing, I also noticed that there is no way to easily adjust the text and styling, and in fact the button text in the creator differs from the rendered text. In the old builder, the Customize Slot form appeared after selecting an item. I will try to add similar functionality for GrapesJS.

![customize_slot](https://github.com/mautic/mautic/assets/102536220/ec53dda3-b86a-4472-9854-12c3feb2db0b)

2023-11-28 10:38 UTC, kuzmany commented
> During testing, I also noticed that there is no way to easily adjust the text and styling, and in fact the button text in the creator differs from the rendered text. In the old builder, the Customize Slot form appeared after selecting an item. I will try to add similar functionality for GrapesJS.

Can you edit it in Builder? We've been using it like this for a long time, and no one has complained. It's definitely better than before.

2024-04-19 15:02 UTC, RCheesley commented
@annamunk sorry, conflicts here too!

2024-07-16 14:08 UTC, RCheesley commented
@annamunk do you think you could resolve the conflicts here? I've connected it up to a reported issue regarding the missing blocks.

2026-06-08 18:22 UTC, andersonjeccel commented
Hey, this PR seems to have been inactive for a long time, with the last update back in 2025. We're tidying up a bit so the review queue stays focused on changes that are still moving forward and getting close to merge. If you plan to continue this work, please reopen it with an update.

2026-06-08 18:22 UTC, closed without merging