[DPMMA-2341] Hide success message before saving the form
mautic/mautic pull request #12923
Opened 2023-11-24 12:56 UTC by annamunk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅]
| New feature/enhancement? (use the a.x branch)      | [❌]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The success message is hidden if $successSessionName has not been set for the session. This PR request also adds message hiding when the value has been set but is evaluated to empty (e.g. 0).

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new landing page and switch "Set as preference center page" to Yes. In content, add at least {successmessage}
and {saveprefsbutton} tokens.
3. Save the landing page and create an email with the page set as preference center.
4. Send a message to your test contact and open the Unsubscribe page.
5. The success message should not be visible immediately after opening the page, before saving the form*.

*Additionally, there is an error with the form: "The CSRF token is invalid. Please try to resubmit the form", but this is a separate problem.

2023-11-24 16:28 UTC, escopecz approved these changes
The code change makes sense 👍

2023-11-28 10:09 UTC, annamunk commented
@escopecz thank you!

2023-12-01 19:57 UTC, kuzmany requested changes
Does not work for me. Success message is hidden, but not display after save form.

This is my PC page:

![image](https://github.com/mautic/mautic/assets/462477/240af2ea-f8c4-42aa-8557-65e574021d22)

2024-04-19 15:03 UTC, RCheesley commented
A conflict to resolve here.

2026-06-08 18:36 UTC, andersonjeccel commented
Hey, this PR has been sitting for a long time, so I'm treating it as stale for now. We're doing a bit of queue cleanup to keep attention on PRs that are still being actively worked on and are closer to merge. If this was a mistake, I'd be glad to see it reopened.

2026-06-08 18:37 UTC, closed without merging