Add IP lookup provider IPAPI
mautic/mautic pull request #12925
Opened 2023-11-25 01:25 UTC by raoulwegat

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | []
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds IP Lookup provider https://ipapi.com.

#### Steps to test this PR:

1. To test you'll need an API key which you can grab from https://ipapi.com by creating a free account. 

2. Test this on Gitpod as you'll need to connect to a URL in Mautic from a **remote IP** (testing locally with DDEV or similar, your traffic will only come from 127.0.0.1, which means the IP lookup will not be used).

3. In the Gitpod Simple Browser, log into Mautic (admin/mautic) then click the cog icon top right, then click Configuration -> System Settings then scroll down to Miscellaneous Settings. Under "IP lookup service", select "IP API" and paste your key into "IP lookup service authentication". Scroll back to top and click Save and Close.

3. Copy the Mautic URL from the Simple Browser, then open a Private Window in your browser and paste that URL in and append something like "/some/url". This will fire a 404 error - don't worry about it.

4. Now go back to the Gitpod window and in Simple Browser Mautic, navigate to Contacts, then click the "Toggle Anonymous contacts" icon on the right of the screen. Your visit should be visible in the table that appears below. If the "Location" column contains an entry, then the IP API lookup was successfull.

2023-11-25 10:51 UTC, RCheesley commented
Thanks so much for making the PR @raoulwegat and welcome to the Mautic community! Appreciate the detailed testing instructions, thanks for that!

Would you mind rebasing this to the 5.1 branch? With the 5.0 launch imminent, features will land in the 5.1 release as we've already passed the freeze for 5.0. Shouldn't hopefully be too much difference between the branches at this time.

2023-11-25 10:55 UTC, RCheesley commented
@raoulwegat please have a look at the failing tests as well, many thanks! Feel free to ping if you need us to re-run them, there's some docs [here](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#phpunit) in case that helps you with running the test suite locally.

2023-11-27 09:17 UTC, escopecz requested changes
Hi, welcome and thanks for the contribution! Please check the automatically reported issues. If you need any help to get the test running, let me know.

2023-11-27 09:17 UTC, escopecz commented on app/bundles/CoreBundle/IpLookup/IpapiLookup.php
> +	 * @param $response
This will keep the static analysis happy
```suggestion
	 * @param mixed[] $response
```

2023-11-27 09:17 UTC, escopecz commented on app/bundles/CoreBundle/Tests/Unit/IpLookup/IpapiLookupTest.php
> +		$mockHttp = $this->createMock(C`lient::class);`
How did this happen? 🙂 
```suggestion
		$mockHttp = $this->createMock(Client::class);
```

2024-04-19 12:22 UTC, LordRembo commented
@raoulwegat Could you check those code change requests and update the branch?

2024-04-29 13:24 UTC, RCheesley commented
I'm removing this from the milestone due to the outstanding feedback. @raoulwegat if you want to get this feature merged, please consider the failing tests and feedback so that we can get this tested and reviewed. Thanks!

2025-01-08 01:57 UTC, closed without merging