Accessibility improvement
mautic/mautic pull request #12929
Opened 2023-11-27 19:56 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This pull request addresses accessibility improvements and corrections to user interface elements. The key changes include:

1. Addition of aria-label attributes to menus and buttons to enhance accessibility.
2. Addition of tabindex attributes to direct screen reader selection to links and buttons instead of decorative interface elements.
3. Correction of role attributes to ensure that interface elements are properly identified by screen readers.
4. Addition of aria-hidden attributes to button icons, preventing screen readers from getting confused when determining what to read to the user.
5. Tooltips have also been added for users without visual limitations to indicate actions performed by buttons consisting only of icons (without text).

#### Steps to test this PR:

There are several alternatives available:

1. **Users without visual limitations**: For these users, simply hover the mouse over the interface buttons, which now display tooltips indicating their purpose. This approach enhances the user experience by providing informative and intuitive guidance.

2. **Accessibility testing with Lighthouse**: Running an accessibility test with Lighthouse in your browser's developer tools will reveal a difference in score between a Mautic dashboard before and after the corrections in this pull request. This provides an objective metric of the accessibility improvement.

3. **Screen reader testing (Narrator)**: You can also test the accessibility implementations by enabling the Narrator in your Windows operating system or an equivalent feature in other OS. Once activated, navigate to the Mautic dashboard and begin exploring elements using the Tab key on your keyboard. This action causes the Narrator to move from one element to another, audibly describing information that is not visually available to the user.

2023-11-28 11:45 UTC, RCheesley commented
@all-contributors please add @andersonjeccel for code.

Welcome to the community @andersonjeccel and thanks for this important PR to start improving Mautic's accessiblity! It looks like there are some failing automated tests which will need to be addressed, once that's done we can get folks testing and reviewing!

2023-11-28 11:47 UTC, RCheesley commented
@all-contributors please add @andersonjeccel for a11y

(Realised there's a special category for accessibility contributions! 🚀 )

2023-11-28 20:35 UTC, escopecz reviewed
Thank you for this! 

This is quite massive PR yet I don't see changes changes on most of the changed files. Anyone understands why? This makes the code review 100 times more difficult

2023-11-28 20:41 UTC, andersonjeccel commented
@escopecz Most of the files have around 10 characters added (aria-hidden properties for icons not to be read by screen readers). I'm not sure why it's being considered as a complete file deletion and addition.

2023-11-28 20:52 UTC, escopecz commented
I consulted with GH Copilot:

> Yes, this can happen due to a few reasons:

> Line Endings: If the line endings in your file have changed, GitHub will show changes on all lines. For example, if you've changed from CRLF (Windows) to LF (Unix), or vice versa.

> Whitespace Changes: If there are changes in the spaces or tabs, GitHub will show changes. This can happen if you've re-indented your code or removed trailing spaces.

> Character Encoding: If the character encoding of the file has changed, GitHub will show changes on all lines. For example, changing from UTF-8 to ISO-8859-1.

> You can add ?w=1 at the end of the URL while checking the diff on GitHub web interface. This will ignore the whitespace changes. For line endings, you might want to standardize them across your project using a .gitattributes file.

Do you use Windows? What code editor?

2023-11-28 20:54 UTC, andersonjeccel commented
I use Windows with WSL (virtualized Ubuntu) for live testing.
I edit through VS Code and commit using GitHub Desktop.

2023-11-28 20:56 UTC, escopecz commented
I ruled out the encoding issue as the output of this command is the same on this branch and 5.x:
```
file -I app/bundles/ApiBundle/Resources/views/Security/login.html.twig
app/bundles/ApiBundle/Resources/views/Security/login.html.twig: text/plain; charset=us-ascii
```

2023-11-28 21:04 UTC, andersonjeccel commented
Do I need to do something for now?

2023-11-28 21:05 UTC, escopecz commented
It's the line endings:

> In Visual Studio Code, you can see the line ending of the currently active file in the status bar at the bottom.

I can see LF on the 5.x branch and CRLF on yours.

```
Visual Studio Code can change the line endings from CRLF to LF. Here's how you can do it:

1. Open the file in Visual Studio Code.
2. Look at the bottom-right corner of the status bar. You should see either CRLF (Windows line endings) or LF (Unix line endings).
3. Click on CRLF or LF, a menu will pop up at the top of the editor.
4. In the menu, select LF to change the line endings of the current file to Unix style. Remember to save the file after changing the line endings.
```

You can also set that globally in VS Code when you search for the `End of Line` setting. This should be fixed before the merge as it would cause troubles in the future when merged. Do you think you can fix it?

2023-11-28 21:24 UTC, andersonjeccel commented
Git seems not to recognize the CRLF to LF change, so it's like the file wasn't modified. Not sure how to help...

2023-11-28 21:30 UTC, escopecz commented
```
If Git is not recognizing the change from CRLF to LF, it's likely because of the core.autocrlf setting in your Git configuration. This setting can be used to automatically convert LF line endings to CRLF when you check out code, and to convert CRLF line endings to LF when you commit.

If you want to change the line endings back to CRLF, you can do so in Visual Studio Code by clicking on LF in the status bar and selecting CRLF from the menu that pops up.

If you want Git to recognize the change, you can turn off the core.autocrlf setting. Here's how you can do it:

git config --global core.autocrlf false

This will stop Git from automatically converting line endings. After changing this setting, you should be able to commit the change from CRLF to LF.

Remember to be careful when changing this setting, as it can affect all your repositories. If you only want to change the setting for a single repository, you can do so by running the command without the --global option while you're in the repository's directory.
```

2024-01-11 09:38 UTC, PatrickJenkner approved these changes
I just tested your changes:
1.  Hovering over the elements shows tooltips like you described
2. An accessibility test with lighthouse showed an increase from 65 to 69 (desktop) and 71 (mobile).
3. Using a screen reader (VoiceOver on Mac) works. However, I have never used a screen reader before, so I cannot say if the implementation is good or could be improved.

Thank you so much for your improvements!

2024-03-20 11:53 UTC, andersonjeccel commented
@RCheesley Should we move this PR forward?

Then I can work on the fixes

2024-04-04 09:46 UTC, RCheesley requested changes
Hi @andersonjeccel - I think there might still be issues with line endings on this PR which makes it almost impossible for us to review.

If you check the files changed, it should only be highlighting the sections which you've changed, not the entire file.

This is especially relevant for the language strings where we effectively would have to check each file line-by-line.

Please can you review and fix this before the PR can be properly reviewed? 

Thanks!

2024-04-04 09:46 UTC, RCheesley commented on app/bundles/CoreBundle/Translations/en_US/messages.ini
I'm not sure why this entire file is showing as new, because you've only changed a few lines. Please can you check the line endings - as otherwise it's almost impossible for people to review properly. It should only highlight the lines you've changed.

2024-04-04 09:46 UTC, RCheesley commented on app/bundles/LeadBundle/Translations/en_US/messages.ini
Same for this file, does not seem relevant to be including it?

2024-04-22 12:57 UTC, andersonjeccel commented
@RCheesley Tried to resume this task but it has a lot of untracked changes so I wouldn’t be able to guide step by step how to test it 
I’ll close this PR to raise new ones, organized and per location (eg navbar or account page)

2024-04-22 12:57 UTC, closed without merging

2024-04-22 12:59 UTC, RCheesley commented
Sounds great!