[type-declarations] Add known return type declarations from new instances
mautic/mautic pull request #12947
Opened 2023-11-29 20:06 UTC by TomasVotruba

2023-11-29 20:31 UTC, TomasVotruba commented
Ready for review :+1:

2023-11-30 11:15 UTC, escopecz requested changes
I found one small improvement WDYT?

2023-11-30 11:15 UTC, escopecz commented on app/bundles/CoreBundle/Helper/PRedisConnectionHelper.php
> +            $inputOptions['aggregate'] = fn () => fn ($sentinels, $options): \Predis\Connection\Aggregate\SentinelReplication => new SentinelReplication(
```suggestion
            $inputOptions['aggregate'] = fn () => fn ($sentinels, $options): SentinelReplication => new SentinelReplication(
```

2023-11-30 13:16 UTC, TomasVotruba commented
@escopecz Looks good, I've added the commit :+1:  
Feel free to merge with these details next time. I'm ok with any improvement :clap:

2023-11-30 13:19 UTC, TomasVotruba commented
@escopecz Btw, could I ask you for rebase before merge if needed? 
It would require some git back and forth work for me, as there is extra commit now.

2023-11-30 13:22 UTC, escopecz approved these changes
I couldn't spot any issue. Thank you Tomas! 👍

2023-11-30 13:29 UTC, TomasVotruba commented
Glad to help :+1:

2023-12-01 13:21 UTC, merged