FEATURE: Adds functionality to extend GrapesJS editor via themes
mautic/mautic pull request #13002
Opened 2023-12-06 18:07 UTC by putzwasser

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR extends GrapesJS to add some sort of import functionality to extend blocks and component types.

The approach is inspired by [this forum post](https://forum.mautic.org/t/adding-custom-blocks-to-grapesjs-builder/23608/3).

When Mautic initializes GrapesJS it tries to fetch a JSON file provided by the current theme.

The file has to be located in /themes/${Mautic.builderTheme}/grapejsblocks/

The file needs to be named:
- `page-html.json` for the landing page editor
- `email-mjml.json` for the MJML email editor
- `email-html.json` for the HTML email editor

The JSON should have two base properties: `blocks` and `types`.

Example:

```json
{
	"blocks": {
		"someSection": {
			// block definition here
		}
	},
	"types": {
		"aHeading": {
			// type definition here
		}
	}
}
```

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add a file `themes/blank/grapejsblocks/page-html.json`
3. Put this content into the file

```json
{
    "blocks": {
        "heading": {
            "label": "Heading",
            "content": "<h1>Put your title here</h1>",
            "category": "Basic",
            "attributes": {
                "title": "Insert h1 block"
            }
        },
        "section": {
            "label": "Section",
            "content": "<section><h1>Put your title here</h1><div>Some DIV</div></section>",
            "category": "Basic",
            "attributes": {
                "title": "Insert section block"
            }
        }
    },
    "types": {}
}
```

4. Open the landing page builder using the `blank` theme. Mautic initializes GrapesJS and loads two blocks into a new `Basic` block category.

![image](https://github.com/mautic/mautic/assets/26040044/c1436cab-41d5-42f6-8f93-630f41945adf)

2023-12-08 08:33 UTC, kuzmany approved these changes
Works for me. NIce 👍

2023-12-08 12:14 UTC, putzwasser commented
What I wanted to point out, but forgot: Someone with experience with GrapesJS should give this a test, please. I "hacked" this together and it works, but I don't have any experience with GrapesJS (yet).

So I'd appreciate it, if someone with experience could have a thorough look, so we can make sure everyone can enjoy using this feature instead of introducing a source of frustration :sweat_smile:

2024-02-27 11:21 UTC, jaetoole commented
@putzwasser I might add something to this PR, the ability to pull in custom GrapesJS plugins - I like this functionality though

2024-02-27 18:30 UTC, putzwasser commented
@jaetoole You're very welcome. A full plugin compatibility would be greatly appreciated.

2024-03-01 06:22 UTC, byt3sage commented
Hey @putzwasser!
Just a few thoughts from me to be able to add a plugin integration, I'd like to move your logic out into a `ThemeConfigService` class and break down blocks and types into its own function. From there I can add in the required functions for loading plugins.

As plugins cannot be dynamically attached to the editor and need to be added upon instantiating the GrapesJS editor, we need these separate functions. This is what led me to split out your code into this separate class so we keep `builder.service.js` nice and clean. This is because I will actually need potentially 3 functions for being able to add these plugins.

Let me know your thoughts and if you want me to go ahead and make these changes! Also @kuzmany happy to hear your thoughts on the above.

2024-04-19 15:01 UTC, RCheesley commented
@putzwasser some conflicts to address here.

@annamunk @patrykgruszka @adiux could you take a look at this PR from the GrapesJS perspective please?

2024-04-19 15:26 UTC, adiux requested changes
I think it would be a good idea to separate this code into a "dynamic block loading plugin" from grapesjs. That is the recommended way for extending GJS: https://grapesjs.com/docs/modules/Plugins.html

2024-04-19 15:26 UTC, adiux commented on plugins/GrapesJsBuilderBundle/Assets/library/js/builder.service.js
> +   * ```
Improve: add a link or mention that the structure of the object has to be compatible (or is fully compatible) with grapesjs blocks and types? So people who are not familiar with the GJS documentation know what the options are.

2024-04-19 15:26 UTC, adiux commented on plugins/GrapesJsBuilderBundle/Assets/library/js/builder.service.js
> +      this.addGrapeJsThemeEditorExtensions('page-html');
you can use ContentService.getMode(editor) from the preset

2024-04-26 13:11 UTC, patrykgruszka requested changes
Looks like a nice feature, but the branch needs to be updated first, so we can test it with the new grapesjs version that was included recently.

2026-06-08 18:22 UTC, andersonjeccel commented
Hey, this PR seems to have been inactive for a long time, with the last update back in 2025. We're tidying up a bit so the review queue stays focused on changes that are still moving forward and getting close to merge. If you plan to continue this work, please reopen it with an update.

2026-06-08 18:22 UTC, closed without merging