[PHP 8.0] Make use of property promotion - step 1
mautic/mautic pull request #13001
Opened 2023-12-06 16:00 UTC by TomasVotruba

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2023-12-06 17:13 UTC, TomasVotruba commented
Ready to go here :+1:  the failing is coverage lag

2023-12-07 10:08 UTC, escopecz requested changes
There is quite a lot of changes. I noticed only some weird comment placement. I suggest to remove them.

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/Event/CustomButtonEvent.php
> +    protected $location, Request $request, array $buttons = [], protected $item = null)
```suggestion
    public function __construct(protected $location, Request $request, array $buttons = [], protected $item = null)
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/Event/StatsEvent.php
> +    protected array $order, array $where, protected User $user)
```suggestion
    public function __construct($table, $start, $limit, protected array $order, array $where, protected User $user)
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/Helper/Chart/ChartQuery.php
> +    protected Connection $connection, \DateTime $dateFrom, \DateTime $dateTo, $unit = null)
```suggestion
    public function __construct(protected Connection $connection, \DateTime $dateFrom, \DateTime $dateTo, $unit = null)
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/IpLookup/AbstractLookup.php
> +         */
```suggestion
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/FormBundle/Collector/AlreadyMappedFieldCollector.php
> +    ) {
In this case the comment even doesn't belong to the property but to the const above it.
```suggestion
    public function __construct(private CacheProviderInterface $cacheProvider) {
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/Validator/FileUploadValidator.php
> +    ) {
```suggestion
    public function __construct(protected TranslatorInterface $translator) {
```

2023-12-07 10:08 UTC, escopecz commented on app/bundles/CoreBundle/Model/IteratorExportDataModel.php
> +    private AbstractCommonModel $model, private array $args, callable $callback, private bool $skipOrdering = false)
```suggestion
    public function __construct(private AbstractCommonModel $model, private array $args, callable $callback, private bool $skipOrdering = false)
```

2023-12-07 10:47 UTC, TomasVotruba commented
I've included all the suggested changed :+1:

2023-12-07 11:32 UTC, escopecz approved these changes

2023-12-07 11:44 UTC, merged

2023-12-07 12:14 UTC, TomasVotruba commented
Awesome 😎😎😎