Removing obvious comments
mautic/mautic pull request #13037
Opened 2023-12-08 19:25 UTC by escopecz

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Cleaning up useless comments that were automatically generated by IDEs many years ago and that were missed by automations that should remove them.

#### Steps to test this PR:

1. No need to test as the comments have no effect on the code.

2023-12-08 19:48 UTC, TomasVotruba commented
Btw, I use ECS for this one and have it in CI, so we avoid manual maintenance. It's much faster than php-cs-fixer as parallel and cached by defaults.

Would you like to give it a try?

2023-12-08 20:16 UTC, escopecz commented
That'd be great to try. I'm afraid that it would require different CS rules though. We had this issue in the past that some of Mautic plugins were using ECS and Mautic was using CSF. The plugin CI would fix the CS one way and when the plugin was added as a git submodule to a Mautic repo and CI would run then it would change the CS another way and it was an infinite loop causing headaches. I'd like to avoid having all plugin developers and companies with another CI on the Mautic repo to reconfigure it.

2023-12-08 23:21 UTC, RCheesley requested changes
Snagged a typo, thanks for removing all the unnecessary comments!

2023-12-08 23:21 UTC, RCheesley commented on app/bundles/CacheBundle/Cache/CacheProvider.php
> + * Povides caching mechanism using adapters, it provides both PSR-6 and PSR-16.
```suggestion
 * Provides caching mechanism using adapters, it provides both PSR-6 and PSR-16.
```

2023-12-09 15:15 UTC, TomasVotruba commented
@escopecz I see. No need to make it more complex now.
My main motivation is the speed, as ECS can analyse whole codebase withing 5 seconds with no cache. While php-cs-fixer takes 30-40 seconds and make daily development pain.

![Peek 2023-12-09 16-14](https://github.com/mautic/mautic/assets/924196/f084371e-6908-4148-9f95-85d6cbcf0dee)

<br>

In the meantime, I've added similar PR to cleanup unused docblock - https://github.com/mautic/mautic/pull/13051

2023-12-12 10:00 UTC, merged