Removes redundant code by adding a twig macro to `FormBundle`
mautic/mautic pull request #13044
Opened 2023-12-08 22:40 UTC by putzwasser

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This adds a twig macro for streamlined form html tag attribute generation. This allows to remove duplicate code.

**Changes**
- New Macro: Creates a macro called tag_attr in `app/bundles/FormBundle/Resources/views/Field/macros.html.twig`.
- Template Updates and Code Clean-up: Modifies existing `Field` twig templates to use this new macro. This change removed redundant code blocks previously used for attribute generation, reducing repetitive code and enhancing twig template readability.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. (Re-)create a form. You should **not** see any change in the rendered HTML.

Please review and test this PR. I created several form fields and they still work as expected, but I may have missed a field.

2024-05-31 12:36 UTC, RCheesley commented
@putzwasser could you address the conflict on this one please? Many thanks!

2024-05-31 17:02 UTC, putzwasser commented
Done

2024-09-09 09:40 UTC, escopecz approved these changes
I looked through the code changes and it looks alright. It makes the Twig files more DRY and readable.

2026-05-07 10:34 UTC, shinde-rahul requested changes
Thanks for this PR.

I checked the change, and the cleanup still looks relevant. 

Since this PR is currently against `5.x` and has gone stale, it may be worth considering a fresh PR against `7.x` if you are still interested in working on this.

So from my side, this still looks worth porting to `7.x`.

2026-06-08 18:36 UTC, andersonjeccel commented
Hey, I'm seeing this PR hasn't had updates for a long time. To help keep the queue manageable, we're closing older inactive PRs and focusing on the ones that are still moving forward. If you want to pick this up again, please reopen it and add the latest changes.

2026-06-08 18:37 UTC, closed without merging