New look and feel
mautic/mautic pull request #13169
Opened 2024-01-07 22:28 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Well, the so waited redesign is here.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Explore the header, notification panel, marketplace page, marketplace item details page, and user account

There are items that have not been touched, so it will remain on the old UI.

2024-01-07 22:56 UTC, andersonjeccel commented
I need a developer help to fix the PHPUnit fail.

I suspect it's caused by changes to the HTML, where I removed the table to use div on the marketplace page.

2024-01-08 13:35 UTC, andersonjeccel commented
closes these issues

#13137 
#13141
#13155
#13154 
#13153 
#13152 
#13157
#13138
#13139 
#13140 
#13142

2024-01-11 15:02 UTC, escopecz commented
I have a question about this. I know that none of the columns is sortable at the moment. But what if we'll want to filter by downloads or stars in the future? All the table (list) pages in Mautic allows to do that. But how to do it in a card view?
Before:
<img width="1674" alt="Screenshot 2024-01-11 at 16 01 07" src="https://github.com/mautic/mautic/assets/1235442/48406e37-7551-4433-b729-202cfa3d073d">
After:
<img width="1682" alt="Screenshot 2024-01-11 at 16 00 19" src="https://github.com/mautic/mautic/assets/1235442/4527801d-7646-424d-9b3e-7bd562ccbc10">

2024-01-11 16:45 UTC, RCheesley requested changes
Thanks for all the work on this! 

Here's some observations:

Generally:

There are a bunch of errors on a mobile device and the menu can't be used. I don't know if this is your PR or if it's a wider issue with Mautic 5.

```
libraries.js?v87b0cc8d:1746 Uncaught TypeError: Cannot read properties of undefined (reading 'mouse')
    at libraries.js?v87b0cc8d:1746:21
    at libraries.js?v87b0cc8d:1752:431
(anonymous) @ libraries.js?v87b0cc8d:1746
(anonymous) @ libraries.js?v87b0cc8d:1752
app.js?v87b0cc8d:110 Uncaught TypeError: mQuery(...).chosen is not a function
    at Mautic.activateChosenSelect (app.js?v87b0cc8d:110:12)
    at HTMLSelectElement.<anonymous> (app.js?v87b0cc8d:64:225)
    at Function.each (libraries.js?v87b0cc8d:98:212)
    at jQuery.fn.init.each (libraries.js?v87b0cc8d:89:190)
    at Mautic.onPageLoad (app.js?v87b0cc8d:64:202)
    at account:1622:24
Mautic.activateChosenSelect @ app.js?v87b0cc8d:110
(anonymous) @ app.js?v87b0cc8d:64
each @ libraries.js?v87b0cc8d:98
each @ libraries.js?v87b0cc8d:89
Mautic.onPageLoad @ app.js?v87b0cc8d:64
(anonymous) @ account:1622
app.js?v87b0cc8d:110 Uncaught TypeError: mQuery(...).chosen is not a function
    at Mautic.activateChosenSelect (app.js?v87b0cc8d:110:12)
    at Mautic.dynamicContentOnLoad (app.js?v87b0cc8d:536:102)
Mautic.activateChosenSelect @ app.js?v87b0cc8d:110
Mautic.dynamicContentOnLoad @ app.js?v87b0cc8d:536
libraries.js?v87b0cc8d:291 jQuery.Deferred exception: mQuery(...).Core is not a function TypeError: mQuery(...).Core is not a function
    at HTMLDocument.<anonymous> (https://8080-andersonjeccel-mautic-er7kx10tmeo.ws-eu107.gitpod.io/media/js/app.js?v87b0cc8d:6:391)
    at mightThrow (https://8080-andersonjeccel-mautic-er7kx10tmeo.ws-eu107.gitpod.io/media/js/libraries.js?v87b0cc8d:281:18)
    at process (https://8080-andersonjeccel-mautic-er7kx10tmeo.ws-eu107.gitpod.io/media/js/libraries.js?v87b0cc8d:282:556) undefined
jQuery.Deferred.exceptionHook @ libraries.js?v87b0cc8d:291
process @ libraries.js?v87b0cc8d:282
setTimeout (async)
(anonymous) @ libraries.js?v87b0cc8d:285
fire @ libraries.js?v87b0cc8d:271
fireWith @ libraries.js?v87b0cc8d:276
fire @ libraries.js?v87b0cc8d:277
fire @ libraries.js?v87b0cc8d:271
fireWith @ libraries.js?v87b0cc8d:276
ready @ libraries.js?v87b0cc8d:293
completed @ libraries.js?v87b0cc8d:293
libraries.js?v87b0cc8d:291 Uncaught TypeError: mQuery(...).Core is not a function
    at HTMLDocument.<anonymous> (app.js?v87b0cc8d:6:391)
    at mightThrow (libraries.js?v87b0cc8d:281:18)
    at process (libraries.js?v87b0cc8d:282:556)
```

This means I can't check any of this PR on a mobile device so worth bearing that in mind.

1. Notifications

When I have a notification, I can barely see the bell under the red blob - can we make it smaller somehow?  Also, the text is black-on-black:

![screenshot-8080-andersonjeccel-mautic-er7kx10tmeo ws-eu107 gitpod io-2024 01 11-16_27_55](https://github.com/mautic/mautic/assets/2930593/60bf1a27-75e5-441f-b5b7-284bc9bc60bc)

Also the text below seems to suggest there's no notifications - guess that should only display in the case that there aren't any notifications.

2. Marketplace

In the videos we saw there was a header pointing people to the docs, but that seems to be missing from the layout:

![screenshot-8080-andersonjeccel-mautic-er7kx10tmeo ws-eu107 gitpod io-2024 01 11-16_33_59](https://github.com/mautic/mautic/assets/2930593/64871b47-8698-4537-aed7-e0fe87d81233)

As a user, seeing the delete icon always scares me ... where we have the refresh plugins button, maybe we could use ♻️ instead, or something similar?

![screenshot-8080-andersonjeccel-mautic-er7kx10tmeo ws-eu107 gitpod io-2024 01 11-16_35_45](https://github.com/mautic/mautic/assets/2930593/1e837bd0-1185-4893-9b02-cec74cb74e87)

Search does not seem to be working correctly - it's not filtering the list of plugins:

![screenshot-8080-andersonjeccel-mautic-er7kx10tmeo ws-eu107 gitpod io-2024 01 11-16_36_57](https://github.com/mautic/mautic/assets/2930593/8d5b0fd4-0fdf-43ab-b3e0-a7396dedbcdf)

3. User profile

Spacing seems a bit weird on the eye on a mobile device due to no padding on the right side:

![screenshot-8080-andersonjeccel-mautic-er7kx10tmeo ws-eu107 gitpod io-2024 01 11-16_39_45](https://github.com/mautic/mautic/assets/2930593/6b863559-e534-4f7f-9042-310026fb05f4)

Otherwise I really like the new interface. It takes a bit to get used to (for example at first I thought there was too much white space on the dashboard but I got used to it after a while!). Great work @andersonjeccel 🚀

2024-01-11 18:50 UTC, patrykgruszka requested changes

2024-01-11 18:50 UTC, patrykgruszka commented on app/bundles/CoreBundle/Assets/css/app.css
This file is generated from LESS files, it will be overwritten everytime someone will run the `grunt compile-less` command. Look at the docs for more info: https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup#development-environment.

2024-01-16 19:39 UTC, RCheesley commented on app/bundles/CoreBundle/Assets/css/app.css
@andersonjeccel please check the feedback here.

2024-01-16 19:39 UTC, RCheesley commented
> I have a question about this. I know that none of the columns is sortable at the moment. But what if we'll want to filter by downloads or stars in the future? All the table (list) pages in Mautic allows to do that. But how to do it in a card view? 

Really good point - a user would want to be able to sort and filter the plugins.

2024-01-16 21:16 UTC, andersonjeccel commented
> I have a question about this. I know that none of the columns is sortable at the moment. But what if we'll want to filter by downloads or stars in the future? All the table (list) pages in Mautic allows to do that. But how to do it in a card view?
> Before:
> <img width="1674" alt="Screenshot 2024-01-11 at 16 01 07" src="https://github.com/mautic/mautic/assets/1235442/48406e37-7551-4433-b729-202cfa3d073d">
> After:
> <img width="1682" alt="Screenshot 2024-01-11 at 16 00 19" src="https://github.com/mautic/mautic/assets/1235442/4527801d-7646-424d-9b3e-7bd562ccbc10">
> 

@escopecz Instead of working to implement the list sorting, we can implement the same filtering we see on e-commerces. 

A select field "Sort by" with the options:
- downloads
- stars
Etc

Even if we use cards, Mautic's system still identifies the items. You can check this in the number of items per page selector that appears per page in the bottom right corner. When you change, the cards act accordingly. :)

2024-01-16 21:46 UTC, andersonjeccel commented
Hey @RCheesley 

> There are a bunch of errors on a mobile device and the menu can't be used. I don't know if this is your PR or if it's a wider issue with Mautic 5.

I can check, but maybe it's not related to the PR as I didn't change JS files... Perhaps I'm going to need some dev help here.

----

1. Didn't touch the red blob, thanks for pointing. Now that we have a 5.0.1 notification, I can work on the notifications text. The "no notifications" text should be inside a code markup to show as you said, I'm going to check.

2. It's probably the LESS problem mentioned, some changes to dev environment didn't come to production. Easy to fix.

Yeah, we can change the trash icon, perhaps on another PR so I can search for the best option.

Search does not work even on the list ahaha. This problem seems to be years old, I opened an issue recently: #13134 

3. I opened a draft issue a week ago, on the UX/UI project, to review and fix all the mobile issues before the ui-redesign branch get merged into 5.1: https://github.com/orgs/mautic/projects/18/views/1?pane=issue&itemId=49193019
It's planned

2024-01-17 08:35 UTC, escopecz commented
> There are a bunch of errors on a mobile device and the menu can't be used. I don't know if this is your PR or if it's a wider issue with Mautic 5.

The mobile JS errors should be fixed by https://github.com/mautic/mautic/pull/13216. We have to merge 5.0 to 5.x and then a rebase should fix it. Let me get that merge going.

> Instead of working to implement the list sorting, we can implement the same filtering we see on e-commerces.

I think that consistency is a good thing. Will we change table to card views everywhere? Is it adding a UX value? I get that tables are boring but there is a reason they are used to display data. For example if I sort by some value I can clearly see in one column the values I care about. With a card view I have to scan the whole screen for the value scattered all over the place.

Did you know that Mautic has a card view in the contact list view? Just go to contacts and press "c" as card. You can get back to table with pressing "t". Is it a useful feature? I'm not so sure. I think that Mautic has issues with greater priority we should tackle first.

2024-01-17 12:20 UTC, andersonjeccel commented on app/bundles/CoreBundle/Assets/css/app.css
Checking, thanks!

2024-01-17 12:26 UTC, andersonjeccel commented
Hey @escopecz, let's dive deeper.

> I think that consistency is a good thing.

Absolutely, consistency will be maintained. Introducing cards for the marketplace doesn't disrupt it, as a modern design system is designed to accommodate this. 😉

> Will we change table to card views everywhere? 

No, that might not be the best approach.

> Is it adding a UX value? 

Definitely! It adds dynamism to the view, so the app doesn't appear monotonous.

Moreover, it enhances accessibility as we have buttons indicating actions for people using screen readers.

For general users, it's now clearer that they can click a button to navigate to another page. This wasn't as evident with the previous table view (we also had feedback about the link appearance issue). While it might seem obvious to someone who has been using Mautic for years, it could be confusing for a first-time user. 

We should focus on improving user onboarding to engage more people with Mautic! 🙌🏻

> I get that tables are boring but there is a reason they are used to display data. 

Absolutely, tables are essential! It's best to keep them as they are for contacts, companies, etc.

Cards offer a visually appealing and navigable presentation, highlighting key information. They concentrate on essential details, facilitating quick decisions without overwhelming with excessive data. 

This makes them a great fit for the marketplace. 😉

> For example if I sort by some value I can clearly see in one column the values I care about. 

Indeed, data on cards is generally easier to read and understand on mobile devices as it's organized more intuitively. Tables might require more effort to locate specific information (like scrolling horizontally every time you want to know which star value is associated with which plugin on a big list; the marketplace plugins count will grow in the future).

> With a card view I have to scan the whole screen for the value scattered all over the place.

The tech industry has embraced this approach, as it's a widely used solution and well described in the design system we are following.

From a user experience perspective, this approach reduces cognitive load by increasing the distance between the information in each plugin. This results in less overhead as we spend the day looking at hundreds of pieces of information on a screen.

> Did you know that Mautic has a card view in the contact list view? Just go to contacts and press "c" as card. You can get back to table with pressing "t". 

That's cool, I wasn't aware of that!

> Is it a useful feature? I'm not so sure. 

If the feature is already there for contacts, there's no need for us to remove it. I wasn't planning to change the contacts table view anyway.

> I think that Mautic has issues with greater priority we should tackle first.

It's possible that the time required to implement sorting headers on the marketplace will be the same as implementing a select field for filtering. We've also had the search field issue for a long time: it doesn't work. When these problems become a priority, we can certainly address them. What are your thoughts on this?

The redesign may not resolve these longstanding issues as they're more complex. But a developer can certainly handle this 💪🏻

2024-01-17 13:43 UTC, escopecz commented
> Absolutely, consistency will be maintained.

> Definitely! It adds dynamism to the view, so the app doesn't appear monotonous.

Aren't you contradicting yourself here? Consistent and monotonous are very close to being synonyms. I get that one is positive and the other negative but they are semantically related and interchangeable.

When you'll have all the list views displayed as tables and one as cards than it's inconsistent, right? Users will have to work in one list view differently than in others. There are already helpers in the code that will make table sorting work out of the box. If we'll go with cards then we'll have to build it. Notice that in the contact card view there is no sorting at all.

Someone had a similar idea very long time ago. Look at the plugins list view. It has cards, the edit view is shown in a modal instead of a new page. It's inconsistent. I'm no UI/UX guy, those are just my personal observations. I like consistency because then I don't have to learn how to work with inconsistent views. Everything is familiar.

Cards are great for displaying different information in each card. Like we do in the dashboard. If you want to display the same data so users can compare the same values and sort by them then the table is the best option.

> it's now clearer that they can click a button to navigate to another page

I disagree with this statement too. In a world where every button looks differently I have a hard time recognising buttons and what is clickable. On the other hand, if there is a blue link on the table then I have no idea to understand that it will take me to the detail page.

I can see you like the flat style. The button in the card reminds me more of a select box than a button. I have to think twice what it really is. I'm also reading many articles saying that material UI was a dead end. Again, not an expert here, but it feels a little like the UIs built 10 years ago.

But don't mind me. Just one screaming man in the crowd. If everyone likes this then let's go ahead. What do I know.

2024-01-17 16:14 UTC, andersonjeccel commented
> Aren't you contradicting yourself here?

No, watch [this video](https://carbondesignsystem.com/all-about-carbon/what-is-carbon/) to understand inconsistency on a design system.

> Consistent and monotonous are very close to being synonyms. I get that one is positive and the other negative but they are semantically related and interchangeable.

"Consistent" refers to maintaining a coherent and predictable experience across a product by using familiar design patterns and elements. Consistency aims to streamline user interactions, while avoiding monotony involves introducing variety and visual interest in a way that still aligns with the overall design language.

> When you'll have all the list views displayed as tables and one as cards than it's inconsistent, right?

In UX/UI design, consistency is crucial, but it doesn't necessarily mean using the same component, like tables or cards, for all list views. The choice between tables and cards should be based on the type of data and user needs.
Using both in a design system is not inconsistent if each is chosen for its strengths and suitability to the content. The key is to make intentional decisions, ensuring a coherent and intuitive user experience.

> There are already helpers in the code that will make table sorting work out of the box.

Are you sure we cannot use them to filter cards, as they're inside the Twig function?

> Someone had a similar idea very long time ago.

We can make it better! 

> Look at the plugins list view. It has cards, the edit view is shown in a modal instead of a new page. It's inconsistent.

The same editing modal is being used everywhere for things forms and the new schedule modal proposed recently by another contributor. It's not inconsistent as you're commonly using them to edit an information way faster than changing to another page (page loading can be slow sometimes, some users are running Mautic on cheaper/worse servers than a big company).

The design system also has a modal pattern. Look [here](https://carbondesignsystem.com/components/modal/usage/)

> I like consistency because then I don't have to learn how to work with inconsistent views.

Is the view inconsistent because you do not like it?

> Cards are great for displaying different information in each card.

That's exactly what's happening... Each card has different information, makes no sense to have them duplicated.

> If you want to display the same data so users can compare the same values and sort by them then the table is the best option.

It depends on whether you are conducting a quantitative or qualitative assessment of what is being displayed. From an end-user perspective, the moment you prioritize a table to showcase this information, you are automatically conditioning the user to look at the plugins based on the number of stars or downloads they have received, rather than their specific functionality or how much they will help the user in their specific needs. The default visualization should not promote one over the other, but having the option available is interesting if the user desires it.

Cards are preferred over tables to display marketplace items because they offer a more visually appealing, mobile-responsive, and user-engaging format. They allow for hierarchy, flexibility, and better scannability, enhancing the overall user experience.

> In a world where every button looks differently I have a hard time recognising buttons and what is clickable.

We call this hierarchy. [Here ](https://carbondesignsystem.com/components/button/usage/) you can learn about primary, secondary and tertiary buttons. We have ghost, danger and icon-only variations too.

> I can see you like the flat style. 

I'm not following a personal opinion to proceed with this redesign.

> I have to think twice what it really is.

Even when it says "See more information"?

> I'm also reading many articles saying that material UI was a dead end. 

That's good to know, thanks. We are not using Material UI.

> Again, not an expert here, but it feels a little like the UIs built 10 years ago.

Carbon was updated last week. There's a huge research knowledge behind it. IBM uses Carbon for their corporate products. 
Are we talking about making Mautic really worse, or making it better in a style you don't like?

2024-01-17 17:10 UTC, andersonjeccel commented
@escopecz 

Let's be honest: 
I'm not a dev (you can see by the noob LESS problem)

just a marketer with knowledge of UX/UI and CSS trying to make Mautic more attractive, I only have desire to learn a bit of development and make the tool better for people and companies

I could only point out what to do, but who would effectively invest time implementing it?

Please look at this PR with kindness, as Mautic isn't related to any form of income acquisition for me 🙏🏻

Issues happen in a big project, I'm going to fix them

2024-01-19 10:38 UTC, escopecz commented
Thanks for the detailed answers! It seems we aren't moving anywhere with our views even with these detailed discussions. Neither of us is a trained UI/UX expert. I'll leave this be and let others to chime in.

2024-01-19 20:11 UTC, kuzmany commented
I welcome changes in the user interface to make it look fresher. It requires a lot of patience because everyone will have their own opinions. If it's a personal activity of a community member, then it's difficult to simply discard their efforts.

Probably, in the first step, you should focus on the main layout. This includes the menu, navbar, footer, right menu, icons, fonts, colors, form elements, tables, and titles. Once this is done, we can proceed to modify the view. However, it's important to note that modifying the views requires a significant amount of coding and writing new unit tests.

From my point of view, it's a step forward, even though some people may not like it. However, it seems like you're taking on a lot, which confuses people when it comes to the results. I believe that if you complete the layout adjustments, it could be merged more quickly as if you were to redesign the views and features.

2024-01-19 21:37 UTC, patrykgruszka commented
I really appreciate the effort you've put into this, @andersonjeccel. However, I think the changes may be too large for a single pull request. It's important that we make room for discussion and prioritise thorough testing (let's care about Firefox - Gecko it's our last open source non-chromium browser engine). While I really like some of the changes you've made, there are aspects that need further attention or improvement.

How about creating a pull request for each component? Implementing changes progressively would make it easier for users to adapt and provide more room for discussion.

2024-01-20 02:37 UTC, andersonjeccel commented
@kuzmany I found that some of the commits where I reverted old CSS styles to proceed with new classes caused the layout break on mobile (I tested all the functionalities on every screen before this, made sure it was perfect).

It's disheartening to have all my work, knowledge and research lose value with John's speech due to errors like the ones we see in several other pull requests before they are fixed.

@patrykgruszka I spoke with other members of the community and was instructed to proceed this way with this specific pull request to avoid excess. 

The first would encompass everything that affects the header, body, marketplace and user account. This includes all elements that were visible in those areas (so things you modify there have an effect on the rest of the platform). The idea was to finalize the pull request with these modifications, only making problem corrections as soon as it was reviewed, without new additions.

Creating a pull request for each component based on this work already done is initially unfeasible, given the way the changed code interacts to make everything work. From the outside, it may appear that the CSS is organized, but many relationships between classes need to be undone and the same element is affected by several overlapping classes without effect (duplicates).

I understand that there are things that need attention and improvements, this will always exist. This is the objective of putting it out there for you to test, getting feedback on what needs to be changed. However, talk about “needs to improve” without pointing the way is challenging for me to get the idea. 

Well, I will close this PR for now until I come with updates to reopen since there are other community actions involved in this redesign.

2024-01-20 02:37 UTC, closed without merging