Enhances filters evaluation by allowing to extend core filters by another filters for pages
mautic/mautic pull request #13226
Opened 2024-01-15 13:48 UTC by Syrgak-Alan

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✖️]
| New feature/enhancement? (use the a.x branch)      | [✔️ ]
| Deprecations?                          | [✖️ ]
| BC breaks? (use the c.x branch)        | [✖️ ]
| Automated tests included?              | [✖️ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Leuchtfeuer.com

This enhancement will allow to add another filters for your dynamic web content by listening to DynamicContentEvents::ON_CONTACTS_FILTER_EVALUATE event.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add some plugin which listens to ON_CONTACTS_FILTER_EVALUATE event and enable this
3. Create DWC which is NOT campaign based(set a slot name) and add filters that you need
4. Place DWC into your landing page by setting in your page builder {dwc=<slot_name>}

2024-01-17 11:40 UTC, kuzmany commented
@Syrgak-Alan Can you please add an example to the description of how the new filter could look in the subscriber? It would help test this pull request.

2024-01-17 18:20 UTC, Syrgak-Alan commented
@kuzmany if I understood you correctly, how namely I wrote evaluation for extended filter which subscribes the event?

2024-01-19 05:58 UTC, kuzmany commented
@Syrgak-Alan we need part of the code that will test it.  Simple subscriber what add new filter and provide it in result. It can be whatever, you can create just another contact email filter.

2024-01-19 08:44 UTC, Syrgak-Alan commented
@kuzmany I provided a snippet of code, which evaluates extended filter

2024-01-29 08:10 UTC, ekkeguembel commented
> @kuzmany I provided a snippet of code, which evaluates extended filter

@Syrgak-Alan where can I find that?

2024-02-19 09:40 UTC, MadlenF approved these changes
Tested this PR as requirement for https://github.com/Leuchtfeuer/mautic-DwcDeviceType-bundle - looks good from user-perpective! 👍

2024-02-19 09:55 UTC, kuzmany requested changes
From my side it does not need these kind of changes.  
You can use your own filters validation on your https://github.com/Leuchtfeuer/mautic-DwcDeviceType-bundle/blob/main/EventListener/DynamicContentSubscriber.php

And other filters (not related to your added filters) you can use  validation from  trait app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php

Something like

     foreach ($filters as $key=>$filter) {
            if ('device_type' === $filter['type']) {
            
            // your logic determine results, not passed return false
            //     $event->setIsEvaluated(true);
            //            $event->setIsMatched(false);
            // return;
            
            // unset custom filters
            unset(filters[$key])
            }
}

               $event->setIsEvaluated(true);
                $event->setIsMatched($this->matchFilterForLead($filters, $leadArray));

2024-02-19 10:11 UTC, Syrgak-Alan commented
@kuzmany 
> From my side it does not need these kind of changes. You can use your own filters validation on your https://github.com/Leuchtfeuer/mautic-DwcDeviceType-bundle/blob/main/EventListener/DynamicContentSubscriber.php
What do you mean by From my side it does not need these kind of changes?
Honestly I didn't quite understand your suggestion in trait and filter validation

2025-01-21 21:29 UTC, biozshock commented
@kuzmany I've took over this task. 

The PR actually solves the problem: in the method `\Mautic\DynamicContentBundle\EventListener\DynamicContentSubscriber::decodeTokens` any inclusion of `{dwc=slot_name}Slot content`, that is found by the `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::findDwcTokens` in the said content, the token will not be replaced, because the event `ContactFiltersEvaluateEvent` is not called for the "content-included DWC", because the the event is called only after the `$xpath->query('//*[@data-slot="dwc"]');` in the `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::getDynamicContentForLead` and then in the `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::getDynamicContentSlotForLead` and then in the `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::filtersMatchContact`.
Your proposed solution works only for the DWC tokens presented in the HTML with the `data-slot="dwc"`, not for the `{dwc` content token. 

In addition i found that the DWC stats are not properly creating stats entry:
The method `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::findDwcTokens` call the `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::getRealDynamicContent`, which in turn calls the `\Mautic\DynamicContentBundle\Model\DynamicContentModel::createStatEntry`, which populate the `dynamic_content_stats` with DWC token stats that are only matched in the content, but are not displayed to the _Lead_, if they are not matched later.

I would propose two different solutions:
1. Extend the PR to remove the unnecessary pass of `$extendedFiltersPassed`
2. Change the PR to use `\Mautic\DynamicContentBundle\Helper\DynamicContentHelper::getDynamicContentSlotForLead` instead of `\Mautic\EmailBundle\EventListener\MatchFilterForLeadTrait::matchFilterForLead` in the `\Mautic\DynamicContentBundle\EventListener\DynamicContentSubscriber::decodeTokens`

2025-02-14 13:44 UTC, escopecz commented
Closing in favore of https://github.com/mautic/mautic/pull/14599. Please test that one as it has tests and passing CI.

2025-02-14 13:44 UTC, closed without merging