Fix call to logger warn method.
mautic/mautic pull request #13252
Opened 2024-01-19 15:55 UTC by AdamBark

warn is not a method, warning appears to be correct.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [ None]
| BC breaks? (use the c.x branch)        | [ None?]
| Automated tests included?              | [ not applicable] 

#### Description:

When running `bin/console mautic:iplookup:download` the following error is thrown without this bugfix if you have no credentials for the Maxmind service.

```In MaxmindDownloadLookup.php line 33:
                                                                                                
  [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]                                   
  Attempted to call an undefined method named "warn" of class "Symfony\Bridge\Monolog\Logger".  
  Did you mean to call "warning"?
```
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run `php bin/console mautic:iplookup:download`

2024-01-19 19:49 UTC, kuzmany submitted a review, later dismissed
Code looks good 🫰

2024-01-20 09:19 UTC, mollux requested changes
@AdamBark while your change fixes that specific error on that specific place, there are 3 other occurrences around that code that use the same non-existing method.
Can you please address those too?

![Screenshot 2024-01-20 at 10 16 40](https://github.com/mautic/mautic/assets/3983285/3b4d9c43-6be7-4add-b679-bef4600df426)

2024-01-21 12:59 UTC, kuzmany approved these changes
Good 👍

2024-01-21 13:31 UTC, mollux approved these changes
Thanks for the additional changes!

2024-01-21 13:33 UTC, mollux commented
@AdamBark I just noticed you made the PR against 5.x, and it should be 5.0, as it's a bugfix. 

Can you rebase your changes based on 5.0? then this PR can be merged

2024-01-22 00:03 UTC, AdamBark commented
> @AdamBark I just noticed you made the PR against 5.x, and it should be 5.0, as it's a bugfix.
> 
> Can you rebase your changes based on 5.0? then this PR can be merged

Will do. I was a bit confused by the various documentations on which branch it should be on so thanks for the clarification. Perhaps this line ["All PRs are made against the c.x branch in the first instance (e.g. 5.x)"](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch) should be amended?

2024-01-22 07:17 UTC, merged