Add a local env file so DDEV runs in dev mode with debug enabled
mautic/mautic pull request #13295
Opened 2024-01-31 14:23 UTC by LordRembo

…ays starts as dev environment with debug mode enabled, when running locally (or in gitpod)

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ #13108]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

With this change, a `.env.local` file is created when Mautic is installed, that way if running in DDEV (for local development or testing in Gitpod), debug bar is enabled and you are in dev mode

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. You should see the debug bar at the bottom of the window, or a square with the Symfony logo (if it is collapsed) which you can click to open the debug bar

2024-01-31 15:13 UTC, RCheesley submitted a review, later dismissed
Works perfectly! 🚀

2024-02-01 08:33 UTC, mollux requested changes
@LordRembo PR works nicely, only change is to also do the same change in the `app/assets/scaffold/files/example.gitignore`.

This file is used for scaffolding that `.gitignore` for composer based installs

This is the reason why https://github.com/mautic/mautic/actions/runs/7727528386/job/21066199695?pr=13295 fails

2024-02-01 09:01 UTC, LordRembo commented
@mollux file added, should be good for re-review now.

2024-02-01 09:33 UTC, mollux approved these changes

2024-02-01 10:45 UTC, merged