Manage length of custom field values
mautic/mautic pull request #13319
Opened 2024-02-06 14:24 UTC by dadarya0

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-02-07 14:06 UTC, escopecz requested changes
Looks good. I suggested a bunch of improvements we can do now with PHP 8. You can accept those that you agree with and merge them all in one commit within the GH UI.

2024-02-07 14:06 UTC, escopecz commented on app/bundles/CoreBundle/Doctrine/Helper/IndexSchemaHelper.php
> +    public function hasUniqueIdentifierIndex(LeadField $leadField)
```suggestion
    /**
     * @throws SchemaException
     */
    public function hasUniqueIdentifierIndex(LeadField $leadField): bool
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Command/UpdateCustomFieldCommand.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Command/UpdateCustomFieldCommand.php
> +    protected function execute(InputInterface $input, OutputInterface $output)
```suggestion
    protected function execute(InputInterface $input, OutputInterface $output): int
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Event/UpdateColumnBackgroundEvent.php
> +    public function getLeadField()
```suggestion
    public function getLeadField(): LeadField
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Event/UpdateColumnBackgroundEvent.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Event/UpdateColumnBackgroundEvent.php
> +class UpdateColumnBackgroundEvent extends Event
```suggestion
final class UpdateColumnBackgroundEvent extends Event
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Event/UpdateColumnEvent.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Event/UpdateColumnEvent.php
> +class UpdateColumnEvent extends Event
```suggestion
final class UpdateColumnEvent extends Event
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Exception/AbortColumnUpdateException.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Helper/IndexHelper.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Field/Helper/IndexHelper.php
> +        );
```suggestion
        $this->indexedColumns = array_map(
            fn ($index) => $index['Column_name'],
            $indexes
        );
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Form/Type/FieldType.php
> +    public static function validateDefaultValue($value, ExecutionContextInterface $context): void
```suggestion
    public static function validateDefaultValue(string $value, ExecutionContextInterface $context): void
```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Tests/Field/Helper/IndexHelperTest.php
> +
```suggestion

declare(strict_types=1);

```

2024-02-07 14:06 UTC, escopecz commented on app/bundles/LeadBundle/Tests/Field/Dispatcher/FieldColumnDispatcherTest.php
> +                }),
```suggestion
                $this->callback(fn (AddColumnBackgroundEvent $event) => $event instanceof UpdateColumnEvent),
```

2024-02-07 16:23 UTC, escopecz requested changes
I tried to make the phone field indexable and this happened:
```
500 Internal Server Error - There is no column with name "email" on table "companies".
/html/vendor/doctrine/dbal/src/Schema/Exception/ColumnDoesNotExist.php:16 at
/html/vendor/doctrine/dbal/src/Schema/SchemaException.php:111 at Doctrine\DBAL\Schema\Exception\ColumnDoesNotExist :: new ( 'email', 'companies' )
/html/vendor/doctrine/dbal/src/Schema/Table.php:785 at Doctrine\DBAL\Schema\SchemaException :: columnDoesNotExist ( 'email', 'companies' )
/html/app/bundles/CoreBundle/Doctrine/Helper/IndexSchemaHelper.php:211 at Doctrine\DBAL\Schema\Table -> getColumn ( 'email' )
/html/app/bundles/CoreBundle/Doctrine/Helper/IndexSchemaHelper.php:90 at Mautic\CoreBundle\Doctrine\Helper\IndexSchemaHelper -> getTextColumns ( array( 'email' ) )
/html/app/bundles/LeadBundle/Field/CustomFieldIndex.php:154 at Mautic\CoreBundle\Doctrine\Helper\IndexSchemaHelper -> addIndex ( array( 'email' ), 'unique_identifier_search' )
/html/app/bundles/LeadBundle/Field/CustomFieldIndex.php:39 at Mautic\LeadBundle\Field\CustomFieldIndex -> updateUniqueIdentifierIndex ( object(LeadField) )
/html/app/bundles/LeadBundle/Field/CustomFieldColumn.php:135 at Mautic\LeadBundle\Field\CustomFieldIndex -> addIndexOnColumn ( object(LeadField) )
/html/app/bundles/LeadBundle/Field/CustomFieldColumn.php:51 at Mautic\LeadBundle\Field\CustomFieldColumn -> processUpdateLeadColumn ( object(LeadField) )
/html/app/bundles/LeadBundle/Model/FieldModel.php:559 at Mautic\LeadBundle\Field\CustomFieldColumn -> createLeadColumn ( object(LeadField) )
/html/app/bundles/LeadBundle/Controller/FieldController.php:297 at Mautic\LeadBundle\Model\FieldModel -> saveEntity ( object(LeadField), true )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\LeadBundle\Controller\FieldController -> editAction ( object(Request), '32', false )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), 2 )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:156 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), 2 )
/html/app/bundles/CoreBundle/Controller/CommonController.php:411 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( 'Mautic\LeadBundle\Controller\FieldController::editAction', array( 'objectId' => '32', 'objectModel' => '', '_stopwatch_token' => '282b7f', '_route' => 'mautic_contactfield_action', '_controller' => 'Mautic\LeadBundle\Controller\FieldController::editAction', 'objectAction' => 'edit', '_route_params' => array( 'objectId' => '32', 'objectAction' => 'edit' ), '_firewall_context' => 'security.firewall.map.context.main', '_security_firewall_run' => '_security_mautic' ), array( 'mauticUserLastActive' => '97', 'mauticLastNotificationId' => '' ) )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( object(Request), 'edit', '32', 0, '' )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), 1 )
/html/vendor/symfony/http-kernel/Kernel.php:202 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), 1, true )
/html/app/AppKernel.php:109 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), 1, true )
/html/app/middlewares/CORSMiddleware.php:76 at AppKernel -> handle ( object(Request), 1, true )
/html/app/middlewares/HSTSMiddleware.php:39 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), 1, true )
/html/app/middlewares/CatchExceptionMiddleware.php:28 at Mautic\Middleware\HSTSMiddleware -> handle ( object(Request), 1, true )
/html/app/middlewares/Dev/IpRestrictMiddleware.php:52 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), 1, true )
/html/app/middlewares/VersionCheckMiddleware.php:58 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), 1, true )
/html/app/middlewares/TrustMiddleware.php:42 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), 1, true )
/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), 1, true )
/html/index.php:19 at Stack\StackedHttpKernel -> handle ( object(Request) )
```
After that the phone field is set as indexable in the UI but I don't see the index in the leads table.

It worked well when creating a new field with specific length and index.

2024-02-08 06:09 UTC, dadarya0 commented
> I tried to make the phone field indexable and this happened:
> 
> ```
> 500 Internal Server Error - There is no column with name "email" on table "companies".
> /html/vendor/doctrine/dbal/src/Schema/Exception/ColumnDoesNotExist.php:16 at
> /html/vendor/doctrine/dbal/src/Schema/SchemaException.php:111 at Doctrine\DBAL\Schema\Exception\ColumnDoesNotExist :: new ( 'email', 'companies' )
> /html/vendor/doctrine/dbal/src/Schema/Table.php:785 at Doctrine\DBAL\Schema\SchemaException :: columnDoesNotExist ( 'email', 'companies' )
> /html/app/bundles/CoreBundle/Doctrine/Helper/IndexSchemaHelper.php:211 at Doctrine\DBAL\Schema\Table -> getColumn ( 'email' )
> /html/app/bundles/CoreBundle/Doctrine/Helper/IndexSchemaHelper.php:90 at Mautic\CoreBundle\Doctrine\Helper\IndexSchemaHelper -> getTextColumns ( array( 'email' ) )
> /html/app/bundles/LeadBundle/Field/CustomFieldIndex.php:154 at Mautic\CoreBundle\Doctrine\Helper\IndexSchemaHelper -> addIndex ( array( 'email' ), 'unique_identifier_search' )
> /html/app/bundles/LeadBundle/Field/CustomFieldIndex.php:39 at Mautic\LeadBundle\Field\CustomFieldIndex -> updateUniqueIdentifierIndex ( object(LeadField) )
> /html/app/bundles/LeadBundle/Field/CustomFieldColumn.php:135 at Mautic\LeadBundle\Field\CustomFieldIndex -> addIndexOnColumn ( object(LeadField) )
> /html/app/bundles/LeadBundle/Field/CustomFieldColumn.php:51 at Mautic\LeadBundle\Field\CustomFieldColumn -> processUpdateLeadColumn ( object(LeadField) )
> /html/app/bundles/LeadBundle/Model/FieldModel.php:559 at Mautic\LeadBundle\Field\CustomFieldColumn -> createLeadColumn ( object(LeadField) )
> /html/app/bundles/LeadBundle/Controller/FieldController.php:297 at Mautic\LeadBundle\Model\FieldModel -> saveEntity ( object(LeadField), true )
> /html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\LeadBundle\Controller\FieldController -> editAction ( object(Request), '32', false )
> /html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), 2 )
> /html/vendor/symfony/framework-bundle/Controller/AbstractController.php:156 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), 2 )
> /html/app/bundles/CoreBundle/Controller/CommonController.php:411 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( 'Mautic\LeadBundle\Controller\FieldController::editAction', array( 'objectId' => '32', 'objectModel' => '', '_stopwatch_token' => '282b7f', '_route' => 'mautic_contactfield_action', '_controller' => 'Mautic\LeadBundle\Controller\FieldController::editAction', 'objectAction' => 'edit', '_route_params' => array( 'objectId' => '32', 'objectAction' => 'edit' ), '_firewall_context' => 'security.firewall.map.context.main', '_security_firewall_run' => '_security_mautic' ), array( 'mauticUserLastActive' => '97', 'mauticLastNotificationId' => '' ) )
> /html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( object(Request), 'edit', '32', 0, '' )
> /html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), 1 )
> /html/vendor/symfony/http-kernel/Kernel.php:202 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), 1, true )
> /html/app/AppKernel.php:109 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), 1, true )
> /html/app/middlewares/CORSMiddleware.php:76 at AppKernel -> handle ( object(Request), 1, true )
> /html/app/middlewares/HSTSMiddleware.php:39 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), 1, true )
> /html/app/middlewares/CatchExceptionMiddleware.php:28 at Mautic\Middleware\HSTSMiddleware -> handle ( object(Request), 1, true )
> /html/app/middlewares/Dev/IpRestrictMiddleware.php:52 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), 1, true )
> /html/app/middlewares/VersionCheckMiddleware.php:58 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), 1, true )
> /html/app/middlewares/TrustMiddleware.php:42 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), 1, true )
> /html/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), 1, true )
> /html/index.php:19 at Stack\StackedHttpKernel -> handle ( object(Request) )
> ```
> 
> After that the phone field is set as indexable in the UI but I don't see the index in the leads table.
> 
> It worked well when creating a new field with specific length and index.

Issue fixed by https://github.com/acquia/mc-cs/pull/767

2024-02-08 09:14 UTC, escopecz commented
@dadarya0 I still cannot create an index on the phone field. It's not throwing the error anymore. I tried also to run
```
bin/console mautic:custom-field:update-column -i 32 -u 1

Column was updated
```
but it didn't help. Is it working for you?

2024-02-08 10:17 UTC, dadarya0 commented
> bin/console mautic:custom-field:update-column

yes, it sis working for me, follow below steps :-
1. clear your cache and regenerate assets as 1 JS file is changed
2. Run migration
3. set 'create_custom_field_in_background' => false and test everything should work instantly
4. set 'create_custom_field_in_background' => true and test everything should work only after command execution.

2024-02-08 10:31 UTC, escopecz commented
It works well on the custom text field I've created. I can add and remove index as I please. But on existing custom fields it doesn't create the index. For example on phone or city fields. Can you try that?

2024-02-08 12:44 UTC, kuzmany commented
Almost everything  works like, but
- same like John, core fields are not updated
- `mautic:custom-field:update-column`  You need the exact ID to make a call. It would be beneficial to periodically update the fields without parameters

2024-02-08 16:27 UTC, escopecz approved these changes
🤦 I was changing the index on the company field but I was looking into the leads table. It works!

@kuzmany let's add this change as a new PR. By default you don't need any command as it works during the field save. I'd like to improve this later with Symfony Messenger as we should create a job when a field is changed that will make the change in the background. Then this command is all we need.

2024-02-08 16:27 UTC, merged

2024-02-08 16:29 UTC, escopecz commented
Oops, I didn't notice that this doesn't have a second review. @rohitpavaskar please test this closed PR post-merge so we have the quality check completed.

2024-02-09 04:56 UTC, kuzmany commented
Another note: 
We have enabled the background option. 
After the update, you will receive an alert stating: "Your custom field is being created. We will notify you when it is complete."

2024-02-09 07:15 UTC, rohitpavaskar reviewed
Working as expected. Thanks!