Failed Event Notifications
mautic/mautic pull request #13402
Opened 2024-02-19 07:27 UTC by rohitp19

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is a WIP PR for changing the way we handle notifications for failed events within campaigns.

Unit tests are incoming, but this can be tentatively reviewed.

This PR leverages the event we already fire, `CampaignEvents::ON_EVENT_FAILED`. We're moving the notification into an event listener in which we are doing some checks to see if the given campaign event has failed for more than 5% of the contacts within the campaign. If so, notify the user. If its failed more than 10%, disable the campaign and notify the user of that.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
1. Create a template email.
2. Create a segment and a campaign sourced from that segment.
3. Put 10 contacts in that segment (preferably faked ones that can actually receive the email)
4. In that campaign, create a "send email" action. Select the email you created earlier.
5. After the email send, create a "Change campaigns" action that adds the user back to this campaign. It says "Restart this campaign" in the dropdown select.
6. Set your Email Settings to "Other SMTP" and give bogus credentials so that the email sending will fail and trigger the campaign event to be re-scheduled.
7. Trigger the campaign and see that the emails are delivered.
8. You'll start generating a ton of entries in your notifications table that the action failed due to the contact having already received the marketing email.
9. You may end up delaying workers, so please only do this in beta. 
10. Unpublish the campaign to stop further alerts.
11. 
12. At step 3, put 40 contacts in the segment.
13. At step 8, you'll only start generating errors after 5% of the contacts have failed (so in this case, with 40 contacts, after the event has failed twice). 
14. You'll see that only 4 or 5 notifications are created until the campaign automatically unpublishes itself.
15. Ensure that you get an email stating your campaign has been unpublished

2024-02-21 05:31 UTC, dadarya0 requested changes
Found only 1 changes.

2024-02-21 05:31 UTC, dadarya0 commented on app/bundles/CampaignBundle/Entity/Event.php
> +    private $failedCount = 0;
```suggestion
    private int $failedCount = 0;
```

2024-02-21 05:36 UTC, dadarya0 approved these changes, later dismissed

2024-02-21 07:43 UTC, dadarya0 commented
@rohitp19 failing on cs fixer.

2024-02-21 10:28 UTC, dadarya0 approved these changes

2024-02-22 07:30 UTC, Galokh66 commented
@rohitp19 
getting 500 server error when i click on campaign or try to edit it.
<img width="1792" alt="Screenshot 2024-02-22 at 12 57 48 PM" src="https://github.com/mautic/mautic/assets/88474171/0044d614-3655-4a08-a505-eaf59560fbee">
Also it breaks when i create a new campaign
<img width="1792" alt="Screenshot 2024-02-22 at 12 59 35 PM" src="https://github.com/mautic/mautic/assets/88474171/37f639d8-0820-491c-bb86-f4d5afa212a0">

2024-02-22 07:54 UTC, rohitp19 commented
@Galokh66 This PR contains a migration. Have you executed the migrations? Those can be executed using `bin/console d:m:m`

2024-02-22 09:44 UTC, Galokh66 commented
Tested and verified the notifications for email failure and campaign unpublished due to failure.
<img width="1792" alt="Screenshot 2024-02-22 at 3 09 16 PM" src="https://github.com/mautic/mautic/assets/88474171/770a0f2f-be32-4d07-b4cd-94635d5fc59e">
<img width="1792" alt="Screenshot 2024-02-22 at 3 09 25 PM" src="https://github.com/mautic/mautic/assets/88474171/bb97d284-6dd5-4773-ae89-ea0dc4afba2a">

2024-02-22 09:47 UTC, Galokh66 approved these changes

2024-02-22 11:09 UTC, merged

2025-02-11 17:27 UTC, cstuder commented
@rohitp19 Question: Is there a way to disable the automatic disabling of campaigns on failures? I'm trying to get a plugin of mine to delay events and one possible way would be to fail and reschedule them. But the new CampaignEventSubscriber disables the campaign due to the threshold.

Details here: https://forum.mautic.org/t/how-do-i-correctly-delay-the-execution-of-a-campaign-action-in-a-plugin/34970/3