Dnc segment sql optimization
mautic/mautic pull request #13413
Opened 2024-02-20 12:44 UTC by aarohiprasad

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL |  N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
SQL optimization for DNC segment. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Run segments:update command, SQL query described in addressed issue is running slow
2. SQL query is using apostrophes for reason parameter

#### Steps to test this PR:
1. Load up this PR
2. Check indexes in lead_donotcontact table
3. Run migrations:migrate
4. Index for lead_id has been deleted, new index for lead_id, channel, reason has been added
5. SQL query is not using apostrophes for reason parameter

2024-02-26 09:23 UTC, escopecz requested changes
@aarohiprasad could you please add this index also to the `DoNotContact` entity? This way the index will be created just for people migrating from an older version of Mautic but if someone installs a fresh Mautic then this index won't exist for them.

2024-02-26 14:47 UTC, escopecz commented on app/bundles/LeadBundle/Entity/DoNotContact.php
> +            ->addIndex(['lead_id', 'channel', 'reason'], 'dnc_reason_search');
```suggestion
            ->addIndex(['lead_id', 'channel', 'reason'], 'leadid_reason_channel');
```
The name should be same https://github.com/mautic/mautic/pull/13413/files#diff-6a40dd21e0b34d38b0c7b9b0e5c046ca0e7de1057ec431b84f6b03dfb1a43e29R55

2024-02-26 15:40 UTC, aarohiprasad commented on app/bundles/LeadBundle/Entity/DoNotContact.php
> +            ->addIndex(['lead_id', 'channel', 'reason'], 'dnc_reason_search');
My bad, I didn't notice!
I'll fix this

2024-02-26 15:46 UTC, escopecz approved these changes
Looks good. Thanks! 👍

2024-03-04 17:39 UTC, Galokh66 commented
Tested and verified sql query not showing apostrophes and lead_donotcontact indexes are properly created
<img width="1792" alt="Screenshot 2024-03-04 at 11 04 42 PM" src="https://github.com/mautic/mautic/assets/88474171/ff2a5a7c-ced8-4874-acff-84da14a28788">
<img width="1792" alt="Screenshot 2024-03-04 at 11 05 01 PM" src="https://github.com/mautic/mautic/assets/88474171/dc6eb010-e236-4328-b2ad-a4f856176f46">

2024-03-04 17:40 UTC, Galokh66 approved these changes

2024-03-05 09:25 UTC, merged