Support for btn-spin for remix icons
mautic/mautic pull request #13450
Opened 2024-02-23 06:03 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Seems like we start using remix icon https://github.com/mautic/mautic/pull/13318
This PR add support for remix icons for btn-spinner

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-02-23 06:52 UTC, LordRembo requested changes
To make sure this doesn't accidentally target 'normal' classes that start with `ri`, I would suggest using `ri-`instead.

2024-02-23 11:49 UTC, kuzmany commented
@LordRembo good point. I've added it.

2024-02-26 14:33 UTC, LordRembo commented
Thinking a bit further, I think it doesn't really make much sense to add the 'spin' functionality like this, because the remix icons will eventually replace the FontAwesome icons. At which point, the `fa-spin` class won't work anymore.
It would be best to either use a class/function provided by the remix iconpack itself, or make a custom one.
@andersonjeccel Does the remix iconpack have a class or function that is equivalent to FontAwesome's spinning functionality?

2024-02-26 14:35 UTC, LordRembo commented
@andersonjeccel maybe you can suggest a good way to add this instead of relying on the FontAwesome classes.

2024-03-05 18:08 UTC, andersonjeccel requested changes
Improved class to prevent conflicts

@LordRembo

2024-03-05 18:08 UTC, andersonjeccel commented on app/bundles/CoreBundle/Assets/js/1.core.js
> +            var hasIcon = mQuery(target).hasClass('fa') || className.startsWith('ri-');
var hasIcon = mQuery(target).hasClass('fa') || className.startsWith('ri-loader');

2024-03-05 18:10 UTC, andersonjeccel commented
@LordRembo Remix does not provide a function for spinning

2024-03-07 09:40 UTC, LordRembo requested changes
Ah, alright, then I propose this PR copies the 'spinning' css behind FontAwesome and puts that in the CSS files. Basically following the same logic.
I believe there's keyframe animations that are used by the `fa-spinner` and/or  `fa-spin` classes that should 1) be copied and the used on a generic `ri-spinner` class.
And 2), the `ri-spinner` class should then be added to the element with `ri-loader` (or whatever icon it is that needs to be spinning).

2024-03-07 09:53 UTC, kuzmany commented
I am a little lost. Anyway, anybody can pick it up and update it to the way of new design patterns. We do not forget also we use in some cases .btn-nospin to prevent use of spinner if we do not need it. Also, you can decide not to use spinner anymore for new design patterns, if not needed.

The goal of the PR was to bring spinner support during the state while we use fa- and ri- icons. 
After removing FA icons, it's obsolete.

2024-03-07 10:08 UTC, LordRembo approved these changes
@kuzmany Yeah, you're right. Sorry, I'm thinking a bit too far ahead. Perfectly fine to make this change now and revamp later.

2024-03-07 10:11 UTC, LordRembo commented
@andersonjeccel Maybe you can mark as 'approved' too, then this thing is ready to push forward

2024-03-12 19:59 UTC, andersonjeccel approved these changes

2024-04-04 19:00 UTC, kuzmany commented
Reopen once If need it ;)

2024-04-05 11:13 UTC, andersonjeccel commented
@kuzmany Could you implement that change I suggested for the icon class?
It needs to start with ri-loader

2024-04-05 11:56 UTC, kuzmany commented
@andersonjeccel Your change does not make sense. This condition checks if elements (button or link) have an icon. If yes, then switch to spinner; after finishing request, get it back.

2024-04-08 10:29 UTC, andersonjeccel commented
@kuzmany 

ri-loader is a prefix for loading icons

we need to make sure the spin feature will apply only to these icons, I suppose 

![image](https://github.com/mautic/mautic/assets/116097999/3d0a1c88-f279-4634-bd5f-a0a267343da8)

how could we fix this? 
I'll leave it open for you to code

thanks again for catching this issue 🙏🏻

2024-09-09 08:33 UTC, kuzmany commented
Outdated

2024-09-09 08:33 UTC, closed without merging