Add batching to notification campaign subscriber
mautic/mautic pull request #13451
Opened 2024-02-23 11:53 UTC by fedys

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      | 
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

The OneSignal plugin still uses legacy campaign code that executes one at a time. Since the OneSignal API itself supports batching, the code could be migrated to the newer way of executing campaigns which works in batches. 

We only batch together multiple player IDs for a single contact instead of player IDs across a batch of contacts. Our campaign code for this feature is using the legacy campaign execution code that processes a single contact at a time regardless if there is a group of contacts executing the same action at the same time.

#### Steps to test this PR:

It is impossible to test this PR as we don't have access to iOS developer resources. This PR is implemented with use of functional tests only.

2024-02-23 12:52 UTC, escopecz requested changes

2024-02-23 12:52 UTC, escopecz commented on app/bundles/NotificationBundle/Api/AbstractNotificationApi.php
> +    abstract public function sendNotification($id, Notification $notification): ResponseInterface;
Can you add the return type into the method comment? This may be a noticable BC break as it's an abstract class that plugins may extend.

2024-02-23 12:52 UTC, escopecz commented on app/bundles/NotificationBundle/Tests/NotificationTrait.php
> +    private $transportMock;
```suggestion
    private MockHandler $transportMock;
```

2024-02-23 13:56 UTC, escopecz approved these changes
The code looks great, thanks Fedy! 👍

2024-03-01 07:13 UTC, Galokh66 approved these changes
PR not testable

2024-03-01 08:28 UTC, merged