[UX] Change "System Report?" to "Visible for other users"
mautic/mautic pull request #13496
Opened 2024-02-28 18:50 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This update revises the label from “System Report?” to “Visible for Other Users” to improve clarity and intuitiveness. The new label directly conveys the functionality, allowing users to understand the option’s purpose without relying on additional tooltips. This change simplifies the user interface, making it more accessible and self-explanatory, thereby enhancing the user experience.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Reports
3. Create new
4. Look at the label

![image](https://github.com/mautic/mautic/assets/116097999/82b0f5eb-c699-4f0c-bcd3-18c7a289dc2e)

2024-02-29 09:37 UTC, code5rick commented
Nice idea. Would just consider if it makes sence to use "Visible for other users" or "Private report".

2024-02-29 09:56 UTC, LordRembo commented
@code5rick "Visible for other users" is maybe a little bit better because it reflects more directly the purpose? "Private report" means a similar thing, but the meaning is a bit obfuscated. Kinda nitpicky I guess, but when I think of the word 'Private', I'm not sure if that means all logged-in people or some kind of subset of users. While "other users" is very direct: it's everyone that is logged-in.

2024-02-29 11:46 UTC, andersonjeccel commented
@code5rick We would have to change the logic behind the buttons and using "Private" would still make a tooltip necessary, that's not good UX

2024-02-29 11:53 UTC, code5rick commented
> @code5rick We would have to change the logic behind the buttons and using "Private" would still make a tooltip necessary, that's not good UX

Following the option of the "Private report" label, the logic would be the same as the current one. There would be no changes needed regarding the logic.

2024-02-29 12:32 UTC, andersonjeccel commented
@code5rick Give one more try to think what would happen if a user selected Yes for Private report

2024-03-01 08:03 UTC, LordRembo commented
@code5rick @andersonjeccel 
I think we're maybe confusing ourselves and each other a bit :D
In the current logic, setting 'Yes' for a 'System report', makes the report visible for all (logged in) users. Which is the same as 'Private report'. If 'private' just means 'everyone who is LOGGED IN'. 

So these are all the options so far, which do the same thing:
* System report
* Private report (where I'd argue the meaning of 'private' is less intuitive then initially thought)
* Visible for other users
* Visible for all logged-in users

2024-03-01 08:17 UTC, Mike-Dropsolid commented
"Visible for all users" would work for me. There's no way to misinterpret that.

"Visible for all logged-in users" if you want to go fully dummy-proof :)

2024-03-01 10:02 UTC, code5rick commented
> "Visible for all logged-in users" if you want to go fully dummy-proof :)

Ahaha awesome this one. I personally liked the 2 suggestions that you maded @Mike-Dropsolid: clear and direct. Let's see what the teams likes!

2024-03-01 22:38 UTC, Esthertests approved these changes
LGTM
on prod
![image](https://github.com/mautic/mautic/assets/156212312/ff2349ec-d862-4c2b-89e7-77c401f842a6)

on Pr changes
![image](https://github.com/mautic/mautic/assets/156212312/3c14e66d-c6a4-4867-a591-763a13534f06)

2024-03-03 08:25 UTC, RCheesley commented
My preference out of the proposed suggestions is:

'Visible for all logged in users' - because it makes it clear it's not for public consumption and that you need to be a logged in user to access.

2024-03-05 06:09 UTC, shinde-rahul commented on app/bundles/ReportBundle/Translations/en_US/messages.ini
> +mautic.report.report.form.issystem.tooltip="Setting this to no will make it visible to you and roles with permission to view other users' reports."
```suggestion
mautic.report.report.form.issystem.tooltip="Setting this to \"No\" will make it visible to you and roles with permission to view other users' reports."
```

2024-03-05 06:10 UTC, shinde-rahul requested changes
If the requested changes does not add more value then, ignore it.

2024-03-05 16:57 UTC, andersonjeccel commented
@LordRembo But everyone needs to be logged in... **There is not an option to make it visible for who is not logged in**, so the logic behind it would change when you make it private (only you) or not private (all users on Mautic)

2024-03-07 09:09 UTC, LordRembo commented
@andersonjeccel In the way it was proposed here in the comments, 'Private' means 'logged in users'. My point is that there's multiple way to interpret that word, especially if someone is not that familiar with the permissions and options for users in Mautic.
But it doesn't really matter for this PR because most reviewers here chose one of the other options.
Looking at the comments, I believe we can all live with "Visible for all logged-in users".

Additionally, @shinde-rahul's changes improve the readability. Probably best to integrate that as well.

2024-03-07 09:11 UTC, LordRembo approved these changes
So yeah, do take a look at the change suggestions

2024-03-07 09:12 UTC, LordRembo requested changes
So yeah, do take a look at the change suggestions

2024-03-14 09:51 UTC, LordRembo approved these changes
nice

2024-03-15 13:18 UTC, RCheesley approved these changes
Thanks for the improvement @andersonjeccel - Good to go! 🚀

2024-03-19 12:31 UTC, escopecz commented
@andersonjeccel please fix the code style issues.

2024-03-19 12:45 UTC, andersonjeccel commented
@escopecz The test result seems not to be related to the PR...

> Run if [[ "CS Fixer" == "PHPSTAN" ]]; then
> Loaded config default from ".php-cs-fixer.php".
> 
> In ConfigurationResolver.php line 390:
>                                                                                
>   The path "app/bundles/CoreBundle/Exception/RecordCanNotUnpublishException.p  
>   hp" is not readable.                                                         
>                                                                                
> 
> fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
> 
> Error: Process completed with exit code 16.

2024-03-19 13:47 UTC, merged

2024-04-16 09:16 UTC, RCheesley commented
This needs a small docs update PR @andersonjeccel @mautic/education-team to remove 'system report'.