Add possibility to stop sending in EmailSendEvent.
mautic/mautic pull request #13506
Opened 2024-02-28 20:52 UTC by mallezie

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

I would like the possibility to stop the sending of an Email through an eventsubscriber. There is already the EmailSendEvent so this looks the logical place to add this. 

Creating an eventsubscriber like below can now with this PR stop sending of the mail. 
`public static function getSubscribedEvents(): array
    {
        return [
            EmailEvents::EMAIL_ON_SEND    => ['stopMailSending', 0],
        ];
    }

    public function stopMailSending(EmailSendEvent $event): void
    {
      $event->setStopSending(TRUE);
    }`

This allows plugin developers to stop mail sending based on certain criteria. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create plugin with above EventListener, and see mails are not sent.

2024-02-29 08:05 UTC, mallezie commented
Added option to specify error message in event subscriber. Updated how to test.

2024-03-06 14:36 UTC, escopecz requested changes
Can it be reduced just to `setSendingError(string $message)` and if an error is set then it will stop sending with this message? Also, please, add PHPUNIT tests to cover this use case.

2024-04-19 16:13 UTC, RCheesley commented
@mallezie some open feedback and conflicts to resolve here please, when you can!

2024-06-13 12:16 UTC, mallezie commented
Closing this one. https://github.com/mautic/mautic/pull/13360 introduced a similar thing, which we use now.

2024-06-13 12:16 UTC, closed without merging