DPMMA-2550 Point Groups API
mautic/mautic pull request #13517
Opened 2024-03-04 13:14 UTC by patrykgruszka

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | TODO
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds API endpoints for Point Groups management.
```
mautic_api_pointGroups_getall          GET     /api/points/groups                                                                               
mautic_api_pointGroups_getone          GET     /api/points/groups/{id}                                                                          
mautic_api_pointGroups_new             POST    /api/points/groups/new                                                                                                                                        
mautic_api_pointGroups_editput         PUT     /api/points/groups/{id}/edit                                                                     
mautic_api_pointGroups_editpatch       PATCH   /api/points/groups/{id}/edit                                                                                                                           
mautic_api_pointGroups_delete          DELETE  /api/points/groups/{id}/delete                                                                   
mautic_api_getcontactpointgroups       GET     /api/contacts/{contactId}/points/groups                                                          
mautic_api_getcontactpointgroup        GET     /api/contacts/{contactId}/points/groups/{groupId}                                                
mautic_api_adjustcontactgrouppoints    POST    /api/contacts/{contactId}/points/groups/{groupId}/{operator}/{value} 
```

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))

2. **Create a new point group**:
   - **Endpoint**: `POST https://your-api-host.com/api/points/groups/new`
   - **Payload**: JSON payload with the following fields:
     ```json
     {
         "name": "New Point Group",
         "description": "Description of the new point group"
     }
     ```

3. **Retrieve all point groups**:
   - **Endpoint**: `GET https://your-api-host.com/api/points/groups`

4. **Update the created point group**:
   - **Endpoint**: `PATCH https://your-api-host.com/api/points/groups/{id}/edit`
   - **Payload**: JSON payload with the fields to update:
     ```json
     {
         "name": "Updated Point Group Name",
         "description": "Updated description of the point group"
     }
     ```

5. **Delete the created point group**:
   - **Endpoint**: `DELETE https://your-api-host.com/api/points/groups/{id}/delete`

6. **Get contact group points**:
   - **Endpoint**: `GET https://your-api-host.com/api/contacts/{leadId}/points/groups`

7. **Adjust contact group points**:
   - **Plus operation**:
     - **Endpoint**: `POST https://your-api-host.com/api/contacts/{leadId}/points/groups/{groupId}/plus/{value}`
   - **Minus operation**:
     - **Endpoint**: `POST https://your-api-host.com/api/contacts/{leadId}/points/groups/{groupId}/minus/{value}`
   - **Set operation**:
     - **Endpoint**: `POST https://your-api-host.com/api/contacts/{leadId}/points/groups/{groupId}/set/{value}`
   - **Divide operation**:
     - **Endpoint**: `POST https://your-api-host.com/api/contacts/{leadId}/points/groups/{groupId}/divide/{value}`
   - **Multiply operation**:
     - **Endpoint**: `POST https://your-api-host.com/api/contacts/{leadId}/points/groups/{groupId}/times/{value}`

When testing these endpoints, ensure that you replace placeholders such as `{leadId}`, `{groupId}`, and `{value}` with actual IDs and values as required for your specific test cases. Additionally, for endpoints that require a request body, provide the appropriate JSON payload with the necessary fields and values.

2024-04-19 16:11 UTC, RCheesley submitted a review, later dismissed
Tested all endpoints (thank you SO MUCH for the awesome documentation in the PR @patrykgruszka it really helps testers when you provide both the path and the snippet!).

All working as expected. Thanks for the great work! 🚀

2024-04-24 18:07 UTC, escopecz requested changes
The code looks great! I have a few small suggestions. The functional tests are testing the happy paths. It would be great to have tests that check also 404s, xss and similar. But happy path tests are still way better than none 👍

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Config/config.php
> +                'controller'      => \Mautic\PointBundle\Controller\Api\PointGroupsApiController::class,
As per the new CS Fixer version:
```suggestion
                'controller'      => Mautic\PointBundle\Controller\Api\PointGroupsApiController::class,
```

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Controller/Api/PointGroupsApiController.php
> +    /** @phpstan-ignore-next-line */
Why is this needed? If it cannot be resolved, could you add the reason to the comment?

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Controller/Api/PointGroupsApiController.php
> +    protected $model;
```suggestion
    private PointGroupModel $model;
```
Or is there some weird inheritance thing going on?

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Controller/Api/PointGroupsApiController.php
> +
```suggestion

declare(strict_types=1);

```

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Tests/Controller/Api/PointGroupsApiControllerTest.php
> +
```suggestion

declare(strict_types=1);

```

2024-04-24 18:07 UTC, escopecz commented on app/bundles/PointBundle/Tests/Controller/Api/PointGroupsApiControllerTest.php
> +        $this->assertSame(200, $deleteResponse->getStatusCode());
```suggestion
        $this->assertSame(Response::HTTP_OK, $deleteResponse->getStatusCode());
```

2024-04-26 10:56 UTC, patrykgruszka commented on app/bundles/PointBundle/Controller/Api/PointGroupsApiController.php
> +    protected $model;
Yes, we can't define the type here.

2024-04-26 10:57 UTC, patrykgruszka commented on app/bundles/PointBundle/Controller/Api/PointGroupsApiController.php
> +    /** @phpstan-ignore-next-line */
Sure, I've added a comment. It is caused by the parent class.

2024-04-26 12:33 UTC, patrykgruszka commented
Thanks! I've updated the code and added some extra tests :)

Would you have some time to look at the related PR in the API library? https://github.com/mautic/api-library/pull/322

2024-04-29 08:32 UTC, escopecz approved these changes
I see no issue in the code. The Point group/score is covered with functional tests 👍

2024-04-29 09:12 UTC, merged