WIP [DPMMA-2187] Segment date filter and "equals" operator
mautic/mautic pull request #13620
Opened 2024-04-09 14:53 UTC by annamunk

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-04-09 19:16 UTC, kuzmany reviewed
Why YYYY-MM-DD should not work with equal expression? Do I miss something?

2024-04-19 10:48 UTC, annamunk commented
@kuzmany I noticed that using these operators with incomplete dates does not return correct results when rebuilding segments. The date would have to be accurate to the second. I assume that for such a specific time we can simply add selected contacts manually. If we need to specify an exact day or time, using another operator is a better idea.

2024-04-19 11:06 UTC, kuzmany commented
@annamunk I think we fixed all things related to equal/not equal here https://github.com/mautic/mautic/pull/11835. 

For example if 

date = -1 days (day = 18.4.2024)
datetime = - 1 days (datetime between  -24 hours and -48 hours)

2024-05-10 15:09 UTC, annamunk commented
@kuzmany let's assume that I would like to create a segment with contacts that were identified on a specific day, e.g. 2023-05-06,  
![contactd_identified](https://github.com/mautic/mautic/assets/102536220/b876850c-9f1a-4db1-8de9-7f733beeb65f)

I set this filtering value in segment settings:
![date_added](https://github.com/mautic/mautic/assets/102536220/f3d41bb7-97f9-4b0a-89e2-1958afbd063c)

When performing a segment rebuild (php bin/console m:s:u), a database query is generated with the following 'where' condition, which does not return matched contacts due to lack of exact time of the day
`... WHERE (l.date_identified = '2023-05-06') ...`

I tested https://github.com/mautic/mautic/pull/11835, but for specific, non-relative dates such as 2023-05-06 the problem with equal/not equal still occurred.

2024-08-20 15:10 UTC, andersonjeccel requested changes
From a UX perspective, it might be a bad experience, because the platform is becoming more technical and developer-centric

To proceed with something like this, it would be ideal to fix the way Mautic handles the date or create a workaround on the UI to avoid an issue... It might not be useful to have only a message, users want solutions

2025-10-04 00:05 UTC, closed without merging