[UX] More contrast for texts
mautic/mautic pull request #13627
Opened 2024-04-10 13:31 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Based on user feedback:

> More contrast: replace the mid gray to a darker gray

The user is suggesting an improvement in the visual contrast of the interface by replacing mid-tone grays with darker shades. This indicates that the current color scheme may not provide sufficient contrast, potentially affecting readability and visual distinction between elements.

The user’s broader need is for a visually accessible and aesthetically pleasing interface that facilitates easy reading and navigation. They are seeking an enhancement in the visual hierarchy that allows users to quickly and effortlessly distinguish between different UI elements.

To address this feedback, this PR adjust the color palette to use darker grays for body text that offer better contrast against other elements. I ensured it meets WCAG accessibility standards for contrast ratios.

![image](https://github.com/mautic/mautic/assets/116097999/d131c6e9-a119-49da-8ea4-93c111ce695d)

The contrast ratio was increased by about ~7 points compared to before.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Look at basically anything, the text will be darker

2024-04-11 08:07 UTC, LordRembo approved these changes
It's an easy fix to do (with no issues as consequence) with an immediate improvement for readability/accessibility, so sounds good to me!

2024-04-11 11:33 UTC, patrykgruszka requested changes
The `app.css` file should be generated automatically from the LESS files. You can generate the CSS by executing the `grunt compile-less` command.

2024-04-11 11:33 UTC, patrykgruszka commented on app/bundles/CoreBundle/Assets/css/app.css
> +  color: #5d6c7c;
This change needs to be done in `CoreBundle/Assets/css/app/less/components/type.less:101`.

2024-04-11 11:33 UTC, patrykgruszka commented on app/bundles/CoreBundle/Assets/css/app.css
> +  color: #262d33;
LESS file: `app/bundles/CoreBundle/Assets/css/app/less/components/steps.less`

2024-04-11 11:33 UTC, patrykgruszka commented on app/bundles/CoreBundle/Assets/css/app.css
> +  color: #262d33 !important;
LESS: `CoreBundle/Assets/css/app/less/components/colors.less`

2024-04-11 17:23 UTC, andersonjeccel commented
@patrykgruszka Thanks for pointing!

As I changed 1 variable, every LESS rule or mixin based on the text color also changed accordingly and reflected on CSS when I ran `grunt compile-less`

These different hex codes are a consequence, nothing hardcoded 😉

2024-04-11 17:38 UTC, patrykgruszka approved these changes
You're right. These variables are dependent on `@text-color`. My earlier comments were not accurate. Looks good 👍

2024-04-12 15:43 UTC, RCheesley approved these changes
Thanks for the PR! LGTM! 🚀

2024-04-12 15:56 UTC, andersonjeccel commented
@RCheesley Based on the approved changes by Patryk and Rembrand, can we consider as code-review-passed?

2024-04-19 09:28 UTC, merged