Add constrain to check if plugin can be published.
mautic/mautic pull request #13696
Opened 2024-04-26 09:05 UTC by rohitpavaskar

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-04-30 12:00 UTC, escopecz requested changes
Thanks Rohit! I found a few places that could improve. Please go through the suggestions and apply them if they make sense.

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Controller/PluginController.php
> +     * @phpstan-ignore-next-line
Can you please add a comment at the end of this line why this needs to be ignored?

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Config/config.php
> +            ],
This shouldn't be necessary for M5. Is it? The tag can be added in services.php if the service isn't autoconfigured.

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Event/PluginIsPublishedEvent.php
> +    }
```suggestion
    private string $message  = true;
    private bool $canPublish = '';

    public function __construct(private int $value, private string $integrationName)
    {
    }
```

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/PluginEvents.php
> +     * The mautic.plugin.is_published_state_changing event is dispatched when a user tries to changes plugin is published state.
```suggestion
     * The mautic.plugin.is_published_state_changing event is dispatched when a user tries to change the published state of a plugin.
```

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Tests/DependencyInjection/Compiler/TestPass.php
> +            /** @phpstan-ignore-next-line  */
Please add a reason why the next line is ignored if it cannot be fixed.

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Tests/Form/Constraint/CanPublishValidatorTest.php
> +
```suggestion

declare(strict_types=1);

```

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Tests/Form/Constraint/CanPublishValidatorTest.php
> +    private MockObject $event;
These should have a `&` the real type like `MockObject&EventDispatcherInterface` as it needs the methods from both. PHP 8 doesn't allow the `&` operator just yet so you'll have to add the real type to the comment along as the `MockObject` type you have there.

2024-04-30 12:00 UTC, escopecz commented on app/bundles/PluginBundle/Translations/en_US/validators.ini
> +mautic.lead_list.not_allowed_plugin_publish="You are not allowed to publish plugin due to insufficient configurations."
It doesn't sound right. Should there be `the` or `this`?
```suggestion
mautic.lead_list.not_allowed_plugin_publish="You are not allowed to publish this plugin due to insufficient configurations."
```

2024-05-15 11:12 UTC, rohitpavaskar commented on app/bundles/PluginBundle/Controller/PluginController.php
> +     * @phpstan-ignore-next-line
AbstractIntegration class is depreciated so phpstan is throwing error

2024-05-15 13:32 UTC, escopecz commented on app/bundles/PluginBundle/Controller/PluginController.php
> +     * @phpstan-ignore-next-line
Good to know. Can you add that info at the end of the line so it's obvious?

2024-05-15 13:33 UTC, escopecz commented on app/bundles/PluginBundle/Controller/PluginController.php
> +     * @phpstan-ignore-next-line
I can see you did that. Thanks!

2024-05-15 13:45 UTC, escopecz approved these changes
Thank you, Rohit! I see no problems in the code changes 👍

2024-05-15 13:50 UTC, escopecz commented
Since this cannot be directly tested without a proprietary plugin, can someone do a second code review? Perhaps @kuzmany ?

2024-06-05 19:27 UTC, RCheesley commented
@rohitpavaskar please could you check the conflict here? Then we'll find some plugin developers to review and test. Thanks in advance!

2025-07-25 10:26 UTC, escopecz approved these changes
I'd make the new classes final, but won't block the PR just because of it 👍

2025-07-25 13:58 UTC, kuzmany approved these changes
I did basic tests and seems good to me.

2025-07-25 14:01 UTC, merged