Form field automatically remapping after being unmapped
mautic/mautic pull request #13744
Opened 2024-05-13 12:29 UTC by fedys

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅]
| New feature/enhancement? (use the a.x branch)      | [❌]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

This PR fixes the following bugs:

1. Icons for mapped form fields are not displayed in the form field listing.
2. Un-mapping a mapped type form field and clicking the "Save" button is causing the field to appear mapped again. In reality the field is just marked as mapped. If you inspect the related database record, you can see the field is not mapped. You can validate that by refreshing your browser. After the refresh the field is no longer marked as mapped.
3. A non-mapped existing form field is auto-mapped when being edited.

#### Steps to test this PR:

1. TBD

2024-05-13 16:23 UTC, escopecz approved these changes
I see no issue in the code 👍 Thanks!

2024-05-13 18:28 UTC, kuzmany requested changes
I found another issue, do not investigate if it's related to code in the PR, but it's worth checking.
If the form returns an error, then the last added field disappears.

https://github.com/mautic/mautic/assets/462477/576fc1a7-32dc-4590-8b2a-e9334878e45d

2024-05-14 06:08 UTC, fedys commented
> I found another issue, do not investigate if it's related to code in the PR, but it's worth checking. If the form returns an error, then the last added field disappears.
> 
>  Zaznam.2024-05-13.202639.mp4

@kuzmany Thanks for point it out! This issue is reproducible in `5.x` too.

2024-05-16 19:52 UTC, kuzmany approved these changes

2024-05-17 10:11 UTC, merged