Prevent run report sheduler If already run
mautic/mautic pull request #13764
Opened 2024-05-20 16:52 UTC by hugoprossaird

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| New feature/enhancement? (use the a.x branch)      | no
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              |  no 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If you use send reports to email, and your report processing take more time like your cron timeout mautic:report:scheduler, command start process same report again. This make issue on big reports
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create report with large data
3. Use export & send
4. Try running the example-command, and a few seconds later, run the same example-command again in parallel using separate terminal windows or background processes
5. After this PR you should see Script in progress. Can force execution by using --force.

2024-05-20 16:55 UTC, hugoprossaird commented
Hello @kuzmany,
Rebase of your PR https://github.com/mautic/mautic/pull/10121 on Mautic 5.
Is this what you expected ?

2024-05-21 11:09 UTC, kuzmany requested changes
Based on CI (https://github.com/mautic/mautic/pull/13764/checks) checks It need  

1, fix CS `composer fixcs`
2. Write unit tests

I would create function tests. Two reports and run scheduler in same time


You can add it to:
https://github.com/mautic/mautic/blob/5fb7ff2283f4f41a60402bb031cae1f3393c19bb/app/bundles/ReportBundle/Tests/Command/ExportSchedulerCommandTest.php

Probably same inspiration take from: https://github.com/mautic/mautic/blob/96ff70c3d57d7a9cf5502411926a82623bdc16f8/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php#L681

2024-05-24 06:00 UTC, hugoprossaird commented
@kuzmany 
I am having trouble executing the command in my test. I am encountering the following error: "There are no commands defined in the 'mautic:reports' namespace." This issue started occurring after I switched the extended class to ModeratedCommand. However, it does not seem to happen in the CI environment.

Still searching :)

2024-05-24 17:00 UTC, hugoprossaird commented
> @kuzmany I am having trouble executing the command in my test. I am encountering the following error: "There are no commands defined in the 'mautic:reports' namespace." This issue started occurring after I switched the extended class to ModeratedCommand. However, it does not seem to happen in the CI environment.
> 
> Still searching :)

Doing like in the CI before executing tests fix that (rm -rf var/cache)

2024-05-24 17:39 UTC, hugoprossaird commented
@kuzmany I added a new test to validate multi-execution of the command ;)

2024-05-27 21:34 UTC, kuzmany commented on app/bundles/ReportBundle/Scheduler/Command/ExportSchedulerCommand.php
> +            return Command::FAILURE;
If script running, It should still return success.  Probably unit tests will work then

2025-10-04 00:05 UTC, closed without merging