Check for null before altering $expr
mautic/mautic pull request #13811
Opened 2024-06-04 10:08 UTC by pjrobertson

Fixes #13810

I think this should go in 5.1, so use 5.1 branch for this PR.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴

| Issue(s) addressed                     | Fixes #13810

2024-06-04 10:19 UTC, RCheesley commented
@pjrobertson thanks for flagging the issue and for the PR to fix it!

Please provide a full description and test instructions using the template provided, if you'd like people to test this PR.

2024-06-04 12:20 UTC, pjrobertson commented
Thanks @RCheesley  - I assumed the testing instructions in the linked issue would be enough, but I have added them here. Thanks!

2024-06-04 12:28 UTC, RCheesley commented
Thanks so much - it just makes it a lot easier for testers who might be new to the process, to have everything in one place!

2024-06-04 12:29 UTC, RCheesley commented
Could you please take a look at the [code style test](https://github.com/mautic/mautic/actions/runs/9365203308/job/25780432703?pr=13811) which is failing? Thanks!

2024-06-04 12:37 UTC, pjrobertson commented
Good spot - fixed!

2024-06-06 15:07 UTC, escopecz requested changes
I'm not convinced this is the right way to fix it. This basically means that if the `getTokens()` method is called without the last parameter then it will ignore the 2 if statements. From which 1 is about viewother permissions. So basically this disables the viewother permission check.

How about to instead add this line somewhere above the checks?

```php
$expr = $expr ?? $this->connection->createExpressionBuilder();
```
This way the `$expr` param will be used and if it is `null`, it will create a fresh one.

2024-06-18 11:10 UTC, pjrobertson commented
This seems to make sense to me, but a similar line is already in there (line 96):

```php
        $exprBuilder = $this->connection->createExpressionBuilder();
```

and is used as part of the problematic `$expr = $expr->with(...)` parts. I guess we could add on line 97 the following instead?

```php
      $expr = $expr ?? $exprBuilder;
```

Does that make sense?

2024-06-18 12:33 UTC, escopecz commented
@pjrobertson it does make sense

2024-06-19 10:28 UTC, pjrobertson commented
Great, thanks @escopecz ! I've made this change and pushed. Please review :)

2024-06-19 13:34 UTC, escopecz reviewed
Looks better! I think we can go even a step further and remove the line above:
```php
$exprBuilder = $this->connection->createExpressionBuilder();
```
And wherever the `$exprBuilder` variable is used we can use `$expr` instead. What do you think?

2024-06-19 21:17 UTC, pjrobertson commented
I can make that change, but I don't really understand the use case here.
This would be a deviation away from the current code. Right now, if `$expr`
is set, then it's used in addition to `$exprBuilder`. But if you make
`$exprBuilder` equal to `$expr` then that would be a potential change.

I suggest leaving it as is. I will test this method on my install to make
sure it still works.

On Wed, 19 Jun 2024 at 14:34, John Linhart ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Looks better! I think we can go even a step further and remove the line
> above:
>
> $exprBuilder = $this->connection->createExpressionBuilder();
>
> And wherever the $exprBuilder variable is used we can use $expr instead.
> What do you think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mautic/mautic/pull/13811#pullrequestreview-2128308538>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABEXH74NO6PBTCKXZOPSDLZIGCHJAVCNFSM6AAAAABIYF3OHCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMRYGMYDQNJTHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-21 07:51 UTC, escopecz commented on app/bundles/CoreBundle/Helper/BuilderTokenHelper.php
> +        $expr = $expr ?? $this->connection->createExpressionBuilder();
Tests uncovered it's not working:
```
TypeError: Mautic\CoreBundle\Entity\CommonRepository::getSimpleList(): Argument #1 ($expr) must be of type ?Doctrine\DBAL\Query\Expression\CompositeExpression, Doctrine\DBAL\Query\Expression\ExpressionBuilder given, called in /home/runner/work/mautic/mautic/app/bundles/CoreBundle/Helper/BuilderTokenHelper.php on line 117
```
How about something like
```suggestion
        $expr = $expr ?? $this->connection->createQueryBuilder()->expr();
```

2024-07-22 20:14 UTC, RCheesley commented
Is this OK with you now @escopecz ?

2024-07-23 09:28 UTC, escopecz commented
Sadly not. The CI is failing. We must create the expression builder some other way. And fix the CS issues. It would be also great to write tests to ensure it works and continues to work in the future.

2024-10-30 08:41 UTC, pjrobertson commented
Just as an update, this c7872a6ab91969a06346c5f0ecfd884e94717aed **does not work**

I upgraded to 5.1.1, and the only solution that currently works for me is the original commit: c8c10eb8edf0fac57b7ecf03fb29255a01f4a0df

2024-11-12 12:02 UTC, shinde-rahul requested changes
Please have a functional test to cover this. The changes look good.

2025-01-20 12:31 UTC, RCheesley commented
@pjrobertson are you able to provide a functional test as requested? It'd be great to get this shipped in the next patch release.

2025-01-21 08:03 UTC, pjrobertson commented
Sorry, I'm kind of new to PHP unit testing. Can you point me in the right direction and I'll try and add one. Although I do not know how I will do this, since it requires a user without 'view other' permissions and then that user to make the request.

2025-01-21 08:57 UTC, escopecz commented
@pjrobertson let's look into this together.

1. Make sure you use [DDEV](https://www.mautic.org/blog/developer/local-mautic-development-with-ddev). In that article there is a section of how to run tests locally.
2. Rebase to the 6.x branch as the tests were changed a little during the Symfony 6 upgrade and the 5.x branch is dead now.
3. Look at similar tests already written for Mautic. There are tests that are changing the users and roles to test permissions. Here is an example: https://github.com/mautic/mautic/blob/6.x/app/bundles/FormBundle/Tests/Controller/SubmissionFunctionalTest.php#L592

Let me know if you get stuck.

2026-06-08 18:37 UTC, andersonjeccel commented
Hey, I'm seeing this PR has been quiet for a while, so it looks stalled. We're doing a small cleanup so the review queue stays focused on PRs that are still being worked on and closer to merge. If this was not the right call, I'm happy to see it reopened and updated.

2026-06-08 18:37 UTC, closed without merging