[UX] Sending at, Activate at and Available from (statuses)
mautic/mautic pull request #13818
Opened 2024-06-07 13:44 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR aligns the schedule options with the status label used by a bundle. Example: Since you make an Asset available for use, it makes sense to schedule "Available from" and "Unavailable from" instead of the generic "Activate at/Deactivate at".

All changes:
- Fixes the broken schedule logic for Emails. When you create a Template Text Message (sms), the "Publish/Activate at" options are hidden. They should also be hidden for Template Emails.
- Aligns Segment Emails and SMS to use "Start sending at" since this way better expresses the functionality 
- Uses "Available from" instead of "Activate at" for resources where the publish label is "Available for use" to improve consistency and feedback (users create a better relationship between the fields)

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Plugins > Twilio > Fill anything and set Active > Save
3. Open Components > Emails > New > Template > See any "Start sending at" options > Save
4. Repeat the step 3 for Template Text Messages (SMS)
5. Open Components > Emails > New > Segment > See "Start sending at" options  > Save
6. Repeat the step 5 for Segment Text Messages (SMS)
7. Open Components > Emails > Open the created Template Email > Dropdown > Add A/B test > See no "Start sending at" options
8. Open Components > Emails > Open the created Segment Email > Dropdown > Add A/B test > See "Start sending at" options
9. Open Components > Assets > New > See "Available from" options
10. Repeat the step 9 for Marketing Messages, Forms and Landing pages

2024-06-14 02:34 UTC, shinde-rahul requested changes
Needs cs fixes.

2024-06-14 02:34 UTC, shinde-rahul commented on app/bundles/AssetBundle/Resources/views/Asset/form.html.twig
> +    		{{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```suggestion
			{{ form_row(form.publishUp, {'label': 'mautic.core.form.available.available_from'}) }}
    		        {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```

2024-06-14 02:34 UTC, shinde-rahul commented on app/bundles/PageBundle/Resources/views/Page/form.html.twig
> +    		  {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```suggestion
              {{ form_row(form.publishUp, {'label': 'mautic.core.form.available.available_from'}) }}
    	     {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```

2024-06-14 11:07 UTC, andersonjeccel commented
@shinde-rahul Thanks for fixing 🙏🏻

2024-06-14 16:18 UTC, shinde-rahul approved these changes
LGTM!!!

2024-07-01 13:08 UTC, oltmanns-leuchtfeuer approved these changes
LGMT from a User-Perspective.

2024-07-15 06:40 UTC, escopecz commented on app/bundles/AssetBundle/Resources/views/Asset/form.html.twig
> +    		        {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
Please fix the indentation.

2024-07-15 06:43 UTC, escopecz requested changes

2024-07-15 06:43 UTC, escopecz commented on app/bundles/EmailBundle/Assets/js/email.js
> +        mQuery('#scheduleOptions').removeClass('hide');
Why to hide it for both list and template types? It's the all types there are. From the programming perspective, it shouldn't be in the if nor else blocks but bellow it as you want to apply it to both. But from the product perspective, why do we have a feature that we want to hide for all options?

2024-07-15 06:43 UTC, escopecz commented on app/bundles/PageBundle/Resources/views/Page/form.html.twig
> +    	     {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
Another indentation issue.

2024-07-15 06:44 UTC, escopecz commented on app/bundles/EmailBundle/Assets/js/email.js
> +        mQuery('#scheduleOptions').removeClass('hide');
Oops, this is `removeClass`. Makes sense then.

2024-07-15 06:46 UTC, escopecz commented on app/bundles/AssetBundle/Resources/views/Asset/form.html.twig
> +    		        {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```suggestion
			{{ form_row(form.publishUp, {'label': 'mautic.core.form.available.available_from'}) }}
    		{{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```

2024-07-15 06:46 UTC, escopecz commented on app/bundles/PageBundle/Resources/views/Page/form.html.twig
> +    	     {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```suggestion
              {{ form_row(form.publishUp, {'label': 'mautic.core.form.available.available_from'}) }}
    	      {{ form_row(form.publishDown, {'label': 'mautic.core.form.available.unavailable_from'}) }}
```

2024-07-15 06:47 UTC, escopecz approved these changes
I fixed the indentations 👍

2024-07-15 06:58 UTC, merged