Landing Page Draft Feature
mautic/mautic pull request #13937
Opened 2024-07-09 05:27 UTC by aarohiprasad

MAUT-3816 : Landing Page Draft feature

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-12-04 10:12 UTC, shinde-rahul commented
@aarohiprasad, Is this PR still being actively worked on? There are some conflicts that need attention. Could you share an update on the progress?

2025-02-27 14:41 UTC, escopecz commented
@shinde-rahul this is ready for testing. I've improved the code and description. I'll work on the docs now.

2025-02-27 15:26 UTC, escopecz submitted a review, later dismissed
I'm Ok with the changes now and I've tested this feature and improved the description.

2025-03-06 15:58 UTC, fedys requested changes
Thanks @aarohiprasad! Please see my code suggestions.

2025-03-06 15:58 UTC, fedys commented on app/bundles/PageBundle/Controller/PageController.php
> +            ) {
```suggestion
            if ($cancelled
                || ($valid && $this->isAnyOfButtonsClicked($form, ['save', 'save_draft', 'apply_draft', 'discard_draft']))
            ) {
```
Let's reduce the duplication and improve readability by extracting the logic into methods as follows.
```php
private function isButtonClicked(FormInterface $form, string $name): bool
{
    return $form->get('buttons')->has($name) && $this->getFormButton($form, ['buttons', $name])->isClicked();
}

/**
 * @param string[] $names
 */
private function isAnyOfButtonsClicked(FormInterface $form, array $names): bool
{
    foreach ($names as $name) {
        if ($this->isButtonClicked($form, $name)) {
            return true;
        }
    }

    return false;
}
```

2025-03-06 15:58 UTC, fedys commented on app/bundles/PageBundle/Controller/PageController.php
> +                    }
```suggestion
                    if ($pageConfig->isDraftEnabled() && !empty($entity->getId())) {
                        $this->dispatcher->dispatch(new PageEditSubmitEvent(
                            $existingPage,
                            $entity,
                            $this->isButtonClicked($form, 'save'),
                            $this->isButtonClicked($form, 'apply'),
                            $this->isButtonClicked($form, 'save_draft'),
                            $this->isButtonClicked($form, 'apply_draft'),
                            $this->isButtonClicked($form, 'discard_draft'),
                        ));
                    }
```
Let's reduce the duplication and improve readability here as well.

2025-03-06 15:58 UTC, fedys commented on app/bundles/PageBundle/Controller/PageController.php
> +            } elseif ($valid && $this->getFormButton($form, ['buttons', 'apply'])->isClicked()) {
```suggestion
            } elseif ($valid && $this->isButtonClicked($form, 'apply')) {
```

2025-03-07 14:08 UTC, escopecz commented
This will also have to be rebased to 7.x once https://github.com/mautic/mautic/pull/14690 is merged

2025-03-07 14:12 UTC, fedys submitted a review, later dismissed
Thanks @escopecz for addressing my code suggestions!

2025-03-07 15:25 UTC, escopecz approved these changes
I rebased to the 7.x branch as 6.x doesn't accept features anymore. @fedy please approve once again.

2025-03-07 16:10 UTC, fedys approved these changes

2025-03-10 12:43 UTC, escopecz commented
The docs here will be as simple as pointing from the landing page docs to the email draft feature as it behaves the same way. However, those docs aren't merged yet so we cannot link to them. I asked Ruth to help us get it to the docs:

https://github.com/mautic/user-documentation/pull/345

2025-03-13 07:12 UTC, dadarya0 commented
@RCheesley @escopecz documentation for this PR:-

https://github.com/mautic/user-documentation/pull/353

2025-03-13 08:28 UTC, merged