Ensure $address is not null before passing it to InvalidEmailException
mautic/mautic pull request #13976
Opened 2024-07-17 09:27 UTC by matbcvo

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13728  

## Description

This PR addresses an issue where the `EmailValidator` class could pass a null value to the `InvalidEmailException` constructor, causing a type error. The changes ensure that the email address passed to the `InvalidEmailException` is always a string.

When the `validate` method of the `EmailValidator` class receives a null value for the `$address` parameter, it leads to a type error in the `InvalidEmailException` constructor. The constructor expects a string but is given null instead, resulting in an error.

Change:
* Modified the `validate` method in `EmailValidator` to handle null or empty email addresses using the null coalescing operator (?:).

_Had to close previous PR as it was based on 5.0 instead of 5.1._

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new segment
4. Add new contact without e-mail address
5. Add newly created contact to new segment
6. Create new campaign, select contact source, add condition check ("has valid e-mail address")
7. Publish new campaign
8. Execute `mautic:campaign:rebuild`
9. Execute `mautic:campaign:trigger` (should not throw any errors)

2024-07-19 14:37 UTC, escopecz requested changes
Can we add
```php
if (!is_string($value)) {
    throw new UnexpectedValueException($value, 'string');
}
```
As suggested in the docs?:

https://symfony.com/doc/5.x/validation/custom_constraint.html#creating-the-validator-itself

With this change the validation message will be `" is invalid."` which doesn't make much sense.

Please cover the changes with tests as well.

2024-10-20 11:54 UTC, matbcvo commented
Hi @escopecz

Thank you for the feedback. I have reworked the validation logic as you suggested by adding the `is_string` check and throwing the `UnexpectedValueException` when the value is not a string.

In addition, I have written test to cover that change, specifically validating that `UnexpectedValueException` is thrown when non-string or null value is passed.

2024-10-20 14:40 UTC, matbcvo commented
I've added the necessary tests to cover the change in `CampaignConditionSubscriber`. Specifically, the tests ensure proper handling of null, invalid, and valid emails:

- `testOnCampaignTriggerConditionReturnsFalseForNullEmail`: Ensures null emails result in false.
- `testOnCampaignTriggerConditionReturnsFalseForInvalidEmail`: Ensures invalid emails result in false.
- `testOnCampaignTriggerConditionReturnsTrueForValidEmail`: Confirms valid emails result in true.

These tests should fully cover the scenarios related to email validation, as requested.

2024-10-21 10:46 UTC, escopecz submitted a review, later dismissed
I tested with this campaign:
![Screenshot 2024-10-21 at 12 45 50](https://github.com/user-attachments/assets/e2230b63-1933-43e9-9644-0b4bfd6f02ae)
And there were no errors and it added the "invalid" tag to the contact. All good 👍

2024-10-21 10:50 UTC, escopecz commented
@matbcvo can you please rebase on top of the 5.x branch and change the target branch of this PR to 5.x? There will be no more releases for 5.1.

2024-10-21 12:09 UTC, matbcvo commented
@escopecz done!

2024-10-21 15:05 UTC, escopecz approved these changes
Awesome, thanks!

2024-10-21 15:05 UTC, merged