Transactional emails
mautic/mautic pull request #14019
Opened 2024-07-29 13:06 UTC by escopecz

WIP

2024-08-27 15:46 UTC, andersonjeccel requested changes
First of all, thanks for the improvement!

**I have some important thoughts, have a look:**
Perhaps now we fall into the same issue you reported in my PRs recently: users urged all the time they want to select the feature

The functionality is perfect, just definitely needs to remove the confirmation screen for segment emails when activating the toggle

Another suggestion would be to rename the label... If you use only "Transactional email" (Yes/No), the label itself will aim to filter people that understands what the difference between marketing vs transactional means (but keep the tooltip, it's really useful!).

We're a marketing automation platform, it's perfectly acceptable to use marketer-specific terminology

"Send to unsubscribed contacts" can easier lead non-marketer people to just go wild and start crucificating the right from contacts to opt-out (I checked and see this pattern in other tools)

2024-08-27 15:59 UTC, ekkeguembel commented
@andersonjeccel I believe unambigous language would be a win
(as opposed to hiding behind terminology that may be "correct" in our sense but people can at best guess the implications  ; )
Thus... How about "**Force-send (ignore unsubscribe)**" ?

@escopecz are we looking at _any_ DNC here, or only at specific reasons, thus avoid sending to bounced emails?

2024-08-28 07:24 UTC, escopecz commented
Adding the last piece of not sending to hard-bounced contacts is blocked by https://github.com/mautic/mautic/pull/12275

2024-08-28 07:33 UTC, escopecz commented
@andersonjeccel 

> users urged all the time they want to select the feature. The functionality is perfect, just definitely needs to remove the confirmation screen for segment emails when activating the toggle

In this case it is important because if they don't understand the feature they will be breaking the law. So if it is a newly added user or someone who saw that warning a year ago and forgot. This must be present to avoid human error that can cost a lot of $$.

> If you use only "Transactional email" (Yes/No), the label itself will aim to filter people that understands what the difference between marketing vs transactional means

The new "Send to unsubscribed" switch is only part of the "transactional" email. With this feature you can send marketing emails to unsubscribed contacts. A truly transactional email will be sent from the campaign action when also the "Repeatable email" switch is set to Yes.

2024-08-28 07:38 UTC, escopecz commented
@ekkeguembel 

> How about "Force-send (ignore unsubscribe)" ?

We had several iterations of this label including this one. But with this you have a negative ("ignore") and asking Yes/No. This is hard to comprehend. That's why English doesn't like to use double negatives. And it is crucial in this feature so people aren't confused what Yes and No means. That's why we went with the positive label of "Send to unsubscribed contacts" which is very clear.

Thanks for asking about the bounces. I found another PR on our fork that should be part of this one and excludes hard bounces from this new switch. But it now [blocks](https://github.com/mautic/mautic/pull/14019#issuecomment-2314520435) this whole feature.

2024-08-28 11:39 UTC, andersonjeccel commented
@escopecz Totally makes sense, thanks for explaining!

2024-12-18 17:01 UTC, waldner commented
Any news here? What's missing for the merge to be completed?

2024-12-19 09:19 UTC, escopecz commented
@waldner It's blocked by https://github.com/mautic/mautic/pull/14019#issuecomment-2314520435

@kuzmany how fare are you with it?

2024-12-19 19:33 UTC, kuzmany commented
@escopecz I will assign me or somebody to fork it on on the beginning of 2025

2025-02-26 10:47 UTC, kuzmany commented
@escopecz Is there a specific part of the A/B testing that is blocked, or do you need the entire PR?

2025-02-26 10:51 UTC, escopecz commented
@kuzmany I don't remember as it's been a few months. But the A/B testing is blocking tens of other PRs form Acquia. The entire PR would be great!

2025-07-03 15:01 UTC, shinde-rahul commented on app/bundles/EmailBundle/Tests/Model/EmailModelFunctionalTest.php
> +        $this->useDefaultFrequencyRules = ' with data set "Default Frequency Rules"' === $this->getDataSetAsString(false);
Hi @escopecz,

I came across the `getDataSetAsString` method in the codebase but couldn’t locate its definition. I tried the following to find it:

```bash
git grep "function getDataSetAsString" $(git for-each-ref --format='%(refname)' refs/heads/)
```

However, I only found its usages via:

```bash
git grep "getDataSetAsString" $(git for-each-ref --format='%(refname)' refs/heads/)
```

Could you please help me with the definition?

Thanks!

2025-07-03 17:06 UTC, shinde-rahul commented on app/bundles/EmailBundle/Tests/Model/EmailModelFunctionalTest.php
> +        $this->useDefaultFrequencyRules = ' with data set "Default Frequency Rules"' === $this->getDataSetAsString(false);
The `getDataSetAsString` method is deprecated and has been removed. Found the fix `$this->useDefaultFrequencyRules = str_contains($this->nameWithDataSet(), 'with data set "Default Frequency Rules"');`

2025-07-07 10:40 UTC, shinde-rahul commented
@escopecz, I need some help understanding the mapping of code with the output for steps 6 to 9
```
6. Send email from campaign, "Include unsubscribed contacts" should work if yes then send email to all contacts including DNC
7. Create a campaign that uses the "Send Email" event.
8. Choose "Transactional" as your email type.
9. You should not get emails with an Unsubscribe link.
```

The Unsubscribe link is getting included. As the email body already contains the token.

2025-07-07 12:03 UTC, escopecz commented
@rahuld-dev this PR is WIP. I'm still waiting for the blocker to be resolved so I could get back to it. Please do not test. It doesn't work.

2025-07-07 12:18 UTC, rahuld-dev commented
> @rahuld-dev this PR is WIP. I'm still waiting for the blocker to be resolved so I could get back to it. Please do not test. It doesn't work.

@shinde-rahul

2025-07-07 13:28 UTC, escopecz commented
Apologies for both of you. Again...

2025-07-07 13:36 UTC, shinde-rahul commented
Hi @escopecz,

I’ve started porting this PR to 7.x in [#15154](https://github.com/mautic/mautic/pull/15154) — you can find the related discussion in [this Slack thread](https://mautic.slack.com/archives/CQMKV0RU1/p1747062559070079).

I’m pausing work on that PR for now. Could you advise on the next steps?

Thanks!

2025-07-07 15:06 UTC, escopecz commented
The next step is to get the blocking PR to get merged so I could finish this one.

2025-07-09 01:52 UTC, shinde-rahul commented
@escopecz, The PR https://github.com/mautic/mautic/pull/12275 was closed in August 2024. It seems like a dead end, at least for now. Meanwhile, I am reading #12275, and if necessary, I can offer a hand to help complete it and unblock this one.

2025-07-09 08:21 UTC, escopecz commented
@npracht promised to push it to the community. I still believe his team will deliver. This PR needs code from that PR.

2025-07-09 09:45 UTC, npracht commented
I think @kuzmany has made some progress on it.

2025-07-14 10:05 UTC, adiux commented
@npracht @kuzmany is there any progress on this?

2025-10-23 09:46 UTC, RCheesley commented
Hi @kuzmany @npracht is the PR coming over? If not we have an offer from @shinde-rahul to support and get the previous PR ready - either way we need to make progress with both the A/B testing and this feature, so it'd be good to have some clarity. Thanks!

2025-10-23 11:39 UTC, kuzmany commented
> Hi @kuzmany @npracht is the PR coming over? If not we have an offer from @shinde-rahul to support and get the previous PR ready - either way we need to make progress with both the A/B testing and this feature, so it'd be good to have some clarity. Thanks!

Add it to next round

2025-10-23 12:41 UTC, RCheesley commented
OK thanks, do you have a rough ETA for that so we can figure out when we're likely to get this one merged?

2025-11-06 21:53 UTC, rabiibrahimi commented
This is a very neat feature; however i think that the **email type** _should_ stay as previously named (**Transactional | Marketing**) most user will be confused if switch to _No | Yes_ and this might cost them money if they choose the wrong answer. the word **Transactional | Marketing** is very clear and visual and would make it easier to make a decision without margin of errors. 

I hope you will consider this :)

2025-11-07 09:33 UTC, adiux commented
@kuzmany any ETA? would love to see this in v7

2025-11-07 09:36 UTC, adiux commented
@rabiibrahimi thanks for your comment. While I agree that once you know what transactional and marketing emails are, it makes a lot of sense. 

But in this case we can have marketing emails that need to be sent out multiple times. E.g. we send newsletters with changing RSS content. So it is a repeatable marketing email.

2025-11-07 09:48 UTC, kuzmany commented
> @rabiibrahimi thanks for your comment. While I agree that once you know what transactional and marketing emails are, it makes a lot of sense.
> 
> But in this case we can have marketing emails that need to be sent out multiple times. E.g. we send newsletters with changing RSS content. So it is a repeatable marketing email.

In short  we have 

- marketing emails
- marketing emails repeatable
- transactional emails


Marketing email respect DNC unsubscribe
Transactional emails do not respect DNC unsubscribe

2025-11-07 09:51 UTC, kuzmany commented
> @kuzmany any ETA? would love to see this in v7

I will work on it from Monday, based on priorities

2025-11-07 10:37 UTC, rabiibrahimi commented
> @rabiibrahimi thanks for your comment. While I agree that once you know what transactional and marketing emails are, it makes a lot of sense.
> 
> But in this case we can have marketing emails that need to be sent out multiple times. E.g. we send newsletters with changing RSS content. So it is a repeatable marketing email.

Totally understand and i appreciate the new feature - it is very useful. My comments were just about names used - it could create confusion - a yes | no is not always a good way to describe features like this. I am sure there could be a better way to rename the email type without using ambiguous names.

2026-01-29 09:09 UTC, adiux commented
@rahuld-dev would you be able to take a look at the conflicts? Would love to see this finally merged.

2026-02-24 09:49 UTC, kuzmany commented
@escopecz @adiux https://github.com/mautic/mautic/pull/15897 It requires some adjustments and should be completed tomorrow with full explanations.

2026-03-03 12:05 UTC, kuzmany commented
@escopecz @adiux ready for tests https://github.com/mautic/mautic/pull/15897

2026-03-03 12:14 UTC, adiux commented
@rahuld-dev pleaes take a look

2026-03-26 15:51 UTC, escopecz commented
Closing in favore of https://github.com/mautic/mautic/pull/15995

2026-03-26 15:51 UTC, closed without merging