[UX] ProTip for switching card and table view
mautic/mautic pull request #14035
Opened 2024-08-01 18:41 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependencies:
- #13896 
- #13912 

This PR adds a template for ProTips that aim to provide extra information for users to get the most out of Mautic.

![image](https://github.com/user-attachments/assets/0f62c124-e9d9-4bee-9c28-77388930835f)

It's reusable and by default it accepts only a translation string for the tip, while icon and styles keep default for all.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts > Scroll down to the bottom and see

2024-08-09 07:57 UTC, abhisekmazumdar approved these changes
That good for user. Looks good to me.

2024-08-23 09:34 UTC, LordRembo approved these changes
The code looks good. Would be good to what changed, after rebase + merging the open dependent PR's.

2024-09-16 04:35 UTC, shinde-rahul requested changes
The code looks good overall, but there are just a couple of CS issues that need to be addressed. Great improvement!

2024-09-16 04:35 UTC, shinde-rahul commented on app/bundles/CoreBundle/Resources/views/Helper/protip.html.twig
> +        <span class="fw-b">{{'mautic.core.protip'|trans}}</span>
```suggestion
        <span class="fw-b">{{ 'mautic.core.protip'|trans }}</span>
```

2024-09-16 04:35 UTC, shinde-rahul commented on app/bundles/CoreBundle/Resources/views/Helper/protip.html.twig
> +        {{tip|trans|raw}}
```suggestion
        {{ tip|trans|raw }}
```

2024-09-16 11:52 UTC, andersonjeccel commented
@shinde-rahul Thanks for reviewing!

I requested to redo after commiting the changes

2024-09-22 04:53 UTC, shinde-rahul approved these changes
Code LGTM!!

Thanks @andersonjeccel!!

2024-09-28 17:02 UTC, Aleks0129 requested changes
1. Contacts after clicking "V" pro tip isn't visible in tile view.

<img width="1200" alt="Screenshot 2024-09-28 at 18 52 10" src="https://github.com/user-attachments/assets/184fe718-4734-4759-b8f2-8700e562400c">

2.Forms looks good.

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/597e5a29-9172-47e9-b6dd-651e5f3b53d4">

3.Tags good as well.

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/87d6749c-7385-4e70-a8c2-9ad07a72c47b">

4.Segments look good.

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/32da5ea7-4d2b-49cd-9551-c86406b99fa0">

5.Assets good.

<img width="1183" alt="Screenshot 2024-09-28 at 18 57 48" src="https://github.com/user-attachments/assets/f10865d2-b159-491b-8632-88ed95ae711a">

6.Points good.

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/76c581cc-b5bf-461a-a929-cb4051b47e25">

7.Triggers good.

<img width="1176" alt="image" src="https://github.com/user-attachments/assets/ae733f91-7957-42a6-85ed-9153830f5724">

8.Emails good.

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/02c0736e-0493-4c76-99bb-eaddb5d84311">

9.Pages good.

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/bedf7449-6521-42ac-8b8a-23dcc322e716">

10.Campaigns good.

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/c07d8b02-888b-4405-885d-34168c599009">

11.Reports good.

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/940e2668-ed91-4927-81a6-01a7c74cfe72">

2024-09-30 11:37 UTC, andersonjeccel commented
@abhisekmazumdar These e2e tests seem to be really unreliable and break easily... Would you like to fix the test?

2024-10-04 15:28 UTC, RCheesley commented
@andersonjeccel could you resolve the conflict please? Thanks!

2024-10-04 18:10 UTC, andersonjeccel commented
Solved!

2024-10-14 07:18 UTC, abhisekmazumdar commented
Working on fixing the test cases.

2024-10-14 11:29 UTC, abhisekmazumdar commented
Looks like all the tests are green now. Please let me know if it fails in the future.

2024-10-14 11:30 UTC, andersonjeccel commented
@abhisekmazumdar Thanks! 😄

2024-10-14 12:50 UTC, merged