[UX] Lead generation analysis for contacts chart
mautic/mautic pull request #14045
Opened 2024-08-06 15:08 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependencies:
- #14043 

This PR helps marketers to have Marketing Insights (MI) about lead generation at a glance, depending on the results and selected date range.

![image](https://github.com/user-attachments/assets/a225dd5b-0d29-4a6b-8649-73541f02e488)

![image](https://github.com/user-attachments/assets/86d76a1b-1bf6-4710-8e9c-46cd4a9b9a9f)

![image](https://github.com/user-attachments/assets/bd330723-ffb6-420f-8517-676cdea565f8)

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-08-06 22:35 UTC, andersonjeccel commented
Points for improvement:
- [ ] show high performance days only when we have more than 1
- [ ] hide message when there’s 0% change in lead generation
- [ ] Use a different footer message for Weekly insights 
- [ ] Consider adding a tooltip for each metric to explain how they are built (or move to documentation)
- [ ] improve the clarity of “average” in weekly insights
- [ ] how much relatable is to set a fixed range of 6 months for weekly analysis when periods are often affected by special events/holidays like Father’s Day?
- [ ] Consider moving weekly metrics to annual

2024-08-07 04:41 UTC, shinde-rahul approved these changes
UX++, thanks @andersonjeccel.

> Code changes LGTM!!!

I'll redo the review once PR is in active state.

2024-08-08 09:58 UTC, andersonjeccel commented
I need help to fix the test :/
@abhisekmazumdar 
@LordRembo

2024-08-09 11:31 UTC, abhisekmazumdar commented
I feel that after making these changes, most of the test cases will also pass. If not, I will be around.

2025-01-11 02:54 UTC, shinde-rahul requested changes
I added some suggestions. Please check the failing pipelines logs as well.

2025-01-11 02:54 UTC, shinde-rahul commented on app/bundles/LeadBundle/EventListener/DashboardSubscriber.php
> +                $chartData = $this->leadModel->getLeadsLineChartData(
I suggest breaking the long method into smaller methods; this will improve the DX and help with maintainability.

2025-01-11 02:54 UTC, shinde-rahul commented on app/bundles/LeadBundle/Resources/views/Widget/created_leads_in_time.html.twig
This needs some indentation.

2025-01-11 02:54 UTC, shinde-rahul commented on app/bundles/LeadBundle/Tests/EventListener/DashboardSubscriberTest.php
> +
`declare(strict_types=1);` is missing.

2025-01-11 02:54 UTC, shinde-rahul commented on app/bundles/LeadBundle/Tests/EventListener/DashboardSubscriberTest.php
> +    public function formatRange(\DateInterval $interval)
A return type is missing. Please check the PHPSTAN pipeline for more details.

2025-01-11 02:54 UTC, shinde-rahul commented on app/bundles/LeadBundle/Tests/EventListener/DashboardSubscriberTest.php
> +class DateHelperStub
We should have one class per file. Please move this to a separate file.

2025-01-17 08:10 UTC, abhisekmazumdar commented on app/bundles/LeadBundle/Tests/EventListener/DashboardSubscriberTest.php
> +            $this->dateHelper
The changes to $this->dateHelper will resolve this issue.

2025-01-17 08:10 UTC, abhisekmazumdar commented on app/bundles/LeadBundle/Tests/EventListener/DashboardSubscriberTest.php
> +class DateHelperStub
Should `DateHelperStub.php` be created under `Tests/Services` ?

I also see that `app/bundles/LeadBundle/Tests/Services/PeakInteractionTimerTest.php` contains two classes. I'm not familiar with the standards, but is it acceptable to have two classes in that file?

2025-01-17 08:13 UTC, abhisekmazumdar commented on app/bundles/LeadBundle/EventListener/DashboardSubscriber.php
> +                $chartData = $this->leadModel->getLeadsLineChartData(
Do you suggest converting all the changes from line 84 to 268 into smaller helper methods?

2025-02-18 16:52 UTC, RCheesley commented
It looks like we've got quite some code review feedback here, so I am going to move this back to the 6.0 Release Candidate milestone to give us more time to get it over the line.

2025-03-12 12:09 UTC, RCheesley commented
Let's get this rebased to 7.x and aim for the alpha release, end of April?

2025-03-27 17:38 UTC, RCheesley commented
Can we get this rebased and fix the conflicts? Thanks!

2025-03-27 22:53 UTC, andersonjeccel commented
@RCheesley Let me try again, I was stuck (help needed)

2025-03-28 11:49 UTC, RCheesley commented
Thanks @andersonjeccel I've updated the base branch to 7.x - did you still need some assistance with this one?

2025-03-28 11:50 UTC, andersonjeccel commented
@RCheesley I was able to fix the tests, all good now

2025-03-28 12:37 UTC, kuzmany approved these changes
I did test and it works, only I saw not rounded number and too many tuesdays (image bellow).
I would use LLM for kind of this reports, instead of write too much of code.

![image](https://github.com/user-attachments/assets/3a514d88-e9a8-4e52-b1a7-46e4c5e6b60d)

2025-05-06 18:33 UTC, andersonjeccel commented
@kuzmany How to reproduce what you're seeing?

Info like this would help:
- Contacts amount
- Screenshot of the chart

2025-05-16 17:24 UTC, closed without merging