Respect doesColumnSupportEmptyValue when building empty/notEmpty filtered queries
mautic/mautic pull request #14078
Opened 2024-08-25 13:07 UTC by cjavad

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | None 
| Related developer documentation PR URL | None 
| Issue(s) addressed                     | None 

## Description

Having segments being built with a filter that asserts "date is not empty" or "date is empty" throws a SQL Exception when performing a comparison between a date and an empty string. 

This only applies to this ComplexRelationValueFilterQueryBuilder.php not the newer BaseFilterQueryBuilder.php that invokes SegmentOperatorQuerySubscriber.php leading to inconsistent results between the two. 

This has only been identified and tested on 5.1, might apply to versions as low as 5.0. 

---
### 📋 Steps to test this PR:

1. Create a custom field using the "date" type on a contact
2. Create a segment that is built based on that field being empty
3. Run the "mautic:segments:update" command

Without this it errors out.

2024-08-27 10:11 UTC, RCheesley commented
Thanks so much for the PR @cjavad and welcome to the community!

I think the failed test was due to Codecov not being able to receive the uploaded report so I've just set that running again.

Would you mind rebasing this onto the 5.1 branch please? As we released 5.1 recently, the next patch release will come from that branch. Let us know if you need any help with doing that.

2024-08-27 10:11 UTC, RCheesley commented
@all-contributors please add @cjavad for code

2024-08-27 11:45 UTC, cjavad commented
Thank you @RCheesley. It should be correctly rebased to 5.1 now with some git magic. No additional checks or tests has been run yet though.

2024-08-27 13:28 UTC, RCheesley commented
Thanks for getting that done so quickly @cjavad 🚀

2024-08-27 14:56 UTC, cjavad commented
Digging deeper it seems this is a duplicate of https://github.com/mautic/mautic/pull/12862 opened almost a year ago :open_mouth: 

Although i prefer my own fix (hehe) there might be a reason for it not being merged earlier?

2024-08-28 09:04 UTC, RCheesley commented
@cjavad most likely a lack of testers (it's a huge challenge for us to find enough people to test and review, if you ever fancy helping check out [https://mau.tc/tester](https://mau.tc/tester)), and because at this time it has unresolved conflicts, however that PR does have automated test coverage which would be preferable. Could you write tests to cover this PR if we took it forward?

@escopecz @kuzmany any thoughts on which approach would be preferable?

2024-08-28 09:16 UTC, cjavad commented
I'll be more than happy to add some tests once applicable.

2024-09-05 10:38 UTC, shinde-rahul requested changes
@cjavad, Please add test cases which will help us with the example and help improve the code coverage.

2024-12-03 07:45 UTC, Bastian2718 approved these changes
Looks good to me! Even with DateTime and mautic:segment:update added my contact to the segment as expected

2024-12-03 08:33 UTC, escopecz commented
Hi @cjavad we cannot this PR as it has no automated test coverage. You can get inspiration of a similar segment filter test for example here: https://github.com/mautic/mautic/blob/5.x/app/bundles/LeadBundle/Tests/Command/UpdateLeadListCommandFunctionalTest.php#L27

2024-12-03 16:13 UTC, cjavad commented
Hi @escopecz i would have loved to have had the time to have added the test previously, but i probably won't be able to get this done for a couple of weeks at least as it is a low priority from our side. But i'll try to see if i can fit it in somewhere.

If anyone is depending on this getting fixed and shipped anyone is more than welcome to take over to get it done.

2026-06-08 18:22 UTC, andersonjeccel commented
Hey, I'm seeing this PR has been quiet for a while and the last update was in 2025, so it looks like it has been stalled for some time. We're doing a little cleanup in the queue so the team can focus on PRs that are still being actively worked on and are closer to merge. If this was not the right call, I'd be happy to see it reopened and updated.

2026-06-08 18:22 UTC, closed without merging

2026-06-08 18:25 UTC, cjavad commented
All good, no problem at all!

I believe this particular issue is still active/ongoing, but we still roll with a patch in production, and sadly do not have the resources to champion this PR at this time.

Happy to answer any questions any future reader might have here.