Remove Irrelevant Icons from Segment Filter List
mautic/mautic pull request #14083
Opened 2024-08-27 11:29 UTC by shinde-rahul

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This pull request addresses the user interface of the segment filter list by removing irrelevant icons. 

| Before                                 | After
| -------------------------------------- | ---
|                <img width="354" alt="1 - Before Filter" src="https://github.com/user-attachments/assets/73f64a07-dadf-4c74-87ca-bf8e79ae8674">                        | <img width="353" alt="3 - After filters" src="https://github.com/user-attachments/assets/5d6d4b84-59c5-4c72-b609-1e2e3028dfea">
| <img width="299" alt="2 - Before Filter widget" src="https://github.com/user-attachments/assets/d217c456-3f37-4824-95a3-fd510ac29b5e"> | <img width="319" alt="4 - After Filter widget" src="https://github.com/user-attachments/assets/54caf884-f4d1-4968-8da7-e1553a49a33e">

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Navigate to segment, and click on New
3. Go to the filters tab
4. Search for Contact Behavior and Actions. The section is not have the icon
5. Select one from the list, e.g., Asset Download; the added filter field should be without an icon.

2024-08-27 12:50 UTC, andersonjeccel requested changes
Wouldn't be better to define the right icons instead of removing?

It'll give Mautic an increased look of faulty/bugged interface if some have and others don't

2024-08-27 13:17 UTC, shinde-rahul commented
@andersonjeccel, Yes, I agree.
The changes were long drafted against the `4.x` branch. This PR is a cherry-picked version of the same.
I need your help with the following,
- While updating, I found that https://github.com/mautic/mautic/blob/2f4299c9ce83feafc42f8f6fcfe37f71e3c300fc/app/bundles/CoreBundle/Assets/css/libraries/builder.less is still referring to FontAwesome icons. I need help updating the same.
- What Icon should be used for **Contact Behavior and Actions**, something like `ri-exchange-line`? 
- And what will be the ideal default filter icon to use, could be `ri-filter-3-fill`?

2024-08-27 14:27 UTC, andersonjeccel commented
@shinde-rahul 

1. Do you mean that we need to add the Remix icons to this file? If yes, in fact it's already available in the libraries.less file, so any classes from remix used will work just fine without adding there

2 and 3. I would like to have a specific icon for each thing. For example, the "Clicked" action would use `ri-cursor-line`, but for "Visited" actions could be `ri-eye-line` _(I can create the list of associations)_

We probably can implement this using a sequence of Twig conditions to check the value attribute for each option on the list 
```
{% if value|e == 'address1' %}
{% set icon = ri-ICON_NAME %}
{% elseif ... %}
...
```
Not exactly a beautiful solution, but the last time I brought in this way, Patryk suggested an extension to define icons (check `app/bundles/CampaignBundle/Twig/Extension/CampaignEventIconExtension.php`)

I can create the complete list for `return match ($eventType) { }` if you create the base twig extension and push the changes to the PR like this example from the file I mentioned (but ofc adapted to what we're doing here):

```
<?php

declare(strict_types=1);

namespace Mautic\CampaignBundle\Twig\Extension;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

final class CampaignEventIconExtension extends AbstractExtension
{
    /**
     * @see Twig_Extension::getFunctions()
     */
    public function getFunctions(): array
    {
        return [
            new TwigFunction('getCampaignEventIcon', [$this, 'getCampaignEventIcon']),
        ];
    }

    public function getCampaignEventIcon(string $eventType): string
    {
        return match ($eventType) {

            //
            // SPACE FOR MY LIST HERE
            //

        };
    }
}
```

2024-08-27 19:00 UTC, kuzmany submitted a review, later dismissed
Seems good 👍

2024-08-28 07:30 UTC, shinde-rahul commented
@andersonjeccel, Thanks for the suggestions; I have added the twig function to get the class name. Please help me update them, thanks.

2024-08-28 10:00 UTC, shinde-rahul commented on app/bundles/LeadBundle/Twig/Extension/SegmentFilterExtension.php
> +        if ('' !== $icon) {
```suggestion
        if ($icon) {
```

2024-08-28 12:15 UTC, andersonjeccel commented on app/bundles/LeadBundle/Twig/Extension/SegmentFilterExtension.php
> +            default                   => '',
```suggestion
            // lead
            'address1'               => 'ri-home-2-line',
            'address2'               => 'ri-home-3-line',
            'attribution'            => 'ri-cash-line',
            'attribution_date'       => 'ri-calendar-event-line',
            'dnc_bounced'            => 'ri-mail-close-line',
            'dnc_bounced_sms'        => 'chat-delete-line',
            'campaign'               => 'ri-megaphone-line',
            'city'                   => 'ri-building-2-line',
            'country'                => 'ri-earth-line',
            'date_added'             => 'ri-calendar-check-line',
            'date_identified'        => 'ri-calendar-todo-line',
            'last_active'            => 'ri-time-line',
            'device_brand'           => 'ri-smartphone-line',
            'device_model'           => 'ri-device-line',
            'device_os'              => 'ri-window-2-line',
            'device_type'            => 'ri-computer-line',
            'email'                  => 'ri-mail-line',
            'generated_email_domain' => 'ri-at-line',
            'facebook'               => 'ri-facebook-box-line',
            'fax'                    => 'ri-printer-line',
            'firstname'              => 'ri-user-line',
            'foursquare'             => 'ri-map-pin-user-line',
            'instagram'              => 'ri-instagram-line',
            'lastname'               => 'ri-user-2-line',
            'mobile'                 => 'ri-smartphone-line',
            'date_modified'          => 'ri-calendar-event-line',
            'owner_id'               => 'ri-user-star-line',
            'phone'                  => 'ri-phone-line',
            'points'                 => 'ri-coins-line',
            'position'               => 'ri-briefcase-4-line',
            'preferred_locale'       => 'ri-translate-2',
            'timezone'               => 'ri-time-zone-line',
            'company'                => 'ri-building-4-line',
            'leadlist'               => 'ri-list-check-2',
            'skype'                  => 'ri-skype-line',
            'stage'                  => 'ri-barricade-line',
            'state'                  => 'ri-map-pin-2-line',
            'globalcategory'         => 'ri-folder-2-line',
            'tags'                   => 'ri-hashtag',
            'title'                  => 'ri-user-star-line',
            'twitter'                => 'ri-twitter-x-line',
            'utm_campaign'           => 'ri-bookmark-2-line',
            'utm_content'            => 'ri-file-text-line',
            'utm_medium'             => 'ri-share-line',
            'utm_source'             => 'ri-link',
            'utm_term'               => 'ri-hashtag',
            'dnc_unsubscribed'       => 'ri-forbid-2-line',
            'dnc_unsubscribed_sms'   => 'ri-forbid-2-line',
            'dnc_manual_email'       => 'ri-mail-forbid-line',
            'dnc_manual_sms'         => 'ri-chat-off-line',
            'website'                => 'ri-global-line',
            'zipcode'                => 'ri-mail-send-line',
            'linkedin'               => 'ri-linkedin-box-line',

            // company
            'companyaddress1'            => 'ri-building-line',
            'companyaddress2'            => 'ri-building-2-line',
            'companyannual_revenue'      => 'ri-money-dollar-circle-line',
            'companycity'                => 'ri-building-4-line',
            'companyemail'               => 'ri-mail-line',
            'companyname'                => 'ri-building-3-line',
            'companycountry'             => 'ri-global-line',
            'companydescription'         => 'ri-file-text-line',
            'companyfax'                 => 'ri-printer-line',
            'companyindustry'            => 'ri-briefcase-4-line',
            'companynumber_of_employees' => 'ri-team-line',
            'companyphone'               => 'ri-phone-line',
            'companystate'               => 'ri-map-pin-2-line',
            'companywebsite'             => 'ri-global-line',
            'companyzipcode'             => 'ri-mail-send-line',

            // behaviors
            'redirect_id'             => 'ri-cursor-line',
            'email_id'                => 'ri-cursor-line',
            'email_clicked_link_date' => 'ri-cursor-line',
            'sms_clicked_link'        => 'ri-cursor-line',
            'sms_clicked_link_date'   => 'ri-cursor-line',
            'lead_asset_download'     => 'ri-download-2-line',
            'sessions'                => 'ri-timer-line',
            'notification'            => 'ri-notification-3-line',
            'lead_email_received'     => 'ri-mail-open-line ',
            'lead_email_read_date'    => 'ri-mail-open-line',
            'lead_email_read_count'   => 'ri-mail-open-line',
            'lead_email_sent_date'    => 'ri-send-plane-2-line',
            'hit_url'                 => 'ri-external-link-line',
            'page_id'                 => 'ri-external-link-line',
            'hit_url_date'            => 'ri-external-link-line',
            'hit_url_count'           => 'ri-external-link-line',
            'referer'                 => 'ri-external-link-line',
            'source'                  => 'ri-external-link-line',
            'source_id'               => 'ri-external-link-line',
            'url_title'               => 'ri-external-link-line',
            'lead_email_sent'         => 'ri-mail-send-line',
            default                   => 'ri-shapes-line',
```

2024-08-28 12:15 UTC, andersonjeccel commented on app/bundles/LeadBundle/Twig/Extension/SegmentFilterExtension.php
> +            default                   => '',
These seem to be good, feel free to modify

2024-08-28 16:05 UTC, andersonjeccel approved these changes
Nice!

2024-08-29 06:10 UTC, shinde-rahul commented on app/bundles/LeadBundle/Tests/Controller/AjaxControllerFunctionalTest.php
> +     * @return iterable<string, array{int, string}>
```suggestion
     * @return iterable<string, array<int, string>>
```

2024-08-29 09:16 UTC, escopecz commented
I understand the intention of this change. The behavior filters were showing the user icon which is confusing. But I think this missed the idea behind the icon meaning in this place. It shows what *object* the filter belongs to. Whether a contact or a company. So if a user have a filter on a City field, the icon shows whether it is a company city field or a contact city field. This change is adding a different icon to every filter which may look nice, but is missing the point.

This PR is also making a hard-coded list of which icon belong to which field/filter. It doesn't think about users creating new custom fields or plugins adding more filters. If this should be implemented, it should hook into the existing events that are dispatched when the filters are being generated so every plugin can add its own icon. And perhaps every custom field should have a selection of an icon.

But again, that is not the point of why the icon is there.

2024-08-29 11:31 UTC, andersonjeccel commented
@escopecz if we follow what you say, we must keep the contact icon for those behaviors to keep consistent as they’re related to contact behavior 

the solution is basically to close this PR

2024-08-29 11:49 UTC, escopecz commented
We can add another icon for behaviors if that's what we want to do, but it would be way simpler than what is in this PR. I would be against merging the PR as is.

2024-08-29 13:00 UTC, shinde-rahul commented
Another suggestion,
What if we add an icon to make aware of the field origin, 
<img width="423" alt="Screenshot 2024-08-29 at 6 27 02 PM" src="https://github.com/user-attachments/assets/c40351b9-b7ae-48ff-b2ea-ae034aa54141">
This would needs styling.

Similar to notes for contact
<img width="247" alt="Screenshot 2024-08-29 at 6 27 20 PM" src="https://github.com/user-attachments/assets/610aa6dc-deb3-4b9d-8300-c69f6ae43d9d">

What do you think?

2024-08-29 13:19 UTC, escopecz commented
@shinde-rahul sure, that would work. But still the definition of where the icons can be configured must be updated so it's extensible at least. There are several events that are generating the segment filters so it should be added there. In my eyes there are more pressing issues on Mautic's backlog. But of course I won't block it if done right.

2024-08-29 16:43 UTC, andersonjeccel commented
@shinde-rahul Tell me if you need my input for something

2024-08-30 03:57 UTC, shinde-rahul commented
@escopecz, I'm working on clearing my long pending PR, so this was second on the list. Once this personal backlog gets cleared, I'll take up others.

2024-08-30 07:46 UTC, escopecz commented
@shinde-rahul I apologise if my comment sounded harsh. I really appreciate anyone making any tiny improvement to this project. Let us know where you'd like to move this PR.

2024-08-30 11:16 UTC, shinde-rahul commented
@escopecz, No worries! I didn't take it negatively at all, and there's no reason to apologize. I'm happy to contribute; I appreciate the input.

2024-08-30 14:59 UTC, shinde-rahul commented on app/bundles/LeadBundle/Resources/views/FormTheme/Filter/_leadlist_filters_entry_widget.html.twig
> +            <div class="col-xs-2 col-sm-1 ai-center d-flex">
@andersonjeccel, please help me style this.
<img width="1117" alt="Screenshot 2024-08-30 at 8 28 33 PM" src="https://github.com/user-attachments/assets/3ceceaeb-357c-4b4f-b2bd-c7e523ee73fb">

Thanks

2024-08-30 15:15 UTC, shinde-rahul commented
@escopecz, I have updated the `\Mautic\LeadBundle\EventListener\FilterOperatorSubscriber` for including `'iconClass'` to the choices configuration. If this is not set, then it won't have any icon.

The following is an example subscriber (only listing),
```php
<?php

declare(strict_types=1);

namespace MauticPlugin\HelloWorldBundle\EventListener;

use Mautic\LeadBundle\Event\LeadListFiltersChoicesEvent;
use Mautic\LeadBundle\LeadEvents;
use Mautic\LeadBundle\Segment\OperatorOptions;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class ExampleSegmentFiltersSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [LeadEvents::LIST_FILTERS_CHOICES_ON_GENERATE => 'onGenerateSegmentFilters'];
    }

    public function onGenerateSegmentFilters(LeadListFiltersChoicesEvent $event)
    {
        $event->addChoice(
            'example-filters',
            'first',
            [
                'label'      => 'Example filters One',
                'properties' => ['type' => 'text'],
                'operators'  => [OperatorOptions::EQUAL_TO],
                'object'     => 'example-filters',
                'iconClass'  => 'ri-bug-2-fill',
            ]
        );

        $event->addChoice(
            'example-filters',
            'second',
            [
                'label'      => 'Example filters Two',
                'properties' => ['type' => 'text'],
                'operators'  => [OperatorOptions::EQUAL_TO],
                'object'     => 'example-filters',
            ]
        );
    }
}
```

2024-09-02 09:24 UTC, escopecz commented
I'm fine with this as it is extensible. But please fix the failing CI checks

2024-09-03 13:26 UTC, shinde-rahul commented
After discussing with @andersonjeccel, we have added an object name instead of an icon. Please see the following, 
<img width="471" alt="5 - After Filter widget" src="https://github.com/user-attachments/assets/de47dc5c-5237-4bc4-a9e6-9035f24a64e7">

2024-09-03 14:51 UTC, escopecz commented
1. I'd prefer the icons and perhaps add tooltips on them describing what they mean. 
2. But I leave this decision on the UI/UX team. I'd definitely rename "Lead" to "Contact" as that's what we use elsewhere in the UI.
3. If no icons, then I think it would make more sense to have "Company City" more than "City (Company)"

2024-09-03 16:05 UTC, andersonjeccel commented
Perhaps the main issue is that it's retrieving the object name (non-translatable)

@shinde-rahul  Could we assign to translation files?

2024-09-10 07:59 UTC, shinde-rahul commented
@andersonjeccel @escopecz, I have updated the label; the translation key is defined as `mautic.lead_list.filter.field.label="<em>%object%</em>: %field%"`.

Please see the screenshot for the same,
<img width="232" alt="Screenshot 2024-09-10 at 1 28 44 PM" src="https://github.com/user-attachments/assets/f7ba86e2-124c-4bd9-91bb-d972bf3b0260">

2024-10-03 14:54 UTC, Aleks0129 requested changes
Segment filter text height looks a bit inaccurate.

<img width="195" alt="Screenshot 2024-10-03 at 16 50 55" src="https://github.com/user-attachments/assets/45218aaa-d25d-4599-a36d-bcfd4f2b387a">

<img width="194" alt="Screenshot 2024-10-03 at 16 51 03" src="https://github.com/user-attachments/assets/bbc81ede-c56c-434e-9e1b-28878f8e5da0">

2025-02-18 02:10 UTC, shinde-rahul commented
> Segment filter text height looks a bit inaccurate.
> 
> <img alt="Screenshot 2024-10-03 at 16 50 55" width="195" src="https://private-user-images.githubusercontent.com/182695073/373303141-45218aaa-d25d-4599-a36d-bcfd4f2b387a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4MDI5MzAsIm5iZiI6MTczOTgwMjYzMCwicGF0aCI6Ii8xODI2OTUwNzMvMzczMzAzMTQxLTQ1MjE4YWFhLWQyNWQtNDU5OS1hMzZkLWJjZmQ0ZjJiMzg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxN1QxNDMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTVmYzVjNDY2NGIwOGMwYzA5NjEwZjE2NjY3NDFjMWM4Njc4ZTk5MmQ0YjIwZWUyMjE5NzQ5ZTkyMzEwODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FkrgAz9bKCfq68HZstSqOzTkhZPh1Bj9tM6Ri2uAO-A"> <img alt="Screenshot 2024-10-03 at 16 51 03" width="194" src="https://private-user-images.githubusercontent.com/182695073/373303187-bbc81ede-c56c-434e-9e1b-28878f8e5da0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4MDI5MzAsIm5iZiI6MTczOTgwMjYzMCwicGF0aCI6Ii8xODI2OTUwNzMvMzczMzAzMTg3LWJiYzgxZWRlLWM1NmMtNDM0ZS05ZTFiLTI4ODc4ZjhlNWRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxN1QxNDMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDRhMmNmOWMxM2ZiNWE4NmY2OWZiNTM4NzJmMjQyODVhOTU5NDE4NWRiZmRhYTFkMDNjYzZhMmYyNDg2YjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ngs4KOwWayMOLg-bn7nRafBqADkcCcee0KQWXFD7vSE">

@Aleks0129, please help me with the browser and viewport details so I can reproduce it.

2025-02-18 04:40 UTC, shinde-rahul commented
@andersonjeccel and @escopecz, this is ready for review.

2025-02-20 09:14 UTC, Bastian2718 commented
Looks good to me

2025-03-25 14:40 UTC, imaabasiee reviewed
https://www.loom.com/share/e0fec3c1a5224370bc1df508df076dc4?sid=4a524f07-f626-459b-97b7-67f959ffddcb
Step 4 says Contact Behaviours and Actions section should not have icons but some items in the list do have icons.

2025-04-25 05:22 UTC, shinde-rahul commented
Should I consider it a feature rather than a bug and rebase it to 7.x?
@escopecz, @andersonjeccel, any thoughts?

2025-04-29 10:56 UTC, escopecz commented
@shinde-rahul yes please

2025-06-02 05:01 UTC, shinde-rahul commented
I have created a cherry-picked version of this PR here https://github.com/mautic/mautic/pull/15064.

2025-06-02 05:21 UTC, shinde-rahul commented
@imaabasiee @escopecz @Aleks0129 @andersonjeccel @kuzmany @Bastian2718 Please review this for 7.x https://github.com/mautic/mautic/pull/15064.

2025-06-02 05:21 UTC, closed without merging