[UI] Marketplace details header
mautic/mautic pull request #14199
Opened 2024-10-14 16:44 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR brings life to plugin details.

- Adds a bigger header
- The header changes its color dynamically based on the plugin name
- All generated colors have enough contrast against the text on top
- It adapts its lightness depending on your theme (light or dark)
- Features a handcrafted background, using icons related to marketing

![image](https://github.com/user-attachments/assets/a4de2d60-6c46-4d7b-9f89-ed6f040913cd)

![image](https://github.com/user-attachments/assets/f7653801-80db-489d-8f83-bd19364d6af9)

![image](https://github.com/user-attachments/assets/808a378e-7f3b-4661-a711-170cbfcbc91f)

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the admin menu
3. Open Marketplace
4. Open any plugins

2025-01-17 04:37 UTC, shinde-rahul reviewed
There is a conflict; please resolve it.

2025-02-18 17:02 UTC, RCheesley requested changes
Love these changes, I just wondered why we've got a duplicated button, perhaps one isn't needed?

![Mautic-02-18-2025_05_00_PM (1)](https://github.com/user-attachments/assets/346cb2fb-1082-4acc-88e0-86e3dc9073c5)
![Mautic-02-18-2025_05_00_PM](https://github.com/user-attachments/assets/a0ff455e-250a-45ee-9fa0-155bf6cb4c3d)

Other than that, all working as expected! 🚀

2025-02-21 13:39 UTC, RCheesley commented
@andersonjeccel can you address this feedback?

2025-02-21 18:51 UTC, RCheesley approved these changes
Thanks for fixing the duplicated button! GTG! 🚀

2025-02-21 19:17 UTC, matbcvo approved these changes
The code changes look good to me. I have tested the PR, and it works as expected.

However, one feature I wish this marketplace had is the ability to display README.md content in a separate tab. For example, my package includes important instructions in the README.md file, such as setup steps needed to use the package. This content is already available in the repository and on the Packagist website, but it would be nice to have it in the marketplace as well.

2025-02-24 10:14 UTC, merged