Add Truly Personal to composer.json
mautic/mautic pull request #14202
Opened 2024-10-16 09:47 UTC by RCheesley

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

## Description

This PR adds the new Simply Personal theme to the app/composer.json file so that it is picked up for composer-based installations - it's a rebase of #10134 for the 5.1 branch (sorry it took so long 😊 )

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check that the Simply Personal theme is installed and available to use.

2024-10-16 11:23 UTC, shinde-rahul approved these changes
Code changes look good to me.

2024-10-16 12:18 UTC, shinde-rahul requested changes

2024-10-16 12:18 UTC, shinde-rahul commented on composer.lock
We should exclude this lock file as the theme `trulypersonal` is already part of the code.

2024-12-01 01:27 UTC, matbcvo commented
This PR can be closed because the theme has already been added to the `composer.json` file through PR #14301.

https://github.com/mautic/mautic/blob/b121176632d980cbd388c14d51ed8dbe8bb02aa4/composer.json#L100

2024-12-02 13:40 UTC, escopecz commented
@RCheesley based on the learnings in https://github.com/mautic/mautic/pull/14301 this PR should just update the composer.lock hash, not adding the theme in. Can you please update composer.lock with just the hash?

2024-12-02 13:43 UTC, RCheesley commented
@escopecz this PR can be closed now that it's added: https://github.com/mautic/mautic/blob/5.x/composer.json#L100

2024-12-02 13:43 UTC, closed without merging