Removing deprecated parts from the PageBundle
mautic/mautic pull request #14244
Opened 2024-11-05 16:44 UTC by JonasLudwig1998

This PR removes some of the deprecated parts in the PageBundle. It's based on the https://github.com/mautic/mautic/pull/14219 and should be merged after this one is merged

2024-12-20 11:35 UTC, escopecz commented
@JonasLudwig1998 can you please rebase/merge and resolve the conflits? M6-alpha will be released in January so we should focus on refactoring PRs like this one.

2025-01-02 09:34 UTC, JonasLudwig1998 commented
@escopecz Done

2025-01-06 15:49 UTC, escopecz requested changes
Just one small thing and then we can merge. I confirmed that none of the deleted classes/methods is used in the codebase.

2025-01-06 15:49 UTC, escopecz commented on UPGRADE-6.0.md
> +- `getNewVsReturningPieChartData` was removed from `Mautic\PageBundle\Model\PageModel`. Use `getUniqueVsReturningPieChartData()` instead.
Please move these into the "BC breaks in the code" section

2025-01-08 09:21 UTC, escopecz approved these changes
Thank you! 👍

2025-01-08 09:22 UTC, escopecz reviewed
Wait, is the change in `.ddev/commands/host/phpmyadmin` intentioinal? Perhaps we could add it to `.gitignore` instead? It's bothering me too. It's being generated by tests or something.

2025-01-08 09:27 UTC, JonasLudwig1998 commented
I like the idea. Should I change the .gitignore directly within this PR?

2025-01-08 09:29 UTC, escopecz commented
Yep, let's do it here. I'll merge it right after.

2025-01-08 09:42 UTC, JonasLudwig1998 commented
Not sure how to get rid of the changes in the .ddev/commands/host/phpmyadmin file. Any idea?

2025-01-08 13:54 UTC, escopecz commented
I chatGPTed it:
***************************
When you add a file to `.gitignore`, it will prevent future changes to that file from being tracked. However, if the file is already being tracked by Git (i.e., it's in the repository's history), `.gitignore` alone won't stop it from showing up in your PR if it's modified. That's likely why you're still seeing changes to the file permissions (`100644 → 100755`) in your pull request.

Here's how to resolve the issue:

1. **Remove the file from the Git index** but keep it in your working directory:

   ```bash
   git rm --cached .ddev/commands/host/phpmyadmin
   ```

   This command removes the file from the Git index (i.e., it tells Git to stop tracking it) but leaves the file intact in your working directory.

2. **Commit the change**:

   ```bash
   git commit -m "Stop tracking the phpmyadmin file"
   ```

3. **Push the changes to your branch**:

   ```bash
   git push origin <your-branch-name>
   ```

After doing this, the file should no longer show up in your PR because it's no longer tracked by Git, and your `.gitignore` entry will prevent it from being tracked in the future.

**Note**: Make sure any necessary backup of the file is done if it’s crucial, as removing it from the Git index will mean it won't be included in future commits, even if altered.
***************************
The file is already there but with different permissions. I'm wondering whether we shouldn't just let the permissions be changed.

2025-01-08 14:13 UTC, JonasLudwig1998 commented
Would be fine with me. Is it necessary to put the file in .gitignore then. I'm currently struggling with the problem that the file is now deleted. I'll make sure that everything works properly tomorrow

2025-01-09 08:26 UTC, JonasLudwig1998 commented
@escopecz Now I changed it back as it was. Is it fine this way, or should I change the permissions for the phpmyadmin file as they were before?

2025-01-09 09:31 UTC, escopecz approved these changes
I think the permission change is fine. It's in ddev which is not meant for production so it does not matter as much as if it was meant for production. The previous comment on that files is https://github.com/mautic/mautic/commit/4e211eb327b9dbf72844bc6d4bbe4bbf4004f6a9 which does not suggest any need for stricter permission. It shows up as a change all the time when developing so it's annoying. I think it's good to go 👍

2025-01-09 09:31 UTC, merged