[UI] Toolbar batch actions
mautic/mautic pull request #14306
Opened 2024-11-28 20:27 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR moves list bulk actions to the toolbar.

https://github.com/user-attachments/assets/21dcf457-97c7-4bf7-9d19-73ee1d5c1b81

Also:
- adds a counter for selected items
- makes export and delete buttons always visible
- creates a new location in php for the buttons that are always visible in the batch actions toolbar
- adds a LESS file for the toolbar styles
- wipe some CSS workarounds used for the old structure in page lists
- maintains compatibility with the tableheader template, so anything using it will keep working

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts
3. Create a contact
4. Create another
5. Back to the list
6. Click on the checkbox from the header to select all
7. See the toolbar
8. Repeat for other pages (companies, segments etc)

2024-11-28 21:06 UTC, andersonjeccel commented
@abhisekmazumdar The failing E2E are real, I made some changes to the structure (moving the dropdown around)

2024-11-28 21:18 UTC, andersonjeccel commented
@abhisekmazumdar Hm, it seems like the PHPUnit test is trying to find the export button (that was also moved)

If you find something actually wrong with the code, ping me to have a look

2024-11-29 08:28 UTC, laurielim requested changes
The toolbar stays visible when you change page but no item is selected:
![image](https://github.com/user-attachments/assets/00ca7fc0-e921-48f1-b9d2-61de1db645ff)

2024-11-29 10:18 UTC, andersonjeccel commented
@laurielim How to reproduce?

I tried this way:

https://github.com/user-attachments/assets/63a1baa2-5779-4f12-8136-ec1f66ec4b61

2024-11-29 10:44 UTC, laurielim commented
@andersonjeccel sorry I was unclear, I meant pagination so stay on contact page, scroll down to the pagination and go to page 2 (assuming you have more contacts than what is shown in the table)

2024-11-29 11:35 UTC, andersonjeccel commented
@laurielim I think that attaching the toolbar reset to general ajax calls is a reliable way to avoid buggy behavior. this must also make the toolbar get automatically dismissed when interacting with the bulk options when relevant

2024-11-29 11:59 UTC, andersonjeccel commented
I had to revert and follow another approach as functionalities like "Change Stages" wouldn't work because checkboxes were dismissed by the ajax call that loaded the modal for similar features

2024-11-29 14:19 UTC, laurielim approved these changes
Reviewed code and nothing unusual stands out. Tested and toolbar gets dismissed when changing pagination now, and works as described.

2024-11-29 16:24 UTC, laurielim requested changes

2024-11-29 16:24 UTC, laurielim commented on app/bundles/CoreBundle/Assets/js/libraries/8a.adminre.js
> +                    $(".toolbar--batch-summary__count").text(checkedBoxes + " items selected");
Just realised that this string isn't translatable the way it is.

2024-12-03 04:17 UTC, shinde-rahul requested changes

2024-12-03 04:17 UTC, shinde-rahul commented on app/bundles/CoreBundle/Assets/js/libraries/8a.adminre.js
> +                    $(".toolbar--batch-summary__count").text(checkedBoxes + " items selected");
Good catch.

2024-12-03 04:17 UTC, shinde-rahul commented on app/bundles/CoreBundle/Resources/views/Helper/list_toolbar.html.twig
> +            <!-- <span class="toolbar--batch-summary__divider">|</span> -->
```suggestion
```

2024-12-03 04:17 UTC, shinde-rahul commented on app/bundles/CoreBundle/Resources/views/Helper/toolbar_bulk_actions.html.twig
> +{% endif %}
```suggestion
{% endif %}

```

2024-12-03 08:11 UTC, laurielim commented on app/bundles/CoreBundle/Resources/views/Helper/list_toolbar.html.twig
> +            <!-- <span class="toolbar--batch-summary__divider">|</span> -->
I created a branch from this one and using this element as I am implementing the Select all feature

2024-12-04 12:06 UTC, andersonjeccel commented on app/bundles/CoreBundle/Assets/js/libraries/8a.adminre.js
> +                    $(".toolbar--batch-summary__count").text(checkedBoxes + " items selected");
I’m often forgetting to remove debug code from my PRs (as the toolbar in the hidden state has translatable text generated by Twig), that’s a point of improvement for me

thank you for flagging it, I’ll seek for a way to avoid again

2024-12-09 13:54 UTC, andersonjeccel commented on app/bundles/CoreBundle/Assets/js/libraries/8a.adminre.js
> +                    $(".toolbar--batch-summary__count").text(checkedBoxes + " items selected");
this was solved

2024-12-16 13:25 UTC, andersonjeccel commented
@matbcvo Hey, would you like to review this one?

If you got some minutes, a help to fix the test would be appreciated :)

---

@laurielim I rebased the PR to target 6.0

2024-12-16 18:34 UTC, laurielim commented
I rebased my working branch and looks like after deleteAction and batchDeleteAction for contacts and companies (that's what I tested) the panel header disappears.
![image](https://github.com/user-attachments/assets/fec60277-c25f-48e1-8d36-38f88f8c549b)

2024-12-17 12:29 UTC, andersonjeccel commented
@laurielim From what you said, I got that some resources still have the batch actions within the table header instead of the toolbar for batch actions

Created this list after checking:

- Contacts OK
- Companies OK
- Segments OK
- Assets OK
- Forms OK
- Landing Pages OK
- Dynamic Content OK
- Campaigns OK
- Marketing Messages OK
- Emails MISSING
- Web Notifications OK
- Mobile Notifications OK
- Focus Items OK
- Manage Actions OK
- Manage Triggers OK
- Manage Groups OK
- Stages MISSING
- Reports OK
- Tags OK
- Custom fields OK
- Users MISSING
- Roles MISSING
- Categories MISSING
- Themes OK
- Webhooks MISSING

I'll work on a fix

Thank you for flagging this issue

2024-12-17 19:00 UTC, andersonjeccel commented
@laurielim yeah, done

2024-12-27 09:35 UTC, laurielim approved these changes
Tested the latest changes, I think this is good to go now.

2025-01-08 09:31 UTC, abhisekmazumdar commented
I don't understand the error for e2e now. I fixed a few of them, but these two are not easy to resolve. Can someone provide some input here?

2025-01-15 09:06 UTC, abhisekmazumdar commented
I tried every possible way to make the search clear button visible for the failed e2e test `ContactManagementCest.php:batchAddAndRemoveSegment`, but I couldn't find what is making it red. :-(

2025-01-15 10:18 UTC, andersonjeccel commented
@abhisekmazumdar what about adding an extra step to check then uncheck the “select all” checkbox?

this would make the toolbar disappear/reset

then maybe add a wait for the button to appear before trying to click

2025-01-15 12:16 UTC, andersonjeccel commented
@abhisekmazumdar It worked!

Do you know why the PHPUnit test might be failing?

2025-01-15 12:21 UTC, abhisekmazumdar commented
So the e2e issue was silly me problem. 😅

But yes, I don't know what happened with PHPUnit.

2025-01-15 12:23 UTC, andersonjeccel commented
@abhisekmazumdar Oh no it's fine, thank you for fixing it
I could have suggested a solution before, sorry for that

2025-01-15 12:24 UTC, andersonjeccel commented
Let's see if updating the branch makes the test suddenly start working

2025-01-15 12:46 UTC, andersonjeccel commented
@abhisekmazumdar Ok, still there

2025-01-15 13:13 UTC, matbcvo commented
Ignore this failing PHPUnit test for now. It’s unrelated to this PR and occurs with other PRs as well.

2025-01-15 14:14 UTC, matbcvo requested changes

2025-01-15 14:14 UTC, matbcvo commented on tests/acceptance/ContactManagementCest.php
> +        $I->wait(1);
It's better to avoid using the `wait` method. Either remove it or replace it with a `waitForElement*` method, such as:
```php
$I->waitForElementNotVisible(ContactPage::$clearAllContactsSelection);
```

2025-01-15 14:14 UTC, matbcvo commented on tests/acceptance/ContactManagementCest.php
> +        $I->wait(1);
Same here, previous comment

2025-01-16 08:07 UTC, abhisekmazumdar commented on tests/acceptance/ContactManagementCest.php
> +        $I->wait(1);
Yes, I have completely removed the wait from the specified section of the code. Thank you for your input.

2025-01-16 15:37 UTC, andersonjeccel commented
@matbcvo Hm, should the test keep failing even when retriggering it?

I'm trying to understand if there's something to do

2025-01-16 15:45 UTC, matbcvo commented
Need to figure out what broke it. The PHPUnit tests began failing after PR #14372 was merged into the 6.x branch. It affects this and other PRs targeting the 6.x branch.

This issue is unrelated to this PR. This PR can be merged into the 6.x branch, as the PHPUnit tests passed earlier.

2025-01-16 18:07 UTC, andersonjeccel commented
Got it, thank you for checking!

2025-01-17 16:51 UTC, andersonjeccel commented
Updating the branch seemed to solve that PHPUnit issue, but now there are new (different) ones

2025-01-20 13:30 UTC, merged