fix: upcoming emails layout
mautic/mautic pull request #14337
Opened 2024-12-05 19:42 UTC by andersonjeccel

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14336 

## Description

fixes mentioned issue

| Before                                 | After
| -------------------------------------- | ---
|    ![image](https://github.com/user-attachments/assets/c7ec5e86-b69a-49ce-83b7-b76779b7fbcb)                                    | ![image](https://github.com/user-attachments/assets/dae24a3f-8799-4221-b28b-65b684a251d9)

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a few contacts (depending on how many elements will appear in the "Upcoming Emails" list).
3. Create a segment.
4. Create a campaign using this segment as the source.
5. Add a "Send email" action to the campaign, scheduling it for the next day (using a relative time period of +1 day).
6. Run the following commands:

```
bin/console mautic:segments:update  
bin/console mautic:campaigns:rebuild  
bin/console mautic:campaigns:trigger
```
7. Check the dashboard for the "Upcoming Emails" widget.

2024-12-05 20:21 UTC, matbcvo commented
Can we make it to display the lead's ID when the lead's name is empty? In one of our customer's Mautic instances, most contacts only have an email address and a company name, without a name.

![image](https://github.com/user-attachments/assets/72ebd98a-bb78-4f9e-9262-a2d6d470daa7)

For example:
```
label: email.lead_name ?: email.lead_id,
```

I think it's better than showing nothing.

![image](https://github.com/user-attachments/assets/3c4589bb-0c3c-487e-9a5f-e3b612cba110)


Unfortunately, it's not possible to make it show the company name because `getUpcomingEvents` does not include it in the returned data. I think I will create an enhancement for this in the 6.x branch.

https://github.com/mautic/mautic/blob/6.x/app/bundles/CampaignBundle/Entity/LeadEventLogRepository.php#L138-L157
It's missing this line:
```
l.company_name AS lead_company_name
```

2024-12-06 09:46 UTC, shinde-rahul approved these changes
The code looks good!! 👍

2024-12-06 09:50 UTC, shinde-rahul commented
After reading the @matbcvo comment, I have not removed the `code-review-needed` label.

2024-12-06 10:37 UTC, kuzmany approved these changes

2024-12-06 12:36 UTC, andersonjeccel commented
@matbcvo Yeah, this can be fixed

---

I'm unhappy about the way this widget displays information in general

- the contact name could be a simple link, because now it looks like it's the main information (catches more attention) when compared to the actual campaigns
- but the widget is about upcoming emails... why can't we see which email template?
- should we keep seeing several instances of the same campaign, thinking of usefulness?

I'd have to explore how the function behind this widget works to come with a better solution
what I released here is just a workaround

2024-12-06 14:52 UTC, matbcvo commented
> should we keep seeing several instances of the same campaign, thinking of usefulness?
I think grouping could be a good idea, but I’m unsure how easy it would be to implement.

---

This function renders the `upcomingemails.html.twig` template in the dashboard:
https://github.com/mautic/mautic/blob/5.2.0/app/bundles/EmailBundle/EventListener/DashboardSubscriber.php#L184-L195

The `getUpcomingEmails `function provides the required data for the widget to render:
https://github.com/mautic/mautic/blob/5.2.0/app/bundles/EmailBundle/Model/EmailModel.php#L2076

The query responsible for fetching the data is located here:
https://github.com/mautic/mautic/blob/6.x/app/bundles/CampaignBundle/Entity/LeadEventLogRepository.php#L138

To retrieve the email template name used in this `email.send` action, you can modify the query as follows:
```sql
em.name AS name
```
and add the following join:
```php
->leftJoin('e', MAUTIC_TABLE_PREFIX.'emails', 'em', 'em.id = e.channel_id AND e.channel = "email"')
```
This allows you to use `email.name` directly in the Twig template.
```twig
{{ email.name }}
```

2024-12-06 16:07 UTC, andersonjeccel commented
@matbcvo Definitely useful

I'm wondering if expanding this way would be considered an enhancement/feature (6.x is the next version for it)
so maybe we'll have to proceed with this PR as bug fix (5.2.1) then release another for expanding

What do you think?

2024-12-06 16:24 UTC, matbcvo commented
Yes, the changes you’re suggesting would be classified as an enhancement rather than a bug fix. Therefore, they need to be implemented in the 6.x branch instead of 5.2.1. It would be great if you could update the line I suggested earlier so we can proceed with this PR as a bug fix. Then, you can implement those changes in a new PR targeting the 6.x branch.

2024-12-09 13:52 UTC, matbcvo requested changes

2024-12-09 13:52 UTC, matbcvo commented on app/bundles/DashboardBundle/Resources/views/Dashboard/upcomingemails.html.twig
> +                                        label: email.lead_name,
Change it to
```
label: email.lead_name ?: email.lead_id,
```
to ensure it displays `email.lead_id` when `email.lead_name` is empty, instead of showing nothing.

Alternatively, use 
```
label: email.lead_name ?: ('mautic.lead.lead'|trans ~ ' #' ~ email.lead_id),
```
to include a translated prefix like `Contact #` for better clarity when falling back to `email.lead_id`.

![image](https://github.com/user-attachments/assets/efff275a-f607-49c0-b857-7292ef9f37d8)

2024-12-09 14:02 UTC, andersonjeccel commented on app/bundles/DashboardBundle/Resources/views/Dashboard/upcomingemails.html.twig
> +                                        label: email.lead_name,
released the second option, thank you for providing the code needed :)

2024-12-09 14:02 UTC, matbcvo commented on app/bundles/DashboardBundle/Resources/views/Dashboard/upcomingemails.html.twig
> +                                        label: email.lead_name,
Thanks @andersonjeccel

2024-12-09 14:07 UTC, matbcvo approved these changes

2024-12-11 08:15 UTC, merged

2024-12-19 15:20 UTC, siteleas commented
> Thanks @andersonjeccel
> 
> Code changes look good to me and the PR has been tested, but I have one suggestion.
> 
> Can we make it to display the lead's ID when the lead's name is empty? In one of our customer's Mautic instances, most contacts only have an email address and a company name, without a first or last name.
> 
> ![image](https://private-user-images.githubusercontent.com/1006437/392978704-72ebd98a-bb78-4f9e-9262-a2d6d470daa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjEyODUsIm5iZiI6MTczNDYyMDk4NSwicGF0aCI6Ii8xMDA2NDM3LzM5Mjk3ODcwNC03MmViZDk4YS1iYjc4LTRmOWUtOTI2Mi1hMmQ2ZDQ3MGRhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTUwOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ4ZTM2NDQyNjI3OGVhZTY1OTdlODkzN2MyNzVkNGQ3MWE5ODQ1NjhiZTVhMDFlY2E0OWM0MDkwMTAzMGU0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g_q0ufzoirNBu2Di_HB5t6K3yz59s6vl3olq3FLhKrk)
> 
> For example:
> 
> ```
> label: email.lead_name ?: email.lead_id,
> ```
> 
> I think it's better than displaying nothing.
> 
> ![image](https://private-user-images.githubusercontent.com/1006437/392981735-3c4589bb-0c3c-487e-9a5f-e3b612cba110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjEyODUsIm5iZiI6MTczNDYyMDk4NSwicGF0aCI6Ii8xMDA2NDM3LzM5Mjk4MTczNS0zYzQ1ODliYi0wYzNjLTQ4N2UtOWE1Zi1lM2I2MTJjYmExMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTUwOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDBhYWM0ODdkOGE0YThkNDU3YmIxYjZhM2E2NDE5NzQ5MjlmOWZmZDNmMmIwOTZiOTEzOGNhNDliMmJjMjBiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tbaPkWB4TFtkF-EWCMY7XYTZoK4Lgf_bKsPl63ddbLg)
> 
> Unfortunately, it's not possible to make it display the company name (like the contacts page does) because `getUpcomingEvents` does not include it in the returned data. I think I will create an enhancement for this in the 6.x branch in the future.
> 
> https://github.com/mautic/mautic/blob/6.x/app/bundles/CampaignBundle/Entity/LeadEventLogRepository.php#L138-L157 It's missing this line:
> 
> ```
> l.company_name AS lead_company_name
> ```

Why not have it show the email address that the email will be sent to if there is no name to display? Wouldn't that be the more straightforward and meaningful approach?

Also, I'm not sure why the person that is being sent an email is shown in a pill outline instead of being shown as a simple hyperlink. Making it a pill outline, to me puts too much prominence to the person being sent the email over the surrounding content. Additionally, having a space between to: and the name like so:

Email to: <ins>bob@bobsco.com</ins>

 or email address of the recipient would be cleaner UI

2024-12-19 15:34 UTC, matbcvo commented
@siteleas Because there wasn’t an email address variable available to use. If I’m not mistaken, @andersonjeccel plans to improve this widget in the 6.x branch, at which point he can add the missing variable to display the email address.