Fixing bug in recent activity widget
mautic/mautic pull request #14396
Opened 2024-12-18 14:49 UTC by JonasLudwig1998

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-12-18 14:58 UTC, matbcvo commented
Thanks for the PR! Please rebase your PR onto the 5.2 branch.

2025-01-03 00:58 UTC, shinde-rahul requested changes
The condition needs to be updated with the log data.

2025-01-03 00:58 UTC, shinde-rahul commented on app/bundles/DashboardBundle/Resources/views/Dashboard/recentactivity.html.twig
> +                        {% if log.userName == system_user or (log.userId is not defined or log.userId is empty) %}
We can enhance the original if statement to `{% if log.userId is defined and log.userId != 0 %}` instead of verifying the username against the system user.
Once the activity is recognized as a system (anonymous), it records this in the audit log table with the `userId` set to 0.

2025-01-08 18:57 UTC, matbcvo commented
I can confirm that this PR resolves the issue – the `System` is no longer linked.

However, there is another issue with `log.route` - the `href` is empty, causing it to redirect to the same dashboard page. It seems that `log.route` is defined, but it contains no value.

![image](https://github.com/user-attachments/assets/22c20124-0a4f-4ec1-87f3-8142d04b1b71)

We can address this issue by adding a check to ensure that `log.route` is not empty.

2025-01-08 18:59 UTC, matbcvo requested changes

2025-01-08 18:59 UTC, matbcvo commented on app/bundles/DashboardBundle/Resources/views/Dashboard/recentactivity.html.twig
> +                        {% if log.route is defined and log.userName != system_user %}
```suggestion
                        {% if log.route is defined and log.route is not empty and log.userName != system_user %}
```

2025-01-09 08:46 UTC, JonasLudwig1998 commented on app/bundles/DashboardBundle/Resources/views/Dashboard/recentactivity.html.twig
> +                        {% if log.route is defined and log.userName != system_user %}
Just implemented your changes

2025-01-09 12:04 UTC, matbcvo approved these changes

2025-01-09 12:33 UTC, matbcvo commented
I just noticed that this issue still persists when interface language is set to something other (eg `Finnish (Finland)`) than the default (`English`).

Other language

![image](https://github.com/user-attachments/assets/38a2b5bd-ae23-441f-9470-9f968816233d)

Default language (`English - United States`)

![image](https://github.com/user-attachments/assets/3aead90d-d15b-478c-8dee-e377ab6e6160)

The following if condition would resolve this issue:
```twig
{% if log.userId is not defined or log.userId == 0 %}
```

2025-01-10 11:49 UTC, matbcvo commented
@JonasLudwig1998 Don't forget to replace line 23. The if condition is still checking the user name instead of the user ID. Once this change is made, it should be good to go.

2025-01-11 03:26 UTC, shinde-rahul approved these changes
Code changes look good to me!!

2025-01-13 15:58 UTC, kuzmany approved these changes
I noticed this issue, and it seems fix it

2025-01-14 13:50 UTC, merged