Use Helper Button in segment's filters
mautic/mautic pull request #14405
Opened 2024-12-20 10:50 UTC by Hugo-Prossaird

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 

## Description

**Initial issue:**
Buttons in segment filter are a bit broken like below:

We suggest to use the same component as in forms:

---
### 📋 Steps to test this PR:

- Go to Segments > New
- Go to filters > Add some filters

2024-12-27 08:32 UTC, kuzmany commented
@andersonjeccel Can you please check this update?

2024-12-27 17:40 UTC, andersonjeccel commented
@kuzmany Ok, I’ll suggest a way to simplify on 02/01

2025-01-03 00:09 UTC, shinde-rahul approved these changes
Code changes look good to me!

2025-01-03 11:58 UTC, andersonjeccel requested changes
I'm happy to see the template being applied, good job!

Just left some suggestions to simplify your PR

2025-01-03 11:58 UTC, andersonjeccel commented on app/bundles/LeadBundle/Resources/views/FormTheme/Filter/_leadlist_filters_entry_widget.html.twig
> +                <div class="segment-button btn-group btn-group-xs pull-right" role="group">
```suggestion
                <div class="segment-button d-flex jc-end btn-group btn-group-xs pull-right" role="group">
```

2025-01-03 11:58 UTC, andersonjeccel commented on app/bundles/LeadBundle/Assets/css/lead.css
> +    justify-content: flex-end;
```suggestion
```

Removing custom styles to use utility classes

2025-01-03 11:58 UTC, andersonjeccel commented on app/bundles/LeadBundle/Assets/css/lead.css
I'd also suggest removing these styles responsible for margin-right as it's not needed within btn-groups, to ensure we won't have weird spacing between btns:

.selected-filters .btn-group .btn {
    margin-right:4px;
}

2025-01-06 07:38 UTC, Hugo-Prossaird commented
@andersonjeccel I updated with your suggestions, thank you for your help !

Now it looks like this:

<img width="1100" alt="Capture d’écran 2025-01-06 à 08 36 38" src="https://github.com/user-attachments/assets/07827879-7341-4649-93eb-ce761126f006" />

2025-01-06 11:48 UTC, andersonjeccel approved these changes
Everything is fine now

2025-01-07 09:35 UTC, merged