Added an activity feed block to the Segment detail page
mautic/mautic pull request #14411
Opened 2024-12-27 03:00 UTC by shinde-rahul

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2025-01-17 07:27 UTC, abhisekmazumdar approved these changes

2025-01-20 16:10 UTC, escopecz requested changes
Nice! One more recommendation

2025-01-20 16:10 UTC, escopecz commented on app/bundles/LeadBundle/Controller/ListController.php
> +        \assert($auditLogModel instanceof AuditLogModel);
Please use [action based DI](https://symfony.com/doc/current/controller.html#controller-accessing-services) instead
```suggestion
```

2025-01-21 13:15 UTC, andersonjeccel commented
Ping me after changes to test

2025-01-28 12:14 UTC, kuzmany approved these changes, later dismissed
Good to me

2025-01-29 09:52 UTC, escopecz commented
@shinde-rahul please take a look at the failing PHPSTAN issue

2025-02-17 11:23 UTC, shinde-rahul commented on app/bundles/LeadBundle/Controller/ListController.php
> +        \assert($auditLogModel instanceof AuditLogModel);
I reverted this one cause, the `\Mautic\LeadBundle\Controller\ListController::viewAction` is being called from `\Mautic\LeadBundle\Controller\ListController::createSegmentModifyResponse` LN#401. This caused some errors.

2025-02-18 08:07 UTC, abhisekmazumdar approved these changes
I see the changes and the activity logs.

2025-02-26 13:31 UTC, escopecz commented on app/bundles/LeadBundle/Controller/ListController.php
> +        \assert($auditLogModel instanceof AuditLogModel);
Well, I solve this by adding the dependency to the places where the method is being called as well. That's how the other dependencies like $listModel were added too.

2025-03-07 07:19 UTC, shinde-rahul commented on app/bundles/LeadBundle/Controller/ListController.php
> +        \assert($auditLogModel instanceof AuditLogModel);
I updated the PR; Please review it.
The commit. to review https://github.com/mautic/mautic/pull/14411/commits/66e2d1460582cad578d6f709d5471693c1750aaa.

2025-03-07 09:07 UTC, escopecz approved these changes
Thanks Rahul! I see no issues in the code. However, I think this will have to be rebased as no new features should go to M6 ([I think](https://mautic.slack.com/archives/CQMKV0RU1/p1741336156241619)). So could you rebase to the 7.x branch? There should be very little changes compared to 6.x at this early stage.

2025-03-07 14:56 UTC, shinde-rahul commented
> So could you rebase to the 7.x branch? 
@escopecz, the PR is ready for 7.x.

2025-03-07 15:33 UTC, merged