DPMMA-2004 Campaign weekday and hour email metrics
mautic/mautic pull request #14414
Opened 2024-12-27 10:49 UTC by patrykgruszka

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-12-28 17:19 UTC, escopecz requested changes
I read through the code and notice a room for small improvements. The main idea looks good. I'm not convinced that our clients will be able to load such a massive query on the email_stats table, but since it's loading via AJAX it won't slow down the campaign detail page. In the worst case it will cause slow DB queries with no value added to the user. It would be nice if we could add a feature flag to hide this option for bigger databases.

2024-12-28 17:19 UTC, escopecz commented on app/bundles/CampaignBundle/Controller/CampaignMetricsController.php
> +        foreach ($hoursRange as $r) {
Using more descriptive variable names improves readability
```suggestion
        foreach ($hoursRange as $hour) {
```

2024-12-28 17:19 UTC, escopecz commented on app/bundles/EmailBundle/Stats/EmailPeriodMetrics.php
> +
```suggestion

declare(strict_types=1);

```

2024-12-28 17:19 UTC, escopecz commented on app/bundles/EmailBundle/Stats/EmailPeriodMetrics.php
> +            ->setParameter('dateTo', $dateTo->setTime(23, 59, 59)->format('Y-m-d H:i:s'))
```suggestion
            ->setParameter('dateTo', $dateTo->setTime(23, 59, 59)->format(DateTimeHelper::FORMAT_DB))
```

2024-12-28 17:19 UTC, escopecz commented on app/bundles/EmailBundle/Stats/EmailPeriodMetrics.php
> +     * @throws \Exception
Is this information helpful for anyone?

2025-01-07 14:32 UTC, patrykgruszka commented
@escopecz I've added your suggestions and an option to disable this feature, but now the CS Fixer is failing everytime. Do you have any idea why?
```
In ConfigurationResolver.php line 395:
                                                                               
  The path "app/bundles/CoreBundle/Doctrine/TranslationMigrationTrait.php" is  
   not readable.   
```

Also, I've tested these stats on a very large database, and it's looking fine for now. Less than 10 seconds for over 25 million `email_stats`.

2025-01-07 15:42 UTC, escopecz commented
@patrykgruszka I saw this happening. The GH Action is building of changed files so it wouldn't scan through all the files. There is a glitch when the branch isn't up to date. Try to rebase/merge fresh 6.x branch and it should resolve the issue.

2025-01-08 07:37 UTC, patrykgruszka commented
Thanks, looks good now!

2025-01-08 09:00 UTC, escopecz approved these changes
I see no issues in the code. Thank you! 👍

2025-01-15 11:58 UTC, matbcvo approved these changes
The code changes look good to me. I’ve tested the PR, and everything works as expected.

2025-01-17 14:46 UTC, merged