New segments filters
mautic/mautic pull request #3477
Opened 2017-02-20 18:34 UTC by kuzmany

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/pull/2912
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Bunch new segment filters. Update version. More clean.
Follow up to https://github.com/mautic/mautic/pull/2912

Page filters:
- Referer
- Source
- Page Title
- Sessions  - number of visits without delay not longer like 30 minutes (same like Google Analytics visits metric)
- Visited URL Date
- Visited URL Count

Email filters
- Email sent
- Email Read Date
- Email Read Count 

Booleans filters:

URL from email
URL from landing page
Redirec URL
- check page_id, email_id, redirect_id from page_hits table 

Notifications  
- check push_id from push_ids table 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Apply and test filters

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2017-02-28 13:34 UTC, virlatinus commented
When testing the "Email Read Count" filter and running 'console mautic:segments:update' I get an SQL error: 
'SELECT count(l.id) as lead_count, max(l.id) as max_id FROM leads l LEFT JOIN lead_lists_leads ll ON (ll.  
  leadlist_id = 14) AND (ll.lead_id = l.id) AND (ll.date_added <= '2017-02-28 13:32:18') WHERE (()) AND (ll.lead_id IS NULL)'

2017-03-01 00:51 UTC, kuzmany commented
@virlatinus typo bug, try again pls 👍

2017-03-03 17:22 UTC, virlatinus approved these changes
Tested it and the PR works as described

2017-03-03 18:12 UTC, alanhartless commented
@kuzmany we really appreciate this! We're going to push this one to 2.8 so we can test it in more depth on large data sets (think millions of page hits).

2017-03-22 13:43 UTC, luizeof commented
There are some filter for Downloaded assets?

2017-04-17 08:01 UTC, escopecz requested changes
I noticed that several small improvements could be done to the code. Please review them.

2017-04-17 08:01 UTC, escopecz commented on app/bundles/LeadBundle/Entity/LeadListRepository.php
> +                    $operand = ($func == 'between' || in_array($func, ['eq', 'gt', 'lt', 'gte', 'lte'])) ? 'EXISTS' : 'NOT EXISTS';
`($func == 'between' || in_array($func, ['eq', 'gt', 'lt', 'gte', 'lte']))`
is the same as
`(in_array($func, ['eq', 'gt', 'lt', 'gte', 'lte', 'between']))`
Isn't it?

2017-04-17 08:01 UTC, escopecz commented on app/bundles/LeadBundle/Entity/LeadListRepository.php
> +                   if ($details['field'] == 'lead_email_read_date') {
There is missing one space to align `if` with the rest of the code

2017-04-17 08:01 UTC, escopecz commented on app/bundles/LeadBundle/Entity/LeadListRepository.php
> +                    if($column == 'hit_url'){
There are several places where the CS is not met. Could you run this PR through the pre-commit hook which will fix the CS?

2017-04-19 10:44 UTC, escopecz approved these changes
I fixed the CS so this could be merged to 2.8.0. I did not find any problem during testing and the filters seems to be returning the right results 👍  Thanks!

2017-04-19 10:45 UTC, merged