New campaign action:  Call remote url
mautic/mautic pull request #4357
Opened 2017-07-05 17:47 UTC by kuzmany

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/854
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Just add new action. 
Return true If response code = 200 or 201.

![image](https://user-images.githubusercontent.com/462477/27877292-5cece8d2-61ba-11e7-8487-33116ae72704.png)

#### Steps to test this PR:
1. Basic test could be create test.php anywhere and call GET or POST there.
2. Extended test could be with service external service.  (I tested with our private address validator service and works with POST request data and headers). Maybe people from could help https://github.com/mautic/mautic/issues/854

2017-07-05 18:28 UTC, Loanatik commented
This is brilliant!

2017-07-06 08:17 UTC, escopecz requested changes
Thanks Zdeno! This feature has been requested many times.

I added some thoughts to the new code, but over all, it looks good to me! Please review the comments and implement them if they make sense to you.

2017-07-06 08:17 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +        }
We have to let the users know why the request failed. It fails silently without any clue of what happened. Whether it returned 500 or timeouted. Could you please add some error messages so the users won't report errors like "the campaign URL call doesn't work", but give them information so they could debug themselves?

You can inspire here: https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/EventListener/CampaignSubscriber.php#L116

2017-07-06 08:17 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
>       * @param AuditLogModel  $auditLogModel
Add the new dependency to the annotation please.

2017-07-06 08:17 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +                    $config['url'],
Maybe the `$data` should be added as a URL query params in this case?

2017-07-06 08:59 UTC, kuzmany commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
>       * @param AuditLogModel  $auditLogModel
Fixed

2017-07-06 09:10 UTC, escopecz reviewed
It was fast!

2017-07-06 09:10 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +            }
I'd also add something like
```
else {
    $event->setFailed('Response returned HTTP code '.$response->code);
}
```
I'm not sure whether the error is run through the translator later. Maybe you'll have to add Translator as a dependency to this Subscriber.

2017-07-06 09:10 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +            return $event->setResult($e->getMessage());
The method should be `setFailed` instead of `setResult`.

2017-07-06 09:10 UTC, kuzmany commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +        }
Improved. Please check it

2017-07-06 13:01 UTC, Loanatik commented
Should have user friendly description:
![image](https://user-images.githubusercontent.com/14249107/27912110-88fa1854-6210-11e7-96cf-2a100395b088.png)

2017-07-06 13:17 UTC, escopecz commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +            }
Ok, should be resolved with the previous commit

2017-07-06 13:32 UTC, Loanatik commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +        $timeout = 10;
How does timeout get set to the value specified by the user?

2017-07-06 16:55 UTC, kuzmany commented on app/bundles/CampaignBundle/EventListener/CampaignSubscriber.php
> +        $timeout = 10;
Yes, already update with timeout option. Check screenshot

![image](https://user-images.githubusercontent.com/462477/27922852-b975a87e-627c-11e7-9090-9796c33e7019.png)

2017-07-07 12:33 UTC, Loanatik commented
Rather than just an authorization header, wouldn't make more sense to allow any custom header similar to the way you can add any data?

2017-07-07 12:46 UTC, kuzmany commented
@Loanatik please send examples, I don't know about it

2017-07-07 13:15 UTC, Loanatik commented
I don't personally have a big need for this, though I'd imagine others will:
![image](https://user-images.githubusercontent.com/14249107/27959244-85c6885e-62db-11e7-9ca7-81e1598da9e9.png)

I have not tested the data section for tokens.  Am I correct in assuming that that they should work?

2017-07-07 13:27 UTC, kuzmany commented
@Loanatik contacts fields tokens coming soon I will add it
Headers: I think It works now but I need look to documentation

2017-07-08 06:57 UTC, Loanatik commented
Hi Z-

    There are a whole slew of improvements that I would like to see in Mautic once #4357 is complete.   Do you want to work on another project?  If so, I think merging duplicates needs improvement .  Is that an area you consider important?

Corey


[LOANATIK_ID_Web]
8520 East Shea Blvd #115, Scottsdale, AZ 85260
www.loanatik.com<http://www.loanatik.com/>

Corey Schwartz
480-588-0397<tel:480-588-0397>
602-739-7060<tel:602-739-7060> (m)
480-696-6495 (f)
cschwartz@Loanatik.com<mailto:cschwartz@Loanatik.com>

Loanatik, l.l.c., 8520 E Shea Blvd #115, Scottsdale, AZ 85260.  www.loanatik.com. 480-568-0333. Copyright 2015. All Rights Reserved. This is not an offer to enter into a loan or agreement. Not all borrowers will qualify. Information, rates and programs are subject to change without prior notice. All products are subject to credit and property approval. Only available in CO & TX. Other restrictions and limitations apply. Corporate NMLS ID #1328447 | NMLS Consumer Access<http://www.nmlsconsumeraccess.org/>
State Licenses: Colorado & Texas License Issued.

From: Zdeno Kuzmany [mailto:notifications@github.com]
Sent: Friday, July 07, 2017 6:28 AM
To: mautic/mautic <mautic@noreply.github.com>
Cc: Corey Schwartz <cschwartz@loanatik.com>; Mention <mention@noreply.github.com>
Subject: Re: [mautic/mautic] New campaign action: Call remote url (magic stick) (#4357)


@Loanatik<https://github.com/loanatik> contacts fields tokens coming soon I will add it
Headers: I think It works now but I need look to documentation

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/mautic/mautic/pull/4357#issuecomment-313680467>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ANlsk-_1sPKl2tG9sU8flDZm0MAgJRRdks5sLjJUgaJpZM4OOqFR>.

2017-07-08 10:05 UTC, kuzmany commented
Added  headers and support for contactfield tokens for data and headers
![image](https://user-images.githubusercontent.com/462477/27984409-c333c184-63d5-11e7-8f05-a6e94814a006.png)

2017-07-08 10:35 UTC, kuzmany commented
Added documentation.
Now ready for tests.

2017-07-10 06:51 UTC, escopecz commented
Note: this PR contains https://github.com/mautic/mautic/pull/4355 which should be merged first.

2017-07-14 17:08 UTC, alanhartless requested changes
Good stuff! I think instead of naming this "Call remote url" let's call it "Send a webhook"

2017-07-14 17:10 UTC, Loanatik commented
I've been testing this PR and it works as described.

2017-07-31 19:38 UTC, calevans commented
Do we have a status on this? Any idea when it will be included?

Cheers! :)
=C=

2017-07-31 19:40 UTC, kuzmany commented
@calevans Mautic 2.10

2017-07-31 21:58 UTC, kuzmany commented
Please re-test. 
Refactor to Send a webhook and moved to MauticWebhookBundle.

2017-08-01 06:52 UTC, escopecz commented
It's failing some CI tests. Please look at those when you get a minute.

2017-08-01 08:06 UTC, kuzmany commented
@escopecz morning. fixed

2017-08-04 19:53 UTC, alanhartless approved these changes
I removed trace and options as they are not applicable to webhooks and added the missing DELETE method to the method choices. I also added a not blank validator to ensure URL is required. Otherwise, good stuff!

2017-08-07 09:00 UTC, escopecz approved these changes
Works great. Amazing feature. Thanks! 👍

2017-08-16 16:04 UTC, merged

2020-05-21 15:52 UTC, k16101997 commented
Will this support nested payload like in the picture
![Screenshot from 2020-05-21 21-20-37](https://user-images.githubusercontent.com/20707546/82577753-0a21ff80-9ba9-11ea-8392-e494aab2b07d.png)

2020-06-04 14:37 UTC, dichvuhuuich commented
> Does it support the payload like in the attached picture
> ![Screenshot from 2020-05-21 21-20-37](https://user-images.githubusercontent.com/20707546/82577753-0a21ff80-9ba9-11ea-8392-e494aab2b07d.png)
> Also how do i know the status / response of a api call in send a webhook

I want to know the status / response of a api call in send a webhook, too, do you know that?