Feature/aws
mautic/mautic pull request #5263
Opened 2017-11-01 13:37 UTC by renjith341

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #1740
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Amazon SES API integration for email handling. It incorporates mautic's token feature. Introduced new 'sendBulkTemplatedEmail' method to send bulk emails with token and templates. Fallback method 'sendRawEmail' is used to send emails with attachments.

#### Steps to test this PR:
1. In email settings select service as 'Amazon SES'.
2. Create new segment email then send email.

2017-12-18 09:33 UTC, AndrassGray commented
Good to see that "Max Messages per 24h" is now honoured.

Would it be possible to get "Max Messages per second" as well. From what I see, the Swiftmailer Throttler plugin would handle this nicely.

Thanks!

2018-02-25 16:10 UTC, amagdy3 commented
Guys, what's the best support to be provided to get this to the light the soonest?

2018-03-27 16:18 UTC, Maxell92 commented
Hello @renjith341,
there are conflict in this PR. Could you rebase your branch to staging please?

Thank you

2018-03-28 11:36 UTC, Maxell92 requested changes
Hello @renjith341,

I made a code review for your PR. It is a great work, however I have a few questions here:

1) We try to keep all new code as much clean as possible. I understand that this PR just changed current implementation to Amazon SES, but do you think it is possible to split code to small classes? You can take a look to Sendgrid API - I implemented it here: https://github.com/mautic/mautic/pull/5412

2) This allows us to write tests. Current code is tested only for a few specific cases, because this implementation makes testing really painful.

3) Could you provide us a documentation how to setup Amazon SES too? There is an issue about this: https://github.com/mautic/documentation/issues/203

Thank you!

2018-03-28 11:36 UTC, Maxell92 commented on app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
> +     * @return mixed
Can you provide a correct typehint please? I think it should be string.

2018-03-28 11:36 UTC, Maxell92 commented on app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
> +            'version' => 'latest',
Are you sure this will work in the future? I think there should be a proper version which is tested and works.

2018-03-28 11:36 UTC, Maxell92 commented on app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
> +            throw new \Exception('Your AWS SES quota is exceeded');
Can you provide a custom Exception here?

2018-03-28 11:36 UTC, Maxell92 commented on app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
> +     * @param type $evt
Could you provide proper typehint here please?

2018-03-30 15:05 UTC, mleffler commented
Hi, We need all merges to happen by Wednesday, April 4 to make it into 2.13.  If you can work on this before then, we would love to include it.  Sorry for the right timeline, and thanks.

2018-04-16 16:03 UTC, amagdy3 commented
Hello @renjith341 - sounds like great work. Anyway I can support so we can get this published ASAP. Let me know if you need an extra hand with testing to get through @Maxell92 requests.

2018-04-30 09:48 UTC, wittwerch commented
Hi guys,
@renjith341 is not working on Mautic anymore, as we have shut down our efforts on contributing. If somebody is interested in taking it over to finish, feel free.

2018-04-30 10:17 UTC, Maxell92 commented
Hello, thank you for information.
We are going to close this PR, because it is not ready to merge. Anyone can create a new branch, continue there and send a new PR if he wants.

2018-04-30 10:17 UTC, closed without merging

2018-06-19 22:04 UTC, davidbnk commented
We are continuing the discussion on PR #6123 if anyone is interested