Microsoft Dynamics FetchLeads  - update
mautic/mautic pull request #5674
Opened 2018-02-03 18:15 UTC by kuzmany

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2018-02-03 18:15 UTC, kuzmany commented
Label: WIP

2018-02-03 18:15 UTC, kuzmany commented
Label: Feature Request

2018-02-06 17:06 UTC, kuzmany commented
Label: WIP

2018-02-06 17:06 UTC, kuzmany commented
Label: Ready to test

2018-02-07 08:55 UTC, npracht commented
I start testing !

2018-03-25 16:16 UTC, dbhurley commented
Due to the work being discussed in removing plugins from core and especially extracting the CRM plugins from core I recommend this work be held out of 2.13. This should be part of the discussion when evaluating how CRM plugins are handled, however, additions to Mautic core CRM is being restricted in the immediate as a result. 

_eg. This should live in a `mautic-dynamics` repository instead of being part of the core release.

2018-03-26 13:40 UTC, npracht commented
@dbhurley clear. Thanks.

2018-10-31 11:01 UTC, npracht commented
@dbhurley i'd suggest that we integrate that to mautic 2.15 as far as it is enhancement of existing. And we'll take out of mautic core when working on Mautic 3 ?

Please confirm.

2018-11-29 12:45 UTC, npracht submitted a review, later dismissed
All the new features are working. @kuzmany could you please add the documentation ?

2019-01-03 05:36 UTC, jmbarneck commented
I just tested this PR and it does not seem to work, here are my results:

[root@cp mauticdev]# php app/console mautic:integration:fetchleads -i Dynamics
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...
    0 [>---------------------------]
0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting
    0 [>---------------------------]
0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Dynamics
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

[root@cp mauticdev]# php app/console mautic:integration:synccontacts -i Dynamics
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...
    0 [>---------------------------]
0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting
    0 [>---------------------------]
0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Dynamics
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

It would be great to get this integration working. Let me know if I can provide more information to help.

2019-05-16 20:58 UTC, javiergas commented
Hi @kuzmany @npracht 
What do we need / how can I help for this PR to be merged?

2019-05-17 07:48 UTC, npracht commented
Hi @javiergas you can test it, tell how is working and not working then Zdeno can finish the work !

2019-07-16 21:59 UTC, javiergas requested changes
Records updated in Dynamics are not updated in Mautic

2019-07-16 21:59 UTC, javiergas commented on plugins/MauticCrmBundle/Integration/DynamicsIntegration.php
>                      $integrationId = $integrationEntityRepo->getIntegrationsEntityId('Dynamics', $object, 'lead',
Hi @npracht, 
I found something very strange that is preventing records by updated from Dynamics:
This line returns nothing but If check what is set to be returned from inside getIntegrationsEntityId() ir seems to be OK.

Using PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

2019-08-23 13:58 UTC, florentpetitjean commented
Hello @kuzmany can you give us an update on this ? 
We will need this very soon for a client.

Thanks,

2019-08-26 16:08 UTC, kuzmany commented
@javiergas @florentpetitjean  can you test it?

2019-08-27 09:06 UTC, florentpetitjean reviewed
I test and it works except for one element : 
When I select lead in specific features  (in the last options, the object to pull data from): 
![image](https://user-images.githubusercontent.com/49391402/63757332-2adb5400-c8ba-11e9-8f89-5bdd61430c32.png)
I can't validate the settings as it require a new field in the contact mapping without showing wich one 
![image](https://user-images.githubusercontent.com/49391402/63757474-65dd8780-c8ba-11e9-913e-ec6a55227eeb.png)

A part form that  : 

- contacts are synchronised in both way
- The option to push to contact or lead in Dynamics works
- And the contact update if they already exists

2019-08-30 08:34 UTC, kuzmany commented
@florentpetitjean  can you re-test with last changes?

2019-08-30 13:33 UTC, florentpetitjean submitted a review, later dismissed
Tested, all is working fine now, good job !

2019-08-30 13:51 UTC, npracht commented
@kuzmany can you add documentation please ?

2019-11-26 10:17 UTC, florentpetitjean commented
Hello @kuzmany 
We got this error  after patching this PR, could you look at it ? Thanks !

[2019-11-26 09:40:06] mautic.NOTICE: Mautic\PluginBundle\Exception\ApiErrorException: Dynamics CRM API error: {"code":400,"headers":{"Cache-Control":"no-cache","Allow":"OPTIONS,GET,HEAD,POST","Content-Type":"multipart\/mixed; boundary=batchresponse_018d32cf-ea07-4fc2-a9f6-829726d45db2","Expires":"-1","Server":"Microsoft-IIS\/10.0","x-ms-service-request-id":"ff2b38c8-750d-4164-bbce-5d692fa53682","Strict-Transport-Security":"max-age=31536000; includeSubDomains","REQ_ID":"ff2b38c8-750d-4164-bbce-5d692fa53682","AuthActivityId":"b8ed2998-0152-42b9-a278-8a10e8fa02f5","x-ms-ratelimit-burst-remaining-xrm-requests":"5994","x-ms-ratelimit-time-remaining-xrm-requests":"1,199.87","OData-Version":"4.0","X-Source":"2061881637365871852146011751712502789492542351481987914118417696641642375934148","Public":"OPTIONS,GET,HEAD,POST","Timing-Allow-Origin":"*","X-Powered-By":"ASP.NET","Date":"Tue, 26 Nov 2019 09:40:05 GMT","Content-Length":"1474"},"body":"--batchresponse_018d32cf-ea07-4fc2-a9f6-829726d45db2\r\nContent-Type: multipart\/mixed; boundary=changesetresponse_ec89406b-3523-49f3-89ea-f5154c9b520f\r\n\r\n--changesetresponse_ec89406b-3523-49f3-89ea-f5154c9b520f\r\nContent-Type: application\/http\r\nContent-Transfer-Encoding: binary\r\nContent-ID: 1145\r\n\r\nHTTP\/1.1 400 Bad Request\r\nContent-Type: application\/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x8006088a\",\"message\":\"Requested API Version 'data' was not understood. Please provide in the format \/api\/data\/v.\/ (example: \/api\/data\/v7.2\/)\",\"innererror\":{\"message\":\"Requested API Version 'data' was not understood. Please provide in the format \/api\/data\/v.\/ (example: \/api\/data\/v7.2\/)\",\"type\":\"Microsoft.Crm.CrmHttpException\",\"stacktrace\":\"   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataRoutingConvention.ParseVersion(String versionString, String exceptionmessage)\\r\\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataRoutingConvention.GetApiVersionFromRequestUri(Uri requestUri, String& echoVersion, Boolean accessedAsIfd)\\r\\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.ValidateApiVersion(Uri serviceRoot)\\r\\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)\"}}}\r\n--changesetresponse_ec89406b-3523-49f3-89ea-f5154c9b520f--\r\n--batchresponse_018d32cf-ea07-4fc2-a9f6-829726d45db2--\r\n"} (uncaught exception) at /home/atmt_arademo/arademo.automation.webmecanik.com/2-15-4-atmt/plugins/MauticCrmBundle/Api/DynamicsApi.php line 58 while running console command `mautic:integration:fetchleads` [] []

2019-12-02 14:39 UTC, kuzmany commented
@florentpetitjean last commit should fix push to integration object issue. Please re-test

2019-12-12 09:42 UTC, autoize commented
@kuzmany, we notice the same 400 error as @florentpetitjean when testing this pull request on 2.15.3. It occurs after a lead has been updated in Dynamics, and the changes should be synced back to Mautic (in this case Dynamics is set as the system of record).

After applying the change mentioned in this [comment](https://github.com/mautic/mautic/issues/4626#issuecomment-450332944) made by @afonseca08 in #4626, the changes **do** successfully sync over from Integration => Mautic.

However we are still getting the same output in console as mentioned by @florentpetitjean.

```
[example@example go]$ sudo -u apache php app/console -v mautic:integration:fetchleads -i Dynamics
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...
jackie@example.onmicrosoft.com
standaloneform@example.com
campaignform@example.com
john.doe@example.com
jane.doe@example.com

Number of leads/contacts fetched: 5

Fetching companies
Fetch companies command is starting
example

Number of companies fetched: 1

Updating/creating leads from Mautic to Dynamics
About 1 to update and about 0 to create/update
This could take some time. Please wait until the process is completed
 1/1 [============================] 100%

  [Mautic\PluginBundle\Exception\ApiErrorException]
  Dynamics CRM API error: {"code":400,"headers":{"Cache-Control":"no-cache","Allow":"OPTIONS,GET,HEAD,POST","Content-Type":"multipar
  t\/mixed; boundary=batchresponse_057576c6-1e68-4f46-812c-0863e9315051","Expires":"-1","Server":"Microsoft-IIS\/10.0","x-ms-service
  -request-id":"0013f6c4-7f91-4a54-bc13-ba7295041b9a","Strict-Transport-Security":"max-age=31536000; includeSubDomains","REQ_ID":"00
  13f6c4-7f91-4a54-bc13-ba7295041b9a","AuthActivityId":"640defa0-2778-4dad-aece-6c4a0d5e346a","x-ms-ratelimit-burst-remaining-xrm-re
  quests":"5986","x-ms-ratelimit-time-remaining-xrm-requests":"1,199.56","OData-Version":"4.0","X-Source":"1269921413096212401753427
  1210610494200161661612514419225159121571491722217225213029","Public":"OPTIONS,GET,HEAD,POST","Timing-Allow-Origin":"*","X-Powered-
  By":"ASP.NET","Date":"Thu, 12 Dec 2019 09:33:19 GMT","Content-Length":"5705"},"body":"--batchresponse_057576c6-1e68-4f46-812c-0863
  e9315051\r\nContent-Type: multipart\/mixed; boundary=changesetresponse_5bb4e116-b8c5-4f18-a39b-d10969f0a852\r\n\r\n--changesetresp
  onse_5bb4e116-b8c5-4f18-a39b-d10969f0a852\r\nContent-Type: application\/http\r\nContent-Transfer-Encoding: binary\r\nContent-ID: 7
  7b5bb61-c01c-ea11-a811-000d3a56957f\r\n\r\nHTTP\/1.1 400 Bad Request\r\nREQ_ID: 0013f6c4-7f91-4a54-bc13-ba7295041b9a\r\nContent-Ty
  pe: application\/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x0\",\"message\":\"An error occ
  urred while validating input parameters: Microsoft.OData.ODataException: An unexpected 'StartArray' node was found when reading fr
  om the JSON reader. A 'StartObject' node was expected.\\r\\n   at Microsoft.OData.Json.JsonReaderExtensions.ValidateNodeType(IJson
  Reader jsonReader, JsonNodeType expectedNodeType)\\r\\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart
  Implementation(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNeste
  dPayload, Boolean allowEmptyPayload)\\r\\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayload
  Kind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmpt
  yPayload)\\r\\n   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()\\r\\n   at Microsoft.OData.ODataRe
  aderCore.ReadImplementation()\\r\\n   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\\r\\n   at System.We
  b.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)\\r\\n   at System.Web.OData.
  Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext rea
  dContext)\\r\\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent c
  ontent, IFormatterLogger formatterLogger)\",\"innererror\":{\"message\":\"An error occurred while validating input parameters: Mic
  rosoft.OData.ODataException: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was
   expected.\\r\\n   at Microsoft.OData.Json.JsonReaderExtensions.ValidateNodeType(IJsonReader jsonReader, JsonNodeType expectedNode
  Type)\\r\\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStartImplementation(ODataPayloadKind payloadKind,
   PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)\\r\\n
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, PropertyAndAnnotationColle
  ctor propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)\\r\\n   at Microsoft.OData.JsonLig
  ht.ODataJsonLightReader.ReadAtStartImplementation()\\r\\n   at Microsoft.OData.ODataReaderCore.ReadImplementation()\\r\\n   at Mic
  rosoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\\r\\n   at System.Web.OData.Formatter.Deserialization.ODataReade
  rExtensions.ReadResourceOrResourceSet(ODataReader reader)\\r\\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeser
  ializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\\r\\n   at System.Web.OData.Format
  ter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)\",
  \"type\":\"Microsoft.Crm.CrmHttpException\",\"stacktrace\":\"   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInp
  utParameters(ModelStateDictionary controllerModelState)\\r\\n   at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityI
  mplementation(String& entityName, String key, EdmEntityObject entityDelta)\\r\\n   at Microsoft.PowerApps.CoreFramework.ActivityLo
  ggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalC
  ustomProperties)\\r\\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityTy
  pe activityType, Func`1 func)\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.Reflec
  tedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   a
  t System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 ar
  guments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r
  \\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.Han
  dleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsy
  ncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime
  .ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugge
  rNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of s
  tack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo
  .Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Syst
  em.Web.Http.Dispatcher.HttpControllerDispatcher.<SendA [...]

2020-01-27 10:55 UTC, RCheesley commented
Hi @kuzmany is there any update on this at all? Are we just pending tests and documentation or do we have other work to be done before this can be merged?

2020-04-06 07:06 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-07-13 14:14 UTC, TravisBuddy commented
## Travis tests have failed

Hey @kuzmany,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 2c829fb0-c513-11ea-af19-3b271fec1f42

2020-07-21 20:24 UTC, RCheesley commented
@kuzmany a Travis fix here

2020-08-28 12:13 UTC, RCheesley commented
@cla-bot check

2021-02-13 20:46 UTC, RCheesley commented
Still has outstanding test coverage issues, I am willing to bump this one more feature release to Mautic 4 and if we have not merged it by then we will close the PR.

2023-08-04 12:20 UTC, RCheesley commented
Conflicts & rebase needed. Pinging @mautic/dynamics-tiger-team - it's an old PR so would be good to check if it's still required!

2024-04-02 07:18 UTC, escopecz commented
@kuzmany could you please check if this issue was fixed with https://github.com/mautic/mautic/pull/13208?

2024-06-05 19:32 UTC, RCheesley commented
I'm going to close this PR given the lack of response over the last years. If someone wishes to pick it up in the future please ping us to re-open the PR. It will need to be rebased to the latest branch.

2024-06-05 19:32 UTC, closed without merging