Added check to verify if leadVal is array for in and !in operator cases
mautic/mautic pull request #5916
Opened 2018-04-07 15:20 UTC by socmov

closes https://github.com/mautic/mautic/issues/5904

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? | n
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5904 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When using dynamic content in an email you can select contact fields to use as filters. If you chose the includes option it would error out as the code assumed that the input value would be an array however my input was a string. 

This failure would result in the emails being sent without populating the dynamic content. People would receive emails with "Hi {contactfield=firstname}"

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create email
2. Add Dynamic Content
3. Create a Variation
4. Choose a filter using a Select type field
5. Choose includes and select two or three options
6. Add the email to a campaign
7. Run the campaign
8. Error: PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php on line 159

The contact value is a string but the code assumed it was an array.  

#### Steps to test this PR:
1. Follow the steps above
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2018-04-26 11:36 UTC, escopecz requested changes
Please fix the code style reported in https://travis-ci.org/mautic/mautic/jobs/363516459#L703

2018-04-26 11:36 UTC, escopecz commented on app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php
> +                    if (getType($leadVal) == 'array') {
Please use [is_array](http://php.net/manual/en/function.is-array.php) instead. (plus once more bellow)

2018-10-08 18:27 UTC, escopecz commented on app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php
> +                        if (in_array($leadVal, $filterVal)) {
There is some duplication of code. How about to just add this if:
```
if (!is_array($leadVal)) {
    $leadVal = [$leadVal];
}
```
and then continue with the original foreach?

2018-11-27 01:21 UTC, mleffler commented
@socmov I see this was your first PR, and you have not been continuing to contribute to Mautic.  Are you interested in finishing this?  If not, and others want the work, does someone else want to do it?  We should make the changes, or close.

2019-04-05 08:32 UTC, npracht commented
@kuzmany or @escopecz i have the feeling it is fixing a real issue. Can one of you carry the end of this PR ?

2019-04-05 08:36 UTC, kuzmany commented
@npracht are you able to reproduce it?

2019-04-05 08:52 UTC, npracht commented
Actually i didn't try. But the description sounded rational. If you cannot reproduce we close it (it is standing here for 1 year...)

2019-04-18 21:45 UTC, socmov reviewed
Streamlined the code for checking for arrays with in and !in filters

2020-03-09 21:42 UTC, RCheesley commented
I think the requested changes were made is that correct? If so let's get this tested and see if we can get it merged in 2.16.1.

2020-03-19 13:38 UTC, dbhurley submitted a review, later dismissed
+1

2020-05-26 08:49 UTC, npracht commented
@socmov can you please review the conflicts ?

2020-06-23 17:01 UTC, RCheesley commented
Hi @socmov if you can resolve the conflicts we can get this tested and shipped with one of the upcoming patch releases, shout if we can help with anything!

2020-08-25 16:50 UTC, RCheesley commented
@cla-bot check

2021-01-20 09:17 UTC, npracht commented
Closing for lack of feedback.

2021-01-20 09:17 UTC, closed without merging