Email Stat Limit: limit number of Stat 'openDetails'
mautic/mautic pull request #6183
Opened 2018-06-07 18:48 UTC by maxlawton

| Q  | A
| --- | ---
| Bug fix? |  Y
| New feature? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

#### Description:

We observed an email client that was sending multiple consecutive open requests. With each request being added to the **Stat** `openDetails` array, the persisted JSON eventually grew too large to be saved to the database. Eventually, MySQL becomes overloaded attempting to deal with so many erroneous (and huge) queries.

To prevent this, we impose a hard limit on the number of entries that can be added to the `openDetails` array.

When calling `Stat#addOpenDetails()`, the argument will only be added to the `openDetails` array if the **Stat**'s `openCount` is less than **Stat::MAX_OPEN_DETAILS** (`1000`). The `openCount` will be incremented regardless.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Request the same tracking pixel thousands of times. ~20,000 was how many went to our server.
2. Watch your webserver and MySQL logs.

#### Steps to test this PR:
1. Request the same tracking pixel more than a thousand times.
2. Watch the resulting **Stat**'s `openCount` increase beyond `1000` while the size of the `openDetails` array's JSON value ceases to change after the thousandth hit.

2018-06-08 06:56 UTC, npracht commented
@alanhartless i'm wondering if this is a good practice. I think the objectives is gained but seems a bit dirty, doesn't it?
Also, then why 1000? Opening 1000 times an email has no sense. 100 is already too much to be logic.

2018-06-08 16:06 UTC, maxlawton commented
@npracht I agree that 1000 _openDetails_ is well outside the realm of reasonable need. I believe that number was chosen as it is 10x the upper bound of useful information and 1/10th the number of entries that can fit in the column. The excessively large value is a compromise, but perhaps an unnecessary one.

Also in agreement that using a fixed value in a class constant is pretty dirty, only slightly better than an inline scalar value. However, I think it has fewer cons than some other options:

* Customizable setting: introduces overhead on performance-critical code
* Moving _openDetails_ to an association: adds query complexity to every insert, bloats schema to support edge case
* Doing nothing: exposes vulnerability for difficult-to-detect and likely unintentional denial of service

2020-04-06 07:01 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-09-20 08:12 UTC, mabumusa1 approved these changes, later dismissed
I think the code is logical and the idea of having 1000 upper limit seems rational the argument that @maxlawton provided looks logical to me and I think this PR should be merged

2020-09-20 08:18 UTC, mabumusa1 commented
@cla-bot check

2020-09-21 09:44 UTC, escopecz requested changes
Needs a test

2020-09-28 15:26 UTC, RCheesley commented
@cla-bot check

2020-09-29 18:26 UTC, escopecz approved these changes
Looking good 👍

2020-09-29 18:46 UTC, kuzmany approved these changes
Good 👍

2020-11-20 10:02 UTC, merged