Not contains support for form value condition expression notLike
mautic/mautic pull request #6905
Opened 2018-11-20 10:54 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2019-01-30 22:41 UTC, alanhartless submitted a review, later dismissed

2020-04-06 06:52 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-04-25 16:39 UTC, kuzmany commented
Rebased

2020-04-25 16:57 UTC, TravisBuddy commented
## Travis tests have failed

Hey @kuzmany,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: cf1452a0-8715-11ea-aff5-4384c8db8986

2020-08-14 21:19 UTC, RCheesley requested changes
I set up the form with options 1, 2 and 3 and submitted a few combinations as instructed.

![screenshot-local mautic3-2020 08 14-22_20_31](https://user-images.githubusercontent.com/2930593/90293611-6761e000-de7c-11ea-81a3-19c518ad4270.png)

Here's how I set up the campaign:

![Edit Campaign _ Mautic (1)](https://user-images.githubusercontent.com/2930593/90293187-6ed4b980-de7b-11ea-8c3f-d0e5d8d8e816.gif)

When I run the campaign, I'm not getting the results I'd expect.

I believe based on my understanding of your instructions that when Option 1 was NOT selected (e.g. the form submission was Option 2 & Option 3 only) it should have added the tag 'Not like 1' and when it DID include Option 1, it should add the tag of 'Is like 1'.

What I am seeing is that all the entries are being tagged with 'Not like 1'.

![screenshot-local mautic3-2020 08 14-22_16_15](https://user-images.githubusercontent.com/2930593/90293434-f4586980-de7b-11ea-8d07-c12c2e46dd22.png)

![screenshot-local mautic3-2020 08 14-22_16_40](https://user-images.githubusercontent.com/2930593/90293441-f6bac380-de7b-11ea-821f-ad87d7fab5c0.png)

![screenshot-local mautic3-2020 08 14-22_17_14](https://user-images.githubusercontent.com/2930593/90293447-f8848700-de7b-11ea-8d7a-6fbe4cbb1b0c.png)

So I was not able to reproduce what I understand to be the correct behaviour that this PR introduces.

Please do correct me if my understanding is wrong!

2020-08-15 16:33 UTC, kuzmany commented
@RCheesley 
But form condition in campaign make condition based an all form results for contact.
That means If your contact has 3 form submission, condition make query based on all 3. Not just sended.
That means If at least one result passed, then go true.
I think works correctly based on your screenshot.

2020-08-28 12:11 UTC, RCheesley commented
@cla-bot check

2021-07-06 15:54 UTC, RCheesley commented
@kuzmany we would like to consider this for the 4.1 release however there is insufficient test coverage for us to add it to the milestone. 

Will you be able to address this please?

Thanks!

2023-12-15 11:17 UTC, kuzmany commented
Close favor to M5 version https://github.com/mautic/mautic/pull/13079

2023-12-15 11:17 UTC, closed without merging