Show publish icons only when having proper permissions.
mautic/mautic pull request #6925
Opened 2018-11-26 13:14 UTC by srdecny

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #3781 
 BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
The publish button was displayed even in cases user did not have proper permissions. This PR fixes this.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new user without any permissions.
2. For every item in left menu (Assets, Forms, Marketing Messages, etc...) set the new user's permissions to View own/View Other/View.
3. For every item in left menu, the publish button can be still seen, although it does nothing when clicked (a spinning wheel animation pops up indefinitely).

#### Steps to test this PR:
1. Apply this PR
2. Repeat reproduce steps
3. The publish button should not be visible now.

#### Backwards compatibility breaks:
I've modified the `app/bundles/CoreBundle/Views/Standard/list.html.php` file. This is apparently used only for Marketing Messages, but if anyone else uses this "default" template, they might have some problems, since the template now checks for `permissions[$permissionBase.':publish']`.

2019-01-30 22:39 UTC, alanhartless requested changes
Can you please use the following format to keep it consistent with the rest of the templates with mixed PHP/HTML? 

```
if (...):
// stuff
endif;
```

2019-02-11 15:21 UTC, srdecny commented
I've fixed the formatting, hopefully I did that correctly and completely.

2019-04-05 08:27 UTC, npracht commented
@srdecny can you have a look at the conflicts and solves them please ?
Thanks !

2019-05-19 18:54 UTC, kuzmany commented
Conflicts not resolved. 
PR moved to next release

2020-03-09 21:55 UTC, RCheesley commented
Maybe consider for 2.16.1 if conflicts can be resolved @dennisameling ?

2020-03-18 09:50 UTC, RCheesley commented
@srdecny do you think you could take a look at the conflicts so that we might be able to test & get this merged in 2.16.1? Many thanks!

2020-03-18 11:07 UTC, srdecny commented
> @srdecny do you think you could take a look at the conflicts so that we might be able to test & get this merged in 2.16.1? Many thanks!

Unfortunately not, I've moved away from Mautic and am too busy.

2020-03-18 11:48 UTC, RCheesley commented
> > @srdecny do you think you could take a look at the conflicts so that we might be able to test & get this merged in 2.16.1? Many thanks!
> 
> Unfortunately not, I've moved away from Mautic and am too busy.

Ah OK, no worries I'll see if we can get it picked up by someone else - thanks for replying!

2020-04-04 08:10 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-20 09:54 UTC, npracht commented
Hello @srdecny could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

2020-08-25 16:48 UTC, RCheesley commented
@cla-bot check

2020-09-19 17:17 UTC, RCheesley commented
Due to the original poster not being able to address the conflicts and there being no other activity, I'm going to close this PR down.

2020-09-19 17:17 UTC, closed without merging