Fix #7045 - API access to list custom fields
mautic/mautic pull request #7046
Opened 2018-12-22 18:57 UTC by pjeby

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #7045 
| BC breaks? | 
| Deprecations? | 

#### Description:
Listing custom fields via the API currently requires **full admin access**; even specifying the "Manage" permission for custom fields is insufficient.  This PR adds the missing `view` permission (fixing the admin privilege requirement), and makes it possible to grant *only* that permission to a role (so you can allow reading the field list without also allowing field management).

#### Steps to reproduce the bug:
1. Create a role without admin privileges, but with "Custom Fields - Manage"
2. Create a user with that role
3. Fetch /api/fields/contact using that user's credentials and see a 403 error

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a role without admin privileges, and either the View or Manage permissions for Custom Fields
3. Fetch /api/fields/contact using that user's credentials and see the field list

2019-01-30 22:36 UTC, alanhartless commented
Let's make them viewable in https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Controller/FieldController.php#L30 for permission consistency sake.

2019-01-30 22:36 UTC, alanhartless requested changes
Let's make them viewable in https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Controller/FieldController.php#L30 for permission consistency sake.

2019-01-30 23:00 UTC, pjeby commented
Do you mean just changing the `:full` to `:view` in those two lines, or something more complex?  The `$permissions` array is passed through to the view, but I'm not sure what it uses it for or how it might be affected by just replacing `full` with `view`.

2019-03-11 23:16 UTC, pjeby commented
@alanhartless : Just an FYI... I'm still waiting on clarification as to what you want changed.  Do you literally just want the two insances of `:full` changed to `:view` or is there something more complex to be done?  As I mentioned above, the `$permissions` are fetched as an array, which is then passed through to the view, so I'm not sure if just making the obvious change is the right thing to do.  Any clarification there would be helpful.  Thanks!

2019-03-15 14:33 UTC, alanhartless commented
@pjeby sorry for the delayed response. I think if we just change full to view here https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Controller/FieldController.php#L32 so that people with view permissions can see the list. 

Then, in the template, change the defaults to only edit or delete with full permission.

https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Views/Field/list.html.php#L54

```
                                'templateButtons' => [
                                    'edit'   => $view['security']->isGranted('lead:fields:full'),
                                    'clone'  => $view['security']->isGranted('lead:fields:full'),
                                    'delete' => $item->isFixed() ? false : $view['security']->isGranted('lead:fields:full'),
                                ],
```

I think that should do it.

2019-03-15 17:01 UTC, pjeby commented
The problem I was talking about was [here](https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Views/Field/list.html.php#L30): the view referenced a `$permissions` array whose contents would be different if [this](https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Controller/FieldController.php#L32) line changed to a different field.  But I figured it out after tracking down isGranted; just need to request both permissions initially, and then reference them in the view.

Anyway, I *think* I figured it out; thanks for the assist!

2020-03-09 21:59 UTC, RCheesley commented
I believe the changes requested were made although it seems to suggest they are still pending. Will tag this for potential inclusion in 2.16.1

2020-03-09 22:16 UTC, pjeby commented
Yes, the changes were made; does the original reviewer need to be the one to note that review?  @alanhartless is shown as being a requested reviewer.

2020-03-16 19:30 UTC, alanhartless commented
@pjeby I think the only two things I see now are:

1) It'll need a migration to ensure that roles that have full access also has view access without having to re-save the role. A higher bit doesn't automatically give permission as this is done code side when the role is saved. https://github.com/mautic/mautic/blob/0d5888471364e3d20a145089fba64f4fa515073f/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php#L145

2) It'll also need some code to ensure that "view" permission is inherited automatically if someone configures "full" without checking the "view." https://github.com/mautic/mautic/blob/03643f39c26d3788b898bb8e5fa77046e7c740b5/app/bundles/LeadBundle/Security/Permissions/LeadPermissions.php#L85

2020-03-16 20:36 UTC, pjeby commented
I've changed the code so that either `full` or `view` permissions are allowed API access.  I'm not clear on why a migration or other change would be required for that, since anyone who already has the "full" permission will retain the ability to view the list.

2020-04-04 08:09 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-20 09:54 UTC, npracht commented
Hello @pjeby could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

2020-06-12 06:33 UTC, patrykgruszka commented
Hi @pjeby could you please resolve the conflicts with 3.x branch? I will test your changes and leave my review. This is crucial when API integration requires access to view custom fields. You need to grant full system privileges, which creates an security issue.

2020-07-16 20:13 UTC, RCheesley commented
@patrykgruszka if there is no response from @pjeby can you resolve the conflicts in a new PR? Would be great to get this fixed!

2020-08-13 12:46 UTC, tomekkowalczyk commented
@patrykgruszka @RCheesley I correct PR with PR #9078

2020-08-15 09:48 UTC, npracht commented
Closing in favor of https://github.com/mautic/mautic/pull/9078

2020-08-15 09:48 UTC, closed without merging