Generated columns
mautic/mautic pull request #7094
Opened 2019-01-03 12:39 UTC by escopecz

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR is adding a [generated column](https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html) based on `email_stats.date_sent`. It will generate the value in format `Y-m-d` and build a new index from it. Then it modifies the line chart queries to use that column instead of formatting the original date.

Original query to load line chart data from email stats table:
```
SELECT DATE_FORMAT(t.date_sent, '%Y-%m-%d') AS date, COUNT(*) AS count FROM mautic_email_stats t WHERE (t.email_id IN (3)) AND (t.date_sent BETWEEN :dateFrom AND :dateTo) GROUP BY DATE_FORMAT(t.date_sent, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.date_sent, '%Y-%m-%d') ASC LIMIT 31
```

New query based on the generated column:
```
SELECT t.generated_sent_date AS date, COUNT(*) AS count FROM mautic_email_stats t WHERE (t.email_id IN (3)) AND (t.date_sent BETWEEN :dateFrom AND :dateTo) GROUP BY t.generated_sent_date ORDER BY t.generated_sent_date ASC LIMIT 31
```

The speed improvement for the select query is somewhere around 3,5x faster. To be more specific, running the query on that 6.6M row table took ~700ms. With this PR it loads in ~200ms.

I've tested adding the new generated column on a email_stats table with 6.6M rows and it took 172 seconds to add it. So it should not cause any troubles to migrate even big instances. But do not use the UI updater. Use the script!

This is an experiment. If we find that it's not causing any troubles we should implement it also for date_read and other date columns in other stat tables used in the line charts.

#### Steps to test this PR:
1. Ensure you can see the generated column definition when viewing the schema changes. You should see something like this:
```
$ app/console doctrine:schema:update --dump-sql | grep generated
ALTER TABLE mautic_email_stats ADD generated_sent_date DATE AS (CONCAT(YEAR(date_sent), "-", LPAD(MONTH(date_sent), 2, "0"), "-", LPAD(DAY(date_sent), 2, "0"))) COMMENT '(DC2Type:generated)';
CREATE INDEX mautic_generated_sent_date_email_id ON mautic_email_stats (generated_sent_date, email_id);
```
2. Run the migration. Generated fields doesn't have a migration file because we don't know whether the database supports generated fields. So we check the database version and run the alter table queries only if the database supports it. You should see this during migration:
```
$ app/console doctrine:migration:migrate

++ adding generated column generated_sent_date
-> ALTER TABLE mautic_email_stats
            ADD generated_sent_date DATE AS (CONCAT(YEAR(date_sent), "-", LPAD(MONTH(date_sent), 2, "0"), "-", LPAD(DAY(date_sent), 2, "0"))) COMMENT '(DC2Type:generated)',
            ADD index `mautic_generated_sent_date_email_id`(generated_sent_date, email_id)
++ generated column added (generated columns: 60.00 MiB - 36 ms)
                    Mautic Migrations
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)No migrations to execute.
```

3. Load a segment email detail page, report based on email stats with the line chart and dashboard with the emails sent widget. All should load correctly (hopefully faster than before) and it should show the same values as before. Test also the sent email dashboard widget and report widget. All time units should still work.

2019-08-15 15:53 UTC, npracht commented
Travis my love...

2019-08-16 07:51 UTC, escopecz commented
Honestly, I don't know what to do with Travis in this case. It passes all tests on my local. Maybe a database version issue? I'd appreciate any idea how to fix it.

2020-03-09 21:39 UTC, RCheesley commented
@escopecz looking like we've got some conflicts with this one too - presume it's going to need refactoring for potential inclusion with 3.1

2020-04-06 06:49 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-12 13:55 UTC, npracht commented
Hi @escopecz is this still relevant for M3 ?
Thanks !

2020-05-12 16:03 UTC, escopecz commented
Probably

2020-06-08 09:45 UTC, TravisBuddy commented
Hey @escopecz,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;builds&#x2F;695947045">View build log</a>

###### TravisBuddy Request Identifier: d74f4500-a96c-11ea-9161-4f77e253115e

2020-06-08 09:48 UTC, TravisBuddy commented
Hey @escopecz,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;builds&#x2F;695948042">View build log</a>

###### TravisBuddy Request Identifier: 44e020d0-a96d-11ea-9161-4f77e253115e

2020-06-08 09:59 UTC, TravisBuddy commented
Hey @escopecz,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;builds&#x2F;695951759">View build log</a>

###### TravisBuddy Request Identifier: c13f9dd0-a96e-11ea-9161-4f77e253115e

2020-06-08 10:01 UTC, TravisBuddy commented
Hey @escopecz,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;builds&#x2F;695952404">View build log</a>

###### TravisBuddy Request Identifier: 0ed9cc00-a96f-11ea-9161-4f77e253115e

2020-06-08 10:03 UTC, TravisBuddy commented
Hey @escopecz,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;builds&#x2F;695952935">View build log</a>

###### TravisBuddy Request Identifier: 5015a040-a96f-11ea-9161-4f77e253115e

2020-06-08 11:16 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;695970631">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................EEEEEEE......................................   61 / 1736 (  3%)
.............................................................  122 / 1736 (  7%)
............E..................................EE............  183 / 1736 ( 10%)
...........................E.................................  244 / 1736 ( 14%)
.........................................................SS..  305 / 1736 ( 17%)
.............................................................  366 / 1736 ( 21%)
.........................................................SS..  427 / 1736 ( 24%)
.............................................................  488 / 1736 ( 28%)
.........PHP Warning - count(): Parameter must be an array or an object that implements Countable - in file /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/unit/Doctrine/Provider/GeneratedColumnsProviderTest.php - at line 75
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/unit/Doctrine/Provider/GeneratedColumnsProviderTest.php on line 75
...............................E....................  549 / 1736 ( 31%)
.............................................................  610 / 1736 ( 35%)
.............................................................  671 / 1736 ( 38%)
.............................................................  732 / 1736 ( 42%)
.........................................E...................  793 / 1736 ( 45%)
...................EE........................................  854 / 1736 ( 49%)
.............................................................  915 / 1736 ( 52%)
.............................................................  976 / 1736 ( 56%)
............................................................. 1037 / 1736 ( 59%)
....................E..EEEEEE................................ 1098 / 1736 ( 63%)
.........EEEEEE.............................................. 1159 / 1736 ( 66%)
.......................................................EEEE.. 1220 / 1736 ( 70%)
..................EEE.........E.........................EE... 1281 / 1736 ( 73%)
............................................................. 1342 / 1736 ( 77%)
................EEEEEEEEEEEEE................................ 1403 / 1736 ( 80%)
...................................E......................... 1464 / 1736 ( 84%)
......................E...................................... 1525 / 1736 ( 87%)
............................................................. 1586 / 1736 ( 91%)
........F.................................................... 1647 / 1736 ( 94%)
.........E...............EEEEEE......EEEEEEEEEEEEEEEEEEEEEEEE 1708 / 1736 ( 98%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEE                                  1736 / 1736 (100%)

Time: 1.1 minutes, Memory: 985.00 MB

There were 112 errors:

1) Mautic\CampaignBundle\Tests\Command\ExecuteEventCommandTest::testEventsAreExecutedForInactiveEventWithSingleContact
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50

2) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForAll
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

3) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForOne
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.p [...]

2020-06-09 12:10 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;696431561">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................EEEEEEE......................................   61 / 1736 (  3%)
.............................................................  122 / 1736 (  7%)
............E..................................EE............  183 / 1736 ( 10%)
...........................E.................................  244 / 1736 ( 14%)
.........................................................SS..  305 / 1736 ( 17%)
.............................................................  366 / 1736 ( 21%)
.........................................................SS..  427 / 1736 ( 24%)
.............................................................  488 / 1736 ( 28%)
.........F..............................E....................  549 / 1736 ( 31%)
.............................................................  610 / 1736 ( 35%)
.............................................................  671 / 1736 ( 38%)
.............................................................  732 / 1736 ( 42%)
.........................................E...................  793 / 1736 ( 45%)
...................EE........................................  854 / 1736 ( 49%)
.............................................................  915 / 1736 ( 52%)
.............................................................  976 / 1736 ( 56%)
............................................................. 1037 / 1736 ( 59%)
....................E..EEEEEE................................ 1098 / 1736 ( 63%)
.........EEEEEE.............................................. 1159 / 1736 ( 66%)
.......................................................EEEE.. 1220 / 1736 ( 70%)
..................EEE.........E.........................EE... 1281 / 1736 ( 73%)
............................................................. 1342 / 1736 ( 77%)
................EEEEEEEEEEEEE................................ 1403 / 1736 ( 80%)
...................................E......................... 1464 / 1736 ( 84%)
......................E...................................... 1525 / 1736 ( 87%)
............................................................. 1586 / 1736 ( 91%)
........F.................................................... 1647 / 1736 ( 94%)
.........E...............EEEEEE......EEEEEEEEEEEEEEEEEEEEEEEE 1708 / 1736 ( 98%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEE                                  1736 / 1736 (100%)

Time: 1.12 minutes, Memory: 985.00 MB

There were 112 errors:

1) Mautic\CampaignBundle\Tests\Command\ExecuteEventCommandTest::testEventsAreExecutedForInactiveEventWithSingleContact
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50

2) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForAll
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

3) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForOne
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

4) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForSome
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendo [...]

2020-06-20 09:34 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;700316596">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................EEEEEEE......................................   61 / 1746 (  3%)
.............................................................  122 / 1746 (  6%)
..............E..................................EE..........  183 / 1746 ( 10%)
.............................E...............................  244 / 1746 ( 13%)
...........................................................SS  305 / 1746 ( 17%)
.............................................................  366 / 1746 ( 20%)
............................................................S  427 / 1746 ( 24%)
S............................................................  488 / 1746 ( 27%)
............PHP Notice - Undefined offset: 0 - in file /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php - at line 69
PHP Notice:  Undefined offset: 0 in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php on line 69
E..............................E.................  549 / 1746 ( 31%)
.............................................................  610 / 1746 ( 34%)
.............................................................  671 / 1746 ( 38%)
.............................................................  732 / 1746 ( 41%)
............................................E................  793 / 1746 ( 45%)
......................EE.....................................  854 / 1746 ( 48%)
.............................................................  915 / 1746 ( 52%)
.............................................................  976 / 1746 ( 55%)
............................................................. 1037 / 1746 ( 59%)
.......................E..EEEEEE............................. 1098 / 1746 ( 62%)
............EEEEEE........................................... 1159 / 1746 ( 66%)
..........................................................EEE 1220 / 1746 ( 69%)
E....................EEE.........E.........................EE 1281 / 1746 ( 73%)
............................................................. 1342 / 1746 ( 76%)
...................EEEEEEEEEEEEE............................. 1403 / 1746 ( 80%)
......................................E...................... 1464 / 1746 ( 83%)
.............................E............................... 1525 / 1746 ( 87%)
............................................................. 1586 / 1746 ( 90%)
...............F............................................. 1647 / 1746 ( 94%)
................E...............EEEEEE......EEEEEEEEEEEEEEEEE 1708 / 1746 ( 97%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE...                        1746 / 1746 (100%)

Time: 1.1 minutes, Memory: 999.00 MB

There were 113 errors:

1) Mautic\CampaignBundle\Tests\Command\ExecuteEventCommandTest::testEventsAreExecutedForInactiveEventWithSingleContact
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50

2) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForAll
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

3) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForOne
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

4) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForSome
Doctrine\DBAL\Schema\SchemaException: The [...]

2020-06-25 10:17 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;701973119">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................EEEEEEE......................................   61 / 1748 (  3%)
.............................................................  122 / 1748 (  6%)
..............E..................................EE..........  183 / 1748 ( 10%)
.............................E...............................  244 / 1748 ( 13%)
...........................................................SS  305 / 1748 ( 17%)
.............................................................  366 / 1748 ( 20%)
.............................................................  427 / 1748 ( 24%)
SS...........................................................  488 / 1748 ( 27%)
.............PHP Notice - Undefined offset: 0 - in file /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php - at line 69
PHP Notice:  Undefined offset: 0 in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php on line 69
E..............................E................  549 / 1748 ( 31%)
.............................................................  610 / 1748 ( 34%)
.............................................................  671 / 1748 ( 38%)
.............................................................  732 / 1748 ( 41%)
.............................................E...............  793 / 1748 ( 45%)
.......................EE....................................  854 / 1748 ( 48%)
.............................................................  915 / 1748 ( 52%)
.............................................................  976 / 1748 ( 55%)
............................................................. 1037 / 1748 ( 59%)
........................E..EEEEEE............................ 1098 / 1748 ( 62%)
.............EEEEEE.......................................... 1159 / 1748 ( 66%)
...........................................................EE 1220 / 1748 ( 69%)
EE....................EEE.........E.........................E 1281 / 1748 ( 73%)
E............................................................ 1342 / 1748 ( 76%)
....................EEEEEEEEEEEEE............................ 1403 / 1748 ( 80%)
.......................................E..................... 1464 / 1748 ( 83%)
..............................E.............................. 1525 / 1748 ( 87%)
............................................................. 1586 / 1748 ( 90%)
................F............................................ 1647 / 1748 ( 94%)
.................E...............EEEEEE......EEEEEEEEEEEEEEEE 1708 / 1748 ( 97%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE....                      1748 / 1748 (100%)

Time: 1.52 minutes, Memory: 1.01 GB

There were 113 errors:

1) Mautic\CampaignBundle\Tests\Command\ExecuteEventCommandTest::testEventsAreExecutedForInactiveEventWithSingleContact
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50

2) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForAll
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

3) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForOne
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'generated_sent_date' on table 'email_stats'.

/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:272
/home/travis/build/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:135
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:309
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:113
/home/travis/build/mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:91
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:139
/home/travis/build/mautic/mautic/vendor/liip/test-fixtures-bundle/src/Test/FixturesTrait.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php:138
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:77
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:61
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:26
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php:50
/home/travis/build/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:18

4) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForSome
Doctrine\DB [...]

2020-06-25 13:12 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;702014264">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.............................................................   61 / 1748 (  3%)
.............................................................  122 / 1748 (  6%)
.............................................................  183 / 1748 ( 10%)
.............................................................  244 / 1748 ( 13%)
...........................................................SS  305 / 1748 ( 17%)
.............................................................  366 / 1748 ( 20%)
.............................................................  427 / 1748 ( 24%)
SS...........................................................  488 / 1748 ( 27%)
.............PHP Notice:  Undefined offset: 0 in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php on line 69
E...............................................  549 / 1748 ( 31%)
.............................................................  610 / 1748 ( 34%)
.............................................................  671 / 1748 ( 38%)
.............................................................  732 / 1748 ( 41%)
.............................................................  793 / 1748 ( 45%)
.......................S.....................................  854 / 1748 ( 48%)
.............................................................  915 / 1748 ( 52%)
.............................................................  976 / 1748 ( 55%)
............................................................. 1037 / 1748 ( 59%)
............................................................. 1098 / 1748 ( 62%)
............................................................. 1159 / 1748 ( 66%)
............................................................. 1220 / 1748 ( 69%)
............................................................. 1281 / 1748 ( 73%)
............................................................. 1342 / 1748 ( 76%)
............................................................. 1403 / 1748 ( 80%)
............................................................. 1464 / 1748 ( 83%)
............................................................. 1525 / 1748 ( 87%)
............................................................. 1586 / 1748 ( 90%)
............................................................. 1647 / 1748 ( 94%)
............................................................. 1708 / 1748 ( 97%)
........................................                      1748 / 1748 (100%)

Time: 15.77 minutes, Memory: 977.00 MB

There was 1 error:

1) Mautic\CoreBundle\Tests\Unit\Doctrine\Provider\GeneratedColumnsProviderTest::testGetGeneratedColumnsIfSupported
Error: Call to a member function getTableName() on null

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/unit/Doctrine/Provider/GeneratedColumnsProviderTest.php:89

ERRORS!
Tests: 1748, Assertions: 5138, Errors: 1, Skipped: 5.

Generating code coverage report in Clover XML format ... done

THE ERROR HANDLER HAS CHANGED!
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml handling the test event returned with error code 2
travis_time:end:098a8800:start=1593089525540428656,finish=1593090483103441626,duration=957563012970,event=script
```

</details>


###### TravisBuddy Request Identifier: 7799b6f0-b6e5-11ea-bb0d-6965ce86ea0c

2020-06-25 13:36 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: e629abe0-b6e8-11ea-bb0d-6965ce86ea0c

2020-06-25 15:14 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 7e9140c0-b6f6-11ea-bb0d-6965ce86ea0c

2020-06-25 16:06 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;702083119">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.............................................................   61 / 1748 (  3%)
.............................................................  122 / 1748 (  6%)
.............................................................  183 / 1748 ( 10%)
.............................................................  244 / 1748 ( 13%)
.....E.E..................EEEEEEE............................  305 / 1748 ( 17%)
..............SS.............................................  366 / 1748 ( 20%)
.............................................................  427 / 1748 ( 24%)
................SS...........................................  488 / 1748 ( 27%)
.............................................................  549 / 1748 ( 31%)
.............................................................  610 / 1748 ( 34%)
.............................................................  671 / 1748 ( 38%)
.............................................................  732 / 1748 ( 41%)
.............................................................  793 / 1748 ( 45%)
.......................S.....................................  854 / 1748 ( 48%)
.............................................................  915 / 1748 ( 52%)
.............................................................  976 / 1748 ( 55%)
............................................................. 1037 / 1748 ( 59%)
............................................................. 1098 / 1748 ( 62%)
............................................................. 1159 / 1748 ( 66%)
............................................................. 1220 / 1748 ( 69%)
............................................................. 1281 / 1748 ( 73%)
............................................................. 1342 / 1748 ( 76%)
............................................................. 1403 / 1748 ( 80%)
............................................................. 1464 / 1748 ( 83%)
............................................................. 1525 / 1748 ( 87%)
............................................................. 1586 / 1748 ( 90%)
............................................................. 1647 / 1748 ( 94%)
............................................................. 1708 / 1748 ( 97%)
........................................                      1748 / 1748 (100%)

Time: 15.96 minutes, Memory: 979.00 MB

There were 9 errors:

1) Mautic\CoreBundle\Tests\Unit\Doctrine\Mapping\GeneratedColumn\GeneratedColumnsTest::testAllGettersAndSeters
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/Doctrine/Mapping/GeneratedColumn/GeneratedColumnsTest.php:32

2) Mautic\CoreBundle\Tests\Unit\Doctrine\Provider\GeneratedColumnsProviderTest::testGetGeneratedColumnsIfSupported
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Event/GeneratedColumnsEvent.php:39
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/Doctrine/Provider/GeneratedColumnsProviderTest.php:86
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/Provider/GeneratedColumnsProvider.php:68
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/Doctrine/Provider/GeneratedColumnsProviderTest.php:93

3) Mautic\CoreBundle\Tests\Unit\EventListener\DoctrineGeneratedColumnsListenerTest::testPostGenerateSchemaWhenTableDoesNotExist
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/EventListener/DoctrineGeneratedColumnsListenerTest.php:54

4) Mautic\CoreBundle\Tests\Unit\EventListener\DoctrineGeneratedColumnsListenerTest::testPostGenerateSchemaWhenColumnExists
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/EventListener/DoctrineGeneratedColumnsListenerTest.php:54

5) Mautic\CoreBundle\Tests\Unit\EventListener\DoctrineGeneratedColumnsListenerTest::testPostGenerateSchemaWhenColumnDoesNotExist
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/EventListener/DoctrineGeneratedColumnsListenerTest.php:54

6) Mautic\CoreBundle\Tests\Unit\EventListener\MigrationCommandSubscriberTest::testAddGeneratedColumnsWillRunOnlyForMigrationCommand
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/EventListener/MigrationCommandSubscriberTest.php:98

7) Mautic\CoreBundle\Tests\Unit\EventListener\MigrationCommandSubscriberTest::testAddGeneratedColumnsWhenNotSupported
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumns.php:42
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/EventListener/MigrationCommandSubscriberTest.php:98

8) Mautic\CoreBundle\Tests\Unit\EventListener\MigrationCommandSubscriberTest::testAddGeneratedColumnsWhenExistsAlready
TypeError: Return value of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn() must be of the type string, null returned

/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:91
/home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doct [...]

2020-06-25 16:17 UTC, TravisBuddy commented
## Travis tests have failed

Hey @escopecz,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;702090871">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.............................................................   61 / 1748 (  3%)
.............................................................  122 / 1748 (  6%)
.............................................................  183 / 1748 ( 10%)
.............................................................  244 / 1748 ( 13%)
....PHP Fatal error:  Declaration of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn(): ?string must be compatible with Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumnInterface::getOriginalDateColumn(): string in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php on line 16
PHP Notice: Declaration of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn(): ?string must be compatible with Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumnInterface::getOriginalDateColumn(): string - in file /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php - at line 16
Symfony\Component\Debug\Exception\FatalErrorException: Notice: Declaration of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn(): ?string must be compatible with Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumnInterface::getOriginalDateColumn(): string - in file /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php - at line 16
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Compile Error: Declaration of Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumn::getOriginalDateColumn(): ?string must be compatible with Mautic\CoreBundle\Doctrine\GeneratedColumn\GeneratedColumnInterface::getOriginalDateColumn(): string in /home/travis/build/mautic/mautic/app/bundles/CoreBundle/Doctrine/GeneratedColumn/GeneratedColumn.php:16
Stack trace:
#0 {main}

Next Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "kernel" service is synthetic, it needs to be set at boot time before it can be used. in /home/travis/build/mautic/mautic/vendor/symfony/dependency-injection/Container.php:334
Stack trace:
#0 /home/travis/build/mautic/mautic/var/cache/test/ContainerWoqwd6t/appTestDebugProjectContainer.php(9416): Symfony\Component\DependencyInjection\Container->get('kernel', 1)
#1 /home/travis/build/mautic/mautic/vendor/symfony/dependency-injection/Container.php(306): ContainerWoqwd6t\appTestDebugProjectContain in /home/travis/build/mautic/mautic/vendor/symfony/dependency-injection/Container.php on line 334

THE ERROR HANDLER HAS CHANGED!
    <div class="row">
                <div class="col-xs-12">
            <h3><i class="fa fa-warning fa-fw text-danger"></i>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h3>
                        <h4 class="mt-15">System administrators, check server logs for errors.</h4>
                    </div>
            </div>
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --coverage-clover=coverage.xml handling the test event returned with error code 255
```

</details>


###### TravisBuddy Request Identifier: 69e20fc0-b6ff-11ea-bb0d-6965ce86ea0c

2020-08-07 09:40 UTC, escopecz commented
FWY there are some critical fixes that we cannot provide to the community until this will be merged.

2020-08-07 09:51 UTC, npracht commented
Then this should be a priority for 3.1.0

2020-08-08 20:18 UTC, dennisameling requested changes
Code LGTM, just left a comment about the minimal MariaDB version.

Note for 2nd reviewer: **this PR can NOT be reviewed on Mautibox because the DB migration needs to be applied manually.**

@escopecz you're right about the DB version check. While we do check for the DB version in the M2 > M3 upgrade script, we don't check it during installation. Added that to https://github.com/mautic/mautic/issues/8452 for later consideration. One minor thing is that the "[Community Release Leader](https://docs.google.com/document/d/11psNpVYpcn4m9ZxyD_a5panpK_A9bHsBrqXNAXjMCwo/edit?pli=1#)" document indicates that DB changes should have DB migrations. I added a link to this PR as an exclusion to that rule. In the future, when we have a DB version check in the installation/update process, the logic should be moved there and a DB migration generated for this functionality IMO.

Tested the PR by applying the migration. The new column is created successfully on MariaDB 10.2:

![image](https://user-images.githubusercontent.com/17739158/89718961-d1354200-d9c3-11ea-87aa-b36735adc209.png)

The "emails in time" widget on the dashboard also works as expected:

![image](https://user-images.githubusercontent.com/17739158/89718977-f5911e80-d9c3-11ea-819a-1d508338b3d8.png)

Only thing is that the line chart below is empty, but it was already empty prior to applying this PR. So I'm assuming that I just don't have enough data in my local instance for that graph to render.

![image](https://user-images.githubusercontent.com/17739158/89718989-10639300-d9c4-11ea-8215-e047b86cfdff.png)

2020-08-08 20:18 UTC, dennisameling commented on app/bundles/CoreBundle/Doctrine/Provider/GeneratedColumnsProvider.php
> +    const MARIADB_MINIMUM_VERSION = '5.2';
Shouldn't this be 10.2 (see https://mariadb.com/kb/en/generated-columns)?

> In MariaDB 10.2 and later, the syntax is also compatible with the syntax for MySQL's generated columns.

2020-08-14 19:29 UTC, kuzmany submitted a review, later dismissed
I've tested it and works like describe. 
Column was created, indexed and query looks use it.

2020-08-17 10:47 UTC, escopecz commented
@dennisameling good catch. No idea how I missed it. There is even a link to that page in the constant's comment. Fixed.

2020-08-17 12:41 UTC, dennisameling approved these changes

2020-08-17 12:42 UTC, merged