Add not exist greater than/ less then for segment filters
mautic/mautic pull request #7126
Opened 2019-01-11 22:16 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added segment filter not exist greater than/less then.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2019-01-30 23:17 UTC, alanhartless requested changes

2019-01-30 23:17 UTC, alanhartless commented on app/bundles/LeadBundle/Entity/OperatorListTrait.php
> +    public function modifyOperators($operatorOption)
I'm not sure I'm a fan of this. I know we use inherited trait methods in other places in older code but it's not considered very "clean" by today's standards, especially with a pass by referenced array. I think the cleaner solution for this scenario is to pass an optional array into getFilterExpressionFunctions that gets merged into `$operatorOption`.

2019-01-30 23:17 UTC, alanhartless commented on app/bundles/LeadBundle/Entity/OperatorListTrait.php
> +    public function modifyOperators($operatorOption)
Or consider refactoring away from this trait.

2020-04-06 06:48 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-08-28 12:10 UTC, RCheesley commented
@cla-bot check

2021-01-25 06:52 UTC, kuzmany commented
This PR need rewrite with use new listeners once after merge Segments refactoring https://github.com/mautic/mautic/pull/8649

Then I close it at the moment

2021-01-25 06:52 UTC, closed without merging