7177: Implemented method to bind parameters when using "where in" exp…
mautic/mautic pull request #7182
Opened 2019-01-30 08:20 UTC by DanielCiochiu

…ression

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? |
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: When building Leads, ExpressionBuilder got an array of strings which resulted into a MySql syntax error due to missing quotes. Added a method to CommonRepository which receives an array (either indexed or associative) and returns an associative array consisting of bounding keys and there corresponding values

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. php app/console mautic:citrix:sync --env=prod

#### Steps to test this PR:
1. php app/console mautic:citrix:sync --env=prod

#### List deprecations along with the new alternative: none
#### List backwards compatibility breaks: none

Courtesy of GosuTeacher.

2019-01-30 23:26 UTC, alanhartless requested changes

2019-01-31 04:19 UTC, DanielCiochiu commented on app/bundles/CoreBundle/Entity/CommonRepository.php
> +        foreach ($valuesArray as $key => &$value) {
Right. Not needed. Updated code.

2019-03-11 03:41 UTC, alanhartless approved these changes

2019-04-24 21:07 UTC, escopecz commented
Based on the conflict it looks like this same issue was resolved by https://github.com/mautic/mautic/pull/7430 which was merged a few hours ago. @kuzmany shall we close this?

2019-04-24 21:09 UTC, closed without merging