Real-time campaign events triggering
mautic/mautic pull request #7213
Opened 2019-02-04 18:25 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

- [x] add migrations

This PR allow trigger events immediately after contact is added to campaign.

![image](https://user-images.githubusercontent.com/462477/52228606-0d5d8300-28b3-11e9-9510-dc8cf25f8347.png)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7213). 
If use own test enviroment `run php app/console doctrine:migrations:migrate`
2. Create campaign with some events (actions/conditions) and enable option `Trigger event's realtime`
3. Add contact to campaign
4. See If events are triggered immediately after contact was added to campaign
5. Then disable option. Add another contact to campaigna and see If events are not triggered immediately. I would by wait for cron

2019-02-06 13:36 UTC, indorock approved these changes

2019-02-06 13:37 UTC, indorock reviewed
looks good

2019-02-06 13:37 UTC, indorock submitted a review, later dismissed
looks good

2019-02-06 16:26 UTC, alanhartless commented
What is the use case for this? 

What happens if your cron jobs to build the campaign membership overlap your cron job to execute the campaign?

2019-02-13 10:47 UTC, indorock commented
@alanhartless we have implemented Mautic with the goal of handling all user-directed emails, including system emails like email verify and password reset emails. Currently even with our cronjob set up at tight intervals, it still takes upwards of 5-10 minutes for one of these emails to reach the user. So we asked @kuzmany to come up with a solution that would fire an email instantly, not reliant on waiting for the email cron job to run.

Regarding your second question, he informed me that it would behave as normal. His words: 

> It's the same workflow like mautic:campaign:trigger but this campaign is triggered for contact after add to campaign . But the code is the same, like If you wait to cron

2020-04-06 06:46 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-08-28 12:09 UTC, RCheesley commented
@cla-bot check

2021-01-30 00:14 UTC, hrouissi commented
Hi there!
Any update on this feature?
This is an interesting one.

2021-07-06 15:41 UTC, RCheesley requested changes
Grammatical suggestions only - have not reviewed the code or tested.

2021-07-06 15:41 UTC, RCheesley commented on app/bundles/CampaignBundle/Translations/en_US/messages.ini
> +mautic.campaign.trigger_realtime="Trigger events realtime"
```suggestion
mautic.campaign.trigger_realtime="Trigger events in real time"
```

2021-07-06 15:41 UTC, RCheesley commented on app/bundles/CampaignBundle/Translations/en_US/messages.ini
> +mautic.campaign.trigger_realtime.tooltip="Trigger events (actions & conditions) immediately after add to campaign. Warning: Enabled option could impact performance."
```suggestion
mautic.campaign.trigger_realtime.tooltip="Trigger events (actions & conditions) immediately after a contact is added to campaign. Warning: Enabling this option could impact performance."
```

2021-07-06 15:45 UTC, RCheesley commented
@kuzmany this PR needs some work and would require very clear documentation. If you wish us to consider this PR please have it ready for the 4.1 release otherwise let's close the PR if it is no longer required.

2021-11-09 08:56 UTC, kuzmany commented
Close favor to https://github.com/mautic/mautic/pull/10587

2021-11-09 08:56 UTC, closed without merging