Fix issue mautic#7032
mautic/mautic pull request #7365
Opened 2019-03-29 10:12 UTC by leo108

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #7032
| BC breaks? |  No
| Deprecations? |  No

2019-03-29 10:15 UTC, npracht commented
@Enc3phale you having skills in js, can you have a look at the code ?

2019-04-09 18:58 UTC, quintmouthaan requested changes
Please look at my comments and make changes if you agree.

2019-04-09 18:58 UTC, quintmouthaan commented on app/bundles/PageBundle/EventListener/BuildJsSubscriber.php
> +        if (sourceNodes.length === 0) {
by returning here if there is no source node the functionality will still not work, even if the source is specified in the src attribute. I suggest to execute the following couple of lines only if sourceNodes.length > 0 and execute the rest of the function even if sourceNodes.length === 0. That way the functionality will also work for video tags with the src attribute

2019-05-12 10:36 UTC, kuzmany commented
Wasn't double tested before the 2.15.2 PR merge deadline so pushing to the next release.

2019-09-18 12:24 UTC, tenil commented
I was able to reproduce the error.
This fix did not work for me.
V. 2.15.2

2019-09-18 12:24 UTC, ghost requested changes
I was able to reproduce the error.
This fix did not work for me.

2020-03-09 22:11 UTC, RCheesley commented
If this issue persists could you update the PR @leo108 or if they aren't able to do so, maybe @quintmouthaan could pick it up taking into account the recommendations?

2020-04-04 07:53 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-20 09:54 UTC, npracht commented
Hello @leo108 could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

2020-06-23 18:05 UTC, RCheesley commented
@leo108 or @quintmouthaan if this is still an issue could you pick this up

2020-06-28 18:25 UTC, dennisameling commented
Easier steps to reproduce:

- Create a landing page in Mautic
- Add a "Code Mode" block and add the following video block to it:
```HTML
<video src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></video>
```

![image](https://user-images.githubusercontent.com/17739158/85955141-f8d4cb80-b97c-11ea-9822-15662a48a72d.png)

- Open the Landing Page in your browser
- See the error show up:

![image](https://user-images.githubusercontent.com/17739158/85955243-73055000-b97d-11ea-8b56-e92c61128d8c.png)

2020-06-28 19:20 UTC, dennisameling commented
Note: this functionality ([Gated Video](https://docs.mautic.org/en/gated-video)) is designed to only work if the `data-form-id` and `data-gate-time` attributes are set on the video element. All other `<video>` elements should be left intact by Mautic. 

Currently, the logic that checks if a `data-form-id` attribute is set comes too late and should be on top of the function. That is what's causing the issue that's been reported: a video that was embedded on a page that happened to have the Mautic tracking JS on it as well was triggering the reported TypeError. This PR should move up that logic so that the error isn't thrown incorrectly.

Note on @quintmouthaan's comment above:
> That way the functionality will also work for video tags with the src attribute

Problem with this is that even though this might work, the developer would need to set a `data-form-id` on the `<video>` element to trigger this functionality, [as described in the docs](https://docs.mautic.org/en/gated-video#using-gated-video). However, when a developer does that, the following logic isn't triggered so the player won't have any controls for the user:
```JS
node.dataset.mp4 = true;
playerFeatures = ['playpause','progress','current','duration','volume','fullscreen'];
```

Example:
- If a dev would add the following video tag to a page: `<video autoplay src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></video>` ... because the `type` attribute [is not supported on the `<video>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) (only on `<source>` elements), the visitor of the page won't see any video controls.

**TL;DR**: Mautic should ignore all video tags that don't have the `data-form-id` and `data-gate-time` attributes [as described in the docs](https://docs.mautic.org/en/gated-video#using-gated-video). The logic that checks this in the code currently comes a bit too late which results in a `TypeError`, which this PR should fix. Please note that Mautic only supports `<video>` elements with proper `<source>` elements in it for the Gated Video functionality.

@RCheesley should we mention the TL;DR in the docs as well?

2020-06-29 13:18 UTC, RCheesley approved these changes
Tested before with the error and after with no error:

Before:

![Screenshot 2020-06-29 at 14 11 54 (2)](https://user-images.githubusercontent.com/2930593/86010426-4dc32100-ba13-11ea-86fb-0a28b6c9a903.png)

After: 
![Screenshot 2020-06-29 at 14 16 27 (2)](https://user-images.githubusercontent.com/2930593/86010457-57e51f80-ba13-11ea-8e77-623e845b77dc.png)

@dennisameling indeed I feel we should ensure that this is documented!

2020-06-29 13:19 UTC, RCheesley commented
P.S. Awesome video!

2020-06-29 14:57 UTC, merged