WIP: make salesforce sync dnc on first integration download
mautic/mautic pull request #7500
Opened 2019-05-06 09:32 UTC by galvani

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2019-05-06 09:41 UTC, galvani commented
FYI: this has been reviewed by mautic inc. so testing might be the only thing needed.

2019-08-15 15:10 UTC, npracht commented
Hi @galvani is that still `WIP`? Also, can you check travis issue?

2019-08-15 15:32 UTC, galvani commented
@npracht no, you could have merged it, I believe recent merge broke it. I will check on it now.

2020-04-04 07:50 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-20 09:53 UTC, npracht commented
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

2020-09-30 22:39 UTC, RCheesley commented
@cla-bot check

2020-10-15 13:19 UTC, npracht commented
@mautic/acquia-po can someone fix this asap ? Otherwise i'll have to postpone from next release again. Thanks.

2020-10-16 20:18 UTC, TravisBuddy commented
## Travis tests have failed

Hey @galvani,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 4th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;736484672">View build log</a>


<details>
  <summary>
    <strong>
     if [ ${TRAVIS_PHP_VERSION:0:3} &#x3D;&#x3D; &quot;7.3&quot; ]; then composer test -- --coverage-clover&#x3D;coverage.xml &amp;&amp; bash &lt;(curl -s https:&#x2F;&#x2F;codecov.io&#x2F;bash); else composer test; fi
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist '--coverage-clover=coverage.xml'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.............................................................   61 / 1821 (  3%)
.............................................................  122 / 1821 (  6%)
.............................................................  183 / 1821 ( 10%)
.............................................................  244 / 1821 ( 13%)
.............................................................  305 / 1821 ( 16%)
............................SS...............................  366 / 1821 ( 20%)
.............................................................  427 / 1821 ( 23%)
................................SS...........................  488 / 1821 ( 26%)
.............................................................  549 / 1821 ( 30%)
.............................................................  610 / 1821 ( 33%)
.............................................................  671 / 1821 ( 36%)
.............................................................  732 / 1821 ( 40%)
.............................................................  793 / 1821 ( 43%)
.......................................................PHP Warning:  Invalid argument supplied for foreach() in /home/travis/build/mautic/mautic/app/bundles/InstallBundle/Command/InstallCommand.php on line 269
......  854 / 1821 ( 46%)
......S......................................................  915 / 1821 ( 50%)
.............................................................  976 / 1821 ( 53%)
............................................................. 1037 / 1821 ( 56%)
............................................................. 1098 / 1821 ( 60%)
............................................................. 1159 / 1821 ( 63%)
............................................................. 1220 / 1821 ( 66%)
............................................................. 1281 / 1821 ( 70%)
............................................................. 1342 / 1821 ( 73%)
............................................................. 1403 / 1821 ( 77%)
............................................................. 1464 / 1821 ( 80%)
............................................................. 1525 / 1821 ( 83%)
.............................................PHP Warning - "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? - in file /home/travis/build/mautic/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 437
PHP Warning:  "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in /home/travis/build/mautic/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php on line 437
................ 1586 / 1821 ( 87%)
............................................................. 1647 / 1821 ( 90%)
............................................................. 1708 / 1821 ( 93%)
.....................................PHP Warning - array_search() expects parameter 2 to be array, null given - in file /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php - at line 114
PHP Warning:  array_search() expects parameter 2 to be array, null given in /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php on line 114
.RPHP Warning - array_search() expects parameter 2 to be array, null given - in file /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php - at line 127
PHP Warning:  array_search() expects parameter 2 to be array, null given in /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php on line 127
...................... 1769 / 1821 ( 97%)
..............E.....................................          1821 / 1821 (100%)

Time: 21.02 minutes, Memory: 1.16 GB

There was 1 error:

1) MauticPlugin\MauticCrmBundle\Tests\Integration\SalesforceIntegrationTest::testUpdateDncByMauticDate
Error: Call to undefined method Mock_LeadModel_4f794625::addDncForLead()

/home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:2846
/home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:2826
/home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Tests/Integration/SalesforceIntegrationTest.php:703

--

There was 1 risky test:

1) MauticPlugin\MauticCrmBundle\Tests\Api\SalesforceApiTest::testRequestQueryAllAndHandle
This test did not perform any assertions

/home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Tests/Api/SalesforceApiTest.php:360

ERRORS!
Tests: 1821, Assertions: 5346, Errors: 1, Skipped: 5, Risky: 1.

Generating code coverage report in Clover XML format ... done

THE ERROR HANDLER HAS CHANGED!
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist handling the test event returned with error code 2
```

</details>


###### TravisBuddy Request Identifier: cddd1a10-0fec-11eb-8acb-27a1e4e1eb88

2020-10-17 15:50 UTC, dennisameling commented
@anton-vlasenko any chance you could look into the failing tests? Thanks!

2020-10-19 06:28 UTC, anton-vlasenko commented
@dennisameling I'm looking into them

2020-10-19 06:53 UTC, TravisBuddy commented
## Travis tests have failed

Hey @galvani,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: c0339960-11d7-11eb-af4f-e3a6e0ba4ce0

2020-10-19 08:13 UTC, TravisBuddy commented
## Travis tests have failed

Hey @galvani,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: ee7fdc10-11e2-11eb-af4f-e3a6e0ba4ce0

2020-10-19 08:40 UTC, dennisameling commented
@anton-vlasenko Though the PHPUnit tests are passing, there are some PHP warnings in there. Would you mind looking into those? Thanks 🚀 

```bash
PHP Warning - array_search() expects parameter 2 to be array, null given - in file /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php - at line 114
PHP Warning:  array_search() expects parameter 2 to be array, null given in /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php on line 114
PHP Warning - array_search() expects parameter 2 to be array, null given - in file /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php - at line 127
PHP Warning:  array_search() expects parameter 2 to be array, null given in /home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Api/SalesforceApi.php on line 127
```

and

```bash
There was 1 risky test:
1) MauticPlugin\MauticCrmBundle\Tests\Api\SalesforceApiTest::testRequestQueryAllAndHandle
This test did not perform any assertions
/home/travis/build/mautic/mautic/plugins/MauticCrmBundle/Tests/Api/SalesforceApiTest.php:360
```

We're almost there 😊

2020-10-19 08:41 UTC, TravisBuddy commented
## Travis tests have failed

Hey @galvani,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: e2a7cc50-11e6-11eb-af4f-e3a6e0ba4ce0

2020-10-19 08:47 UTC, anton-vlasenko commented
@dennisameling I've fixed the errors you mentioned. Let's see if it helps.

2020-10-19 10:05 UTC, anton-vlasenko commented
I don't have time to write additional tests right now, but I will be able to do it in 2-3 hours.

2020-10-19 14:38 UTC, anton-vlasenko commented
I wrote 1 unit test but I don't have the capacity to write more unit tests.
The PR is still failing. I may add more tests later.

2020-11-21 18:21 UTC, RCheesley commented
@anton-vlasenko also a conflict to resolve so we will probably have to push this back again

2021-02-13 13:23 UTC, RCheesley commented
This one needs to be rebased please @mautic/acquia-po

2021-05-02 18:32 UTC, kuzmany requested changes

2021-05-02 18:32 UTC, kuzmany commented on plugins/MauticCrmBundle/Api/SalesforceApi.php
>              $fields   = implode(', ', array_unique($fields));
$fields are passed to to requestQueryAllAndHandle method and should be array

This return error

`Type error: Argument 2 passed to MauticPlugin\MauticCrmBundle\Api\SalesforceApi::requestQueryAllAndHandle() must be of the type array, string given`

2022-01-16 08:34 UTC, kuzmany commented
@galvani need resolve conflicts

2022-10-10 12:10 UTC, escopecz commented
Also rebase to 5.x branch

2023-08-04 11:52 UTC, escopecz commented
Closing in favore of https://github.com/mautic/mautic/pull/12622

2023-08-04 11:52 UTC, closed without merging