Disable tracking 404
mautic/mautic pull request #7614
Opened 2019-06-17 20:58 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/7565
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
404 error page tracking visitors. 
This causes a lot of anonymous contacts from bots.
This PR disable trackig of 404 not found pages

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try in incognito not existed url: https://yourmautic.com/whatever
2. Go to Mautic > Contacts and switch to anonymous list view
3. See new contact was create with https://yourmautic.com/whatever page hit

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps
3. See If 404 not found page wasn't tracked

![image](https://user-images.githubusercontent.com/462477/59636220-46580f00-9153-11e9-8c46-79816fd9f6d4.png)

2019-06-18 08:17 UTC, indorock submitted a review, later dismissed

2019-06-20 10:20 UTC, aspiers reviewed
Hi, thanks a lot for doing this!!  It looks great but it's not clear to me whether the option disables tracking of *all* 404s, or just anonymous 404s?  As explained in https://github.com/mautic/mautic/issues/7565#issuecomment-497675707 it is important that 404s generated by known contacts are still tracked, even when the option is enabled.

2019-06-25 02:03 UTC, ghost requested changes
Requesting changes to en_US entries for improved grammar, punctuation.

2019-06-25 02:03 UTC, ghost commented on app/bundles/PageBundle/Translations/en_US/messages.ini
> +mautic.page.config.form.disable_tracking_404.tooltip="If enabled, not founded page will not tracking"
```suggestion
mautic.page.config.form.disable_tracking_404.tooltip="If enabled, unidentified visits to 404 response code error pages will not be tracked."
```

2019-06-25 02:03 UTC, ghost commented on app/bundles/PageBundle/Translations/en_US/messages.ini
> +mautic.page.config.form.disable_tracking_404="Disable tracking 404 error page"
```suggestion
mautic.page.config.form.disable_tracking_404="Disable 404 error page tracking"
```

2019-06-25 10:38 UTC, kuzmany commented
@mightyfree thank you

@aspiers at the moment, client did pay just for this feature. 
I agree with your suggestion, but there is no budget for extra hours. If you are interest let me now and I can extend it.

2019-06-28 10:22 UTC, indorock commented
> @mightyfree thank you
> 
> @aspiers at the moment, client did pay just for this feature.
> I agree with your suggestion, but there is no budget for extra hours. If you are interest let me now and I can extend it.

@kuzmany how much more time do you estimate you'll need to add that extra change?

2019-07-13 01:05 UTC, kuzmany commented
thanks to @indorock  donate
I've added support for disable tracking 404 page for anonymous contacts
PR, description and steps to reproduce/tests was updated.

Please re-test @aspiers  @indorock

2019-08-21 12:26 UTC, RCheesley commented
Tried to test this in Mautibox but it says "Patch could not be applied. Try rebasing the branch for this pull request."

2019-10-09 16:11 UTC, virgilwashere requested changes
Has been working well on 2.15.1/2.15.2.

2019-10-09 16:11 UTC, virgilwashere commented on app/bundles/PageBundle/Translations/en_US/messages.ini
>  mautic.page.config.form.google.analytics.tooltip="Insert the analytics script to have it automatically included in the soure of landing pages."
This was updated in 5f9139c, and fails against [release:2.15.3](/mautic/mautic/tree/2.15.3).

```suggestion
mautic.page.config.form.google.analytics.tooltip="Insert the analytics script to have it automatically included in the source of landing pages."
```

Has been working well on 2.15.1/2.15.2

2019-10-12 16:20 UTC, virgilwashere approved these changes
(pressed the wrong button)

2019-10-12 16:20 UTC, virgilwashere commented on app/bundles/PageBundle/Translations/en_US/messages.ini
>  mautic.page.config.form.google.analytics.tooltip="Insert the analytics script to have it automatically included in the soure of landing pages."
I think the PR still needs a rebase.

[Mautibox agrees](https://mautibox.com/7614):
> Patch could not be applied. Try rebasing the branch for this pull request.

2019-10-12 16:22 UTC, virgilwashere requested changes
### rebase required

I think the PR still needs a rebase.

[Mautibox agrees](https://mautibox.com/7614):
> Patch could not be applied. Try rebasing the branch for this pull request.


### applying the current version

However, I successfully applied the PR using

```console
$ git apply --verbose --recount -C1 7614.diff
```

which just checks [lines 35-38](https://github.com/mautic/mautic/blob/0bc4e7e9e0ccec9a58ecdcad798e1c951049fceb/app/bundles/PageBundle/Translations/en_US/messages.ini#L35-L38) of `messages.ini`

https://github.com/mautic/mautic/blob/0bc4e7e9e0ccec9a58ecdcad798e1c951049fceb/app/bundles/PageBundle/Translations/en_US/messages.ini#L35-L38

2019-10-14 05:45 UTC, kuzmany commented
@virgilwashere ready to test https://mautibox.com/7614

2019-10-17 13:06 UTC, virgilwashere commented
@kuzmany I had a problem where contacts were not being created properly from a form submission. 

Form has firstname last name and email fields set to save to contact. But result is a contact with IP address only. 
Form fields are listed in History.

But if I toggle 'Skip 404' to 'No' the form submission saves the contact correctly.

2020-04-06 06:23 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-07-30 15:30 UTC, RCheesley commented
@kuzmany another with conflicts to be resolved :)

2020-08-16 19:27 UTC, RCheesley commented
Bumping to 3.2 due to unresolved conflicts

2020-08-28 12:06 UTC, RCheesley commented
@cla-bot check

2020-11-15 17:50 UTC, kuzmany commented
Conflicts resolved

2021-10-20 00:48 UTC, fr500 commented
let's hope this is merged soon, this is still an issue and I hope it can be fixed in m4

2021-11-26 07:54 UTC, jos0405 submitted a review, later dismissed
This works as expected. After turning on the feature any 404 on the Mautic (sub)domain is not tracked. Very much needed feature.

2021-11-26 23:52 UTC, mabumusa1 submitted a review, later dismissed
I checked this PR and implemented on a live server with tracking on. I sent a request via Paython bot to 404 page, the contact was not marked.

I also tried from a browser, a contact was not created.

I think this PR is read to go once we get phpstan working

2021-11-28 08:20 UTC, mabumusa1 approved these changes
Thanks @kuzmany, after the new changes I think this PR is ready to commit

2021-11-29 17:46 UTC, merged

2022-01-28 12:55 UTC, tomekkowalczyk commented
@kuzmany I understand that the mechanism works only on Mautic websites? If I place the tracking code on an external website and visit the 404 website, an anonymous contact is still created.

2022-01-29 09:55 UTC, kuzmany commented
@tomekkowalczyk it cover all 404 produced by Mautic, not from website