Points action update
mautic/mautic pull request #8161
Opened 2019-11-27 19:31 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2019-12-04 11:25 UTC, escopecz commented
@kuzmany I removed this PR from the M3 project because we want to track only issues there. And please check Travis.

2019-12-10 20:58 UTC, dongilbert requested changes

2019-12-10 20:58 UTC, dongilbert commented on app/bundles/EmailBundle/EventListener/PointSubscriber.php
> +        if ($action->getType() != 'email.open') {
Here we can use the `checkContext` that I suggested be added to the PointChangeActionExecutedEvent.

2019-12-10 20:58 UTC, dongilbert commented on app/bundles/PointBundle/Event/PointBuilderEvent.php
> +        if (!array_key_exists('callback', $action) && !array_key_exists('eventName', $action)) {
Since it's m2-to-m3 I think we should drop support for callbacks now and refactor to events

2019-12-10 20:58 UTC, dongilbert commented on app/bundles/PointBundle/Event/PointChangeActionExecutedEvent.php
> +
Can we add a `checkContext` method here?

```php
public function checkContext(string $context): bool
{
    return $this->pointAction->getType() === $context;
}
```

2019-12-10 20:58 UTC, dongilbert commented on app/bundles/PointBundle/Model/PointModel.php
> +    private function invokeCallback(Point $action, Lead $lead, $eventDetails, array $settings)
I think we should drop callback support altogether

2019-12-11 08:06 UTC, kuzmany commented
@escopecz so this PR is removed from Mautic3 or not?

2019-12-11 09:07 UTC, escopecz commented
@kuzmany it will to go into M3. We want to get rid of MauticFactory. We are not certain we will be able to do so for all occurrences but we definitely want to merge in WIP PRs like this one. Did I answer your question or is there something else behind it?

2019-12-19 20:57 UTC, dongilbert commented
Please rebase this to the 3.x branch

2020-04-04 15:19 UTC, closed without merging