Add  Skip if exists to form to matching tab
mautic/mautic pull request #8196
Opened 2019-12-05 17:12 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2019-12-06 13:56 UTC, johbuch commented
@kuzmany I tested it only work if a contact already has a value. 
For example my contact already has a firstname. So if I enable "If exist, not overwrite", then when I submit the form with another value, then it won't overtwrite so OK.

But if the contact does not have a value, so if it is empty in the database, then it won't work. The field will stay empty after the form submission.

2019-12-09 16:55 UTC, kuzmany commented
@johbuch fixed. please re-test

2019-12-10 08:23 UTC, johbuch submitted a review, later dismissed
everything works now 
thanks zdeno

2020-04-04 17:26 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-04-26 20:14 UTC, TravisBuddy commented
## Travis tests have failed

Hey @kuzmany,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;679826760">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................PHP Fatal error:  Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void in /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php on line 44
PHP Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44
Symfony\Component\Debug\Exception\FatalErrorException: Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44

THE ERROR HANDLER HAS CHANGED!
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Site is offline</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" type="image/x-icon" href="bin/phpunitmedia/images/favicon.ico"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/libraries.css"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/app.css"/>
</head>

<body>
<div class="container">
    <div class="row">
                <div class="col-sm-offset-3 col-sm-6">
            <div class="bg-white pa-lg text-center" style="margin-top:100px;">
                <i class="fa fa-warning fa-5x"></i>
                <h2>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h2>
                                <h4 class="mt-15">System administrators, check server logs for errors.</h4>
                            </div>
        </div>
            </div>
    </div>
</body>
</html>
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist handling the test event returned with error code 255
```

</details>


###### TravisBuddy Request Identifier: 8949cb70-87fa-11ea-9c26-c9c9fa839a9b

2020-04-26 20:16 UTC, kuzmany commented
Rebased

2020-04-26 20:20 UTC, TravisBuddy commented
## Travis tests have failed

Hey @kuzmany,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;679827940">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................PHP Fatal error:  Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void in /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php on line 44
PHP Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44
Symfony\Component\Debug\Exception\FatalErrorException: Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44

THE ERROR HANDLER HAS CHANGED!
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Site is offline</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" type="image/x-icon" href="bin/phpunitmedia/images/favicon.ico"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/libraries.css"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/app.css"/>
</head>

<body>
<div class="container">
    <div class="row">
                <div class="col-sm-offset-3 col-sm-6">
            <div class="bg-white pa-lg text-center" style="margin-top:100px;">
                <i class="fa fa-warning fa-5x"></i>
                <h2>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h2>
                                <h4 class="mt-15">System administrators, check server logs for errors.</h4>
                            </div>
        </div>
            </div>
    </div>
</body>
</html>
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist handling the test event returned with error code 255
```

</details>


###### TravisBuddy Request Identifier: 4edbcc30-87fb-11ea-9c26-c9c9fa839a9b

2020-04-27 07:11 UTC, TravisBuddy commented
## Travis tests have failed

Hey @kuzmany,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;mautic&#x2F;mautic&#x2F;jobs&#x2F;679964826">View build log</a>


<details>
  <summary>
    <strong>
     composer test
    </strong>
  </summary>

```
> bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................PHP Fatal error:  Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void in /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php on line 44
PHP Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44
Symfony\Component\Debug\Exception\FatalErrorException: Notice: Declaration of Mautic\Migrations\Version20191206110334::up(Doctrine\DBAL\Schema\Schema $schema) must be compatible with Mautic\CoreBundle\Doctrine\AbstractMauticMigration::up(Doctrine\DBAL\Schema\Schema $schema): void - in file /home/travis/build/mautic/mautic/app/migrations/Version20191206110334.php - at line 44

THE ERROR HANDLER HAS CHANGED!
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Site is offline</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" type="image/x-icon" href="bin/phpunitmedia/images/favicon.ico"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/libraries.css"/>
    <link rel="stylesheet" href="bin/phpunitmedia/css/app.css"/>
</head>

<body>
<div class="container">
    <div class="row">
                <div class="col-sm-offset-3 col-sm-6">
            <div class="bg-white pa-lg text-center" style="margin-top:100px;">
                <i class="fa fa-warning fa-5x"></i>
                <h2>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h2>
                                <h4 class="mt-15">System administrators, check server logs for errors.</h4>
                            </div>
        </div>
            </div>
    </div>
</body>
</html>
Script bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist handling the test event returned with error code 255
```

</details>


###### TravisBuddy Request Identifier: 4dc85100-8856-11ea-88d0-3540a036c4cf

2020-05-21 17:40 UTC, naveensirohi1 commented
@kuzmany Greetings, I cannot understand how to test it. Kindly suggest.

2020-08-16 19:49 UTC, RCheesley commented
Bumping to 3.2 - needs recent tests & a rebase for codecov (recommend waiting until we finish the merges for 3.1 first!)

2020-08-28 12:02 UTC, RCheesley commented
@cla-bot check

2020-09-15 07:23 UTC, sPradella approved these changes, later dismissed
all fine thank you

2020-12-09 18:24 UTC, escopecz requested changes
Looks nice, Zdeno. I have a few suggestions. I know you wrote it for M2, but when you're in it, consider adding PHP 7 syntax.

2020-12-09 18:24 UTC, escopecz commented on app/bundles/FormBundle/Form/Type/FieldType.php
> +                    'data'  => isset($options['data']['leadFieldNotOverwrite']) ? $options['data']['leadFieldNotOverwrite'] : false,
```suggestion
                    'data'  => $options['data']['leadFieldNotOverwrite'] ?? false,
```

2020-12-09 18:24 UTC, escopecz commented on app/bundles/FormBundle/Entity/Field.php
> +    public function isLeadFieldNotOverwrite()
When you'll be doing changes, could you please also add param and return types to the new methods?

2020-12-09 18:24 UTC, escopecz commented on app/bundles/FormBundle/Model/SubmissionModel.php
> -     * @var IpLookupHelper
All these property type comments are still good to have. Please add them back

2020-12-09 18:24 UTC, escopecz commented on app/bundles/FormBundle/Translations/en_US/messages.ini
> +mautic.form.field.form.leadFieldNotOverwrite="If exist, not overwrite"
How about
```suggestion
mautic.form.field.form.leadFieldNotOverwrite="Do not overwrite"
```

2020-12-09 18:24 UTC, escopecz commented on app/bundles/FormBundle/Translations/en_US/messages.ini
> +mautic.form.field.form.leadFieldNotOverwrite.tooltip="Contact field value is not ovewrite If exists"
And then
```suggestion
mautic.form.field.form.leadFieldNotOverwrite.tooltip="If yes, contact field value will not be overwritten with the form field value if not empty."
```

2021-02-13 18:06 UTC, RCheesley requested changes
Just a small grammar suggestion.

2021-02-13 18:06 UTC, RCheesley commented on app/bundles/FormBundle/Model/SubmissionModel.php
> +            $this->logger->debug('FORM: Not overwrite contact fields to process '.implode(',', $notOverwriteFields));
```suggestion
            $this->logger->debug('FORM: Do not overwrite contact fields to process '.implode(',', $notOverwriteFields));
```

2021-02-13 18:07 UTC, RCheesley commented
Conflicts here as well @kuzmany

2021-03-10 09:39 UTC, RCheesley requested changes

2021-03-10 09:39 UTC, RCheesley commented on app/bundles/FormBundle/Translations/en_US/messages.ini
> +mautic.form.field.form.leadFieldNotOverwrite.tooltip="If yes, contact field value will not be overwritten with the form field value if not empty."
I think we could make this clearer for the user

```suggestion
mautic.form.field.form.leadFieldNotOverwrite.tooltip="If set to yes, the contact field value will not be overwritten with the form field value when the contact field already contains data."
```

2021-07-13 09:56 UTC, npracht commented
@kuzmany it needs to address conflicts

2021-08-20 08:24 UTC, npracht submitted a review, later dismissed
I tested by enabling this feature on my Lastname form field and it works as expected !
Other fields are also working properly.

<img width="894" alt="Capture d’écran 2021-08-20 à 10 23 16" src="https://user-images.githubusercontent.com/14075239/130203793-9b8ea1d6-6295-4d52-bea9-17ca5f4f5f19.png">
<img width="898" alt="Capture d’écran 2021-08-20 à 10 23 22" src="https://user-images.githubusercontent.com/14075239/130203807-7c8cee33-3875-43d6-a2d6-87d258610c3d.png">

2021-09-08 10:19 UTC, RCheesley commented
Hi folks,

I have just been reviewing this and testing from the UX perspective. I think that the wording on the switch is somewhat confusing.

I think it would make more sense if it said 'Overwrite field contents' with **yes** meaning that it **will** overwrite the field contents, and **no** meaning that it will **not** overwrite the field contents.

At the moment it is confusing - we say 'Do not overwrite' and then if you set it to **yes**, according to the tooltip the field will **not** be overwritten.  Setting a field to yes generally means an affirmative action, rather than a negative action.

Is it possible to tweak that easily @kuzmany?

cc'ing @adiux from the UX perspective.

2021-09-08 10:28 UTC, RCheesley requested changes
See comment about UX

2021-09-08 14:23 UTC, adiux commented
I agree with @RCheesley . It is less confusing if we say what it does. 

E.g. Overwrite field contents. Maybe even: `Overwrite existing content`

2021-09-09 19:41 UTC, kuzmany commented
Your suggestion has one snag. By default it work in `Overwrite field contents` mode. Then not make sense add option to Overwrite field contents form my side.
The reason for PR is add option to disable this behavior. Also it would require migrations and make risky upgrades. If upgrades failed, could broke a lot of forms and make mess.

2021-09-14 17:32 UTC, adiux commented
@kuzmany to clarify: we don't want to change the default behavior in the code. We only ask to change how the fields and the label are displayed. 

Instead of asking 'if not':
![image](https://user-images.githubusercontent.com/13075514/133305764-5fbbc84d-3d32-42ac-9fc2-1c337f8c4277.png)

we ask the other way around:
![image](https://user-images.githubusercontent.com/13075514/133305643-baee8178-1aa2-46e7-9326-56326c59cc9d.png)

2021-09-15 09:47 UTC, kuzmany commented
I think 
If exists, not overwrite is opposite to Overwrite  existing content. Not equivalent

2021-09-15 11:55 UTC, adiux commented
yes, I agree it is different things if you have the same default answer. But I think we are ok if we ask the question in a different way - and give a different default answer too. But maybe I'm missing something... 

In this example it should be the same:

Do not overwrite existing content (if exist, do not overwrite): yes
=> existing content is not overwritten

vs

Overwrite existing content: no
=> existing content is not overwritten

2021-09-16 09:44 UTC, kuzmany commented
@adiux of course it's different thing. It need re-arrange code, make migrations and update/create another unit tests...
This PR keep current import behavior and add new option to enable new feature/behavior of import. 
Your suggestion  add option enabled by default with current behavior and option to disable it.
Still sounds same?

2021-09-16 13:53 UTC, adiux commented
@kuzmany yes, to me it still sounds like the same. My logic is that as long as we only change the frontend, and we don't change the default behavior, we don't have to change the schema, migration, etc.

The **current** button label is: Do not overwrite existing content
Default selected state button: no
=> existing content is overwritten

The **proposed** button label is: Overwrite existing content
Default selected state button: yes
=> existing content is overwritten

2021-10-08 17:51 UTC, kuzmany commented
I don't understand If we've already use same feature in imports, why we need change it in another part of Mautic. Especially If we invest thousands of hours to community and really need focus somewhere else. This make for us another hours to make migrations for our customers  + changes + tests etc. I am really disappointed and tired
 
![image](https://user-images.githubusercontent.com/462477/136600358-c62d3556-906e-4afd-87a5-5a3d65591960.png)

2021-10-11 09:29 UTC, npracht commented
Okay.
I agree with @adiux, putting it in positive way is much nicer.
Nevertheless, I also agree with Zdeno, we already have this way of working with exact same words and actions in the app.

I suggest we consider this nice feature now with this (as we said it re-uses already existing feature in the app on forms) and open a new issue with objective to modify as suggest @adiux for a better UX.

@RCheesley what do you think ?

2021-10-11 09:35 UTC, RCheesley commented
@npracht sure that sounds like an acceptable compromise, I feel like there are quite a few things like this across the product which don't really make sense from the user perspective, so perhaps it could form part of a process to bring some uniformity to things like switches and options, for example, driven by the UX tiger team.

2021-10-11 09:53 UTC, npracht commented
Agree @RCheesley we should list this in a Confluence topic maybe ?
According to this decision, can you re-review the PR ?

Thanks

2021-10-12 16:07 UTC, adiux commented
Thanks for picking this up. This works for me in this case. 

I think it will be a lot of effort to ”redesign" existing features. Maybe we can have a UX checklist that needs to be fulfilled before new functionality is accepted. Something like this would be the gold standard: https://developer.android.com/design

But I think something like his can already be a very good start: https://developer.atlassian.com/cloud/trello/guides/power-ups/public-power-up-guidelines/#guidelines

2021-11-09 09:48 UTC, npracht commented
I've created [issue in JIRA](https://mautic.atlassian.net/jira/software/c/projects/MAT/boards/35?modal=detail&selectedIssue=MAT-45)

2021-11-09 09:52 UTC, npracht commented
Added doc: https://github.com/mautic/mautic-documentation/pull/279

2021-11-09 09:53 UTC, npracht commented
@RCheesley and @adiux please confirm with JIRA issue + doc we are now ready to commit ?

2023-08-24 19:14 UTC, RCheesley commented
Removing this from the OSF board until it is rebased.

2023-08-25 06:53 UTC, adiux commented
> @RCheesley and @adiux please confirm with JIRA issue + doc we are now ready to commit ?

This sounds good to me. In addition, we should have a minimal UX checklist that one has to fulfil in order to merge a PR.

2024-08-21 08:58 UTC, kuzmany commented
Close at the moment. We will pick it up once ready for M5

2024-08-21 08:58 UTC, closed without merging