Improve empty placeholder for code mode and text slot
mautic/mautic pull request #8340
Opened 2020-01-20 21:39 UTC by kuzmany

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR improve https://github.com/mautic/mautic/pull/6810
Placeholder for empty text or code mode slot not work with  html   tags without content. This PR should fixed it

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create email with code mode slot
2. Set `<strong></strong>` to code mode block and click to another slot
3. You shouldn't see any placeholder, not possible click to code mode slot in builder again

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps. Now code mode block should works with HTML tags without content
3. Also test text slot If works properly

![image](https://user-images.githubusercontent.com/462477/72759302-8e517f80-3bd5-11ea-8d54-939310444fb9.png)

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

2020-01-21 09:22 UTC, florentpetitjean requested changes
Hello, 

I still got the block disapearing if I only have code markup in my block like this :
![image](https://user-images.githubusercontent.com/49391402/72791620-e9b45980-3c37-11ea-82b3-20b86cb1cec5.png)

Works fine for empty block tough. 

Thanks

2020-01-24 16:45 UTC, npracht requested changes
The fix does not wok for page buildere

2020-01-26 22:04 UTC, kuzmany commented
@florentpetitjean @npracht fixed with last commit. 
Tested also on mautibox

2020-01-27 12:56 UTC, npracht submitted a review, later dismissed
It works properly now 👍

2020-04-12 10:32 UTC, kuzmany commented
Rebased

2020-05-14 06:21 UTC, npracht submitted a review, later dismissed
Still work with last commit and improve UX

2020-06-19 13:31 UTC, dennisameling commented
@kuzmany could you please rebase against the updated `staging` branch now that 3.0.0 is released? There's a lot of conflicting files. Sorry and thanks in advance 🚀

2020-06-28 05:09 UTC, kuzmany commented
@dennisameling rebased

2020-06-28 11:44 UTC, kuzmany commented
@dennisameling rebased and resolved conflicts. I think not need unit tests

2020-08-15 17:29 UTC, RCheesley approved these changes
Tested on email builder and the code mode slot remains, whereas previously before the patch it disappeared when I clicked out of it.

![screenshot-local mautic3-2020 08 15-18_26_51](https://user-images.githubusercontent.com/2930593/90317986-09d59e00-df25-11ea-97b1-2393a34e60ef.png)

Also checked in the landing page builder 👍  thanks for the PR!

2020-08-15 20:54 UTC, dennisameling approved these changes
Thanks @kuzmany! 🚀

2020-08-16 08:28 UTC, merged