Webhooks: JSON payload if content-type header is set to 'application/json'
mautic/mautic pull request #8375
Opened 2020-01-30 13:18 UTC by neyric

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| Automated tests included? |no
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/7869
| BC breaks? | no
| Deprecations? | no

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

In a campaign, fix the "Send a Webhook" for services requiring a JSON Payload, by adding a conversion to JSON if the head 'content-type' is set to 'application/json'

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Cf https://github.com/mautic/mautic/issues/7869

#### Steps to test this PR:
1. Cf https://github.com/mautic/mautic/issues/7869

#### List deprecations along with the new alternative:
N/A 

#### List backwards compatibility breaks:
N/A

2020-02-25 00:28 UTC, victorburgos12 commented
Can this change also include POST method?
I need to send a POST webhoock to zoom.us to register a user to a webinar and zoom only accepts json format.

2020-03-31 00:18 UTC, ImCowboySibs commented
Hi, when I implement this PR on Mautic 2.16.1 I am met with the following error:

**PHP Notice:  Undefined index: content-type in /var/www/html/app/bundles/WebhookBundle/Helper/CampaignHelper.php on line 108**

Have you tested this on Mautic 2.16.1 or would be willing to update this PR to function with Mautic 2.16.1

2020-03-31 10:06 UTC, RenzoF requested changes
I think this should check if the 'content-type' key exists in the array before evaluating.

2020-03-31 10:12 UTC, npracht commented
Also please check Travis CI issue

2020-04-03 16:57 UTC, npracht commented
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

2020-05-20 09:32 UTC, npracht commented
Hello @neyric could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback. Thanks !

2020-06-10 06:49 UTC, npracht commented
@mabumusa1 would you be able to carry that PR ? Commit different changes you mentioned and change branch targeted to 3.x ?

2020-06-10 07:10 UTC, mabumusa1 commented
@npracht I can do it over the weekend. I also suggest that we change the default behavior to use JSON by default instead of sending `x-www-form-urlencoded`. the code will be something like this

```
                $headers = array_change_key_case($headers);
                //if no content-type is defined, default to application/json and encode body
                if(!array_key_exists('content-type', $headers) || $headers['content-type'] == 'application/json' ){
                    $headers['content-type'] = 'application/json';
                    $payload = json_encode($payload);                    
                }
```
This change I already implemented and tested so it is PR thing, you can read the code here

https://github.com/mabumusa1/mautic/commit/672d68e21e619e1bf3200171e00055967f1a44ba

What do you think?

2020-06-10 07:31 UTC, npracht commented
Hello !
I think that i want to thank you for answering that fast and carrying that work. From the technical side, make the PR you think is the best for mautic community and we'll have other community contributors that will review it ;)

2020-06-24 19:10 UTC, TravisBuddy commented
## Travis tests have failed

Hey @neyric,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 61941360-b64e-11ea-aaf6-456b40a357ff

2020-06-26 09:43 UTC, RCheesley commented
@mabumusa1 could you take a look at the Travis issue? I am not sure from the comments above if we are working on this PR or if there is another one for Mautic 3.x - either way can you let us know please? Bumping to a later release.

2020-06-27 08:24 UTC, mabumusa1 commented
@RCheesley I created a new PR for Mautic 3.x, Please use PR #8959 instead of this one. it uses the same logic, passed Travis tests and I tested it on mautibox as well

2020-07-16 17:38 UTC, closed without merging