Recommended MySql version bumbed from 5.5.3 to 5.7.14
mautic/mautic pull request #8394
Opened 2020-02-05 09:41 UTC by escopecz

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://acquia.slack.com/archives/CPVGZE516/p1578392663001500
| BC breaks? | Yes, but it's only a recommendation, not hard limit.
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

I asked the community in Slack if we can bump the MySql version and there was no one against. It will let us use more advanced features like https://github.com/mautic/mautic/pull/7094.

#### Steps to test this PR:
1. Just a readme change. Nothing to test. Just review.

2020-02-05 11:54 UTC, anton-vlasenko requested changes

2020-02-05 11:54 UTC, anton-vlasenko commented on UPGRADE-3.0.md
> +*   Minimal MySql version was increased from v5.5.3 to v5.7.14
```suggestion
*   Minimal MySQL version was increased from v5.5.3 to v5.7.14
```
This is really a nitpick. But I think we should use the same spelling in all of the documents (in README.md we spell it as `MySQL`).

2020-02-05 12:13 UTC, anton-vlasenko approved these changes
@escopecz Could you please merge this PR?

2020-02-05 12:48 UTC, merged

2020-08-07 15:18 UTC, digitall-it commented
Just wanted to let you know that I cannot upgrade from v2.x to v3.0.1 because I'm stuck with MySQL v5.5.65.

2020-08-07 15:44 UTC, escopecz commented
I'm sorry about that. But consider changing your server provider if you are forced to use unsupported software versions. According to https://fromdual.com/support-for-mysql-from-oracle the extended support for 5.5 ended in Dec 2018. This is a security risk.

2020-08-07 17:42 UTC, digitall-it commented
I understand, but on CentOS 7, a distro still widely used, upgrading from mariaDB 5.5 to 10.x (a drop-in replacement for MySQL 5.7.x) is a major task, which many didn't discover they had to do until now that they have to upgrade Mautic to 3.x and are stuck with the older version now.