Save email_id to email_stats for quick Emails
mautic/mautic pull request #8537
Opened 2020-03-07 20:42 UTC by bookin

The problem when I send an Email from the Contact page, the Mautic doesn't save email_id to the email_stats and as example performance center doesn't work for these emails.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Create the Email with the Custom Performance Center
2. Open the contact page and send the Email from the contact page by "Send Email" button
3. Try to unsubscribe and you will see the default Performance Center instead of the custom

2020-03-08 09:58 UTC, kuzmany approved these changes
Yes, now it works as you describe.
Send custom email from email template respect email ID

![image](https://user-images.githubusercontent.com/462477/76160571-96d12b80-612b-11ea-84c6-19a9a853edf5.png)

2020-05-26 12:32 UTC, kuzmany requested changes

2020-05-26 12:32 UTC, kuzmany commented on app/bundles/LeadBundle/Controller/LeadController.php
> +
Should move this code 

```
// Set Content
$mailer->setBody($email['body']);
$mailer->parsePlainText($email['body']);
```

after `$mailer->setEmail($emailEntity);` condition

This prevent reset changed content form email entity

2020-06-23 17:14 UTC, RCheesley commented
@bookin could you take a look at the suggestions made in the PR please? Would be great to get this tested and out with one of the upcoming patch releases!

2020-06-26 09:04 UTC, RCheesley commented
@bookin as this will reduce coverage we need tests before we can merge this PR - moving to 3.0.2, please take a look at the suggestions in the PR also? Many thanks!

2020-07-17 20:33 UTC, kuzmany submitted a review, later dismissed
I fixed that issue. Works for me properly now 👍

2020-08-25 16:36 UTC, RCheesley commented
@cla-bot check

2020-09-21 16:20 UTC, RCheesley commented
Bumping to 3.1.2 due to an unsigned contributors agreement and automated tests being required.

@bookin please take a look before the **18th October** if we are going to merge this - alternatively @kuzmany if the OP does not respond we can consider creating a new PR.

2020-11-23 18:36 UTC, bookin commented
Hi @RCheesley, I am sorry, I couldn't chance to answer 
Is it still actually?

2020-11-23 18:42 UTC, RCheesley commented
@bookin hi there, welcome back!

We could consider for the next release if you can please sign the Contributors Agreement - we will also need to improve the test coverage, can you do that or would you like some assistance?

2021-02-19 08:10 UTC, npracht reviewed
👍🏽 tested and works

2021-02-19 08:10 UTC, npracht approved these changes

2021-02-19 14:13 UTC, kuzmany commented
I found some issue, need more touch.

2021-02-19 15:27 UTC, kuzmany commented
I've noticed this PR not increase send count of email, but increase read count of email. I am able to fix it later.

2021-03-04 00:06 UTC, alanhartless commented
Just noting that the original intent of the "Import from an existing template" option was to only load existing content but not track against the email entity. There is the risk that this could have unintended effects as a result since it changes the original intent of the feature. 

Although untested, the first one that comes to mind is translation support. Emails sent directly to the contact are fully customizable once the content is imported. But if there is a translation associated with the email template, I think there is a chance the contact will be sent one of the translations instead of the custom content.

2021-03-04 07:07 UTC, kuzmany commented
@alanhartless then I close it.
The solution could be create another option to directly send email to contact.

2021-03-04 07:07 UTC, closed without merging