M3 changed to flush queue before cc and bcc are cleared
mautic/mautic pull request #8768
Opened 2020-05-07 11:13 UTC by hluchas

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
Fixing bug where cc and bcc emails are not sent from the Send to User campaign action. This is required for fixing the Selenium tests. We also want to avoid regressing the bug where the cc and bcc emails could get sent multiple times if there is more than one email in the 'To' field.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign with action 'Send Email to User'
2. In the action, add 2 unique emails each to the 'To', 'Cc' and 'Bcc' fields
3. Trigger the campaign action
4. Check that each email address receives exactly one email

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat reproduction steps

2020-05-12 21:04 UTC, dennisameling requested changes
@hluchas 
I'm seeing PHP notices after applying your PR. However, the functionality itself works as expected (all email addresses receive the email just once, this is the case before and after applying the PR). I used an SMTP server for testing. 

```
dennis@mautic3dennis-web:/var/www/html$ bin/console mautic:campaigns:trigger
Triggering events for campaign 2
Triggering events for newly added contacts
1 total events(s) to be processed in batches of 100 contacts
 1/1 [============================] 100%PHP Notice:  Array to string conversion in /var/www/html/app/bundles/EmailBundle/Model/SendEmailToUser.php on line 60
PHP Stack trace:
PHP   1. {main}() /var/www/html/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/html/bin/console:43
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/console/Application.php:148
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:74
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/html/vendor/symfony/console/Application.php:255
PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:86
PHP   7. Mautic\CampaignBundle\Command\TriggerCampaignCommand->run() /var/www/html/vendor/symfony/console/Application.php:1005
PHP   8. Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute() /var/www/html/vendor/symfony/console/Command/Command.php:255
PHP   9. Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:277
PHP  10. Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:328
PHP  11. Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:372
PHP  12. Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent() /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php:122
PHP  13. Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts() /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php:222
PHP  14. Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:245
PHP  15. Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:172
PHP  16. Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:201
PHP  17. Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent() /var/www/html/app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php:67
PHP  18. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php:89
PHP  19. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->doDispatch() /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:44
PHP  20. Mautic\EmailBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionSendEmailToUser() /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:214
PHP  21. Mautic\EmailBundle\Model\SendEmailToUser->sendEmailToUsers() /var/www/html/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php:377
PHP  22. implode() /var/www/html/app/bundles/EmailBundle/Model/SendEmailToUser.php:60

Notice: Array to string conversion in /var/www/html/app/bundles/EmailBundle/Model/SendEmailToUser.php on line 60

Call Stack:
    0.0011     401352   1. {main}() /var/www/html/bin/console:0
    0.0613    1240848   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/html/bin/console:43
    0.0697    1400264   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/console/Application.php:148
    0.5348    9746328   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:74
    0.5350    9746944   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/html/vendor/symfony/console/Application.php:255
    0.5350    9746944   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:86
    0.5366    9755744   7. Mautic\CampaignBundle\Command\TriggerCampaignCommand->run() /var/www/html/vendor/symfony/console/Application.php:1005
    0.5370    9757464   8. Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute() /var/www/html/vendor/symfony/console/Command/Command.php:255
    0.5751   10515776   9. Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:277
    0.5756   10517152  10. Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:328
    0.5758   10517152  11. Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute() /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:372
    0.5936   10790328  12. Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent() /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php:122
    0.6306   11249224  13. Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts() /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php:222
    0.6314   11251472  14. Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:245
    0.8167   13045208  15. Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:172
    0.8168   13045208  16. Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute() /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php:201
    0.8168   13045232  17. Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent() /var/www/html/app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php:67
    0.8180   13050496  18. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php:89
    0.8180   13050256  19. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->doDispatch() /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:44
    0.8180   13050256  20. Mautic\EmailBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionSendEmailToUser() /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:214
    0.8181   13050872  21. Mautic\EmailBundle\Model\SendEmailToUser->sendEmailToUsers() /var/www/html/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php:377
    1.4253   14446608  22. implode() /var/www/html/app/bundles/EmailBundle/Model/SendEmailToUser.php:60

PHP Notice:  Array to string conversion in /var/www/html/app/bundles/EmailBundle/Model/SendEmailToUser.php on line 60
PHP Stack trace:
PHP   1. {main}() /var/www/html/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/html/bin/console:43
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/console/Application.php:148
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:74
PHP   5. [...]

2020-05-13 11:38 UTC, hluchas commented
Reproduced with this action configuration
![Snímek obrazovky 2020-05-13 v 13 21 17](https://user-images.githubusercontent.com/12815758/81807768-f8908600-951e-11ea-8fce-88fd7eae11d4.png)

Working on this

2020-05-13 13:36 UTC, hluchas commented
@dennisameling fixed in https://github.com/mautic/mautic/pull/8768/commits/3bca0172df4e4b387831b43f47eed79b69c4623e

2020-05-13 21:40 UTC, dennisameling approved these changes
CLI command works without issues now. Thanks @hluchas 🎉

2020-05-15 03:13 UTC, merged