M3 Add maxmind data purge command
mautic/mautic pull request #8769
Opened 2020-05-07 12:30 UTC by hluchas

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds a new command that will use the MaxMind Do Not Sell List to find data that we need to purge from our contacts and remove it.

#### Steps to test this PR:
1. Follow the testing steps for the command that Lukas added here: https://github.com/mautic/mautic/pull/8647. Running this command will get you the MaxMind Do not sell list.
2. Run this command mautic:max-mind:purge. It should complete successfully.
3. If there were not any matches found, then edit / add one of the IPs from the list into your ip_address table
4. Run again and see that a match was found.
5. To test purge, add a city to the details column for the ip you added in the ip_address table
6. Update the lead that is mapped to that IP to have the same city
7. Run the command again
8. The command should find a match, finish successfully and checking the contact will show that the city is now NULL

2020-05-07 12:30 UTC, hluchas commented
Blocked by https://github.com/mautic/mautic/pull/8647

2020-08-16 18:51 UTC, RCheesley commented
Bumping to 3.2 due to blocking PR pending feedback therefore this one cannot be merged.

2020-08-16 18:52 UTC, RCheesley commented
Bumping to 3.2 due to PR blocking having unresolved conflicts.

2020-09-11 13:24 UTC, RCheesley commented
@cla-bot check

2020-10-14 07:53 UTC, hluchas commented
Hi @RCheesley.
CLA log says 
```
2020-09-11T13:24:15.300Z INFO The contributors @mtshaw3 have not signed the CLA, adding error status to the pull request
```
He's no longer part of Acquia, neither Mautic contributor.

What we can do with this?

2020-10-27 09:52 UTC, RCheesley commented
Looks like that's one that I missed on the CLA bot list, I'll take a look.

2020-10-27 11:30 UTC, RCheesley commented
@cla-bot check

2020-10-27 11:30 UTC, RCheesley commented
@hluchas all sorted! 🎉

2020-10-28 07:41 UTC, hluchas commented
Thank you @RCheesley  ;-)

2020-11-23 14:59 UTC, RCheesley requested changes
Tests need small fix for PHPUnit 8

2020-11-23 14:59 UTC, RCheesley commented on app/bundles/CoreBundle/Tests/Unit/Command/MaxMindDoNotSellPurgeCommandTest.php
> +    protected function setUp()
```suggestion
    protected function setUp(): void
```

Fix for PHPUnit 8

2020-11-23 14:59 UTC, RCheesley commented on app/bundles/CoreBundle/Tests/Unit/IpLookup/MaxMindDoNotSellListTest.php
> +    protected function setUp()
```suggestion
    protected function setUp(): void
```
Fix for PHPUnit 8

2020-11-23 15:24 UTC, hluchas commented
@RCheesley Looks good!

2020-11-23 16:25 UTC, RCheesley commented
> @RCheesley Looks good! But not the test coverage

That's probably because we just made a release so Staging will have some changes!

2020-12-09 16:06 UTC, escopecz approved these changes
Looks good 👍

2020-12-14 13:59 UTC, RCheesley approved these changes

2020-12-14 13:59 UTC, merged