Upstream company view
mautic/mautic pull request #8812
Opened 2020-05-20 15:42 UTC by alfredoct96

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL |  /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | /
| Deprecations? | /

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added view page for companies.
It includes:
* Basic company's info
* Button to export company's info
* Graph with sum of engagement and points of each company's contact
* Table with pagination of all contacts of company

The request so includes all routes to get all contacts of company and export company info.

I added also methods for 
* view company page
* get sum of engagements and score of each company's user
* export company's info

![mautic1](https://user-images.githubusercontent.com/50916237/82302408-d7fe7b00-99b9-11ea-84d6-7aa8c628c6b1.png)

![mautic2](https://user-images.githubusercontent.com/50916237/82302487-f49ab300-99b9-11ea-8a63-e21ed7abeef9.png)

#### Steps to test this PR:
1. Load up [this PR](https://m3.mautibox.com)
2. Create a company and assign some users to it
3. Go to Company menù and click to a company, it will take you to company view page.

2020-05-20 16:01 UTC, npracht commented
Thanks @alfredoct96 this is an awesome contribution !!!!

2020-05-21 08:56 UTC, GiuseppeIuculano commented on app/bundles/LeadBundle/Views/Company/company.html.php
> + * @copyright   2014 Mautic Contributors. All rights reserved
Why copyright 2014 ? I think it should be 2020, but better to ask Mautic people :-)

2020-05-21 13:44 UTC, naveensirohi1 commented
Tried to test the info, found the following:
1. In the exported file the Name of the company does not appear, it shows the email. I blv the 
<img width="746" alt="Screen Shot 2020-05-21 at 6 43 14 PM" src="https://user-images.githubusercontent.com/63360745/82563759-40ee1a80-9b95-11ea-88e0-5262b36610c1.png">

Tests Done:
1. Created a company:
![Companies_Info](https://user-images.githubusercontent.com/63360745/82563959-9296a500-9b95-11ea-81fc-105bf0649653.png)
2. Created a contact and added the contact to the company,
<img width="1440" alt="Screen Shot 2020-05-21 at 6 40 23 PM" src="https://user-images.githubusercontent.com/63360745/82564010-a9d59280-9b95-11ea-835d-8865ced67e57.png">
3. Verified the following:
Added view page for companies.
It includes:
- Basic company's info
- Button to export company's info - Exports the information in .csv format. 
- Graph with sum of engagement and points of each company's contact
- Table with pagination of all contacts of company

<img width="1440" alt="Screen Shot 2020-05-21 at 7 03 18 PM" src="https://user-images.githubusercontent.com/63360745/82564235-0fc21a00-9b96-11ea-86f5-132c91799452.png">
<img width="1440" alt="Screen Shot 2020-05-21 at 6 41 01 PM" src="https://user-images.githubusercontent.com/63360745/82564272-1e103600-9b96-11ea-910c-70890e20b654.png">

@alfredoct96 -> How does point scenario work?

2020-05-21 15:52 UTC, kuzmany requested changes

2020-05-21 15:52 UTC, kuzmany commented on app/bundles/LeadBundle/Views/Company/list_rows_contacts.html.php
> +$customButtons = [
These lines looks like unnecessary

2020-05-21 16:29 UTC, alfredoct96 commented on app/bundles/LeadBundle/Views/Company/list_rows_contacts.html.php
> +$customButtons = [
Thanks! I removed the lines

2020-06-22 17:02 UTC, closed without merging