Update AjaxController.php
mautic/mautic pull request #9081
Opened 2020-08-13 13:35 UTC by ramandi

To avoid 500 Internal Server Error while removing the "Do not contact" tag from a contact's preferences, as described in https://github.com/mautic/mautic/issues/9017

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #9017

#### Description:
Change model name (mautic.lead.model.dnc -> lead.dnc) to avoid error.  getModel composes the full name from the short one.

2020-08-14 14:12 UTC, wise-gorilla requested changes
Please also check line #350

2020-08-16 08:58 UTC, wise-gorilla approved these changes

2020-08-25 16:25 UTC, RCheesley commented
@cla-bot check

2020-09-07 00:42 UTC, gmenezesg approved these changes

2020-09-19 11:22 UTC, RCheesley commented
Hi @ramandi thanks for making this PR! 

It turned out that the DNC issue was much deeper than we originally thought, and a PR has been created in #9186 which is attempting to pick up all the instances where DNC had become broken rather than just the single one that is covered in this PR.

I noticed that your PR has an additional line we had not captured in that PR so I've asked for it to be added.

I'd like to go ahead and close this PR down in favour of #9186 but we will ensure that you are credited in the release notes as contributing to this PR.

2020-09-19 11:22 UTC, closed without merging

2020-09-21 17:45 UTC, jacobshilitz commented
Hello, 
1. My PR #9186 is not related to this PR.
2. `mautic.lead.model.dnc` is declared in more [than one place](https://github.com/mautic/mautic/search?q=mautic.lead.model.dnc&unscoped_q=mautic.lead.model.dnc) if it has to be replaced, then it has to be done everywhere