Fix datetime picker for contact/company fields
mautic/mautic pull request #9161
Opened 2020-09-02 15:27 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | https://github.com/mautic/mautic/issues/8958

#### Description:
When editing a contacts custom datefield value, I do not get a date popup anymore. This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a date/time contact field
3: Create new contact and notice that there is  date selector finally

2020-09-04 08:00 UTC, StoppingBuck requested changes
Nevermind, I made a mistake. Please delete this comment.

2020-09-04 08:02 UTC, StoppingBuck approved these changes
I can confirm that the date picker shows up when following the instructions:
1. Create a custom field on Contact with Type=DateTime
2. Create new contact
3. There's the picker

2020-09-17 12:51 UTC, Sven-leuchtfeuer approved these changes
Everything is OK. If I follow the instruction then the date picker is displayed.

2020-09-18 16:16 UTC, RCheesley commented
@kuzmany could you take a look at improving test coverage?

2020-09-21 12:04 UTC, RCheesley commented
Bumped to 3.1.2 pending improvements in test coverage

2020-09-21 12:25 UTC, kuzmany commented
I don't think this need unit tests

2020-10-01 14:22 UTC, mabumusa1 commented
@RCheesley I tried this PR, it works as expected, I do not think there is a need for a unit test for this one

2020-10-01 14:22 UTC, mabumusa1 approved these changes
The code works as expected, this PR is good from a code and testing perspective

2020-10-12 06:56 UTC, merged