Fix query is always an array
mautic/mautic pull request #9323
Opened 2020-10-20 04:58 UTC by adiwegs

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging or 3.1
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          |no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | no
| Related developer documentation PR URL | no
| Issue(s) addressed                     | 

#### Description:
Fixes 500 server error when parameters are attached to an url 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a landingage. e.g. test
3. Hit it without being logged in (or tracking won't work). E.g. https://mautibox.com/staging/test?utm_source=linkedin&utm_medium=social&utm_campaign=mautic&utm_content=testing

2020-10-28 20:42 UTC, escopecz commented
@adiwegs how is this PR different from https://github.com/mautic/mautic/pull/9265?

2020-10-28 20:43 UTC, escopecz requested changes

2020-10-28 20:43 UTC, escopecz commented on app/bundles/PageBundle/Model/PageModel.php
> +    public function getHitQuery(Request $request, $page = null): array
Changing signature of a public of protected method is considered a BC break.

2020-11-08 16:05 UTC, adiwegs commented
This is a bug fix that is also included in #9265. I separated it to test the fix without the rest of the code.

2020-11-10 08:46 UTC, escopecz commented
The code looks great. Now could you write a functional test for this? It would ensure that the URL with query params works and will continue to work after future changes. See for example https://github.com/mautic/mautic/blob/51726b01aa718083649d84228a80e5023e0d58cc/app/bundles/LeadBundle/Tests/Controller/CompanyControllerTest.php#L43

A page can be created in the test like
```php
$page = new Page();
$page->set... // Set all the required properties
$this->em->persist($page);
$this->em->flush();

// And then access the URL for example like
$this->client->request(Request::GET, "{$page->getAlias()}?utm_source=linkedin&utm_medium=social&utm_campaign=mautic&utm_content=testing");
$clientResponse = $this->client->getResponse();
$this->assertEquals(Response::HTTP_OK, $clientResponse->getStatusCode());
```

2021-02-02 07:15 UTC, adiux commented
I have added the Tests from #9265 to this branch too. So this fix has tests and can be merged.

2021-02-02 11:46 UTC, RCheesley commented
@cla-bot check

2021-02-03 16:07 UTC, kuzmany commented
@adiux Does it prevent the issue

`PHP Warning - Invalid argument supplied for foreach() - in file /pathtomautic/app/bundles/PageBundle/Model/PageModel.php - at line 1179`

2021-02-03 18:16 UTC, adiux commented
@kuzmany yes

2021-04-09 05:59 UTC, adiux commented
Closed in favour of https://github.com/mautic/mautic/pull/9265

2021-04-09 05:59 UTC, closed without merging