Add composer.json and composer.lock to release zip archive
mautic/mautic pull request #9341
Opened 2020-10-28 13:29 UTC by dmitryuk

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | https://github.com/mautic/docker-mautic/pull/101

Some plugins requires php composer dependencies, so impossible to install them correctly because composer.json and composer.lock are not exists in official docker images.
The PR adds files to future releases.
Example plugins:
https://github.com/mautic/composer-plugin
https://github.com/rmuilwijk/MauticFBAdsLeadAdsBundle

2020-10-28 21:03 UTC, escopecz requested changes
I would love this change!

But I believe that the reason why those files are removed from the prod release is security. An attacker can easily get sense of what PHP packages and versions are in the Mautic instance. Also what version of Mautic it is. Very valuable information when you are looking for backdoor. 

We could restrict access in the .htaccess file for Apache. But I'm not sure how to prevent it for Nginx.

2020-10-29 02:57 UTC, dmitryuk commented
@escopecz I have added deny of composer files to Apache's .htaccess as you mentioned above.

2020-10-29 12:17 UTC, RCheesley commented
@cla-bot check

2020-10-29 12:17 UTC, RCheesley commented
Thank you for the PR @dmitryuk, much appreciated!

2020-10-30 09:09 UTC, escopecz approved these changes
Looks good 👍 
<img width="428" alt="Screen Shot 2020-10-30 at 10 09 16" src="https://user-images.githubusercontent.com/1235442/97681089-0370b000-1a98-11eb-9c18-c628ee3a735b.png">

2020-11-06 10:43 UTC, merged

2020-12-01 16:39 UTC, dennisameling commented
Just dropping a comment here: the protection in `.htaccess` only applies to Apache users. Users who use Nginx with Mautic won't have this protection, but they won't have any protection out of the box anyway. Best would be if Mautic had a "public" folder with only an `index.php` file, like other Symfony apps have had for a long time. Might be something to consider for Mautic 4 maybe?