Enabling company tokens in webhook campaign action
mautic/mautic pull request #9371
Opened 2020-11-04 21:42 UTC by mabumusa1

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #7615

#### Description:
This replaces the PR #7625

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

2020-11-20 14:50 UTC, fedys requested changes
I tested token `{contactfield=companyzipcode}` and it didn't work. Only the following tokens work:
-  `{contactfield=companyname}`
-  `{contactfield=companycity}`
-  `{contactfield=companycountry}`
-  `{contactfield=is_primary}`

You need to add `companyzipcode` (and probably other company fields) into [this query](https://github.com/mautic/mautic/blob/3991c3df7c22cdfdfd1fbc063904cd7027bab90c/app/bundles/LeadBundle/Entity/CompanyRepository.php#L117).

2020-11-20 14:55 UTC, escopecz commented
@fedys That's done in https://github.com/mautic/mautic/pull/9270 So do you think we can merge this if that one is merged as well?

2020-11-20 15:03 UTC, fedys commented
@escopecz definitely!

2020-11-20 15:05 UTC, fedys approved these changes
After discussion with @escopecz this PR will work properly once  #9270 is merged.

2020-11-21 12:54 UTC, RCheesley approved these changes
Thanks for this PR @mabumusa1 !

Tested using https://webhook.site:

![screenshot-webhook site-2020 11 21-12_52_09 (2)](https://user-images.githubusercontent.com/2930593/99877794-85b44600-2bf8-11eb-9f0d-50c891475321.png)

Confirmed without the PR applied that the company name field is empty (used this rather than zip code based on the comments above).

![screenshot-webhook site-2020 11 21-12_52_09 (1)](https://user-images.githubusercontent.com/2930593/99877801-95338f00-2bf8-11eb-9fbb-6a8a030f2af3.png)

After applying the PR the company name comes through as expected and matches the company assigned to the contact:

![screenshot-webhook site-2020 11 21-12_52_09](https://user-images.githubusercontent.com/2930593/99877812-a5e40500-2bf8-11eb-84c8-3138f040b7bf.png)

2020-11-21 14:00 UTC, merged