Improve Page Hits tracking performance
mautic/mautic pull request #9375
Opened 2020-11-06 14:54 UTC by xnohat

Improve Page Hits tracking performance by change other of code lines

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no

#### Description:
Discovery impact to server load performance of Page Hits tracking when server get heavy load traffic

#### Explain:
PageModel->hitPage() method will overload Server because it query LeadModel to get Lead very heavy double times, to fix that, change order of codes, get Lead first by getCurrentLead()  and pass as argument to hitPage(), getCurrentLead() is lightweight and fast execution, hitPage() will skip query current Lead again and using passed Lead.
Execution Time of page hits processing will change from 0.2 us down to 0.01 us, increase performance 2000% . PHP-FPM will not get full connections any time later

#### Steps to test this PR:
This PR require manual test
1. Load test by Apache Bench with 5000 concurrent connection in 5 minutes and get 1st server load report
2. Load up [this PR](https://mautibox.com)
3. Load test by Apache Bench with 5000 concurrent connection in 5 minutes and get 1st server load report
Server load immediately drop many times ( depend on server hardware specs )

2020-11-06 16:22 UTC, mabumusa1 commented
@xnohat if you need help getting this PR merged, please let me know. I think this is a very good code improvement

2020-11-06 16:48 UTC, TravisBuddy commented
## Travis tests have failed

Hey @xnohat,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: d55b5590-204f-11eb-9dab-419bf2960c30

2020-11-07 12:27 UTC, RCheesley commented
Thanks for your PR @xnohat and for the detailed instructions for testing.

Could you take a look at signing the contributors agreement on the link above please?

2020-11-09 18:38 UTC, xnohat commented
> Thanks for your PR @xnohat and for the detailed instructions for testing.
> 
> Could you take a look at signing the contributors agreement on the link above please?

I have done for signing the contributors agreement

2020-11-09 19:13 UTC, RCheesley commented
@cla-bot check

2020-11-20 12:02 UTC, fedys requested changes

2020-11-20 12:02 UTC, fedys commented on app/bundles/PageBundle/Controller/PublicController.php
> +        $lead = $leadModel->getCurrentLead();
Method `LeadModel::getCurrentLead()` no longer exists in the `staging` branch. You should use `\Mautic\LeadBundle\Tracker\ContactTracker::getContact()` instead.

2020-11-20 12:02 UTC, fedys commented on app/bundles/PageBundle/Controller/PublicController.php
> +        $model->hitPage(null, $this->request, '200', $lead);
Passing `$lead` completely bypasses the logic in [PageModel](https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Model/PageModel.php#L462-L479). This alters current application behaviour. E.g. `ct` query parameter is not taken into account, etc.

2020-11-20 12:02 UTC, fedys commented on app/bundles/PageBundle/Controller/PublicController.php
> +        $model->hitPage(null, $this->request, '200', $lead);
Passing `$lead` completely bypasses the logic in [PageModel](https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Model/PageModel.php#L462-L479). This alters current application behaviour. E.g. `ct` query parameter is not taken into account, etc.

2020-11-23 11:37 UTC, RCheesley commented
@xnohat please can you review the feed

2020-11-24 22:14 UTC, mabumusa1 commented
@xnohat this is a valuable PR, we would love to get your contribution, I hope you have some time to review the comments and publish the changes. I would love to test it again

2021-03-05 14:35 UTC, npracht commented
@xnohat do you plan to continue working on this PR or i should close it ?
Thanks a lot for your help :)

2021-12-21 03:09 UTC, closed without merging