Force to array for groupBy and aggregators in reports
mautic/mautic pull request #9392
Opened 2020-11-10 16:19 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This happend If you use default reports from older instances. If aggregators and orderBy columns are null it return a lot of errors for Leads and Points report (id 5 after installation)

![image](https://user-images.githubusercontent.com/462477/98700457-7e7b7580-2378-11eb-8b2c-6f889e138f09.png)

Errors:

`[2020-10-26 16:15:40] mautic.WARNING: PHP Warning - array_merge(): Argument #2 is not an array - in file /path/app/bundles/ReportBundle/Entity/Report.php - at line 505 [] [] [2020-10-26 16:15:40] mautic.WARNING: PHP Warning - array_merge(): Argument #1 is not an array - in file /path/app/bundles/ReportBundle/Entity/Report.php - at line 497 [] [] [2020-10-26 16:15:40] mautic.WARNING: PHP Warning - in_array() expects parameter 2 to be array, null given - in file /path/app/bundles/ReportBundle/Event/ReportGeneratorEvent.php - at line 400 {"column":"comp.companyname","columns":null} []`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create basic report
3. Force set aggregators and group_by columns to null 
4. See errors in report details reported above
5. After fix it should work properly

2020-11-18 20:10 UTC, escopecz submitted a review, later dismissed
Makes sense. But could you also fix the return type comments when it's certain that those 2 methods will always return an array?

2020-11-20 13:03 UTC, hluchas requested changes
The return type is always clear here.
Please consider my suggestions
TY!

2020-11-20 13:03 UTC, hluchas commented on app/bundles/ReportBundle/Entity/Report.php
>      public function getGroupBy()
```suggestion
    public function getGroupBy(): array
```

2020-11-20 13:03 UTC, hluchas commented on app/bundles/ReportBundle/Entity/Report.php
>      public function getAggregators()
```suggestion
    public function getAggregators(): array
```

2020-11-21 10:07 UTC, kuzmany commented
@hluchas thanks, make sense. I applied it.

2020-11-21 12:53 UTC, escopecz requested changes
As much as I'd like to have the return types it's a BC change. That's why [I suggested to fix only the return types in the comments](https://github.com/mautic/mautic/pull/9392#pullrequestreview-533834795).

Imagine that someone is extending the Report entity and overwriting those 2 methods. It cause a PHP error now as the return type would mismatch.

2020-11-22 11:05 UTC, kuzmany commented
@escopecz thanks, I've revert back and change comments type.

2020-11-23 08:05 UTC, escopecz approved these changes, later dismissed
Thanks @kuzmany! 👍

2020-11-23 08:05 UTC, escopecz commented
Although it will need some tests to be mergeable...

2021-05-14 06:18 UTC, npracht commented
@escopecz @hluchas can you please review one more time ? I think all your comments have been addressed :)

2021-05-15 19:55 UTC, RCheesley commented
@kuzmany I tried to test this but I am unable to replicate the original issue. Is this still relevant?

I have edited the points & leads report in the DB and set the values to (NULL) as you suggest, and when I access the report I am not seeing any errors in the logs (using dev mode).

2021-05-17 20:19 UTC, escopecz commented
@RCheesley @npracht https://github.com/mautic/mautic/pull/9392#issuecomment-731996508 still hasn't been addressed

2024-06-20 08:05 UTC, kuzmany commented
Close. Do not want to rebase it to M5

2024-06-20 08:05 UTC, closed without merging