disabling FI tracking by deactivating pixel
mautic/mautic pull request #9404
Opened 2020-11-13 14:25 UTC by luguenth

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | n.A.
| Related developer documentation PR URL | n.A.
| Issue(s) addressed                     | n.A.

#### Description:

We wanted to get rid of tracking when using Focus Items. So we made a setting for the FocusBundle to not include the Tracking-Pixel if disabled. So there'll be no more Tracking-Cookies any more.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to the Configuration Page
3. Select Focus Settings.
4. Disable the Tracking-Pixel
5. Create a FI
6. embed this item at another Website
7. Look into the DevConsole, there shouldn't be any mtc-tracking cookies anymore. Except the FI-Cookie

2020-11-13 14:43 UTC, ekkeguembel commented
Background: This allows Focus Items to be used even if a **Consent Manager** is used and the user has denied consent to tracking, marketing cookies etc.
The mautic_focus cookie will still be set (can be defined as "technically required") but nothing else.

2020-11-18 20:02 UTC, escopecz requested changes
Great feature! I've found a couple ways how to improve the code. Please check if it makes sense for you. 

Also the CodeCov check is failing. Please add one more test. Check the CodeCov details to see what can be still covered.

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/EventListener/ConfigSubscriber.php
> + * @copyright   2014 Mautic Contributors. All rights reserved
```suggestion
 * @copyright   2020 Mautic Contributors. All rights reserved
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/EventListener/ConfigSubscriber.php
> +class ConfigSubscriber implements EventSubscriberInterface
Some offensive programming won't hurt.
```suggestion
final class ConfigSubscriber implements EventSubscriberInterface
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/EventListener/ConfigSubscriber.php
> +    public static function getSubscribedEvents()
The method comment can be removed when we can use return types for new methods in Mautic 3 🎉 
```suggestion
    public static function getSubscribedEvents(): array
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/EventListener/ConfigSubscriber.php
> +    public function onConfigGenerateTracking(ConfigBuilderEvent $event)
```suggestion
    public function onConfigGenerateTracking(ConfigBuilderEvent $event): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Form/Type/FocusConfigTrackingPageType.php
> + * @copyright   2014 Mautic Contributors. All rights reserved
```suggestion
 * @copyright   2020 Mautic Contributors. All rights reserved
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/EventListener/ConfigSubscriber.php
> +
```suggestion

declare(strict_types = 1);
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Form/Type/FocusConfigTrackingPageType.php
> +
```suggestion

declare(strict_types = 1);
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Form/Type/FocusConfigTrackingPageType.php
> + * Class ConfigType.
Please remove this class comment completely.

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Form/Type/FocusConfigTrackingPageType.php
> +                'data'  => isset($options['data']['focus_pixel_enabled']) ? (bool) $options['data']['focus_pixel_enabled'] : false,
Why is the default value false?
```suggestion
                'data'  => (bool) $options['data']['focus_pixel_enabled']) ?? true,
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/Form/Type/FocusConfigTrackingPageTypeTest.php
> +                    'data'  => isset($options['data']['focus_pixel_enabled']) ? (bool) $options['data']['focus_pixel_enabled'] : false,
Why is the default value false?
```suggestion
                'data'  => (bool) $options['data']['focus_pixel_enabled']) ?? true,
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/EventListener/ConfigSubscriberTest.php
> +
```suggestion

declare(strict_types = 1);
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/Form/Type/FocusConfigTrackingPageTypeTest.php
> +/*
```suggestion

declare(strict_types = 1);

/*
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/Form/Type/FocusConfigTrackingPageTypeTest.php
> +    public function testGetBlockPrefix()
```suggestion
    public function testGetBlockPrefix(): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/Form/Type/FocusConfigTrackingPageTypeTest.php
> +    public function testBuildForm()
```suggestion
    public function testBuildForm(): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/Form/Type/FocusConfigTrackingPageTypeTest.php
> +    public function setUp()
```suggestion
    public function setUp(): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/EventListener/ConfigSubscriberTest.php
> +    protected function setUp()
```suggestion
    protected function setUp(): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Tests/EventListener/ConfigSubscriberTest.php
> +    public function testGetSubscribedEvents()
```suggestion
    public function testGetSubscribedEvents(): void
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Translations/en_US/messages.ini
> +mautic.page.config.form.focus.pixel.enabled.tooltip = "If set to no, there will be no Tracking Cookies set."
Let's add the reason for why would anyone want to turn it off to the tooltip.
```suggestion
mautic.page.config.form.focus.pixel.enabled.tooltip = "If set to no, there will be no Tracking Cookies set. This allows Focus Items to be used even if a Consent Manager is used and the user has denied consent to tracking, marketing cookies etc. The mautic_focus cookie will still be set (can be defined as "technically required") but nothing else."
```

2020-11-18 20:02 UTC, escopecz commented on plugins/MauticFocusBundle/Model/FocusModel.php
> +                'tracking_enabled' => $this->coreParametersHelper->get('focus_pixel_enabled'),
```suggestion
                'tracking_enabled' => $this->coreParametersHelper->get('focus_pixel_enabled', true),
```

2021-03-26 14:38 UTC, luguenth commented
Did I overlook some change requests? They seem resolved for me. But GitHub still states there are requests, where can I find them?

2021-07-01 10:06 UTC, luguenth commented
@escopecz can you recheck the PR? There still seem to be requested changes, but I can't find them.

2021-07-16 09:58 UTC, escopecz commented on plugins/MauticFocusBundle/Translations/en_US/messages.ini
> +mautic.page.config.form.focus.pixel.enabled.tooltip = "If set to no, there will be no Tracking Cookies set. This allows Focus Items to be used even if a Consent Manager is used and the user has denie
The inner double quotes will have to be escaped or changed to single quotes.

```suggestion
mautic.page.config.form.focus.pixel.enabled.tooltip = "If set to no, there will be no Tracking Cookies set. This allows Focus Items to be used even if a Consent Manager is used and the user has denied consent to tracking, marketing cookies etc. The mautic_focus cookie will still be set (can be defined as \"technically required\") but nothing else."
```

2021-07-16 10:00 UTC, luguenth commented
Alright, I accepted your Code Changes :) Could you re-review please? :rocket:

2021-07-16 11:05 UTC, escopecz commented
I see no issues in the code. But I'm a bit confused from the testing. I see no cookies stored at all even without this configuration. I can see `mautic_device_id`, `mtc_sid` and `mtc_id` keys and values stored in local storage. And this happens when I enable or disable this feature. Am I missing something?

2021-07-16 13:58 UTC, RCheesley commented
@luguenth any tips to help @escopecz with reproducing the issue this PR is meant to be fixing?

2021-07-16 18:55 UTC, ekkeguembel commented
@RCheesley @escopecz we reviewed today, and decided that we are unsure about the exact _desired_ behavior in conjunction with various consent managers.
-> Let's not put this into 4.0 but rather take a bit of time on Monday and make sure we do the right thing.

2021-12-21 03:10 UTC, closed without merging