Fix reset form field alias
mautic/mautic pull request #9443
Opened 2020-11-25 17:25 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Noticed issue  reset custom alias of field was reset every time while we edit it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create new form
3. Create new field **Custom** with Field HTML name **custom1**
4. Save it
5. Open it and see Field HTML name is still **custom1**
6. Save again and see Field HTML name is now **custom**
7. We expect still **custom1** alias of field

![image](https://user-images.githubusercontent.com/462477/100260554-d81f9a80-2f49-11eb-8182-59e2b4a368ca.png)

2020-12-14 16:25 UTC, escopecz requested changes
Plus needs a test

2020-12-15 10:41 UTC, escopecz requested changes

2020-12-15 10:41 UTC, escopecz commented on app/bundles/FormBundle/Controller/FieldController.php
> +                                $formField['alias'] ? $formField['alias'] : $formField['label'],
Hmm, my suggestion was not saved for some reason. Trying once more
```suggestion
                                $formField['alias'] ?? $formField['label'],
```

2021-02-09 17:27 UTC, mohit-rocks approved these changes
I did a quick test on local and it seems working fine.
Attaching small video recording for the same:

<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/4ec35c10f2f748ff90ef6bbf23f8f868" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

2021-02-09 17:35 UTC, RCheesley commented
@escopecz is this one good to go now? I know you had a few suggestions earlier in the process so just checking that this is good from your perspective before we merge

2021-02-11 10:49 UTC, escopecz submitted a review, later dismissed
I see no issue. Thanks Zdeno! 👍

2021-02-11 10:51 UTC, escopecz reviewed
Although, double-checking the test. It does not test the change in the FieldController but the `generateAlias` method in the FormModel. It doesn't make much sense.

2021-02-11 10:57 UTC, escopecz commented
I don't want to block this PR. If the release leader thinks it's OK to test different part of the code than which was changed to get the green light from Codecov check then feel free to merge.

2021-02-13 20:22 UTC, RCheesley commented
I will allow this one to pass having tested and confirmed that the PR does fix the reported issue, however in the future please  @kuzmany take on board the [comments from John](https://github.com/mautic/mautic/pull/9443#pullrequestreview-588433745))

2021-02-13 20:22 UTC, merged