Fixes mautic/issues/9187 - Migration to increase field length for remo…
mautic/mautic pull request #9542
Opened 2020-12-28 07:16 UTC by saitanay

closes https://github.com/mautic/mautic/issues/9187

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | not applicable
| Related developer documentation PR URL | not applicable
| Issue(s) addressed                     | Fixes #9187

#### Description:
Allows long URLs (more than 191 chars) for remote assers. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Add a remote asset with a really long url. If you don't have one such, you can try the below with 2500+ Characters- 
`https://www.mautic.org/sites/default/files/content-images/Mautic_Logo_RGB_LB_39.png?random=RdkfEXkKJoYZojXeEqhXFTxgfCWrdiyiq2sPmPMDatuHgGsEdJA5QlfoHWCWJnc4goI3X3iR2BU9IRelxLzoyHcKa3pDEkdVtyp966c6pXWDtepAJg8EvcAvbsiNonyLsKVEvKv0QWFrEo4hMyR8ST7XAG7tlC1gFtnuhz5oRCPQy0akLjQ0guZr8khdyjjLtXY3DMzsTdlsx3OpMBHL5rihTxyfPrXcbBL3HW1O4hO8oMoPoagtlZXiYTQvPCnZJHJIhyd6VZztp3Uol41kWvyjbCxqKPqBOCS9jnt1DsH99PzNdJVJhw8XJwKQZ0SbPHSt439GmKfFhmbdHU78KPMwbiPYOBf90anedRUEoij86uez14GDnZbrPwGRPc2ft8SuVyF7a7gInF0DZfAwUPmTdWBOAsgK5YzKA3yJWuBI6BxQzlm9vnQb1cBQCHMm6L5fiBzxTTCJLQMSA173xIf9XCqsltBPFTXmeXFYyBCOO7ROPBa18FNejIIOA71AQR8TNFJSRhhSWEZO4PXfopXvuKce50I2Xx73QttdRkDejwE2AcFdFXdFH4lnphExmP0zms9dAylOms2oPkLnt6goqWISsob05KzNZ8tfrVoZ26eXrCCdDj94iGjYcZnnAc5UGHaIva7QyIOAUSHTYk9AlhDs1bV7I6etz7iw9FKt3smNJRbuW70sgbPBOiP48nHZZTuFcm5mBCvgbkhdPVxVlIIVXL3Ma0XKN2Hon0sk9WbdcXyNoPbTXaacAbOroTB4fcIiksUSr1iPpo3De7KI6YVYd7mJfwY0BYA3g1tZTT4CdqP3cLrgwjb8vsBLD4WopDkte6SAM09mu4YwXIOF6bt1ctXefqPKoSh2bzdpLORQlthO0NQSf8Ma9UY42OWmQAzRGRsfDYi2tVrzasmci1lhdaqOoOOv7ldlZMmBjYbeNi0dlc8b4bFTuKF6fGNaGhzQ4znD45ByQ2TN2xrywMChO2fKJpZKvTs4tB0haGP7FkH24a23XPz0uv45ZzosSUURSnqST0jFd2BDYDC6fxD4HIJ3seFesDugKm3yX2qXm7H4q4YizzP6Ht0pPLVASrMgAgQtf4YDNAQ6WE5QEdjMNbYmy2m65FpoL9e8gweoYFO6UrpfI3SShKvsJQ7nFSyRRfOUXunCjh0USBJZpvkUQbYDp3PAytodLseECI3hERomadTGU8gWzpeFFwqoF95UYUtLjgLr0CHn38pGgT5qaXJPcmqjapg1nvZIUqU5rwojKDpw8pNMYqJ1VryACXS4f40dkfXCG9JAUlwCnXxkwv1nzuqt6O11N0pPkhWb70G6zOnmXL8YdfLbQHOZj0MlYTzJevrLWtWuGwhLEnwakcc2n8c4g9kpWCjC2dsLQ0jy7Ougz7K7vPLqCZcqDrnptDU6kGELluOr1sNarEfWsteBICq6v46F5YtIDLhjLvyith5yiwomWspzKeaHYpA1FlIRVjMzKcMpWh0DbzwYyDHaxBo84APhX3bUFH3O8KNUezksW5HsNwZ3y0n6AGucnM23XkCmKu2ldVXVpLiAa2fQzEyd1brbrljP0DulZz1KoQnrgabgc3FjFVRBxAcA8I7Ik0wifYqUZxgkBDvmSHel3x2wXT9M9dx4bXjxxFcyAiulsTEwsndQkO1hRmaT8GxgRqtw2rRYw1LpGGkIbcEYGeyR8pgXNLOtLyw76XPHsy5cxspoLUzB2PYGFFapiarYpi4ERbv1Yd36YQmlZJSNvRUggnQ3ZLYyfgytN0wkhBnE1cbRt29Fy08FKtQcRAWi0HZcFcGUYqRdVnB08b72TEh1AhsiGilPV7tbprCLIdbiE7wn5DWDPWbIrHgDE9hyUYX7AJzJtFogZYxqIcagLaCWyrg98CqUji0in5kwHvkBFaLoVLA4gcgysgOTHMEnOKogrjplDv4RHB7iRDrt9wEcsJTYjzzMVnOkIcoOk7z7VqRx8iywymTR1gHbnwlQp2uxIT9BKDvOHLuYqYnSEHGBuCOLyQ82BGZGYWKdt8cHhlZkD4OAtUR5k3uzTCUfaGRwrzCKWFdG1ErCxJn0yQ8soT915ZA5sGWOzLQsnjlapVSVWBaAHWqhJZCgvjiwezjfdJyN3MTSJEZtMaBJ9KkZjpCDURDmCtSW4l5LLvrErTYefJzAgvqoUFA1mJdoD6BaCUXUq7zsujCp3S1sFetbCdt589WM8adDxz6A1xkJJRABXQ8JvWTsUpqmKVOdyQh5YIKVvVaUkT4Rw00MU5afLMZAqjjM57tInovdMOBXMwhhQ2OOatqx2sg7MafnQd1uu0dNWVp6Tym7T9dCQJFVjLzqHiYmQAMNEaNyfitXJtoDVOzqVlM23sUCP8VjbDAzzUd5239hUrhkcF5V8uoeBFbcuyhDwXoY8Yljx6SSX5HFjzXqUpoxsIAghvAyHTxxGM2U4aTd0elO4LOhEQ2yCmC7z7BUvazlaErHcHyBdw9QO2GluHOb
`

2020-12-28 07:18 UTC, saitanay commented
Original PR - https://github.com/mautic/mautic/pull/9541 was raised against 3.2

Since this contains a migration, raising a PR against features branch for 3.3

2020-12-29 05:19 UTC, npracht commented
check @cla-bot

2020-12-31 17:50 UTC, saitanay commented
check @cla-bot

2021-01-01 19:58 UTC, kuzmany requested changes
Require also make changes in entity  https://github.com/mautic/mautic/blob/features/app/bundles/AssetBundle/Entity/Asset.php#L180

2021-01-04 09:07 UTC, saitanay commented
> Require also make changes in entity https://github.com/mautic/mautic/blob/features/app/bundles/AssetBundle/Entity/Asset.php#L180

Added https://github.com/mautic/mautic/pull/9542/files#diff-06bd5db022defd8aa419f97be262bf61a2862a02d4bda16d611664d5e58433f7L184

2021-01-05 08:11 UTC, kuzmany requested changes
originalFileName need to by changed in entity too https://github.com/mautic/mautic/pull/9542/files#diff-06bd5db022defd8aa419f97be262bf61a2862a02d4bda16d611664d5e58433f7L189

Both could be change to CLASS constant Types::TEXT same like here

https://github.com/mautic/mautic/blob/features/app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php#L205

2021-01-18 17:23 UTC, RCheesley commented
@saitanay could you review the [suggestion from @kuzmany ](https://github.com/mautic/mautic/pull/9542#pullrequestreview-561584887) please?

2021-03-05 14:30 UTC, npracht commented
Hello @saitanay any chance you end it ? Then we can merge it :)

2021-05-27 08:26 UTC, dadarya0 commented
> originalFileName need to by changed in entity too https://github.com/mautic/mautic/pull/9542/files#diff-06bd5db022defd8aa419f97be262bf61a2862a02d4bda16d611664d5e58433f7L189
> 
> Both could be change to CLASS constant Types::TEXT same like here
> 
> https://github.com/mautic/mautic/blob/features/app/bundles/CoreBundle/Doctrine/Mapping/ClassMetadataBuilder.php#L205

Suggestion implemented
https://github.com/mautic/mautic/pull/9542/commits/6f79001a9c7ebc2a44829f0bbda77bd9503a69f1

2021-05-27 16:56 UTC, kuzmany approved these changes
Looks good 👍

2021-07-15 06:35 UTC, npracht approved these changes
Before:
```
[2021-07-14 06:39:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO assets (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, title, description, alias, storage_location, path, remote_path, original_file_name, lang, publish_up, publish_down, download_count, unique_download_count, revision, extension, mime, size, disallow, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2021-07-14 06:39:53", 1, "Norman Pracht", null, null, null, null, null, null, "remote asset", null, "remote-asset", "remote", null, "https:\/\/www.mautic.org\/sites\/default\/files\/content-images\/Mautic_Logo_RGB_LB_39.png?random=RdkfEXkKJoYZojXeEqhXFTxgfCWrdiyiq2sPmPMDatuHgGsEdJA5QlfoHWCWJnc4goI3X3iR2BU9IRelxLzoyHcKa3pDEkdVtyp966c6pXWDtepAJg8EvcAvbsiNonyLsKVEvKv0QWFrEo4hMyR8ST7XAG7tlC1gFtnuhz5oRCPQy0akLjQ0guZr8khdyjjLtXY3DMzsTdlsx3OpMBHL5rihTxyfPrXcbBL3HW1O4hO8oMoPoagtlZXiYTQvPCnZJHJIhyd6VZztp3Uol41kWvyjbCxqKPqBOCS9jnt1DsH99PzNdJVJhw8XJwKQZ0SbPHSt439GmKfFhmbdHU78KPMwbiPYOBf90anedRUEoij86uez14GDnZbrPwGRPc2ft8SuVyF7a7gInF0DZfAwUPmTdWBOAsgK5YzKA3yJWuBI6BxQzlm9vnQb1cBQCHMm6L5fiBzxTTCJLQMSA173xIf9XCqsltBPFTXmeXFYyBCOO7ROPBa18FNejIIOA71AQR8TNFJSRhhSWEZO4PXfopXvuKce50I2Xx73QttdRkDejwE2AcFdFXdFH4lnphExmP0zms9dAylOms2oPkLnt6goqWISsob05KzNZ8tfrVoZ26eXrCCdDj94iGjYcZnnAc5UGHaIva7QyIOAUSHTYk9AlhDs1bV7I6etz7iw9FKt3smNJRbuW70sgbPBOiP48nHZZTuFcm5mBCvgbkhdPVxVlIIVXL3Ma0XKN2Hon0sk9WbdcXyNoPbTXaacAbOroTB4fcIiksUSr1iPpo3De7KI6YVYd7mJfwY0BYA3g1tZTT4CdqP3cLrgwjb8vsBLD4WopDkte6SAM09mu4YwXIOF6bt1ctXefqPKoSh2bzdpLORQlthO0NQSf8Ma9UY42OWmQAzRGRsfDYi2tVrzasmci1lhdaqOoOOv7ldlZMmBjYbeNi0dlc8b4bFTuKF6fGNaGhzQ4znD45ByQ2TN2xrywMChO2fKJpZKvTs4tB0haGP7FkH24a23XPz0uv45ZzosSUURSnqST0jFd2BDYDC6fxD4HIJ3seFesDugKm3yX2qXm7H4q4YizzP6Ht0pPLVASrMgAgQtf4YDNAQ6WE5QEdjMNbYmy2m65FpoL9e8gweoYFO6UrpfI3SShKvsJQ7nFSyRRfOUXunCjh0USBJZpvkUQbYDp3PAytodLseECI3hERomadTGU8gWzpeFFwqoF95UYUtLjgLr0CHn38pGgT5qaXJPcmqjapg1nvZIUqU5rwojKDpw8pNMYqJ1VryACXS4f40dkfXCG9JAUlwCnXxkwv1nzuqt6O11N0pPkhWb70G6zOnmXL8YdfLbQHOZj0MlYTzJevrLWtWuGwhLEnwakcc2n8c4g9kpWCjC2dsLQ0jy7Ougz7K7vPLqCZcqDrnptDU6kGELluOr1sNarEfWsteBICq6v46F5YtIDLhjLvyith5yiwomWspzKeaHYpA1FlIRVjMzKcMpWh0DbzwYyDHaxBo84APhX3bUFH3O8KNUezksW5HsNwZ3y0n6AGucnM23XkCmKu2ldVXVpLiAa2fQzEyd1brbrljP0DulZz1KoQnrgabgc3FjFVRBxAcA8I7Ik0wifYqUZxgkBDvmSHel3x2wXT9M9dx4bXjxxFcyAiulsTEwsndQkO1hRmaT8GxgRqtw2rRYw1LpGGkIbcEYGeyR8pgXNLOtLyw76XPHsy5cxspoLUzB2PYGFFapiarYpi4ERbv1Yd36YQmlZJSNvRUggnQ3ZLYyfgytN0wkhBnE1cbRt29Fy08FKtQcRAWi0HZcFcGUYqRdVnB08b72TEh1AhsiGilPV7tbprCLIdbiE7wn5DWDPWbIrHgDE9hyUYX7AJzJtFogZYxqIcagLaCWyrg98CqUji0in5kwHvkBFaLoVLA4gcgysgOTHMEnOKogrjplDv4RHB7iRDrt9wEcsJTYjzzMVnOkIcoOk7z7VqRx8iywymTR1gHbnwlQp2uxIT9BKDvOHLuYqYnSEHGBuCOLyQ82BGZGYWKdt8cHhlZkD4OAtUR5k3uzTCUfaGRwrzCKWFdG1ErCxJn0yQ8soT915ZA5sGWOzLQsnjlapVSVWBaAHWqhJZCgvjiwezjfdJyN3MTSJEZtMaBJ9KkZjpCDURDmCtSW4l5LLvrErTYefJzAgvqoUFA1mJdoD6BaCUXUq7zsujCp3S1sFetbCdt589WM8adDxz6A1xkJJRABXQ8JvWTsUpqmKVOdyQh5YIKVvVaUkT4Rw00MU5afLMZAqjjM57tInovdMOBXMwhhQ2OOatqx2sg7MafnQd1uu0dNWVp6Tym7T9dCQJFVjLzqHiYmQAMNEaNyfitXJtoDVOzqVlM23sUCP8VjbDAzzUd5239hUrhkcF5V8uoeBFbcuyhDwXoY8Yljx6SSX5HFjzXqUpoxsIAghvAyHTxxGM2U4aTd0elO4LOhEQ2yCmC7z7BUvazlaErHcHyBdw9QO2GluHOb", "Mautic_Logo_RGB_LB_39.png?random=RdkfEXkKJoYZojXeEqhXFTxgfCWrdiyiq2sPmPMDatuHgGsEdJA5QlfoHWCWJnc4goI3X3iR2BU9IRelxLzoyHcKa3pDEkdVtyp966c6pXWDtepAJg8EvcAvbsiNonyLsKVEvKv0QWFrEo4hMyR8ST7XAG7tlC1gFtnuhz5oRCPQy0akLjQ0guZr8khdyjjLtXY3DMzsTdlsx3OpMBHL5rihTxyfPrXcbBL3HW1O4hO8oMoPoagtlZXiYTQvPCnZJHJIhyd6VZztp3Uol41kWvyjbCxqKPqBOCS9jnt1DsH99PzNdJVJhw8XJwKQZ0SbPHSt439GmKfFhmbdHU78KPMwbiPYOBf90anedRUEoij86uez14GDnZbrPwGRPc2ft8SuVyF7a7gInF0DZfAwUPmTdWBOAsgK5YzKA3yJWuBI6BxQzlm9vnQb1cBQCHMm6L5fiBzxTTCJLQMSA173xIf9XCqsltBPFTXmeXFYyBCOO7ROPBa18FNejIIOA71AQR8TNFJSRhhSWEZO4PXfopXvuKce50I2Xx73QttdRkDejwE2AcFdFXdFH4lnphExmP0zms9dAylOms2oPkLnt6goqWISsob05KzNZ8tfrVoZ26eXrCCdDj94iGjYcZnnAc5UGHaIva7QyIOAUSHTYk9AlhDs1bV7I6etz7iw9FKt3smNJRbuW70sgbPBOiP48nHZZTuFcm5mBCvgbkhdPVxVlIIVXL3Ma0XKN2Hon0sk9WbdcXyNoPbTXaacAbOroTB4fcIiksUSr1iPpo3De7KI6YVYd7mJfwY0BYA3g1tZTT4CdqP3cLrgwjb8vsBLD4WopDkte6SAM09mu4YwXIOF6bt1ctXefqPKoSh2bzdpLORQlthO0NQSf8Ma9UY42OWmQAzRGRsfDYi2tVrzasmci1lhdaqOoOOv7ldlZMmBjYbeNi0dlc8b4bFTuKF6fGNaGhzQ4znD45ByQ2TN2xrywMChO2fKJpZKvTs4tB0haGP7FkH24a23XPz0uv45ZzosSUURSnqST0jFd2BDYDC6fxD4HIJ3seFesDugKm3yX2qXm7H4q4YizzP6Ht0pPLVASrMgAgQtf4YDNAQ6WE5QEdjMNbYmy2m65FpoL9e8gweoYFO6UrpfI3SShKvsJQ7nFSyRRfOUXunCjh0USBJZpvkUQbYDp3PAytodLseECI3hERomadTGU8gWzpeFFwqoF95UYUtLjgLr0CHn38pGgT5qaXJPcmqjapg1nvZIUqU5rwojKDpw8pNMYqJ1VryACXS4f40dkfXCG9JAUlwCnXxkwv1nzuqt6O11N0pPkhWb70G6zOnmXL8YdfLbQHOZj0MlYTzJevrLWtWuGwhLEnwakcc2n8c4g9kpWCjC2dsLQ0jy7Ougz7K7vPLqCZcqDrnptDU6kGELluOr1sNarEfWsteBICq6v46F5YtIDLhjLvyith5yiwomWspzKeaHYpA1FlIRVjMzKcMpWh0DbzwYyDHaxBo84APhX3bUFH3O8KNUezksW5HsNwZ3y0n6AGucnM23XkCmKu2ldVXVpLiAa2fQzEyd1brbrljP0DulZz1KoQnrgabgc3FjFVRBxAcA8I7Ik0wifYqUZxgkBDvmSHel3x2wXT9M9dx4bXjxxFcyAiulsTEwsndQkO1hRmaT8GxgRqtw2rRYw1LpGGkIbcEYGeyR8pgXNLOtLyw76XPHsy5cxspoLUzB2PYGFFapiarYpi4ERbv1Yd36YQmlZJSNvRUggnQ3ZLYyfgytN0wkhBnE1cbRt29Fy08FKtQcRAWi0HZcFcGUYqRdVnB08b72TEh1AhsiGilPV7tbprCLIdbiE7wn5DWDPWbIrHgDE9hyUYX7AJzJtFogZYxqIcagLaCWyrg98CqUji0in5kwHvkBFaLoVLA4gcgysgOTHMEnOKogrjplDv4RHB7iRDrt9wEcsJTYjzzMVnOkIcoOk7z7VqRx8iywymTR1gHbnwlQp2uxIT9BKDvOHLuYqYnSEHGBuCOLyQ82BGZGYWKdt8cHhlZkD4OAtUR5k3uzTCUfaGRwrzCKWFdG1ErCxJn0yQ8soT915ZA5sGWOzLQsnjlapVSVWBaAHWqhJZCgvjiwezjfdJyN3MTSJEZtMaBJ9KkZjpCDURDmCtSW4l5LLvrErTYefJzAgvqoUFA1mJdoD6BaCUXUq7zsujCp3S1sFetbCdt589WM8adDxz6A1xkJJRABXQ8JvWTsUpqmKVOdyQh5YIKVvVaUkT4Rw00MU5afLMZAqjjM57tInovdMOBXMwhhQ2OOatqx2sg7MafnQd1uu0dNWVp6Tym7T9dCQJFVjLzqHiYmQAMNEaNyfitXJtoDVOzqVlM23sUCP8VjbDAzzUd5239hUrhkcF5V8uoeBFbcuyhDwXoY8Yljx6SSX5HFjzXqUpoxsIAghvAyHTxxGM2U4aTd0elO4LOhEQ2yCmC7z7BUvazlaErHcHyBdw9QO2GluHOb", "en", null, null, 0, 0, 1, "png", "image\/png", 35103, 0, null]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'remote_path' at row 1" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO assets (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, title, description, alias, storage_location, path, remote_path, original_file_name, lang, publish_up, publish_down, download_count, unique_download_count, revision, extension, mime, size, disallow, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2021-07-14 06:39:53\", 1, \"Norman Pracht\", null, null, null, null, null, null, \"remote asset\", null, \"remote-asset\", \"remote\", null, \"https:\\/\\/www.mautic.org\\/sites\\/default\\/files\\/content-images\\/Mautic_Logo_RGB_LB_39.png?random=RdkfEXkKJoYZojXeEqhXFTxgfCWrdiyiq2sPmPMDatuHgGsEdJA5QlfoHWCWJnc4goI3X3iR2BU9IRelxLzoyHcKa3pDEkdVtyp966c6pXWDtepAJg8EvcAvbsiNonyLsKVEvKv0QWFrEo4hMyR8ST7XAG7tlC1gFtnuhz5oRCPQy0akLjQ0guZr8khdyjjLtXY3DMzsTdlsx3OpMBHL5rihTxyfPrXcbBL3HW1O4hO8oMoPoagtlZXiYTQvPCnZJHJIhyd6VZztp3Uol41kWvyjbCxqKPqBOCS9jnt1DsH99PzNdJVJhw8XJwKQZ0SbPHSt439GmKfFhmbdHU78KPMwbiPYOBf90anedRUEoij86uez14GDnZbrPwGRPc2ft8SuVyF7a7gInF0DZfAwUPmTdWBOAsgK5YzKA3yJWuBI6BxQzlm9vnQb1cBQCHMm6L5fiBzxTTCJLQMSA173xIf9XCqsltBPFTXmeXFYyBCOO7ROPBa18FNejIIOA71AQR8TNFJSRhhSWEZO4PXfopXvuKce50I2Xx73QttdRkDejwE2AcFdFXdFH4lnphExmP0zms9dAylOms2oPkLnt6goqWISsob05KzNZ8tfrVoZ26eXrCCdDj94iGjYcZnnAc5UGHaIva7QyIOAUSHTYk9AlhDs1bV7I6etz7iw9FKt3smNJRbuW70sgbPBOiP48nHZZTuFcm5mBCvgbkhdPVxVlIIVXL3Ma0XKN2Hon0sk9WbdcXyNoPbTXaacAbOroTB4fcIiksUSr1iPpo3De7KI6YVYd7mJfwY0BYA3g1tZTT4CdqP3cLrgwjb8vsBLD4WopDkte6SAM09mu4YwXIOF6bt1ctXefqPKoSh2bzdpLORQlthO0NQSf8Ma9UY42OWmQAzRGRsfDYi2tVrzasmci1lhdaqOoOOv7ldlZMmBjYbeNi0dlc8b4bFTuKF6fG [...]

2021-07-15 08:01 UTC, merged