Bug report graph line leads
mautic/mautic pull request #9547
Opened 2020-12-30 10:53 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                |  features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
If we create a report based on contacts from the segment:
1. Data source: Contacts
2. Filters equals Segment
![image](https://user-images.githubusercontent.com/39382654/103345681-519f3100-4a92-11eb-8e8d-ac687c4467a2.png)

and we add "New contacts added (Line graph)" we have data not compatible with the table

![image](https://user-images.githubusercontent.com/39382654/103344997-785c6800-4a90-11eb-9075-a689d285f407.png)

The query to the database looks like this  
```
SELECT DATE_FORMAT(l.date_added, '%Y-%m') AS date, COUNT(*) AS count FROM leads l 
INNER JOIN lead_lists_leads s 
ON s.lead_id = l.id 
AND s.manually_removed = 0 
WHERE (s.date_added IS NULL OR (s.date_added BETWEEN :dateFrom AND :dateTo)) 
AND (s.leadlist_id = :i4csleadlistid)
GROUP BY DATE_FORMAT(l.date_added, '%Y-%m') 
ORDER BY DATE_FORMAT(l.date_added, '%Y-%m') 
ASC LIMIT 4
```

In my opinion it should look like this
```
SELECT DATE_FORMAT(s.date_added, '%Y-%m') AS date, COUNT(*) AS count FROM leads l 
INNER JOIN lead_lists_leads s 
ON s.lead_id = l.id 
AND s.manually_removed = 0 
WHERE (s.date_added IS NULL OR (s.date_added BETWEEN :dateFrom AND :dateTo)) 
AND (s.leadlist_id = :i4csleadlistid) 
GROUP BY DATE_FORMAT(s.date_added, '%Y-%m') 
ORDER BY DATE_FORMAT(s.date_added, '%Y-%m') 
ASC LIMIT 4

```
Correct line graph
![image](https://user-images.githubusercontent.com/39382654/103346794-67622580-4a95-11eb-8d89-a2871ca91617.png)

2021-01-01 20:15 UTC, kuzmany requested changes
Doesn't work If don't use segment filter:


` 500 Internal Server Error - An exception occurred while executing 'SELECT DATE_FORMAT(s.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM 9547_leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY DATE_FORMAT(s.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(s.date_added, '%Y-%m-%d') ASC LIMIT 32' with params ["2020-12-01 00:00:00", "2021-01-01 20:13:43"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.date_added' in 'field list' `

You can test it here: https://mautibox.com/9547/s/reports/view/11

2021-01-01 20:16 UTC, kuzmany requested changes
Doesn't work If don't use segment filter:


` 500 Internal Server Error - An exception occurred while executing 'SELECT DATE_FORMAT(s.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM 9547_leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY DATE_FORMAT(s.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(s.date_added, '%Y-%m-%d') ASC LIMIT 32' with params ["2020-12-01 00:00:00", "2021-01-01 20:13:43"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.date_added' in 'field list' `

You can test it here: https://mautibox.com/9547/s/reports/view/11

2021-01-01 20:19 UTC, kuzmany commented on app/bundles/LeadBundle/EventListener/ReportSubscriber.php
> +                    $chartQuery->modifyTimeDataQuery($queryBuilder, 'date_added', 's');
You should add tablePrefix s just If query contain lead_lists_leads table

2021-01-20 08:45 UTC, npracht approved these changes
Well done !
<img width="1437" alt="Capture d’écran 2021-01-20 à 09 43 31" src="https://user-images.githubusercontent.com/14075239/105149609-ffd34f00-5b03-11eb-9fdb-c36d94f2236f.png">

2021-01-22 17:24 UTC, RCheesley commented
I think that this has already been fixed - or I am not understanding the instructions.

Using 3.2.5-Release Candidate I see a correct line chart that corresponds with the number of contacts added:

![screenshot-mautic32 ddev site-2021 01 22-17_22_02](https://user-images.githubusercontent.com/2930593/105523639-88094e00-5cd6-11eb-8f3e-19d3816b4f2b.png)

@npracht @tomekkowalczyk could you please confirm?

2021-01-23 09:49 UTC, kuzmany approved these changes
Works for me. 
Code looks good 👍

2021-01-23 09:50 UTC, kuzmany commented
@RCheesley this issue is related to report's contacts line graph

![image](https://user-images.githubusercontent.com/462477/105575036-c8b1a780-5d68-11eb-9ac0-435ca1e6805d.png)

2021-01-23 12:43 UTC, merged