Add environment variables for running test suite.
mautic/mautic pull request #9717
Opened 2021-02-23 16:28 UTC by mohit-rocks

Add base environment variables file.
Update setup file to copy it at appropriate place.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no (Not required)
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #... 

#### Description:
Adding sample environment variables that can be picked up while running PHPUnit test cases on local.

#### Steps to test this PR:
1. Pull the PR on local
2. Run ` sh .ddev/mautic-setup.sh`
3. When you run above script, ensure that ddev setup is not pre-configured. 
4. This will copy `.env.dist` from `.ddev` folder to the main folder of the project.

2021-02-23 16:30 UTC, mohit-rocks commented
Related original PR #9669

2021-02-24 09:07 UTC, dennisameling requested changes
This looks great, just two minor nits! 🚀

2021-02-24 09:07 UTC, dennisameling commented on .gitignore
> +!.ddev/.env.dist
This line is superfluous 😊 it'll also work without this line 👍🏼 

```suggestion
```

2021-02-24 09:07 UTC, dennisameling commented on .ddev/.env.dist
> +# .env.test
We can remove this comment 😊 

```suggestion
```

2021-02-24 12:33 UTC, dennisameling requested changes
Sorry but you removed the line in the wrong `.env.dist` file, please see the "Files changed" tab 😊  I requested the change on the `.ddev/.env.dist`. Thanks in advance 🚀

2021-02-24 13:16 UTC, mohit-rocks commented
Hi @dennisameling 
Sorry for the back n forth. I've updated the appropriate files. 
Please review the changes.

2021-02-24 14:53 UTC, dennisameling approved these changes, later dismissed
Awesome! Thank you! 🚀

2021-02-24 14:59 UTC, npracht commented
We can add that to 3.3.2 right ? I can label it `chore` also right ?

2021-02-24 18:34 UTC, dennisameling commented
Let's keep it as a bug, since it affects developers who are cloning Mautic from GitHub and using DDEV to contribute to it. 3.3.2 is fine 👍🏼

2021-03-13 21:13 UTC, RCheesley commented
Changed the base to 3.3 for merging in 3.3.2 - if all tests pass we should be good to go but it may well need to be rebased @mohit-rocks !

2021-04-30 17:02 UTC, RCheesley commented
@mohit-rocks if you have a moment can you rebase this for the features branch if we are to merge it in Mautic 4? Thanks!

2021-05-04 12:03 UTC, RCheesley commented
As this has not yet been rebased we will have to get this into a later release.

2021-05-14 17:01 UTC, merged