Segment email send to email address just once
mautic/mautic pull request #9781
Opened 2021-03-12 10:36 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Our client want use contacts with same email address, but avoid send more times to that email address, even If contact's are in segments.
This PR added new configuration parameter to enable avoid send segment email to more like one unique email address.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

2022-02-18 14:37 UTC, volha-pivavarchyk approved these changes, later dismissed
Works well as expected

2022-05-04 09:14 UTC, jos0405 commented
@kuzmany could you plz update this? I'll test immediately and it could be merged.

2022-05-06 08:40 UTC, kuzmany commented
@jos0405 done

2022-05-09 12:15 UTC, jos0405 submitted a review, later dismissed
Tested, works fine!

2022-05-13 14:06 UTC, volha-pivavarchyk submitted a review, later dismissed
Works well

2022-05-16 10:29 UTC, escopecz requested changes
There is a failing test:
```
There was 1 error:

1) Mautic\EmailBundle\Tests\Model\EmailModelFunctionalTest::testSendEmailToTwoSameEmailAddressWithOptionSegmentEmailOnceToEmailAddress
LogicException: You cannot re-create the client when a transaction rollback for cleanup is enabled. Turn it off using $useCleanupRollback property or avoid re-creating a client.

/home/runner/work/mautic/mautic/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php:85
/home/runner/work/mautic/mautic/app/bundles/EmailBundle/Tests/Model/EmailModelFunctionalTest.php:106
phpvfscomposer:///home/runner/work/mautic/mautic/vendor/phpunit/phpunit/phpunit:97
```

2022-05-16 10:29 UTC, escopecz commented on app/bundles/EmailBundle/Entity/EmailRepository.php
> +    protected $segmentEmailOnceToEmailAddress;
```suggestion
    private bool $segmentEmailOnceToEmailAddress = false;
```

2022-05-16 10:29 UTC, escopecz commented on app/bundles/EmailBundle/Tests/Model/EmailModelFunctionalTest.php
> +        $this->connection->executeQuery("SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))");
Why is this here? I think that's why the transaction rollback fails.

2024-05-21 08:16 UTC, npracht commented
Closed in favor of https://github.com/mautic/mautic/pull/13768 rebased against M5.

2024-05-21 08:16 UTC, closed without merging