Unschedule previous iterations when a contact enter a campaign.
mautic/mautic pull request #9829
Opened 2021-03-25 16:51 UTC by giomasce

This patch fixes #9797, preventing that contacts belonging
"twice" to a campaign eventually lead to database integrity
errors.

Signed-off-by: Giovanni Mascellani <giovanni@mascellani.eu>

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | none
| Related developer documentation PR URL | none-->
| Issue(s) addressed                     | Fixes #9797

#### Description:

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat the actions in https://github.com/mautic/mautic/issues/9797#issuecomment-804262839, noticing that they do not lead to a database integrity error or to misscheduled emails anymore

2021-03-25 16:58 UTC, a-sandris commented
The same issue happened in our setup as well, which basically stopped all the campaigns. 

Not sure about the correctness of the PR (since I am not a PHP dev) but the approach solved the problem.

2021-03-25 16:59 UTC, RCheesley commented
Great - thanks for making the PR to address the issue! Hopefully we can get some folk to test and review during the sprint this weekend - if you are available to join us some time Fri-Sun we would really love to have your help in the #mautic-4 channel on Slack (https://mautic.org/slack for an invite if you are not there already!)

2021-06-23 09:14 UTC, giomasce commented
Hi, is this eventually going to be considered? Thanks!

2021-09-28 11:13 UTC, RCheesley commented
@giomasce we are planning for this to be included in the 4.0.2 release (end of October) providing we have adequate testing and code review in time. Sorry for the delay, we are very short of people testing and reviewing PRs and are working through them as fast as we can!

2021-11-17 21:45 UTC, dongilbert approved these changes, later dismissed
Tested this locally and it does resolve the stated issue. Thanks @giomasce for providing such detailed logs and descriptions in #9797 - that was very helpful in understanding what's going on.

2021-11-24 11:28 UTC, RCheesley commented
@giomasce could you please rebase this on 4.x and then we can hopefully get it merged in the 4.1 release if we get one more tester :)

2021-11-24 19:48 UTC, giomasce commented
Done.

2021-11-25 20:48 UTC, giomasce commented
Wow, I cannot believe I managed to appease PHPSTAN!

2021-12-17 16:59 UTC, RCheesley commented
@giomasce if you can rebase this to the 4.1 branch then we can merge - we've got two tests and a code review which is sufficient. Thanks and sorry for the multiple rebases!

2021-12-17 20:27 UTC, giomasce commented
Done.

2021-12-20 10:28 UTC, escopecz approved these changes
Approving so I could merge as the original approval is stale after the rebase.

2021-12-20 10:55 UTC, escopecz requested changes
Actually, looking at the code there is no PHPUNIT test added. The new code must be covered in order to merge it in.

2021-12-20 10:55 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/CampaignRepository.php
> +    public function unscheduleContacts($contacts, $campaign)
```suggestion
    /**
     * @param \Doctrine\Common\Collections\ArrayCollection<string, Lead> $contacts
     */
    public function unscheduleContacts(ArrayCollection $contacts, Campaign $campaign): void
```

2021-12-20 10:55 UTC, escopecz commented on app/bundles/CampaignBundle/Executioner/ContactFinder/KickoffContactFinder.php
> +    public function unscheduleContacts($contacts, $campaign)
```suggestion
    /**
     * @param ArrayCollection<string, Lead> $contacts
     */
    public function unscheduleContacts(ArrayCollection $contacts, Campaign $campaign): void
```

2021-12-20 10:55 UTC, escopecz commented on app/bundles/CampaignBundle/Entity/CampaignRepository.php
> +        }
I'm just geeking out here, but another option how to write this is
```suggestion
        $contactIds = $contacts->map(fn (Lead $contact) => return (int) $contact->getId());
```

2021-12-20 13:55 UTC, escopecz commented
I discussed this with our product team. They think that it may depend on the exact scenario whether the marketer wants to:
1. Schedule events for every form submission
2. Unschedule the previous events and leave the new ones
3. Unschedule the new events and leave the original ones

Since every marketer may need different behavior, shouldn't this be configurable on the campaign level?

2021-12-21 20:33 UTC, giomasce commented
I don't have any problem with making this thing configurable, but I don't think I have the time to implement this configurability. Let me just stress that the current behaviour is buggy, it's not just a problem of limited configurability: as described in #9797, there are conditions under which Mautic throws an integrity exception and drops unrelated contacts from a campaign. Therefore I recommend to accept this PR even if it doesn't feature the configuration options as described by @escopecz.

2022-01-10 20:03 UTC, giomasce commented
I'm trying my best to contribute phpunit tests, but I am finding it very hard to even run the tests in a clean Mautic checkout (without my commit). I installed DDEV and Mautic following the instructions in https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup in a brand new Debian stable installation, but when I run the phpunit tests there are countless which are already failing. It's hard to develop unit tests when you can't even run those already provided. Are those installation instructions current?

2022-01-12 15:25 UTC, escopecz commented
@giomasce please take a look at https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#automated-testing. The tests may be failing because the functional tests don't have DB connection from the `.env` file. Also, use the `--filter` option to run only the test(s) you want. It takes some time to run them all just to get to the one you work on.

2022-01-24 17:10 UTC, RCheesley commented
As this is pending tests I am going to bump it to the next release (4.2, end of February) where we will hopefully be able to get it over the line!

2022-01-24 18:48 UTC, giomasce commented
For the record, I started writing tests, but I still have to learn and have very little spare time, so it might take some time.

2022-02-09 09:49 UTC, kuzmany commented
I remove ready to commit flag. 

@escopecz are you able to assists with this to make unit tests and make it ready before 4.2?

2022-02-09 09:56 UTC, escopecz commented
I won't be able to get to it in upcoming weeks. Maybe some day. @giomasce would you have time to finish the test?

2022-02-09 10:00 UTC, giomasce commented
It's on my todo list, I plan to keep working on this issue, but not in the immediate future, because of other life commitments.

2022-08-16 17:29 UTC, RCheesley commented
Thanks folks! Will need a rebase once the tests are added as we are now releasing from the 4.4 branch.

2025-07-07 08:10 UTC, closed without merging

2025-07-07 08:10 UTC, jos0405 commented
The bug related is closed already: https://github.com/mautic/mautic/issues/9797, so 'Im closing it. In case it's still relevant, we can reopen, but needs rebase.