Allow plugin create own deduplicate logic
mautic/mautic pull request #9844
Opened 2021-03-27 21:39 UTC by kuzmany

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Follow up to https://github.com/mautic/mautic/pull/7502

Common `mautic:contacts:deduplicate` already deduplicate contacts by unique fields from configurations. But sometimes we need custom check for duplications (for example based on firstname/lastname/phone). This PR added dispatcher to checkForDuplicateContacts method allow load duplicate contacts by plugin. 
This allow also create own command (for example `mautic:contacts:deduplicate:custom`) along with core one. 

#### Steps to test this PR:
1. Install and setup MauticCustomDeduplicateBundle https://github.com/mtcextendee/mautic-custom-deduplicate-bundle
2. Choose in plugins settings:
firstname, lastname, phone
and not empty email
3. Create two contacts without email but with same firstname, lastname, and phone.
4. Run `php app/console mautic:contacts:deduplicate:custom`
5. See If contacts were merged
6. Then create two contacts again
7. Go to Mautic > Contacts
8. Run Custom deduplicate from menu
![image](https://user-images.githubusercontent.com/462477/57359025-f7dc4b80-7176-11e9-94ed-eb0dee9e0c24.png)
9. Wait and then see If you have at least two notification in notification area (started, finished)
![image](https://user-images.githubusercontent.com/462477/57359081-12aec000-7177-11e9-92ff-e77991f0e875.png)
10. Check If contacts were merged

2021-04-21 07:49 UTC, escopecz requested changes
Found some small improvements that can be made. Also please cover the rows that CodeCov is reporting with tests.

2021-04-21 07:49 UTC, escopecz commented on app/bundles/LeadBundle/Event/DuplicateContactsEvent.php
> +
```suggestion

declare(strict_types=1);

```

2021-04-21 07:49 UTC, escopecz commented on app/bundles/LeadBundle/Event/DuplicateContactsEvent.php
> +    public function getFields()
```suggestion
    public function getFields(): array
```
Please add param and return type for all new methods.

2021-04-21 07:49 UTC, escopecz commented on app/bundles/LeadBundle/Event/DuplicateContactsEvent.php
> +     */
There is no value in this comment.
```suggestion
```

2021-04-21 07:49 UTC, escopecz commented on app/bundles/LeadBundle/Exception/NotHandledDuplicationByPlugin.php
> +class NotHandledDuplicationByPlugin extends \Exception
```suggestion
class DuplicationNotHandledByPlugin extends \Exception
```

2021-08-22 15:18 UTC, donbowman commented
seems this is still relevan to 4.0.0-rc since https://mtcextendee.com/our-works/mautic-plugins/custom-deduplicate-for-mautic/ would like to use it.

2022-05-03 10:02 UTC, RCheesley commented
This one has a conflict to be resolved.

2022-05-03 10:03 UTC, kuzmany commented
Let's close it. Do not support it anyomore

2022-05-03 10:03 UTC, closed without merging