Fixed mysql 8.0.16 Incorrect DATETIME value: ''
mautic/mautic pull request #9876
Opened 2021-04-04 21:06 UTC by karser

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "3.3"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #8198

#### Description:

This was a breaking change introduced in MySQL 8.0.16 but not treated as such, mautic works on 8.0.15 and earlier
Discussion here: https://bugs.mysql.com/bug.php?id=93513

#### Steps to test this PR:
1. Create a segment
2.  Add filter on a DateTime field with condition empty (or not empty)
3. Create a contact with empty (or not empty) DateTime field 
4. run `bin/console mautic:segments:update`
Expected: contact is added to segment
Actual: Got an error `Incorrect DATETIME value: ''`

2021-04-20 13:17 UTC, escopecz requested changes
It looks fine. Just needs PHPUNIT tests.

This will cause conflicts with https://github.com/mautic/mautic/pull/8649 though.

2021-04-20 13:17 UTC, escopecz commented on app/bundles/LeadBundle/Segment/ContactSegmentFilter.php
> +    public function isColumnTypeDate()
```suggestion
    public function isColumnTypeDate(): bool
```

2021-07-19 13:32 UTC, RCheesley commented
Bump :) 
@karser are you able to please pull in the latest Features branch and rebase? We will also need the unit tests as requested above, can you do that or would you need some help with that?

2021-07-20 11:30 UTC, karser commented
@escopecz I resolved your first comment. Could you please suggest an existing unit test I could add this case to?
@RCheesley I need this fix to be in 3.3. I can create another PR against `features` once this PR is approved.

2021-07-20 11:42 UTC, RCheesley commented
@karser sorry we are [not making any more releases in the 3.3 series](https://www.mautic.org/mautic-releases), except for security fixes. So this will not go anywhere unless you make it compatible with the Features branch.

2021-07-20 12:45 UTC, RCheesley commented
Looks like there is a [code style](https://github.com/mautic/mautic/pull/9876/checks?check_run_id=3113829665#step:6:75) issue to fix please :)

2021-08-11 14:43 UTC, scottmont commented
Please merge this.

2021-09-07 14:27 UTC, RCheesley commented
Hi there,

Thank you for your contribution!

As we have released Mautic 4 now, the 3.x version is out of active support and therefore will not receive any further bug fixes or features.

If this PR is still relevant to Mautic 4, please either 

- Rebase on the 4.0 branch (for bug fixes) or the 4.x branch (for features and enhancements), or 
- Close this PR and make a fresh one on the correct branch.

If it is no longer relevant to Mautic 4, please close the PR.

Thanks in advance!

2021-12-21 04:09 UTC, closed without merging