Send email to DNC flag contacts via API
mautic/mautic pull request #9900
Opened 2021-04-13 09:45 UTC by tomekkowalczyk

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
The functionality allows you to send e-mails via API to contacts who have the DNC flag.

![image](https://user-images.githubusercontent.com/39382654/114532971-ae8fb300-9c4d-11eb-84ca-d3f0cb344191.png)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Send an email to the person who has the DNC flag

2021-04-20 09:38 UTC, escopecz commented
Please create a new functional test to https://github.com/mautic/mautic/blob/features/app/bundles/EmailBundle/Tests/Controller/Api/EmailApiControllerFunctionalTest.php where you can inspire from existing tests.

2021-05-16 16:55 UTC, RCheesley commented
@tomekkowalczyk can you please provide the functional tests as requested? Otherwise we will have to close the PR. Thanks!

2022-02-01 09:23 UTC, tomekkowalczyk commented
@RCheesley a request to open a task

2022-02-05 07:55 UTC, kuzmany commented
@tomekkowalczyk nice PR, can you check CS fixer and other reports If need it. I would like check it during the next week and add it to 4.2 release

2022-02-05 07:56 UTC, kuzmany commented
Also can you add note to dev docs? https://developer.mautic.org/#send-email-to-contact

2022-03-30 09:43 UTC, tomekkowalczyk commented
@kuzmany PR for documentation has been done https://github.com/mautic/developer-documentation/pull/200

2022-03-30 10:58 UTC, kuzmany commented
@tomekkowalczyk nice! Then just resolve failing checks and we can go

2022-03-30 20:01 UTC, tomekkowalczyk commented
@kuzmany done

2022-03-31 06:53 UTC, escopecz requested changes
The test looks good! I noticed it could be improved a little. Please take a look.

One more request: Please create the data used for the test by creating the entities and flushing them to the database via Entity Manager. It's multiple times faster than creating the data via API. We already had several rounds of improving test speed, so this is adding on top of the tech debt.

2022-03-31 06:53 UTC, escopecz commented on app/bundles/EmailBundle/Tests/Controller/Api/EmailApiControllerFunctionalTest.php
> +        $response       = json_decode($clientResponse->getContent(), true);
I'm missing an assertion that the contact was successfully unsubscribed. If this fails then the rest of the test will show false positive.

2022-03-31 06:53 UTC, escopecz commented on app/bundles/EmailBundle/Tests/Controller/Api/EmailApiControllerFunctionalTest.php
> +        $this->assertTrue($responseData['success']);
Can we also assert that the email_stat entry is present for that contact and email? This is ensuring that the API response success but that does not mean that the email was actually sent.

2022-06-06 11:17 UTC, tomekkowalczyk commented
@kuzmany done, but J send one  commit ([21ec764](https://github.com/mautic/mautic/pull/9900/commits/21ec764c44176af1fc55816b3e127112c2517060)) with wrong email

2022-06-06 11:39 UTC, escopecz approved these changes
Looks good to me 👍

2022-06-06 11:56 UTC, tomekkowalczyk commented
@cla-bot check

2022-06-06 11:58 UTC, tomekkowalczyk commented
@RCheesley How can I correct verification/cla-signed with wrong email?

2022-06-06 11:59 UTC, RCheesley commented
> @RCheesley How can I correct verification/cla-signed with wrong email?

Add the email to your GitHub profile - does not have to be the main email address but does need to be present (and I think maybe also verified) - then call the bot to check with @ cla-bot check :)

2022-06-06 20:29 UTC, tomekkowalczyk commented
@RCheesley  my last commit b4a495f275aec2f363b76b834e9b48b2d045a59e  have correct email but 
commit 21ec764c44176af1fc55816b3e127112c2517060 is email address tkowalczyk 

CLA-BOT
"Some commits from the following contributors are not signed with a valid email address: tkowalczyk." 
I'can't add email tkowalczyk to my HitHub profile.

2022-06-06 20:31 UTC, RCheesley commented
I don't know if you can easily re-do the commit but otherwise we can just manually override it as we know it was your code and you have already signed :)

2022-06-10 06:52 UTC, tomekkowalczyk commented
@RCheesley I would like to manually overwrite it and the topic will be taken care of ;)

2025-07-07 08:16 UTC, jos0405 commented
Hello @tomekkowalczyk ! Is this PR still relevant? If so, can you plz rebase it to Mautic 7?
Otherwise I can also just close it.

2025-10-06 07:04 UTC, closed without merging

2025-10-06 08:47 UTC, kuzmany commented
Pushed again 7.x https://github.com/mautic/mautic/pull/15534